Repository gammapy/gammapy, pull requests merged in 2018-07, with the labels that each got.

#1448 Correcting exposure unit in MapMaker
  gammapy/cube/new.py
  gammapy/cube/tests/test_new.py
Labels: bug, feature

#1447 Add a PSFKernel to perform PSF convolution on Maps
  gammapy/cube/__init__.py
  gammapy/cube/psf_kernel.py
  gammapy/cube/tests/test_psf_kernel.py
  gammapy/maps/geom.py
Labels: feature

#1452 Bugfix for `setup.py build_docs`
  gammapy/utils/docs.py
Labels: bug

#1295 Define coordinate and axis names for Gammapy
  docs/development/howto.rst
Labels: cleanup

#1454 Improve SkyModelMapFit
  gammapy/cube/fit.py
  gammapy/cube/models.py
  gammapy/cube/tests/test_fit.py
Labels: feature

#1457 Psf kernel
  gammapy/cube/psf_kernel.py
Labels: feature

#1458 Exchange XML model registry
  gammapy/utils/serialization/tests/test_xml.py
  gammapy/utils/serialization/xml.py
Labels: cleanup, feature

#1468 Correct Map.crop(), Map.upsample(), Map.downsample() to have proper u…
  gammapy/maps/hpxnd.py
  gammapy/maps/tests/test_hpxmap.py
  gammapy/maps/tests/test_wcsnd.py
  gammapy/maps/wcsnd.py
Labels: bug

#1456 Add light curve upper limits
  gammapy/stats/poisson.py
  gammapy/stats/tests/test_poisson.py
  gammapy/time/lightcurve.py
  gammapy/time/tests/test_lightcurve.py
Labels: feature

#1470 Background added to model evaluator
  gammapy/cube/fit.py
  gammapy/cube/models.py
  gammapy/cube/tests/test_fit.py
  gammapy/cube/tests/test_models.py
Labels: feature

#1432 Add functions and class to work with PSFs with gammapy.maps
  gammapy/cube/__init__.py
  gammapy/cube/psf_map.py
  gammapy/cube/tests/test_psf_map.py
  gammapy/irf/psf_analytical.py
  gammapy/irf/tests/test_psf_analytical.py
Labels: feature

#1473 Add units in map reproject
  gammapy/maps/hpxnd.py
  gammapy/maps/tests/test_wcsnd.py
  gammapy/maps/wcsnd.py
Labels: bug

#1460 Flux point doc string
  gammapy/spectrum/flux_point.py
Labels: cleanup, docs

#1476 Add evaluate method to the background 3D
  gammapy/irf/background.py
  gammapy/irf/tests/test_background.py
Labels: feature

#1426 New background estimation for phase-resolved spectra.
  gammapy/background/__init__.py
  gammapy/background/phase.py
  gammapy/background/tests/test_phase.py
Labels: feature

#1478 Add containment_radius_map function and its test
  gammapy/cube/psf_map.py
  gammapy/cube/tests/test_psf_map.py
Labels: feature

#1482 Add handling for maps and cube in xml registry
  gammapy/utils/serialization/tests/test_xml.py
  gammapy/utils/serialization/xml.py
Labels: feature

#1480 Modify test_fit to use less pixels.
  gammapy/cube/tests/test_fit.py
Labels: tests

#1486 Handle error estimation when fit failed
  gammapy/spectrum/fit.py
Labels: feature

#1489 Add + operator for SkyModel
  gammapy/cube/models.py
  gammapy/cube/tests/test_models.py
Labels: feature

#1484 Changed point source model
  gammapy/image/models/new.py
  gammapy/image/models/tests/test_models.py
Labels: feature

#1490 Remove gammapy.data.target
  gammapy/data/__init__.py
  gammapy/data/target.py
  gammapy/data/tests/test_obs_stats.py
  gammapy/data/tests/test_target.py
  gammapy/time/tests/test_lightcurve.py
Labels: cleanup

#1491 Hide SpectrumFit.model
  gammapy/spectrum/fit.py
  gammapy/spectrum/sherpa_utils.py
  gammapy/spectrum/tests/test_fit.py
Labels: cleanup

#1492 Follow-up: Add Robust periodogram to gammapy.time
  docs/time/period.rst
  gammapy/time/period.py
  gammapy/time/plot_periodogram.py
  gammapy/time/tests/test_period.py
  gammapy/time/tests/test_plot_periodogram.py
Labels: cleanup, feature

#1495 Modified MapMaker to allow partially contained observations
  gammapy/cube/new.py
  gammapy/cube/tests/test_new.py
  gammapy/maps/tests/test_wcsnd.py
  gammapy/maps/wcsnd.py
Labels: cleanup

#1493 Fix spectrum energy grouping
  docs/spectrum/energy_group.rst
  docs/spectrum/index.rst
  gammapy/spectrum/energy_group.py
  gammapy/spectrum/tests/test_energy_group.py
Labels: cleanup

#1477 Use new evaluate method of Background3D in MapMaker
  gammapy/cube/new.py
  gammapy/irf/background.py
Labels: feature

#1496 Add integration to background 3D
  gammapy/irf/background.py
  gammapy/irf/tests/test_background.py
Labels: feature

#1498 code cleanup: renamed fit_minuit to fit_iminuit
  gammapy/cube/fit.py
  gammapy/spectrum/fit.py
  gammapy/utils/fitting/iminuit.py
  gammapy/utils/fitting/tests/test_iminuit.py
Labels: cleanup

#1497 add evaluate with the same API than background 3D
  gammapy/cube/new.py
  gammapy/irf/background.py
  gammapy/irf/tests/test_background.py
Labels: feature

#1501 Make min and max optional in XML reader
  gammapy/utils/serialization/tests/test_xml.py
  gammapy/utils/serialization/xml.py
Labels: feature

#1502 Switch lima to use WcsNDMap instead of SkyImage
  docs/detect/index.rst
  gammapy/detect/kernel.py
  gammapy/detect/lima.py
  gammapy/detect/tests/test_lima.py
Labels: cleanup

#1505 Remove old Sherpa 3D map analysis code
  gammapy/cube/core.py
  gammapy/cube/sherpa_.py
  gammapy/cube/tests/test_sherpa_.py
Labels: cleanup

#1506 Remove old SkyCubeImages class
  gammapy/cube/__init__.py
  gammapy/cube/core.py
  gammapy/cube/images.py
  gammapy/cube/tests/test_core.py
  gammapy/cube/tests/test_images.py
Labels: cleanup

#1499 Rename detx, detx to fov_lon and fov_lat in background 3D
  gammapy/cube/new.py
  gammapy/irf/background.py
  gammapy/irf/tests/test_background.py
  gammapy/irf/tests/test_irf_write.py
Labels: cleanup

#1507 Change evaluate and integrate method in background2D
  gammapy/cube/new.py
  gammapy/irf/background.py
  gammapy/irf/tests/test_background.py
Labels: cleanup

#1508 Remove lots of old stuff
  examples/example_iact_data_peek.py
  examples/example_plot_background_model.py
  examples/test_fov_coord_transform.py
  examples/test_fov_coord_transform2.py
  gammapy/background/__init__.py
  gammapy/background/off_data_background_maker.py
  gammapy/background/tests/test_fov_cube.py
  gammapy/background/tests/test_models.py
  gammapy/background/tests/test_off_data_background_maker.py
  gammapy/cube/__init__.py
  gammapy/cube/cube_pipe.py
  gammapy/cube/exposure.py
  gammapy/cube/tests/test_cube_pipe.py
  gammapy/cube/tests/test_exposure.py
  gammapy/cube/tests/test_utils.py
  gammapy/cube/utils.py
  gammapy/data/tests/test_obs_table.py
  gammapy/datasets/__init__.py
  gammapy/datasets/make.py
  gammapy/datasets/tests/test_make.py
  gammapy/image/basic.py
  gammapy/irf/tests/test_psf_analytical.py
  gammapy/scripts/__init__.py
  gammapy/scripts/image_pipe.py
  gammapy/scripts/image_pipe_example.yaml
  gammapy/scripts/tests/test_image_pipe.py
Labels: cleanup

#1511 Remove parmin and parmax for some XML models
  gammapy/cube/models.py
  gammapy/utils/serialization/tests/test_xml.py
  gammapy/utils/serialization/xml.py
Labels: cleanup

#1509 Edit PhaseBackgroundEstimator and test_phase to generalize
  gammapy/background/phase.py
  gammapy/background/tests/test_phase.py
Labels: feature

#1513 Remove old code in gammapy.background
  gammapy/background/__init__.py
  gammapy/background/fov.py
  gammapy/background/tests/test_fov.py
  gammapy/scripts/__init__.py
  gammapy/scripts/cube_background.py
Labels: cleanup

#1514 Move GaussianBand2D to SourceCatalogLargeScaleHGPS
  examples/example_energy_offset_array.py
  gammapy/background/models.py
  gammapy/background/tests/test_models.py
  gammapy/catalog/hess.py
  gammapy/catalog/tests/test_hess.py
  gammapy/data/event_list.py
  gammapy/data/hdu_index_table.py
  gammapy/irf/psf_3d.py
  gammapy/irf/psf_table.py
  gammapy/scripts/cta_irf.py
Labels: cleanup

#1515 Remove old background model code
  gammapy/background/__init__.py
  gammapy/background/energy_offset_array.py
  gammapy/background/fov_cube.py
  gammapy/background/models.py
  gammapy/background/tests/test_energy_offset_array.py
Labels: cleanup

#1517 Remove cta_utils and CTASpectrumObservation
  examples/example_cta_simulation.py
  gammapy/scripts/__init__.py
  gammapy/scripts/cta_utils.py
  gammapy/scripts/tests/test_cta_utils.py
  gammapy/spectrum/tests/test_models.py
Labels: cleanup

#1518 Remove old Sherpa image fit CLI
  gammapy/irf/psf_core.py
  gammapy/scripts/image_fit.py
  gammapy/scripts/main.py
  gammapy/scripts/tests/test_image_fit.py
Labels: cleanup

#1519 Remove old, unfinished methods in detect
  docs/detect/index.rst
  gammapy/detect/__init__.py
  gammapy/detect/iterfind.py
  gammapy/detect/matched_filter.py
  gammapy/detect/tests/test_iterfind.py
  gammapy/detect/tests/test_matched_filter.py
  gammapy/spectrum/core.py
  gammapy/spectrum/crab.py
  gammapy/spectrum/extract.py
  gammapy/spectrum/results.py
  gammapy/spectrum/simulation.py
Labels: cleanup

#1520 Small cleanup in gammapy.image
  gammapy/image/core.py
  gammapy/image/measure.py
  gammapy/image/plotting.py
  gammapy/image/profile.py
  gammapy/image/tests/test_utils.py
  gammapy/image/utils.py
  gammapy/stats/data.py
Labels: cleanup

#1521 Remove gammapy/catalog/xmatch.py
  gammapy/catalog/__init__.py
  gammapy/catalog/tests/test_xmatch.py
  gammapy/catalog/xmatch.py
Labels: cleanup

#1522 Remove some usage of SkyImage
  gammapy/catalog/core.py
  gammapy/catalog/tests/test_core.py
  gammapy/catalog/tests/test_hess.py
  gammapy/data/event_list.py
  gammapy/data/tests/test_event_list.py
Labels: cleanup

#1523 Move code in gammapy.image
  gammapy/cube/__init__.py
  gammapy/cube/counts.py
  gammapy/cube/new.py
  gammapy/cube/tests/test_counts.py
  gammapy/image/__init__.py
  gammapy/image/profile.py
  gammapy/image/radial_profile.py
  gammapy/image/tests/test_profile.py
  gammapy/image/tests/test_radial_profile.py
Labels: cleanup

#1524 Remove gammapy image ts CLI
  gammapy/scripts/image_ts.py
  gammapy/scripts/main.py
  gammapy/scripts/tests/test_image_ts.py
Labels: cleanup

#1525 Change gammapy image bin to gammapy.maps; add back TS map test
  docs/development/howto.rst
  gammapy/detect/tests/test_test_statistics.py
  gammapy/scripts/image_bin.py
  gammapy/scripts/tests/test_image_bin.py
  gammapy/utils/fits.py
Labels: cleanup

#1526 Remove old FoVBackgroundEstimator
  gammapy/background/ring.py
Labels: cleanup

#1527 Rewrite ASmooth to use gammapy.maps
  gammapy/image/asmooth.py
  gammapy/image/tests/test_asmooth.py
Labels: cleanup

#1534 Remove old cruft from gammapy.datasets
  gammapy/datasets/fermi.py
  gammapy/datasets/tests/test_fermi.py
Labels: cleanup

#1535 Clean up KernelBackgroundEstimator
  gammapy/detect/kernel.py
  gammapy/detect/tests/test_kernel.py
  gammapy/irf/psf_table.py
Labels: cleanup

#1503 Add energy dispersion in map analysis
  gammapy/cube/fit.py
  gammapy/cube/models.py
  gammapy/cube/psf_kernel.py
  gammapy/cube/tests/test_fit.py
  gammapy/cube/tests/test_models.py
  gammapy/irf/energy_dispersion.py
Labels: feature

#1536 Small renames in map functions and evaluator
  gammapy/astro/darkmatter/utils.py
  gammapy/cube/fit.py
  gammapy/cube/models.py
  gammapy/cube/new.py
  gammapy/cube/tests/test_fit.py
  gammapy/cube/tests/test_models.py
  gammapy/cube/tests/test_new.py
Labels: cleanup

#1537 Simpler names for map evaluator and fit?
  gammapy/cube/fit.py
  gammapy/cube/models.py
  gammapy/cube/tests/test_fit.py
  gammapy/cube/tests/test_models.py
Labels: question

#1544 Change KernelBackgroundEstimator to use gammapy.maps
  gammapy/detect/kernel.py
  gammapy/detect/tests/test_kernel.py
Labels: cleanup

#1512 Fixes/addresses #1481, left a TODO for the `error_method` implementation
  gammapy/spectrum/fit.py
Labels: bug

#1549 Fix links to notebooks broken
  gammapy/utils/docs.py
Labels: bug

#1553 Introduces a minuit_kwargs argument for the fit_iminuit function
  docs/conf.py
  gammapy/cube/fit.py
  gammapy/spectrum/fit.py
  gammapy/utils/fitting/iminuit.py
Labels: feature

#1554 Introduce map clone method
  gammapy/cube/new.py
  gammapy/detect/kernel.py
  gammapy/detect/lima.py
  gammapy/maps/base.py
  gammapy/maps/geom.py
  gammapy/maps/hpx.py
  gammapy/maps/hpxnd.py
  gammapy/maps/tests/test_base.py
  gammapy/maps/wcs.py
  gammapy/maps/wcsnd.py
Labels: cleanup, feature

#1560 Small modeling / XML cleanup
  gammapy/spectrum/models.py
  gammapy/utils/fitting/iminuit.py
  gammapy/utils/fitting/tests/test_iminuit.py
  gammapy/utils/modeling.py
  gammapy/utils/serialization/tests/test_xml.py
  gammapy/utils/serialization/xml.py
  gammapy/utils/tests/test_modeling.py
Labels: cleanup

#1556 SkyModel parameter sync with components
  gammapy/catalog/tests/test_hess.py
  gammapy/cube/fit.py
  gammapy/cube/models.py
  gammapy/cube/tests/test_fit.py
  gammapy/cube/tests/test_models.py
  gammapy/utils/fitting/iminuit.py
  gammapy/utils/fitting/tests/test_iminuit.py
Labels: bug

#1565 Gammapy image cleanup
  gammapy/image/measure.py
  gammapy/image/plotting.py
  gammapy/image/tests/test_measure.py
  gammapy/image/tests/test_plotting.py
  gammapy/image/tests/test_utils.py
  gammapy/image/utils.py
Labels: cleanup

#1566 Small fix to prepare the switch to the new obs classes
  gammapy/spectrum/extract.py
Labels: cleanup

#1563 Improve modeling parameter handling
  gammapy/cube/models.py
  gammapy/cube/tests/test_fit.py
  gammapy/spectrum/crab.py
  gammapy/spectrum/tests/test_fit.py
  gammapy/utils/fitting/iminuit.py
  gammapy/utils/fitting/tests/test_iminuit.py
  gammapy/utils/modeling.py
  gammapy/utils/serialization/tests/test_xml.py
  gammapy/utils/serialization/xml.py
  gammapy/utils/tests/test_modeling.py
Labels: bug, cleanup

#1567 Clarify errordef=1 in iminuit interface
  gammapy/utils/fitting/iminuit.py
Labels: cleanup

#1564 Migrate gammapy.detect to Maps
  docs/detect/index.rst
  gammapy/detect/test_statistics.py
  gammapy/detect/tests/test_test_statistics.py
Labels: cleanup

#1568 Remove IACT and Fermi-LAT basic image estimators
  gammapy/image/__init__.py
  gammapy/image/basic.py
  gammapy/image/tests/test_basic.py
Labels: cleanup

#1569 Remove aplpy dependency
  .travis.yml
  dev/docker/commands.sh
  docs/conf.py
  docs/image/plotting.rst
  docs/image/survey_example.py
  docs/install/conda.rst
  docs/install/dependencies.rst
  docs/nitpick-exceptions
  environment-dev.yml
  gammapy/conftest.py
  gammapy/image/plotting.py
  gammapy/scripts/info.py
  setup.py
Labels: cleanup

#1562 Added MapMaker.run
  gammapy/cube/new.py
  gammapy/cube/tests/test_new.py
Labels: feature

#1543 First attempt for an interactive plotter of 3D Map
  gammapy/maps/wcsnd.py
Labels: feature

#1277 PIG 2 - New low-level analysis code
  docs/development/pigs/pig-002.rst
Labels: pig

#1558 Change the way of integrating the background rate in MapMaker
  gammapy/cube/new.py
  gammapy/cube/tests/test_new.py
Labels: feature

#1581 Add required dependency to scipy for test_containment_radius_map
  gammapy/cube/tests/test_psf_map.py
Labels: tests

#1584 Some corrections to pig-002 to avoid sphinx errors
  docs/development/pigs/index.rst
  docs/development/pigs/pig-002.rst
Labels: docs

#1585 Cleanup and small fixes to HDU index table
  gammapy/data/hdu_index_table.py
  gammapy/data/tests/test_hdu_index_table.py
Labels: bug, cleanup

#1586 Less optional dependencies
  .travis.yml
  docs/conf.py
  docs/datasets/index.rst
  docs/development/howto.rst
  docs/install/dependencies.rst
  docs/install/macports.rst
  docs/install/other.rst
  docs/references.txt
  gammapy/conftest.py
  gammapy/datasets/fermi.py
  gammapy/scripts/info.py
Labels: cleanup, docs

#1587 Remove SkyImageList
  gammapy/image/lists.py
  gammapy/image/tests/test_lists.py
Labels: cleanup

#1576 Migrate detect.cwt to WcsNDMaps
  gammapy/detect/cwt.py
  gammapy/detect/tests/test_cwt.py
  gammapy/maps/wcs.py
Labels: cleanup

#1592 Add and improve "edges" mode for map pix coordinates
  gammapy/cube/tests/test_models.py
  gammapy/cube/tests/test_new.py
  gammapy/maps/tests/test_wcs.py
  gammapy/maps/wcs.py
Labels: cleanup, feature

#1573 Migrate image measure and profile to maps
  docs/image/colormap_example.py
  gammapy/detect/tests/test_test_statistics.py
  gammapy/image/measure.py
  gammapy/image/models/tests/test_gauss.py
  gammapy/image/profile.py
  gammapy/image/tests/test_measure.py
  gammapy/image/tests/test_profile.py
  gammapy/maps/wcs.py
Labels: cleanup

#1593 Remove FermiGalacticCenter and FermiLATDataset
  docs/irf/plot_fermi_psf.py
  gammapy/cube/tests/test_core.py
  gammapy/datasets/__init__.py
  gammapy/datasets/fermi.py
  gammapy/datasets/tests/test_fermi.py
  gammapy/irf/tests/test_psf_table.py
Labels: cleanup

#1594 Remove SkyImage and SkyCube
  docs/image/index.rst
  gammapy/cube/__init__.py
  gammapy/cube/core.py
  gammapy/cube/tests/test_core.py
  gammapy/image/__init__.py
  gammapy/image/core.py
  gammapy/image/tests/test_core.py
Labels: cleanup

#1595 Update gammapy.image RST docs
  docs/image/index.rst
  docs/image/sky_image.rst
Labels: cleanup, docs

#1598 Update docs/development/howto.rst
  docs/development/howto.rst
Labels: cleanup, docs

#1600 Remove `LogEnergyAxis` and `gammapy/spectrum/diffuse.py`
  gammapy/spectrum/__init__.py
  gammapy/spectrum/diffuse.py
  gammapy/spectrum/tests/test_diffuse.py
  gammapy/spectrum/tests/test_utils.py
  gammapy/spectrum/utils.py
Labels: cleanup

#1601 Fix SkyPointSource normalization
  gammapy/image/models/new.py
  gammapy/image/models/tests/test_models.py
Labels: bug

#1602 Auto-format docs RST pages
  docs/astro/darkmatter/index.rst
  docs/astro/index.rst
  docs/astro/population/index.rst
  docs/astro/population/plot_spiral_arm_models.py
  docs/astro/source/index.rst
  docs/background/index.rst
  docs/background/make_reflected_regions.py
  docs/background/reflected.rst
  docs/catalog/gammacat.rst
  docs/catalog/index.rst
  docs/cube/index.rst
  docs/datasets/index.rst
  docs/detect/index.rst
  docs/development/dataformats.rst
  docs/development/intro.rst
  docs/development/pigs/index.rst
  docs/development/pigs/pig-001.rst
  docs/development/pigs/pig-002.rst
  docs/development/release.rst
  docs/development/setup.rst
  docs/getting-started.rst
  docs/image/colormap_example.py
  docs/image/index.rst
  docs/image/models.rst
  docs/image/plotting.rst
  docs/image/survey_example.py
  docs/index.rst
  docs/install/check.rst
  docs/install/conda.rst
  docs/install/dependencies.rst
  docs/install/index.rst
  docs/install/macports.rst
  docs/install/other.rst
  docs/install/pip.rst
  docs/irf/index.rst
  docs/irf/plot_edisp.py
  docs/irf/theory.rst
  docs/maps/hpxmap.rst
  docs/maps/index.rst
  docs/references.rst
  docs/scripts/index.rst
  docs/scripts/significance.py
  docs/spectrum/fitting.rst
  docs/spectrum/index.rst
  docs/stats/feldman_cousins.rst
  docs/stats/fit_statistics.rst
  docs/stats/index.rst
  docs/stats/plot_fc_gauss.py
  docs/stats/plot_fc_poisson.py
  docs/time/index.rst
  docs/time/period.rst
  docs/tutorials.rst
  docs/utils/index.rst
Labels: cleanup, docs

#1603 Update sub-package doc page headings
  docs/astro/index.rst
  docs/background/index.rst
  docs/catalog/index.rst
  docs/cube/index.rst
  docs/data/index.rst
  docs/datasets/index.rst
  docs/detect/index.rst
  docs/image/index.rst
  docs/index.rst
  docs/irf/index.rst
  docs/maps/index.rst
  docs/scripts/index.rst
  docs/spectrum/index.rst
  docs/stats/index.rst
  docs/time/index.rst
  docs/utils/index.rst
Labels: docs

#1599 Improve iminuit fitting interface a little bit
  gammapy/cube/fit.py
  gammapy/cube/tests/test_fit.py
  gammapy/spectrum/fit.py
  gammapy/spectrum/tests/test_fit.py
  gammapy/utils/fitting/iminuit.py
  gammapy/utils/modeling.py
Labels: cleanup

#1606 Change FluxPointFitter to use minuit
  gammapy/spectrum/flux_point.py
  gammapy/spectrum/tests/test_flux_point.py
  gammapy/utils/fitting/sherpa.py
  gammapy/utils/fitting/tests/test_sherpa.py
  gammapy/utils/sherpa.py
Labels: cleanup

#1610 Re-organise code files in gammapy.cube
  gammapy/astro/darkmatter/profiles.py
  gammapy/astro/darkmatter/tests/test_profiles.py
  gammapy/astro/darkmatter/tests/test_spectra.py
  gammapy/astro/darkmatter/tests/test_utils.py
  gammapy/astro/darkmatter/utils.py
  gammapy/cube/__init__.py
  gammapy/cube/background.py
  gammapy/cube/counts.py
  gammapy/cube/exposure.py
  gammapy/cube/make.py
  gammapy/cube/new.py
  gammapy/cube/tests/test_background.py
  gammapy/cube/tests/test_exposure.py
  gammapy/cube/tests/test_make.py
  gammapy/cube/tests/test_new.py
  gammapy/maps/tests/test_wcs.py
  gammapy/maps/wcs.py
Labels: cleanup
