Repository gammapy/gammapy, pull requests merged in 2018-11, with the labels that each got.

#1895 Renaming obs and obs_list attributes
  gammapy/background/phase.py
  gammapy/background/reflected.py
  gammapy/background/tests/test_phase.py
  gammapy/background/tests/test_reflected.py
  gammapy/cube/make.py
  gammapy/cube/tests/test_make.py
  gammapy/data/data_store.py
  gammapy/data/obs_stats.py
  gammapy/data/observations.py
  gammapy/data/tests/test_data_store.py
  gammapy/data/tests/test_obs_stats.py
  gammapy/data/tests/test_obs_summary.py
  gammapy/irf/irf_reduce.py
  gammapy/irf/tests/test_fits_prod.py
  gammapy/irf/tests/test_irf_reduce.py
  gammapy/scripts/spectrum_pipe.py
  gammapy/scripts/tests/test_spectrum_pipe.py
  gammapy/spectrum/extract.py
  gammapy/spectrum/tests/test_extract.py
  gammapy/time/lightcurve.py
  gammapy/time/tests/test_lightcurve.py
  tutorials/analysis_3d.ipynb
  tutorials/background_model.ipynb
  tutorials/cta_data_analysis.ipynb
  tutorials/hess.ipynb
  tutorials/image_fitting_with_sherpa.ipynb
  tutorials/light_curve.ipynb
  tutorials/spectrum_analysis.ipynb
  tutorials/spectrum_pipe.ipynb
Labels: cleanup

#1891 Arithmetics of maps
  gammapy/maps/base.py
  gammapy/maps/tests/test_base.py
Labels: feature

#1898 Review and unify quantity handling
  gammapy/astro/darkmatter/profiles.py
  gammapy/astro/darkmatter/spectra.py
  gammapy/astro/population/simulate.py
  gammapy/astro/source/pwn.py
  gammapy/astro/source/snr.py
  gammapy/background/reflected.py
  gammapy/background/ring.py
  gammapy/catalog/fermi.py
  gammapy/catalog/gammacat.py
  gammapy/catalog/hawc.py
  gammapy/catalog/hess.py
  gammapy/catalog/tests/test_hawc.py
  gammapy/cube/background.py
  gammapy/cube/fit.py
  gammapy/cube/make.py
  gammapy/cube/models.py
  gammapy/cube/psf_map.py
  gammapy/cube/tests/test_models.py
  gammapy/data/event_list.py
  gammapy/data/obs_summary.py
  gammapy/image/models/core.py
  gammapy/image/models/tests/test_core.py
  gammapy/image/profile.py
  gammapy/irf/effective_area.py
  gammapy/irf/energy_dispersion.py
  gammapy/irf/tests/test_background.py
  gammapy/maps/geom.py
  gammapy/maps/hpxnd.py
  gammapy/maps/wcs.py
  gammapy/maps/wcsnd.py
  gammapy/spectrum/core.py
  gammapy/spectrum/crab.py
  gammapy/spectrum/flux_point.py
  gammapy/spectrum/models.py
  gammapy/spectrum/observation.py
  gammapy/spectrum/profile.py
  gammapy/spectrum/results.py
  gammapy/spectrum/sensitivity.py
  gammapy/spectrum/utils.py
  gammapy/time/lightcurve.py
  gammapy/time/simulate.py
  gammapy/utils/fitting/parameter.py
  gammapy/utils/nddata.py
  gammapy/utils/serialization/xml.py
  gammapy/utils/tests/test_table.py
  gammapy/utils/tests/test_units.py
  gammapy/utils/wcs.py
  setup.py
Labels: cleanup

#1902 Add geometry check for map arithmetics
  gammapy/maps/base.py
  gammapy/maps/tests/test_base.py
Labels: feature

#1904 Fix parameter limit handling in fitting
  gammapy/stats/poisson.py
  gammapy/utils/fitting/iminuit.py
  gammapy/utils/fitting/parameter.py
  gammapy/utils/fitting/sherpa.py
  gammapy/utils/fitting/tests/test_iminuit.py
  gammapy/utils/fitting/tests/test_parameter.py
  gammapy/utils/fitting/tests/test_sherpa.py
Labels: bug

#1903 Improve flux points class
  gammapy/catalog/fermi.py
  gammapy/catalog/gammacat.py
  gammapy/catalog/hess.py
  gammapy/catalog/tests/test_fermi.py
  gammapy/data/observations.py
  gammapy/spectrum/flux_point.py
  gammapy/spectrum/results.py
  gammapy/spectrum/tests/test_flux_point.py
  gammapy/spectrum/tests/test_flux_point_core.py
  gammapy/spectrum/utils.py
Labels: cleanup

#1911 Add known install issues sub-section to docs
  docs/install/check.rst
Labels: docs

#1910 Add tests for gammapy.utils.modeling.Fit
  gammapy/utils/fitting/parameter.py
  gammapy/utils/fitting/tests/test_fit.py
  gammapy/utils/fitting/tests/test_iminuit.py
  gammapy/utils/fitting/tests/test_sherpa.py
Labels: tests

#1915 Remove likelihood profiles from FitResult
  gammapy/spectrum/tests/test_fit.py
  gammapy/utils/fitting/fit.py
Labels: cleanup

#1914 Introduce gammapy.utils.fitting.Model base class
  gammapy/cube/models.py
  gammapy/image/models/core.py
  gammapy/spectrum/models.py
  gammapy/time/models.py
  gammapy/utils/fitting/__init__.py
  gammapy/utils/fitting/model.py
  gammapy/utils/fitting/tests/test_fit.py
  gammapy/utils/fitting/tests/test_model.py
Labels: feature

#1906 Adapt tests for Astropy master fails
  gammapy/catalog/tests/test_fermi.py
  gammapy/data/pointing.py
  gammapy/data/tests/test_gti.py
  gammapy/data/tests/test_observations.py
  gammapy/data/tests/test_pointing.py
  gammapy/utils/testing.py
Labels: tests

#1918 Add parameter correlation matrix from covar method
  gammapy/stats/__init__.py
  gammapy/stats/tests/test_utils.py
  gammapy/stats/utils.py
  gammapy/utils/fitting/parameter.py
  gammapy/utils/fitting/tests/test_parameter.py
Labels: cleanup

#1920 Add gammapy.utils.fitting.scipy
  gammapy/utils/fitting/__init__.py
  gammapy/utils/fitting/fit.py
  gammapy/utils/fitting/iminuit.py
  gammapy/utils/fitting/likelihood.py
  gammapy/utils/fitting/scipy.py
  gammapy/utils/fitting/sherpa.py
  gammapy/utils/fitting/tests/test_fit.py
  gammapy/utils/fitting/tests/test_scipy.py
Labels: feature

#1921 Unify interpolation and add broadcasting to ScaledRegularGridInterpolator
  gammapy/catalog/hess.py
  gammapy/cube/background.py
  gammapy/cube/exposure.py
  gammapy/irf/background.py
  gammapy/irf/effective_area.py
  gammapy/irf/energy_dispersion.py
  gammapy/irf/tests/test_effective_area.py
  gammapy/irf/tests/test_energy_dispersion.py
  gammapy/maps/tests/test_wcsnd.py
  gammapy/maps/wcsnd.py
  gammapy/spectrum/models.py
  gammapy/utils/interpolation.py
  gammapy/utils/nddata.py
  gammapy/utils/tests/test_nddata.py
Labels: cleanup

#1922 Add Fit.covar method
  gammapy/spectrum/tests/test_flux_point.py
  gammapy/utils/fitting/fit.py
  gammapy/utils/fitting/iminuit.py
  gammapy/utils/fitting/scipy.py
  gammapy/utils/fitting/tests/test_fit.py
Labels: feature

#1924 Static image updated for analysis_3d notebook
  tutorials/images/DC1_3d.png
Labels: docs

#1908 Take observation time from GTI table
  gammapy/data/obs_table.py
  gammapy/data/observations.py
  gammapy/data/tests/test_obs_table.py
  gammapy/data/tests/test_observations.py
Labels: cleanup

#1912 Introducing the ObservationFilter class
  gammapy/data/__init__.py
  gammapy/data/event_list.py
  gammapy/data/filters.py
  gammapy/data/gti.py
  gammapy/data/observations.py
  gammapy/data/tests/test_filters.py
Labels: feature

#1925 Add MapFit test for one energy bin
  gammapy/cube/tests/test_fit.py
Labels: feature

#1927 Improve Fit class, add confidence method
  gammapy/utils/fitting/fit.py
  gammapy/utils/fitting/iminuit.py
  gammapy/utils/fitting/parameter.py
  gammapy/utils/fitting/tests/test_fit.py
Labels: feature

#1929 Rewrite FluxpointEstimator
  gammapy/spectrum/flux_point.py
  gammapy/spectrum/models.py
  gammapy/spectrum/tests/test_flux_point.py
  gammapy/utils/fitting/fit.py
Labels: cleanup

#1926 Fix MapAxis interpolation FITS serialisation
  gammapy/maps/geom.py
  gammapy/maps/tests/test_wcs.py
Labels: bug

#1909 Cleaning of irf/io.py to introduce load_CTA_IRF helper function
  gammapy/irf/io.py
  gammapy/irf/tests/test_io.py
  gammapy/spectrum/tests/test_sensitivity.py
  tutorials/simulate_3d.ipynb
  tutorials/spectrum_simulation_cta.ipynb
Labels: cleanup

#1930 Add sections in documentation navigation bar
  docs/index.rst
  docs/install/check.rst
Labels: cleanup, docs

#1932 Improve Fit.likelihood_profile
  gammapy/image/models/core.py
  gammapy/spectrum/models.py
  gammapy/spectrum/tests/test_fit.py
  gammapy/spectrum/tests/test_flux_point.py
  gammapy/spectrum/tests/test_results.py
  gammapy/utils/fitting/fit.py
  gammapy/utils/fitting/iminuit.py
  gammapy/utils/fitting/parameter.py
  gammapy/utils/fitting/scipy.py
  gammapy/utils/fitting/sherpa.py
  gammapy/utils/fitting/tests/test_fit.py
  gammapy/utils/fitting/tests/test_parameter.py
Labels: cleanup

#1933 Add likelihood profiles to FluxPointEstimator
  gammapy/spectrum/__init__.py
  gammapy/spectrum/flux_point.py
  gammapy/spectrum/profile.py
  gammapy/spectrum/tests/test_flux_point.py
  gammapy/spectrum/tests/test_profile.py
  gammapy/utils/fitting/iminuit.py
  gammapy/utils/interpolation.py
  tutorials/cta_data_analysis.ipynb
  tutorials/spectrum_analysis.ipynb
Labels: feature

#1934 FluxPointEstimator test and docs improvements
  gammapy/cube/models.py
  gammapy/image/models/core.py
  gammapy/spectrum/flux_point.py
  gammapy/spectrum/models.py
  gammapy/spectrum/tests/test_flux_point.py
  gammapy/spectrum/tests/test_flux_point_estimator.py
  gammapy/utils/fitting/fit.py
  gammapy/utils/fitting/iminuit.py
  gammapy/utils/fitting/model.py
  gammapy/utils/fitting/parameter.py
  gammapy/utils/fitting/tests/test_parameter.py
  tutorials/spectrum_analysis.ipynb
Labels: cleanup, tests

#1939 Update gammapy/_astropy_init.py
  gammapy/_astropy_init.py
Labels: infrastructure

#1937 No copy of input and result model in fit
  gammapy/cube/fit.py
  gammapy/cube/tests/test_fit.py
  gammapy/spectrum/fit.py
  gammapy/spectrum/flux_point.py
  gammapy/spectrum/tests/test_fit.py
  gammapy/spectrum/tests/test_flux_point.py
  gammapy/utils/fitting/fit.py
  gammapy/utils/fitting/iminuit.py
  gammapy/utils/fitting/parameter.py
  gammapy/utils/fitting/tests/test_fit.py
Labels: cleanup, feature

#1940 Debug why pytest hangs or fails in some CI builds
  gammapy/_astropy_init.py
Labels: bug, infrastructure, tests

#1948 Using explicit imports to fix pytest 3.7+ issue
  .travis.yml
  appveyor.yml
  azure-pipelines.yml
  environment-dev.yml
  gammapy/conftest.py
  setup.py
Labels: tests

#1945 Update CHANGES.rst for v0.9
  CHANGES.rst
Labels: docs

#1949 Add fit minos_contour method
  gammapy/spectrum/flux_point.py
  gammapy/utils/fitting/fit.py
  gammapy/utils/fitting/iminuit.py
  gammapy/utils/fitting/tests/test_fit.py
Labels: feature

#1950 typo fix in 0.9 changelog
  CHANGES.rst
Labels: docs

#1951 Add keepdim options (issue #1935)
  gammapy/cube/make.py
  gammapy/cube/tests/test_make.py
  gammapy/maps/base.py
  gammapy/maps/geom.py
  gammapy/maps/tests/test_geom.py
  gammapy/maps/tests/test_wcsnd.py
  gammapy/maps/wcsnd.py
Labels: feature

#1957 Add edisp in MapEvaluator for simulate_3d notebook
  tutorials/simulate_3d.ipynb
Labels: cleanup

#1961 Add pytest.mark.remote_data
  gammapy/scripts/tests/test_download.py
  setup.cfg
Labels: tests

#1278 PIG 3 - Plan for dropping Python 2.7 support
  docs/development/pigs/pig-003.rst
Labels: pig

#1962 Change data access from all notebooks to GAMMAPY_DATA
  Dockerfile
  tutorials/fermi_lat.ipynb
  tutorials/notebooks.yaml
  tutorials/sed_fitting_gammacat_fermi.ipynb
  tutorials/spectrum_pipe.ipynb
Labels: docs
