Repository gammapy/gammapy, pull requests merged in 2018-08, with the labels that each got.

#1611 Moving observation classes to observations.py
  gammapy/data/__init__.py
  gammapy/data/data_store.py
  gammapy/data/observations.py
  gammapy/data/tests/test_data_store.py
  gammapy/data/tests/test_observationlist.py
  gammapy/data/tests/test_observations.py
Labels: cleanup

#1613 Remove tevcat mask
  gammapy/background/tests/test_reflected.py
  gammapy/data/tests/test_obs_stats.py
  gammapy/data/tests/test_obs_summary.py
  gammapy/spectrum/tests/test_extract.py
  gammapy/time/tests/test_lightcurve.py
Labels: cleanup

#1614 Add sherpa fitting backend prototype
  gammapy/utils/fitting/__init__.py
  gammapy/utils/fitting/sherpa.py
  gammapy/utils/fitting/tests/test_sherpa.py
Labels: feature

#1615 Minor cleanup of new maps code
  gammapy/astro/darkmatter/tests/test_utils.py
  gammapy/astro/darkmatter/utils.py
  gammapy/cube/background.py
  gammapy/cube/counts.py
  gammapy/cube/exposure.py
  gammapy/cube/make.py
  gammapy/cube/psf_map.py
  gammapy/cube/tests/test_background.py
  gammapy/cube/tests/test_counts.py
  gammapy/cube/tests/test_exposure.py
  gammapy/cube/tests/test_fit.py
  gammapy/cube/tests/test_make.py
Labels: cleanup

#1617 Remove offset_max from map make functions
  gammapy/cube/background.py
  gammapy/cube/counts.py
  gammapy/cube/exposure.py
  gammapy/cube/make.py
  gammapy/cube/tests/test_background.py
  gammapy/cube/tests/test_exposure.py
  gammapy/cube/tests/test_fit.py
  gammapy/cube/tests/test_make.py
Labels: cleanup

#1616 Improve reflected background region finder
  docs/background/make_reflected_regions.py
  gammapy/background/reflected.py
  gammapy/background/tests/test_reflected.py
Labels: bug

#1621 Improve make_exposure_map tests
  gammapy/cube/exposure.py
  gammapy/cube/tests/test_exposure.py
Labels: cleanup

#1622 Better test case for MapMaker
  gammapy/cube/make.py
  gammapy/cube/tests/test_make.py
Labels: cleanup

#1605 Remove old sherpa backend from SpectrumFit
  gammapy/scripts/tests/test_spectrum_pipe.py
  gammapy/spectrum/fit.py
  gammapy/spectrum/models.py
  gammapy/spectrum/sherpa_utils.py
  gammapy/spectrum/tests/test_fit.py
  gammapy/spectrum/tests/test_flux_point.py
  gammapy/spectrum/tests/test_models.py
  gammapy/utils/fitting/iminuit.py
Labels: cleanup

#1625 Split MapMakerObs from MapMaker
  gammapy/cube/background.py
  gammapy/cube/counts.py
  gammapy/cube/make.py
  gammapy/cube/tests/test_make.py
Labels: cleanup, feature

#1626 Improve map making test cases
  gammapy/cube/background.py
  gammapy/cube/tests/test_background.py
  gammapy/cube/tests/test_exposure.py
Labels: cleanup, tests

#1627 Fix refpix argument handling in WcsGeom.create
  gammapy/maps/tests/test_wcs.py
  gammapy/maps/wcs.py
Labels: bug

#1628 Move mask_region to WcsGeom
  gammapy/background/tests/test_reflected.py
  gammapy/maps/tests/test_wcs.py
  gammapy/maps/tests/test_wcsnd.py
  gammapy/maps/wcs.py
  gammapy/maps/wcsnd.py
Labels: cleanup

#1632 Improve background map making
  gammapy/cube/background.py
  gammapy/cube/make.py
  gammapy/cube/tests/test_make.py
  gammapy/irf/tests/test_background.py
Labels: bug, cleanup

#1631 Modified fill_map_counts to deal with columns without units
  gammapy/cube/counts.py
  gammapy/cube/tests/test_counts.py
Labels: bug

#1630 Introducing new observation container class
  gammapy/data/observations.py
Labels: feature

#1640 Add selection which map to to map maker
  gammapy/cube/make.py
Labels: feature

#1645 Polish gammapy.maps a bit
  gammapy/maps/base.py
  gammapy/maps/hpxnd.py
  gammapy/maps/tests/test_geom.py
  gammapy/maps/wcsnd.py
Labels: cleanup

#1648 Add unit, meta and geom property setter in Map base class
  gammapy/cube/exposure.py
  gammapy/maps/base.py
  gammapy/maps/geom.py
  gammapy/maps/hpx.py
  gammapy/maps/hpxmap.py
  gammapy/maps/hpxnd.py
  gammapy/maps/tests/test_base.py
  gammapy/maps/wcs.py
  gammapy/maps/wcsmap.py
  gammapy/maps/wcsnd.py
Labels: cleanup

#1634 Add SkyDiffuseCube model for 3D maps
  gammapy/cube/models.py
  gammapy/cube/tests/test_models.py
  gammapy/image/models/new.py
  gammapy/image/models/tests/test_models.py
Labels: feature

#1649 Make map interp_image a private method
  gammapy/maps/tests/test_wcsnd.py
  gammapy/maps/wcsnd.py
Labels: cleanup

#1653 Consistent argument name model in MapEvaluator and MapFit
  gammapy/cube/fit.py
  gammapy/cube/models.py
  gammapy/cube/tests/test_fit.py
Labels: cleanup

#1639 Simplify map axis handling
  gammapy/cube/counts.py
  gammapy/cube/psf_kernel.py
  gammapy/cube/psf_map.py
  gammapy/cube/tests/test_counts.py
  gammapy/cube/tests/test_psf_kernel.py
  gammapy/cube/tests/test_psf_map.py
  gammapy/maps/geom.py
  gammapy/maps/wcsnd.py
Labels: cleanup

#1650 Introduce gammapy.cube.models?
  docs/cube/index.rst
  gammapy/cube/__init__.py
  gammapy/cube/fit.py
  gammapy/cube/models.py
  gammapy/cube/tests/test_fit.py
  gammapy/cube/tests/test_models.py
  gammapy/utils/serialization/tests/test_xml.py
Labels: cleanup

#1641 Cleanup FluxPointEstimator and SpectrumFitsingle o…
  gammapy/spectrum/fit.py
  gammapy/spectrum/flux_point.py
Labels: cleanup

#1657 Rename to LightCurveTableModel and PhaseCurveTableModel
  gammapy/time/models.py
  gammapy/time/tests/test_models.py
Labels: cleanup

#1655 Modify map cutout method
  gammapy/background/tests/test_reflected.py
  gammapy/cube/make.py
  gammapy/cube/tests/test_make.py
  gammapy/maps/tests/test_wcsnd.py
  gammapy/maps/wcsnd.py
Labels: cleanup

#1656 Make parnames unambigious in minuit interface
  examples/example_2_gauss.py
  gammapy/cube/models.py
  gammapy/spectrum/fit.py
  gammapy/utils/fitting/iminuit.py
  gammapy/utils/fitting/tests/test_iminuit.py
  gammapy/utils/modeling.py
  gammapy/utils/tests/test_modeling.py
Labels: feature

#1658 Bundle skimage block_reduce in gammapy.extern
  .travis.yml
  appveyor.yml
  dev/docker/commands.sh
  docs/conf.py
  docs/install/conda.rst
  docs/install/dependencies.rst
  docs/install/macports.rst
  environment-dev.yml
  gammapy/detect/tests/test_test_statistics.py
  gammapy/extern/__init__.py
  gammapy/extern/skimage.py
  gammapy/maps/tests/test_wcsnd.py
  gammapy/maps/wcsnd.py
  gammapy/scripts/info.py
  setup.py
Labels: cleanup

#1659 Rename SourceLibrary to SkyModels
  examples/example_2_gauss.py
  gammapy/catalog/gammacat.py
  gammapy/catalog/tests/test_gammacat.py
  gammapy/cube/models.py
  gammapy/cube/tests/test_models.py
  gammapy/utils/serialization/tests/test_xml.py
  gammapy/utils/serialization/xml.py
Labels: cleanup

#1660 Fix spectrum energy grouping, use nearest neighbor method
  gammapy/spectrum/energy_group.py
  gammapy/spectrum/tests/test_energy_group.py
Labels: feature

#1662 Minor code cleanup
  examples/example_2_gauss.py
  gammapy/astro/darkmatter/spectra.py
  gammapy/astro/darkmatter/utils.py
  gammapy/cube/models.py
  gammapy/cube/tests/test_psf_kernel.py
  gammapy/data/tests/test_event_list.py
  gammapy/data/tests/test_obs_stats.py
  gammapy/detect/cwt.py
  gammapy/detect/lima.py
  gammapy/detect/test_statistics.py
  gammapy/detect/tests/test_test_statistics.py
  gammapy/image/models/gauss.py
  gammapy/image/profile.py
  gammapy/irf/energy_dispersion.py
  gammapy/irf/tests/test_irf_write.py
  gammapy/maps/hpx.py
  gammapy/maps/hpxnd.py
  gammapy/maps/tests/test_wcs.py
  gammapy/maps/tests/test_wcsnd.py
  gammapy/maps/wcs.py
  gammapy/scripts/cta_sensitivity.py
  gammapy/spectrum/core.py
  gammapy/spectrum/crab.py
  gammapy/spectrum/extract.py
  gammapy/spectrum/fit.py
  gammapy/spectrum/flux_point.py
  gammapy/spectrum/models.py
  gammapy/spectrum/simulation.py
  gammapy/spectrum/tests/test_core.py
  gammapy/spectrum/tests/test_crab.py
  gammapy/spectrum/tests/test_fit.py
  gammapy/spectrum/tests/test_models.py
  gammapy/spectrum/tests/test_simulation.py
  gammapy/stats/tests/test_fit_statistics.py
  gammapy/stats/tests/test_poisson.py
  gammapy/time/lightcurve.py
  gammapy/utils/coordinates/fov.py
  gammapy/utils/docs.py
  gammapy/utils/fitting/iminuit.py
Labels: cleanup

#1661 Remove SpectrumFit _est_errors_iminuit ?
  gammapy/spectrum/fit.py
  gammapy/spectrum/tests/test_results.py
  gammapy/utils/modeling.py
Labels: cleanup

#1666 Cleanup gammapy.astro.darkmatter
  docs/astro/darkmatter/index.rst
  gammapy/astro/darkmatter/spectra.py
  gammapy/astro/darkmatter/tests/test_utils.py
  gammapy/astro/darkmatter/utils.py
Labels: cleanup

#1667 Move gammapy.script.cta_irf to gammapy.irf.io
  gammapy/irf/__init__.py
  gammapy/irf/io.py
  gammapy/irf/tests/test_io.py
  gammapy/scripts/__init__.py
  gammapy/scripts/tests/test_cta_sensitivity.py
Labels: cleanup

#1668 Move SensitivityEstimator to gammapy.spectrum
  gammapy/scripts/__init__.py
  gammapy/spectrum/__init__.py
  gammapy/spectrum/sensitivity.py
  gammapy/spectrum/tests/test_sensitivity.py
Labels: cleanup

#1677 Move 2D multi-Gauss helpers to gammapy.utils
  gammapy/cube/psf_kernel.py
  gammapy/image/models/__init__.py
  gammapy/irf/psf_core.py
  gammapy/irf/psf_table.py
  gammapy/utils/gauss.py
  gammapy/utils/tests/test_gauss.py
Labels: cleanup

#1672 Cleanup SpectrumResult
  gammapy/spectrum/fit.py
  gammapy/spectrum/flux_point.py
  gammapy/spectrum/models.py
  gammapy/spectrum/results.py
  gammapy/spectrum/tests/test_fit.py
  gammapy/spectrum/tests/test_flux_point.py
  gammapy/spectrum/tests/test_models.py
  gammapy/spectrum/tests/test_results.py
Labels: cleanup

#1676 Fix test_integrate_spectrum_ecpl
  gammapy/spectrum/tests/test_utils.py
Labels: cleanup, tests

#1675 Implement excess_matching_significance and add test
  gammapy/stats/poisson.py
  gammapy/stats/tests/test_poisson.py
Labels: feature

#1678 Remove old GaussPSF class
  gammapy/irf/psf_core.py
Labels: cleanup

#1680 Move gammapy/irf/psf_analytical.py -> gammapy/irf/psf_gauss.py
  gammapy/irf/__init__.py
  gammapy/irf/io.py
  gammapy/irf/psf_gauss.py
  gammapy/irf/tests/test_psf_gauss.py
Labels: cleanup

#1682 Another step to improve multi-Gauss PSF code
  gammapy/irf/__init__.py
  gammapy/irf/psf_core.py
  gammapy/irf/psf_gauss.py
  gammapy/irf/tests/test_psf_core.py
  gammapy/irf/tests/test_psf_gauss.py
Labels: cleanup

#1683 Code cleanup from make flake8
  Makefile
  gammapy/cube/background.py
  gammapy/cube/fit.py
  gammapy/detect/tests/test_lima.py
  gammapy/image/measure.py
  gammapy/irf/psf_gauss.py
  gammapy/irf/tests/test_effective_area.py
  gammapy/scripts/tests/test_spectrum_pipe.py
  gammapy/spectrum/fit.py
  gammapy/spectrum/models.py
  gammapy/spectrum/tests/test_models.py
  gammapy/time/period.py
  gammapy/time/plot_periodogram.py
  gammapy/time/tests/test_lightcurve.py
  gammapy/utils/array.py
  gammapy/utils/coordinates/tests/test_fov.py
Labels: cleanup

#1684 Add coding guideline for class repr, str, info
  docs/development/howto.rst
Labels: cleanup

#1685 Add quantity support to MapCoord and MapCoord based methods
  gammapy/maps/base.py
  gammapy/maps/geom.py
  gammapy/maps/tests/test_geom.py
  gammapy/maps/tests/test_wcsnd.py
  gammapy/maps/wcs.py
  gammapy/maps/wcsnd.py
Labels: cleanup, feature

#1687 Added `to_observation_cta` method to `DataStoreObservation`
  examples/example_observation_cta.py
  gammapy/data/observations.py
  gammapy/data/tests/test_observations.py
Labels: feature

#1686 Exchange value by factor and scale in Parameter
  gammapy/spectrum/tests/test_simulation.py
  gammapy/utils/array.py
  gammapy/utils/fitting/iminuit.py
  gammapy/utils/fitting/sherpa.py
  gammapy/utils/fitting/tests/test_sherpa.py
  gammapy/utils/modeling.py
  gammapy/utils/serialization/xml.py
  gammapy/utils/tests/test_modeling.py
Labels: feature

#1690 Fix unit conversion in SpectrumEnergyGroupMaker
  gammapy/spectrum/energy_group.py
  gammapy/spectrum/tests/test_energy_group.py
Labels: bug

#1691 Reactivate Flux Points tests
  gammapy/spectrum/flux_point.py
  gammapy/spectrum/tests/test_flux_point.py
Labels: cleanup, tests

#1688 Correct diagonal matrix creation in EnergyDispersion
  gammapy/cube/fit.py
  gammapy/cube/tests/test_fit.py
  gammapy/cube/tests/test_models.py
  gammapy/irf/energy_dispersion.py
  gammapy/irf/tests/test_energy_dispersion.py
Labels: bug

#1693 Unify unit handling in gammapy.maps
  gammapy/maps/base.py
  gammapy/maps/geom.py
Labels: cleanup

#1674 Improve width argument handling in map methods
  gammapy/maps/tests/test_wcs.py
  gammapy/maps/tests/test_wcsnd.py
  gammapy/maps/wcs.py
  gammapy/maps/wcsnd.py
Labels: bug

#1692 Change Parameter unit to Unit object
  gammapy/spectrum/results.py
  gammapy/utils/modeling.py
  gammapy/utils/serialization/xml.py
  gammapy/utils/tests/test_modeling.py
Labels: cleanup

#1694 Rename ParameterList to Parameters
  docs/spectrum/index.rst
  gammapy/astro/darkmatter/profiles.py
  gammapy/cube/models.py
  gammapy/image/models/core.py
  gammapy/spectrum/crab.py
  gammapy/spectrum/fit.py
  gammapy/spectrum/models.py
  gammapy/spectrum/results.py
  gammapy/spectrum/tests/test_flux_point.py
  gammapy/time/models.py
  gammapy/utils/fitting/iminuit.py
  gammapy/utils/fitting/sherpa.py
  gammapy/utils/fitting/tests/test_iminuit.py
  gammapy/utils/fitting/tests/test_sherpa.py
  gammapy/utils/gauss.py
  gammapy/utils/modeling.py
  gammapy/utils/serialization/xml.py
  gammapy/utils/tests/test_modeling.py
Labels: cleanup

#1695 Introduce `WcsNDMap.convolve()` method
  gammapy/background/ring.py
  gammapy/cube/fit.py
  gammapy/cube/psf_kernel.py
  gammapy/cube/tests/test_psf_kernel.py
  gammapy/detect/kernel.py
  gammapy/detect/lima.py
  gammapy/detect/test_statistics.py
  gammapy/detect/tests/test_lima.py
  gammapy/maps/wcsnd.py
Labels: cleanup, feature

#1696 Add parameter auto scale
  gammapy/cube/tests/test_fit.py
  gammapy/scripts/tests/test_spectrum_pipe.py
  gammapy/spectrum/flux_point.py
  gammapy/spectrum/tests/test_fit.py
  gammapy/utils/fitting/iminuit.py
  gammapy/utils/fitting/sherpa.py
  gammapy/utils/fitting/tests/test_iminuit.py
  gammapy/utils/modeling.py
  gammapy/utils/tests/test_modeling.py
Labels: feature

#1681 Make image mapmaker
  gammapy/cube/exposure.py
  gammapy/cube/make.py
  gammapy/cube/tests/test_exposure.py
  gammapy/cube/tests/test_make.py
Labels: feature

#1697 Follow up PR to #1695
  gammapy/cube/tests/test_psf_kernel.py
  gammapy/detect/lima.py
  gammapy/detect/tests/test_lima.py
  gammapy/maps/tests/test_wcsnd.py
  gammapy/maps/wcsnd.py
Labels: cleanup

#1704 Add test for KernelBackgroundEstimator without defaults
  gammapy/detect/kernel.py
  gammapy/detect/tests/test_kernel.py
Labels: bug, tests

#1703 Merge SkySumModel and SkyModels
  gammapy/catalog/hess.py
  gammapy/catalog/tests/test_hess.py
  gammapy/cube/models.py
  gammapy/cube/tests/test_models.py
Labels: cleanup

#1706 Rewrite test for gammapy.stats.fit_statistics
  dev/sherpa/stats/produce_test_values.py
  gammapy/stats/tests/test_fit_statistics.py
Labels: cleanup, tests

#1702 Add exclusion mask handling to MapFit
  gammapy/cube/fit.py
  gammapy/cube/tests/test_fit.py
Labels: feature

#1708 Update parameter scaling mechanism
  gammapy/utils/fitting/iminuit.py
  gammapy/utils/fitting/sherpa.py
  gammapy/utils/modeling.py
  gammapy/utils/tests/test_modeling.py
Labels: cleanup, feature

#1709 What's new, changelog and announcement for v0.8
  CHANGES.rst
  dev/notes/announce-0.8.txt
  docs/maps/index.rst
Labels: docs

#1710 Clean up TableModel implementation
  gammapy/astro/darkmatter/spectra.py
  gammapy/spectrum/models.py
  gammapy/spectrum/tests/test_models.py
Labels: cleanup

#1711 Clean up map reprojection
  docs/cube/index.rst
  docs/data/index.rst
  docs/maps/index.rst
  gammapy/maps/base.py
  gammapy/maps/hpxnd.py
  gammapy/maps/tests/test_base.py
  gammapy/maps/wcsnd.py
Labels: cleanup

#1713 Improve plot_interactive() method
  gammapy/maps/base.py
  gammapy/maps/hpxnd.py
  gammapy/maps/wcsnd.py
Labels: cleanup, feature

#1716 Remove copy option in gammapy.maps get_image, slice and cutout methods
  gammapy/background/ring.py
  gammapy/maps/base.py
  gammapy/maps/geom.py
  gammapy/maps/hpx.py
  gammapy/maps/tests/test_base.py
  gammapy/maps/wcs.py
  gammapy/maps/wcsnd.py
Labels: cleanup

#1721 Fix Sphinx nitpicky warnings
  CHANGES.rst
  docs/astro/darkmatter/index.rst
  docs/astro/index.rst
  docs/catalog/index.rst
  docs/development/howto.rst
  docs/development/intro.rst
  docs/install/dependencies.rst
  docs/maps/index.rst
  docs/scripts/index.rst
  docs/time/period.rst
  docs/utils/index.rst
  gammapy/catalog/fermi.py
  gammapy/catalog/gammacat.py
  gammapy/catalog/hess.py
  gammapy/catalog/registry.py
  gammapy/cube/fit.py
  gammapy/cube/models.py
  gammapy/cube/psf_kernel.py
  gammapy/data/data_store.py
  gammapy/data/event_list.py
  gammapy/data/gti.py
  gammapy/data/obs_stats.py
  gammapy/data/obs_summary.py
  gammapy/data/observations.py
  gammapy/image/asmooth.py
  gammapy/image/models/core.py
  gammapy/irf/background.py
  gammapy/irf/io.py
  gammapy/maps/base.py
  gammapy/maps/geom.py
  gammapy/maps/hpxmap.py
  gammapy/maps/wcsnd.py
  gammapy/spectrum/fit.py
  gammapy/spectrum/flux_point.py
  gammapy/spectrum/models.py
  gammapy/spectrum/results.py
  gammapy/spectrum/sensitivity.py
  gammapy/stats/poisson.py
  gammapy/stats/significance.py
  gammapy/time/lightcurve.py
  gammapy/time/models.py
  gammapy/time/period.py
  gammapy/time/plot_periodogram.py
  gammapy/time/tests/test_period.py
  gammapy/utils/coordinates/other.py
  gammapy/utils/fits.py
  gammapy/utils/modeling.py
  gammapy/utils/time.py
Labels: cleanup, docs

#1722 Change many OrderedDict to dict
  gammapy/astro/population/spatial.py
  gammapy/astro/population/velocity.py
  gammapy/background/ring.py
  gammapy/catalog/registry.py
  gammapy/data/obs_stats.py
  gammapy/data/observers.py
  gammapy/detect/cwt.py
  gammapy/detect/test_statistics.py
  gammapy/image/asmooth.py
  gammapy/maps/geom.py
  gammapy/maps/hpx.py
  gammapy/spectrum/cosmic_ray.py
  gammapy/spectrum/powerlaw.py
Labels: cleanup

#1723 Code cleanup
  gammapy/catalog/fermi.py
  gammapy/catalog/tests/test_fermi.py
  gammapy/catalog/tests/test_gammacat.py
  gammapy/cube/make.py
  gammapy/cube/tests/test_exposure.py
  gammapy/cube/tests/test_fit.py
  gammapy/cube/tests/test_psf_kernel.py
  gammapy/detect/lima.py
  gammapy/detect/tests/test_lima.py
  gammapy/detect/tests/test_test_statistics.py
  gammapy/maps/geom.py
  gammapy/maps/hpx.py
  gammapy/maps/hpxnd.py
  gammapy/maps/tests/test_base.py
  gammapy/maps/tests/test_hpxmap.py
  gammapy/maps/tests/test_hpxsparse.py
  gammapy/maps/tests/test_sparse.py
  gammapy/maps/tests/test_wcs.py
  gammapy/maps/tests/test_wcsnd.py
  gammapy/maps/utils.py
  gammapy/maps/wcs.py
  gammapy/maps/wcsnd.py
  gammapy/spectrum/models.py
  gammapy/spectrum/tests/test_models.py
  gammapy/utils/distributions/general_random.py
  gammapy/utils/distributions/tests/test_general_random.py
  gammapy/utils/fitting/tests/test_iminuit.py
  gammapy/utils/modeling.py
  gammapy/utils/scripts.py
  gammapy/utils/table.py
  gammapy/utils/tests/test_scripts.py
Labels: cleanup

#1726 Clean up test stdout output
  gammapy/catalog/core.py
  gammapy/catalog/tests/test_core.py
  gammapy/catalog/tests/test_fermi.py
  gammapy/catalog/tests/test_gammacat.py
  gammapy/catalog/tests/test_registry.py
  gammapy/data/tests/test_observers.py
  gammapy/detect/lima.py
  gammapy/image/measure.py
  gammapy/irf/psf_king.py
  gammapy/maps/geom.py
  gammapy/maps/tests/test_hpx.py
  gammapy/spectrum/extract.py
  gammapy/utils/tests/test_nddata.py
Labels: cleanup

#1671 Improve SensitivityEstimator
  gammapy/spectrum/sensitivity.py
  gammapy/spectrum/tests/test_sensitivity.py
Labels: cleanup

#1730 Make Map.plot_interactive() work for ND
  gammapy/maps/base.py
Labels: feature

#1727 Skip tests of notebooks if version package does not match
  test_notebooks.py
Labels: tests

#1712 Links specific notebooks in Binder
  docs/tutorials.rst
  environment-dev.yml
  gammapy/utils/docs.py
Labels: docs

#1731 Fix and unify `Map.iter_by_image()` behaviour
  docs/maps/index.rst
  gammapy/background/ring.py
  gammapy/maps/base.py
  gammapy/maps/hpxnd.py
  gammapy/maps/tests/test_base.py
  gammapy/maps/tests/test_wcsnd.py
  gammapy/maps/wcsnd.py
Labels: bug, cleanup

#1732 Fix or disable pylint errors
  Makefile
  gammapy/__main__.py
  gammapy/astro/population/tests/test_spatial.py
  gammapy/background/reflected.py
  gammapy/cube/models.py
  gammapy/data/event_list.py
  gammapy/data/observations.py
  gammapy/data/tests/test_pointing.py
  gammapy/image/plotting.py
  gammapy/irf/psf_gauss.py
  gammapy/irf/psf_table.py
  gammapy/maps/hpx.py
  gammapy/scripts/main.py
  gammapy/spectrum/energy_group.py
  gammapy/spectrum/fit.py
  gammapy/spectrum/observation.py
  gammapy/stats/feldman_cousins.py
  gammapy/stats/fit_statistics.py
  gammapy/utils/distributions/general_random.py
  gammapy/utils/docs.py
  gammapy/utils/energy.py
Labels: cleanup

#1739 Add make black command
  Makefile
  gammapy/__init__.py
  gammapy/conftest.py
  gammapy/datasets/__init__.py
  gammapy/datasets/core.py
  gammapy/datasets/load.py
  gammapy/datasets/setup_package.py
  gammapy/datasets/tests/test_load.py
Labels: cleanup

#1741 Add Fermipy build and activate Sherpa dev build in .travis.yml
  .travis.yml
Labels: infrastructure, tests

#1719 Default print_level=0 for iminuit?
  gammapy/utils/fitting/iminuit.py
Labels: cleanup

#1746 Unify and fix testing of .plot() methods
  docs/development/howto.rst
  gammapy/background/tests/test_reflected.py
  gammapy/data/tests/test_event_list.py
  gammapy/data/tests/test_obs_summary.py
  gammapy/image/tests/test_profile.py
  gammapy/irf/tests/test_effective_area.py
  gammapy/irf/tests/test_energy_dispersion.py
  gammapy/irf/tests/test_io.py
  gammapy/irf/tests/test_psf_3d.py
  gammapy/irf/tests/test_psf_table.py
  gammapy/maps/tests/test_hpxmap.py
  gammapy/maps/tests/test_wcsnd.py
  gammapy/maps/wcsnd.py
  gammapy/spectrum/tests/test_core.py
  gammapy/spectrum/tests/test_fit.py
  gammapy/spectrum/tests/test_flux_point.py
  gammapy/spectrum/tests/test_models.py
  gammapy/spectrum/tests/test_observation.py
  gammapy/spectrum/tests/test_results.py
  gammapy/time/tests/test_lightcurve.py
  gammapy/utils/testing.py
Labels: cleanup, tests

#1748 Introduce DataStoreChecker and ObservationChecker
  gammapy/data/data_store.py
  gammapy/data/event_list.py
  gammapy/data/hdu_index_table.py
  gammapy/data/tests/test_data_store.py
  gammapy/data/tests/test_event_list.py
  gammapy/irf/psf_check.py
Labels: cleanup, feature

#1750 Remove EventListDataset class
  gammapy/data/event_list.py
  gammapy/data/tests/test_event_list.py
Labels: cleanup

#1751 Improve EventList and data checkers
  gammapy/data/data_store.py
  gammapy/data/event_list.py
  gammapy/data/gti.py
  gammapy/data/observations.py
  gammapy/data/tests/test_data_store.py
  gammapy/data/tests/test_event_list.py
  gammapy/data/tests/test_observations.py
  gammapy/irf/psf_check.py
  gammapy/utils/testing.py
Labels: cleanup, feature

#1749 Minor clean up cube models
  gammapy/cube/fit.py
  gammapy/cube/models.py
  gammapy/cube/tests/test_models.py
Labels: cleanup

#1752 Remove unused map utility functions
  gammapy/maps/hpx.py
  gammapy/maps/wcs.py
Labels: cleanup

#1754 Add SkyDiffuseMap normalization option
  gammapy/image/models/core.py
  gammapy/image/models/tests/test_core.py
Labels: feature

#1753 Update HESS data files used in tests and examples
  gammapy/background/tests/test_reflected.py
  gammapy/data/data_store.py
  gammapy/data/event_list.py
  gammapy/data/hdu_index_table.py
  gammapy/data/obs_summary.py
  gammapy/data/tests/test_data_store.py
  gammapy/data/tests/test_event_list.py
  gammapy/data/tests/test_hdu_index_table.py
  gammapy/data/tests/test_obs_stats.py
  gammapy/data/tests/test_obs_summary.py
  gammapy/data/tests/test_observations.py
  gammapy/irf/psf_3d.py
  gammapy/irf/tests/test_effective_area.py
  gammapy/irf/tests/test_fits_prod.py
  gammapy/scripts/tests/test_spectrum_pipe.py
  gammapy/spectrum/tests/test_extract.py
  gammapy/time/tests/test_lightcurve.py
  gammapy/utils/serialization/xml.py
Labels: cleanup, docs, tests
