Repository gammapy/gammapy, pull requests merged in 2018-06, with the labels that each got.

#1421 Add map region mask
  gammapy/maps/base.py
  gammapy/maps/tests/test_geom.py
  gammapy/maps/tests/test_wcsnd.py
  gammapy/maps/wcs.py
  gammapy/maps/wcsnd.py
Labels: feature

#1415 Add gammapy.astro.darkmatter
  docs/astro/darkmatter/index.rst
  docs/astro/index.rst
  docs/tutorials.rst
  gammapy/astro/darkmatter/__init__.py
  gammapy/astro/darkmatter/profiles.py
  gammapy/astro/darkmatter/spectra.py
  gammapy/astro/darkmatter/utils.py
Labels: feature

#1433 Fix map write for custom axis name
  gammapy/maps/geom.py
  gammapy/maps/tests/test_wcsnd.py
Labels: bug

#1435 Add __repr__ methods to Maps and related classes
  gammapy/maps/base.py
  gammapy/maps/geom.py
  gammapy/maps/hpx.py
  gammapy/maps/tests/test_base.py
  gammapy/maps/tests/test_geom.py
  gammapy/maps/tests/test_hpx.py
  gammapy/maps/tests/test_wcs.py
  gammapy/maps/wcs.py
  gammapy/maps/wcsnd.py
Labels: feature

#1434 Fix gamma_rate in SpectrumObervation.stats_in_range
  gammapy/data/obs_stats.py
  gammapy/spectrum/observation.py
Labels: bug

#1439 Handling binsz and width units in Map.create
  gammapy/maps/base.py
  gammapy/maps/hpx.py
  gammapy/maps/tests/test_base.py
  gammapy/maps/wcs.py
Labels: cleanup

#1438 Add get image convenience methods to maps
  docs/tutorials.rst
  gammapy/maps/base.py
  gammapy/maps/geom.py
  gammapy/maps/tests/test_base.py
  gammapy/maps/wcs.py
Labels: feature

#1443 Add `.slice_by_idx()` methods to gammapy maps
  docs/maps/index.rst
  gammapy/maps/base.py
  gammapy/maps/geom.py
  gammapy/maps/hpx.py
  gammapy/maps/tests/test_base.py
  gammapy/maps/wcs.py
Labels: feature

#1446 Add WCS map cutout method
  gammapy/maps/tests/test_wcsnd.py
  gammapy/maps/wcsnd.py
Labels: feature
