Repository gammapy/gammapy, pull requests merged in 2018-09, with the labels that each got.

#1761 Add black notebooks functionality
  black_notebooks.py
Labels: docs

#1760 Add conda env file for release v0.8
  environment.yml
Labels: feature

#1365 Change testing of notebooks to testipynb
  .travis.yml
  environment-dev.yml
  test_notebooks.py
Labels: tests

#1382 Improved and transparent favicon
  docs/_static/gammapy_logo.ico
Labels: cleanup, docs

#1369 Download data and notebooks with CLI gammapy download
  gammapy/scripts/download.py
  gammapy/scripts/main.py
Labels: feature

#1759 Add find_peaks in gammapy.image
  .travis.yml
  CHANGES.rst
  docs/conf.py
  docs/install/conda.rst
  docs/install/dependencies.rst
  docs/install/macports.rst
  docs/install/other.rst
  environment-dev.yml
  environment.yml
  gammapy/conftest.py
  gammapy/image/measure.py
  gammapy/image/tests/test_measure.py
  gammapy/scripts/info.py
  setup.py
Labels: bug, cleanup

#1762 Move find_peaks to gammapy.detect
  gammapy/detect/__init__.py
  gammapy/detect/find.py
  gammapy/detect/tests/test_find.py
  gammapy/image/measure.py
  gammapy/image/tests/test_measure.py
Labels: cleanup

#1771 Require iminuit 1.3.2
  environment-dev.yml
  environment.yml
  gammapy/utils/fitting/tests/test_iminuit.py
  setup.py
Labels: bug, tests

#1758 Rename regions as_patch to as_artist
  gammapy/background/reflected.py
  gammapy/background/tests/test_reflected.py
Labels: astropy, cleanup, upstream

#1736 Remove or fix HpxToWcsMapping read method
  gammapy/maps/hpx.py
Labels: bug, cleanup, question

#1769 MapFit fails with integer mask
  gammapy/cube/fit.py
Labels: bug

#1766 gammapy jupyter CLI to perform global actions on notebooks
  .travis.yml
  black_notebooks.py
  environment-dev.yml
  gammapy/scripts/jupyter.py
  gammapy/scripts/main.py
Labels: docs

#1772 test_notebooks.py uses gammapy.scripts.jupyter.test_notebook
  .travis.yml
  environment-dev.yml
  test_notebooks.py
Labels: cleanup

#1767 Showing two decimals in energy
  gammapy/maps/base.py
Labels: cleanup

#1724 Support Python 3.7
  .travis.yml
  appveyor.yml
  gammapy/time/tests/test_lightcurve.py
Labels: infrastructure, tests

#1775 Change HDUIndexTable.get_hdu to leave FITS file open
  gammapy/data/hdu_index_table.py
  gammapy/data/tests/test_hdu_index_table.py
Labels: bug

#1777 Propagate opts_minuit in fitting functions
  gammapy/scripts/spectrum_pipe.py
  gammapy/spectrum/fit.py
Labels: feature

#1763 Improvement of gammapy download
  gammapy/scripts/download.py
  gammapy/scripts/main.py
Labels: feature

#1776 Fix map docs examples
  docs/maps/index.rst
  gammapy/maps/base.py
  gammapy/maps/geom.py
  gammapy/maps/tests/test_base.py
  gammapy/maps/wcs.py
Labels: bug, docs

#1782 Fix opts_minuit handling in fit_minuit()
  gammapy/spectrum/flux_point.py
  gammapy/utils/fitting/iminuit.py
Labels: bug

#1781 Add tests for gammapy download
  gammapy/scripts/tests/test_download.py
Labels: tests

#1785 Unify API of Gammapy Fit classes
  docs/spectrum/index.rst
  gammapy/cube/fit.py
  gammapy/cube/models.py
  gammapy/cube/tests/test_fit.py
  gammapy/scripts/spectrum_pipe.py
  gammapy/spectrum/fit.py
  gammapy/spectrum/flux_point.py
  gammapy/spectrum/tests/test_fit.py
  gammapy/spectrum/tests/test_flux_point.py
  gammapy/utils/fitting/__init__.py
  gammapy/utils/fitting/base.py
  gammapy/utils/fitting/iminuit.py
  gammapy/utils/fitting/tests/test_iminuit.py
Labels: cleanup

#1787 Move Parameter and Parameters to gammapy.utils.fitting
  docs/utils/index.rst
  gammapy/astro/darkmatter/profiles.py
  gammapy/cube/models.py
  gammapy/image/models/core.py
  gammapy/spectrum/crab.py
  gammapy/spectrum/models.py
  gammapy/spectrum/tests/test_flux_point.py
  gammapy/time/models.py
  gammapy/utils/fitting/__init__.py
  gammapy/utils/fitting/fit.py
  gammapy/utils/fitting/parameter.py
  gammapy/utils/fitting/tests/test_iminuit.py
  gammapy/utils/fitting/tests/test_parameter.py
  gammapy/utils/fitting/tests/test_sherpa.py
  gammapy/utils/serialization/xml.py
Labels: cleanup

#1789 Further improve Fit class
  docs/spectrum/fitting.rst
  docs/spectrum/index.rst
  examples/example_2_gauss.py
  gammapy/cube/tests/test_fit.py
  gammapy/scripts/spectrum_pipe.py
  gammapy/spectrum/fit.py
  gammapy/spectrum/flux_point.py
  gammapy/spectrum/tests/test_fit.py
  gammapy/spectrum/tests/test_flux_point.py
  gammapy/utils/fitting/fit.py
  gammapy/utils/fitting/iminuit.py
  gammapy/utils/fitting/sherpa.py
  gammapy/utils/fitting/tests/test_iminuit.py
  gammapy/utils/fitting/tests/test_sherpa.py
Labels: cleanup, feature

#1786 Add option for downloading the whole tutorials pack
  gammapy/scripts/download.py
  gammapy/scripts/downloadclass.py
  gammapy/scripts/jupyter.py
  gammapy/scripts/main.py
  gammapy/scripts/tests/test_download.py
Labels: feature

#1794 Improve EventList plots
  gammapy/data/event_list.py
  gammapy/data/tests/test_event_list.py
Labels: feature

#1796 Update HESS 4 Crab example dataset
  docs/data/index.rst
  docs/getting-started.rst
  docs/spectrum/fitting.rst
  docs/spectrum/index.rst
  gammapy/data/event_list.py
  gammapy/spectrum/observation.py
  gammapy/spectrum/tests/test_fit.py
  gammapy/spectrum/tests/test_flux_point.py
  gammapy/spectrum/tests/test_observation.py
  gammapy/spectrum/tests/test_results.py
  tutorials/notebooks.yaml
  tutorials/spectrum_models.ipynb
Labels: cleanup

#1793 Simplify init function of `DataStore` class
  gammapy/data/data_store.py
  gammapy/data/tests/test_data_store.py
Labels: cleanup

#1800 Add ObservationTableChecker and improve EVENTS checker
  gammapy/data/data_store.py
  gammapy/data/event_list.py
  gammapy/data/obs_table.py
  gammapy/data/tests/test_data_store.py
  gammapy/data/tests/test_obs_table.py
Labels: feature

#1799 Fix EnergyDispersion write and to_sherpa
  gammapy/irf/energy_dispersion.py
  gammapy/spectrum/tests/test_observation.py
Labels: bug

#1801 Process tutorials
  .gitignore
  .travis.yml
  Makefile
  process_tutorials.py
  tutorials/images/cta-1dc.png
  tutorials/images/gammapy_datastore_butler.png
  tutorials/images/gammapy_maps.png
Labels: docs

#1806 Fix datasets access in tutorials and CI
  .travis.yml
  gammapy/scripts/jupyter.py
  process_tutorials.py
  test_notebooks.py
  tutorials/analysis_3d.ipynb
  tutorials/astropy_introduction.ipynb
  tutorials/cta_data_analysis.ipynb
  tutorials/cta_sensitivity.ipynb
  tutorials/detect_ts.ipynb
  tutorials/image_fitting_with_sherpa.ipynb
  tutorials/intro_maps.ipynb
  tutorials/light_curve.ipynb
  tutorials/nddata_demo.ipynb
  tutorials/notebooks.yaml
  tutorials/simulate_3d.ipynb
  tutorials/spectrum_analysis.ipynb
  tutorials/spectrum_pipe.ipynb
  tutorials/spectrum_simulation.ipynb
  tutorials/spectrum_simulation_cta.ipynb
Labels: docs

#1802 Adding Binder space for Gammapy repo
  Dockerfile
  README.rst
  binder.py
  gammapy/utils/docs.py
Labels: docs

#1807 Change smoothing kernel definitions to match that of astropy
  docs/image/survey_example.py
  gammapy/data/event_list.py
  gammapy/maps/tests/test_wcsnd.py
  gammapy/maps/wcsnd.py
Labels: cleanup, feature

#1808 Rewrite getting started, improve tutorials and install pages
  docs/getting-started.rst
  docs/index.rst
  docs/install/index.rst
  docs/references.txt
  docs/tutorials.rst
Labels: docs

#1809 Adapt tutorials to the new Map.smooth() signature
  tutorials/analysis_3d.ipynb
  tutorials/astropy_introduction.ipynb
  tutorials/cta_data_analysis.ipynb
  tutorials/first_steps.ipynb
  tutorials/image_fitting_with_sherpa.ipynb
  tutorials/intro_maps.ipynb
Labels: docs

#1810 Change CTADATA to GAMMAPY_DATA in notebooks
  process_tutorials.py
  tutorials/analysis_3d.ipynb
  tutorials/cta_1dc_introduction.ipynb
  tutorials/cta_data_analysis.ipynb
  tutorials/simulate_3d.ipynb
  tutorials/spectrum_simulation_cta.ipynb
Labels: docs

#1815 Dataset access in notebooks with $GAMMAPY_DATA
  .travis.yml
  process_tutorials.py
  test_notebooks.py
  tutorials/astropy_introduction.ipynb
  tutorials/cwt.ipynb
  tutorials/detect_ts.ipynb
  tutorials/fermi_lat.ipynb
  tutorials/first_steps.ipynb
  tutorials/image_fitting_with_sherpa.ipynb
  tutorials/intro_maps.ipynb
  tutorials/light_curve.ipynb
  tutorials/spectrum_analysis.ipynb
  tutorials/spectrum_fitting_with_sherpa.ipynb
  tutorials/spectrum_pipe.ipynb
Labels: cleanup, docs

#1814 Remove Github API in gammapy download CLI
  gammapy/scripts/download.py
  gammapy/scripts/downloadclass.py
  gammapy/scripts/main.py
  test_notebooks.py
  tutorials/notebooks.yaml
Labels: cleanup, docs

#1812 Add likelihood profile methods to `Fit`
  gammapy/spectrum/fit.py
  gammapy/spectrum/tests/test_fit.py
  gammapy/spectrum/tests/test_flux_point.py
  gammapy/utils/fitting/fit.py
Labels: cleanup, feature

#1817 Update on install and getting started documentation
  docs/getting-started.rst
  docs/references.txt
  docs/tutorials.rst
Labels: docs

#1818 Add HESS make background model tutorial
  tutorials/background_model.ipynb
Labels: docs

#1821 Improve analysis 3D tutorial
  gammapy/cube/models.py
  gammapy/cube/tests/test_fit.py
  gammapy/utils/fitting/parameter.py
  tutorials/analysis_3d.ipynb
Labels: docs

#1822 Use GAMMAPY_DATA in Gammapy codebase
  docs/catalog/gammacat.rst
  docs/data/index.rst
  docs/detect/index.rst
  docs/image/index.rst
  docs/image/survey_example.py
  docs/maps/index.rst
  docs/scripts/index.rst
  docs/spectrum/fitting.rst
  docs/spectrum/index.rst
  docs/time/index.rst
  examples/example_2_gauss.py
  examples/example_observation_cta.py
  gammapy/astro/darkmatter/spectra.py
  gammapy/catalog/fermi.py
  gammapy/catalog/gammacat.py
  gammapy/catalog/hawc.py
  gammapy/cube/counts.py
  gammapy/cube/psf_kernel.py
  gammapy/cube/psf_map.py
  gammapy/cube/tests/test_background.py
  gammapy/cube/tests/test_exposure.py
  gammapy/cube/tests/test_fit.py
  gammapy/data/data_store.py
  gammapy/data/event_list.py
  gammapy/data/gti.py
  gammapy/detect/cwt.py
  gammapy/irf/background.py
  gammapy/irf/effective_area.py
  gammapy/irf/tests/test_effective_area.py
  gammapy/irf/tests/test_psf_gauss.py
  gammapy/spectrum/models.py
  gammapy/spectrum/observation.py
  gammapy/spectrum/sensitivity.py
  gammapy/utils/fits.py
  tutorials/cta_sensitivity.ipynb
  tutorials/notebooks.yaml
Labels: cleanup

#1823 Speed up download with multiprocessing
  gammapy/scripts/downloadclass.py
Labels: docs, feature
