Repository gammapy/gammapy, pull requests merged in 2019-03, with the labels that each got.

#2062 Show clear traceback when AtProduction_gammas.dat dataset not found
  gammapy/astro/darkmatter/spectra.py
Labels: cleanup

#2065 Added evaluation radius for the SkyEllipse model, and a test
  gammapy/image/models/core.py
  gammapy/image/models/tests/test_core.py
Labels: feature

#2050 Notebook for 3D joint analysis
  tutorials/analysis_3d.ipynb
  tutorials/analysis_3d_joint.ipynb
  tutorials/notebooks.yaml
Labels: feature

#2066 Add SkyModel.position and frame attribute
  gammapy/catalog/tests/test_hess.py
  gammapy/cube/fit.py
  gammapy/cube/models.py
  gammapy/cube/tests/test_models.py
  gammapy/image/models/core.py
  gammapy/image/models/tests/test_core.py
  gammapy/maps/tests/test_wcs.py
  gammapy/maps/tests/test_wcsnd.py
  gammapy/maps/wcs.py
  tutorials/analysis_3d.ipynb
  tutorials/fermi_lat.ipynb
  tutorials/hess.ipynb
Labels: feature

#2070 Fix gammapy jupyter for last version of jupyter
  gammapy/scripts/jupyter.py
Labels: bug

#2069 Add scipy as fitting backend
  gammapy/utils/fitting/iminuit.py
  gammapy/utils/fitting/parameter.py
  gammapy/utils/fitting/scipy.py
  gammapy/utils/fitting/tests/test_iminuit.py
  gammapy/utils/fitting/tests/test_scipy.py
  gammapy/utils/fitting/tests/test_sherpa.py
Labels: feature

#2063 Dark matter annihilation flux / spectral model
  gammapy/astro/darkmatter/spectra.py
  gammapy/astro/darkmatter/tests/test_spectra.py
  gammapy/astro/darkmatter/tests/test_utils.py
  gammapy/astro/darkmatter/utils.py
  tutorials/astro_dark_matter.ipynb
Labels: feature

#2038 Tutorial for pulsar analysis
  tutorials/pulsar_analysis.ipynb
Labels: docs

#2064 A convenience function to simulate a dataset
  gammapy/cube/simulate.py
  gammapy/cube/tests/test_simulate.py
Labels: feature

#2071 Implement MapDataset npred evaluation using cutouts
  gammapy/cube/fit.py
  gammapy/cube/models.py
  gammapy/cube/tests/test_fit.py
  tutorials/analysis_3d.ipynb
  tutorials/fermi_lat.ipynb
  tutorials/hess.ipynb
  tutorials/simulate_3d.ipynb
Labels: cleanup, feature

#2076 Clean up `maps/wcs.py`
  gammapy/cube/tests/test_psf_kernel.py
  gammapy/cube/tests/test_simulate.py
  gammapy/maps/base.py
  gammapy/maps/hpx.py
  gammapy/maps/hpxnd.py
  gammapy/maps/tests/test_base.py
  gammapy/maps/tests/test_wcs.py
  gammapy/maps/tests/test_wcsnd.py
  gammapy/maps/wcs.py
  gammapy/maps/wcsnd.py
Labels: cleanup

#2080 Simplify Parameters init
  gammapy/spectrum/crab.py
  gammapy/spectrum/tests/test_flux_point.py
  gammapy/utils/fitting/model.py
  gammapy/utils/fitting/parameter.py
Labels: cleanup

#2082 Fix minuit frozen pars handling in Fit.confidence()
  gammapy/utils/fitting/iminuit.py
  gammapy/utils/fitting/parameter.py
  gammapy/utils/fitting/tests/test_fit.py
  gammapy/utils/fitting/tests/test_parameter.py
Labels: bug

#2077 MCMC tutorial with emcee
  docs/tutorials.rst
  tutorials/images/MCMC-gammapy.png
  tutorials/mcmc_sampling.ipynb
  tutorials/notebooks.yaml
Labels: docs

#2086 Fix test_likelihood_profile in test_flux_point.py
  gammapy/spectrum/tests/test_flux_point.py
Labels: tests

#2088 Set Cython language_level=3
  gammapy/detect/_test_statistics_cython.pyx
  gammapy/maps/_sparse.pyx
Labels: cleanup

#322 Add code quality build in CI
  Makefile
  azure-pipelines.yml
  gammapy/astro/darkmatter/spectra.py
  gammapy/astro/darkmatter/utils.py
  gammapy/cube/counts.py
  gammapy/cube/fit.py
  gammapy/cube/models.py
  gammapy/image/models/core.py
  gammapy/image/plotting.py
  gammapy/irf/irf_reduce.py
  gammapy/irf/tests/test_irf_reduce.py
  gammapy/irf/tests/test_psf_table.py
  gammapy/spectrum/flux_point.py
  gammapy/spectrum/tests/test_flux_point.py
  gammapy/stats/data.py
  gammapy/time/models.py
Labels: cleanup, infrastructure

#2084 Read field-of-view coordinate system definition from BKG FITS header
  gammapy/cube/make.py
  gammapy/irf/background.py
Labels: feature

#2058 Add MapMakerRing class
  gammapy/background/background_estimate.py
  gammapy/background/ring.py
  gammapy/background/tests/test_ring.py
  gammapy/cube/make.py
  gammapy/cube/tests/test_make.py
  gammapy/detect/lima.py
  tutorials/cta_data_analysis.ipynb
  tutorials/hess.ipynb
  tutorials/image_analysis.ipynb
  tutorials/image_fitting_with_sherpa.ipynb
Labels: feature

#2042 Make datasets index files version-coupled with Gammapy repo
  dev/datasets/README.rst
  dev/datasets/make_dataset_index.py
  gammapy/scripts/downloadclasses.py
Labels: cleanup, docs

#325 Add pydocstyle docstring checker
  Makefile
  gammapy/catalog/fermi.py
  gammapy/catalog/gammacat.py
  gammapy/catalog/hawc.py
  gammapy/catalog/hess.py
  gammapy/cube/__init__.py
  gammapy/cube/edisp_map.py
  gammapy/cube/fit.py
  gammapy/cube/make.py
  gammapy/cube/models.py
  gammapy/cube/psf_kernel.py
  gammapy/cube/psf_map.py
  gammapy/cube/simulate.py
  gammapy/data/obs_summary.py
  gammapy/data/pointing.py
  gammapy/detect/lima.py
  gammapy/image/plotting.py
  gammapy/irf/background.py
  gammapy/irf/effective_area.py
  gammapy/irf/irf_reduce.py
  gammapy/irf/psf_gauss.py
  gammapy/maps/base.py
  gammapy/maps/geom.py
  gammapy/maps/hpx.py
  gammapy/maps/wcs.py
  gammapy/maps/wcsnd.py
  gammapy/spectrum/energy_group.py
  gammapy/spectrum/extract.py
  gammapy/spectrum/fit.py
  gammapy/spectrum/flux_point.py
  gammapy/spectrum/powerlaw.py
  gammapy/spectrum/sensitivity.py
  gammapy/tests/__init__.py
  gammapy/time/lightcurve.py
  gammapy/utils/coordinates/other.py
  gammapy/utils/distributions/general_random.py
  gammapy/utils/distributions/utils.py
  gammapy/utils/docs.py
  gammapy/utils/fits.py
  gammapy/utils/gauss.py
Labels: cleanup, docs, infrastructure

#2092 Remove CompoundSkyModel
  examples/example_2_gauss.py
  gammapy/cube/models.py
  gammapy/cube/tests/test_models.py
Labels: cleanup

#2093 Clean up psf unit handling
  gammapy/catalog/hess.py
  gammapy/irf/psf_3d.py
  gammapy/irf/psf_gauss.py
  gammapy/irf/psf_table.py
  gammapy/spectrum/models.py
  gammapy/utils/interpolation.py
  gammapy/utils/nddata.py
Labels: cleanup

#2085 Modify irfmap stacking
  gammapy/cube/edisp_map.py
  gammapy/cube/psf_map.py
  gammapy/cube/tests/test_edisp_map.py
  gammapy/cube/tests/test_psf_map.py
Labels: feature

#2091 Turn enable_deprecations_as_exceptions on in conftest.py
  gammapy/astro/population/simulate.py
  gammapy/astro/population/tests/test_simulate.py
  gammapy/conftest.py
  gammapy/irf/psf_table.py
  gammapy/maps/base.py
  gammapy/maps/geom.py
  gammapy/spectrum/utils.py
  gammapy/stats/tests/test_feldman_cousins.py
  gammapy/utils/distributions/general_random.py
Labels: tests

#2047 Add SpectrumDataset class
  gammapy/spectrum/fit.py
  gammapy/spectrum/tests/test_fit.py
Labels: feature

#2078 Fix invalid value handling for maps with bool and int data
  gammapy/background/tests/test_reflected.py
  gammapy/maps/base.py
  gammapy/maps/geom.py
  gammapy/maps/hpx.py
  gammapy/maps/hpxnd.py
  gammapy/maps/tests/test_wcsnd.py
  gammapy/maps/utils.py
  gammapy/maps/wcs.py
  gammapy/maps/wcsnd.py
Labels: bug, cleanup

#2097 Tutorial notebook cleanup
  docs/tutorials.rst
  tutorials/images/gammapy_mcmc.png
  tutorials/mcmc_sampling.ipynb
  tutorials/notebooks.yaml
Labels: cleanup, docs

#2098 Remove gammapy.datasets submodule
  docs/datasets/index.rst
  docs/development/dataformats.rst
  gammapy/datasets/__init__.py
  gammapy/datasets/core.py
  gammapy/datasets/datasets.yaml
  gammapy/datasets/load.py
  gammapy/datasets/setup_package.py
  gammapy/datasets/tests/__init__.py
  gammapy/datasets/tests/test_load.py
  gammapy/utils/testing.py
Labels: cleanup

#2100 Remove copy option in PSFMap and EDispMap stack
  gammapy/cube/edisp_map.py
  gammapy/cube/psf_map.py
  gammapy/cube/tests/test_edisp_map.py
  gammapy/cube/tests/test_psf_map.py
Labels: cleanup

#2101 Add Dataset abstract base class
  gammapy/cube/fit.py
  gammapy/spectrum/fit.py
  gammapy/spectrum/flux_point.py
  gammapy/utils/fitting/datasets.py
Labels: feature

#2099 Remove added PyCharm metadata from cells in notebooks
  gammapy/scripts/jupyter.py
Labels: feature
