Repository gammapy/gammapy, pull requests merged in 2019-09, with the labels that each got.

#2330 Migrate SpectrumAnalysisIACT to the high-level interface
  gammapy/scripts/analysis.py
  gammapy/scripts/config/schema.yaml
  gammapy/scripts/tests/test_analysis.py
Labels: feature

#2332 Add dataset-index target to make file
  Makefile
  dev/datasets/make_dataset_index.py
  gammapy/scripts/downloadclasses.py
Labels: feature, infrastructure

#2335 Remove SpectrumAnalysisIACT class
  gammapy/scripts/__init__.py
  gammapy/scripts/analysis.py
  gammapy/scripts/spectrum_pipe.py
  gammapy/scripts/tests/test_analysis.py
  gammapy/scripts/tests/test_spectrum_pipe.py
  tutorials/hess.ipynb
Labels: cleanup

#2321 Dissolve gammapy.image
  docs/image/index.rst
  docs/image/plotting.rst
  docs/maps/colormap_example.py
  docs/maps/index.rst
  docs/maps/plotting.rst
  gammapy/cube/ring.py
  gammapy/detect/__init__.py
  gammapy/detect/asmooth.py
  gammapy/detect/tests/test_asmooth.py
  gammapy/image/__init__.py
  gammapy/maps/__init__.py
  gammapy/maps/image_utils.py
  gammapy/maps/measure.py
  gammapy/maps/plotting.py
  gammapy/maps/profile.py
  gammapy/maps/tests/test_measure.py
  gammapy/maps/tests/test_plotting.py
  gammapy/maps/tests/test_profile.py
  tutorials/hgps.ipynb
Labels: cleanup

#2338 Add model registries and Model.from_dict method
  gammapy/cube/models.py
  gammapy/image/models/__init__.py
  gammapy/image/models/core.py
  gammapy/scripts/analysis.py
  gammapy/spectrum/models.py
  gammapy/spectrum/tests/test_models.py
  gammapy/utils/fitting/model.py
  gammapy/utils/serialization/io.py
Labels: cleanup

#2339 Fix unused TableModel(values_scale=) argument
  gammapy/astro/darkmatter/spectra.py
  gammapy/irf/effective_area.py
  gammapy/spectrum/models.py
Labels: bug, cleanup

#2334 Simplify and extend background model handling
  gammapy/astro/darkmatter/spectra.py
  gammapy/cube/fit.py
  gammapy/cube/models.py
  gammapy/image/models/core.py
  gammapy/maps/base.py
  gammapy/spectrum/models.py
  gammapy/utils/serialization/tests/test_io.py
  tutorials/fermi_lat.ipynb
Labels: cleanup, feature

#2340 Cleanup background model YAML serilization
  gammapy/cube/fit.py
  gammapy/cube/models.py
  gammapy/image/models/core.py
  gammapy/utils/fitting/model.py
  gammapy/utils/serialization/io.py
  gammapy/utils/serialization/tests/data/example2.yaml
  gammapy/utils/serialization/tests/data/examples.yaml
  gammapy/utils/serialization/tests/make_test_data.py
  tutorials/analysis_3d.ipynb
Labels: cleanup

#2344 Change return type of `WcsGeom.get_coord()` to quantities
  gammapy/cube/fit.py
  gammapy/cube/psf_kernel.py
  gammapy/image/models/tests/test_core.py
  gammapy/maps/geom.py
  gammapy/maps/hpxnd.py
  gammapy/maps/tests/test_wcs.py
  gammapy/maps/tests/test_wcsnd.py
  gammapy/maps/wcs.py
  tutorials/analysis_3d.ipynb
  tutorials/fermi_lat.ipynb
  tutorials/image_fitting_with_sherpa.ipynb
Labels: cleanup

#2345 Add `SpectrumDataset.create()`
  gammapy/data/gti.py
  gammapy/data/tests/test_gti.py
  gammapy/spectrum/dataset.py
  gammapy/spectrum/tests/test_dataset.py
Labels: feature

#2218 PIG 13 - Gammapy dependencies and distribution
  docs/development/pigs/index.rst
  docs/development/pigs/pig-013.rst
Labels: pig

#2351 Change OrderedDict to dict
  docs/maps/index.rst
  gammapy/catalog/core.py
  gammapy/catalog/gammacat.py
  gammapy/catalog/hess.py
  gammapy/catalog/tests/test_core.py
  gammapy/catalog/tests/test_gammacat.py
  gammapy/data/obs_table.py
  gammapy/data/observations.py
  gammapy/irf/background.py
  gammapy/irf/effective_area.py
  gammapy/irf/energy_dispersion.py
  gammapy/irf/psf_check.py
  gammapy/maps/base.py
  gammapy/maps/geom.py
  gammapy/maps/hpx.py
  gammapy/maps/hpxmap.py
  gammapy/maps/hpxnd.py
  gammapy/maps/hpxsparse.py
  gammapy/maps/plotting.py
  gammapy/maps/profile.py
  gammapy/maps/tests/test_base.py
  gammapy/maps/tests/test_geom.py
  gammapy/maps/wcs.py
  gammapy/maps/wcsmap.py
  gammapy/maps/wcsnd.py
  gammapy/modeling/models/spectrum/tests/test_crab.py
  gammapy/scripts/info.py
  gammapy/spectrum/dataset.py
  gammapy/spectrum/flux_point.py
  gammapy/time/lightcurve_estimator.py
  gammapy/time/period.py
  gammapy/utils/fits.py
  gammapy/utils/nddata.py
  gammapy/utils/random/inverse_cdf.py
  gammapy/utils/table.py
  gammapy/utils/tests/test_table.py
  setup.cfg
Labels: cleanup

#2333 YAML template for settings in high-level interface
  gammapy/scripts/analysis.py
  gammapy/scripts/config/schema.yaml
  gammapy/scripts/tests/test_analysis.py
Labels: feature

#2346 Add `SpectrumDatasetOnOff.create()`
  gammapy/spectrum/dataset.py
  gammapy/spectrum/tests/test_dataset.py
Labels: feature

#2352 Move models files to gammapy/modeling/models
  docs/utils/index.rst
  gammapy/astro/darkmatter/profiles.py
  gammapy/irf/background.py
  gammapy/modeling/models/__init__.py
  gammapy/modeling/models/cube.py
  gammapy/modeling/models/cube/__init__.py
  gammapy/modeling/models/cube/tests/__init__.py
  gammapy/modeling/models/image/__init__.py
  gammapy/modeling/models/image/tests/__init__.py
  gammapy/modeling/models/spatial.py
  gammapy/modeling/models/spectral.py
  gammapy/modeling/models/spectral_cosmic_ray.py
  gammapy/modeling/models/spectral_crab.py
  gammapy/modeling/models/spectrum/__init__.py
  gammapy/modeling/models/spectrum/tests/__init__.py
  gammapy/modeling/models/tests/test_cube.py
  gammapy/modeling/models/tests/test_spatial.py
  gammapy/modeling/models/tests/test_spectral.py
  gammapy/modeling/models/tests/test_spectral_cosmic_ray.py
  gammapy/modeling/models/tests/test_spectral_crab.py
  gammapy/modeling/models/tests/test_time.py
  gammapy/modeling/models/time.py
  gammapy/modeling/models/time/__init__.py
  gammapy/modeling/models/time/tests/__init__.py
  gammapy/utils/integrate.py
  gammapy/utils/serialization/tests/test_io.py
  gammapy/utils/serialization/tests/test_xml.py
  gammapy/utils/serialization/xml.py
  gammapy/utils/tests/test_integrate.py
Labels: cleanup

#2354 Move gammapy.utils.fitting to gammapy.modeling
  docs/spectrum/fitting.rst
  docs/spectrum/index.rst
  docs/utils/index.rst
  gammapy/astro/darkmatter/profiles.py
  gammapy/astro/darkmatter/spectra.py
  gammapy/cube/fit.py
  gammapy/cube/tests/test_fit.py
  gammapy/modeling/__init__.py
  gammapy/modeling/datasets.py
  gammapy/modeling/fit.py
  gammapy/modeling/iminuit.py
  gammapy/modeling/likelihood.py
  gammapy/modeling/model.py
  gammapy/modeling/models/cube.py
  gammapy/modeling/models/spatial.py
  gammapy/modeling/models/spectral.py
  gammapy/modeling/models/spectral_crab.py
  gammapy/modeling/models/time.py
  gammapy/modeling/parameter.py
  gammapy/modeling/sampling.py
  gammapy/modeling/scipy.py
  gammapy/modeling/sherpa.py
  gammapy/modeling/tests/test_datasets.py
  gammapy/modeling/tests/test_fit.py
  gammapy/modeling/tests/test_iminuit.py
  gammapy/modeling/tests/test_model.py
  gammapy/modeling/tests/test_parameter.py
  gammapy/modeling/tests/test_scipy.py
  gammapy/modeling/tests/test_sherpa.py
  gammapy/scripts/analysis.py
  gammapy/spectrum/dataset.py
  gammapy/spectrum/flux_point.py
  gammapy/spectrum/tests/test_dataset.py
  gammapy/spectrum/tests/test_fit.py
  gammapy/spectrum/tests/test_flux_point.py
  gammapy/time/lightcurve_estimator.py
  gammapy/utils/fitting/__init__.py
  gammapy/utils/fitting/tests/__init__.py
  gammapy/utils/serialization/io.py
  gammapy/utils/serialization/tests/make_test_data.py
  gammapy/utils/serialization/tests/test_io.py
  gammapy/utils/serialization/xml.py
  tutorials/analysis_3d.ipynb
  tutorials/analysis_3d_joint.ipynb
  tutorials/cta_data_analysis.ipynb
  tutorials/fermi_lat.ipynb
  tutorials/hess.ipynb
  tutorials/image_analysis.ipynb
  tutorials/mcmc_sampling.ipynb
  tutorials/pulsar_analysis.ipynb
  tutorials/sed_fitting_gammacat_fermi.ipynb
  tutorials/simulate_3d.ipynb
  tutorials/spectrum_analysis.ipynb
  tutorials/spectrum_simulation.ipynb
Labels: cleanup

#2355 Move gammapy.utils.serialization to gammapy.modeling
  gammapy/modeling/datasets.py
  gammapy/modeling/models/cube.py
  gammapy/modeling/serialize.py
  gammapy/modeling/serialize_xml.py
  gammapy/modeling/tests/data/example2.yaml
  gammapy/modeling/tests/data/examples.yaml
  gammapy/modeling/tests/data/make.py
  gammapy/modeling/tests/test_serialize_xml.py
  gammapy/modeling/tests/test_serialize_yaml.py
  gammapy/utils/serialization/__init__.py
  gammapy/utils/serialization/tests/__init__.py
  setup.cfg
Labels: cleanup

#2356 Add `SpectrumDataset.stack()`
  gammapy/spectrum/dataset.py
  gammapy/spectrum/tests/test_dataset.py
Labels: feature

#2359 Remove `BackgroundModels` class
  gammapy/cube/fit.py
  gammapy/cube/tests/test_fit.py
  gammapy/modeling/datasets.py
  gammapy/modeling/models/cube.py
  gammapy/modeling/models/tests/test_cube.py
  gammapy/modeling/serialize.py
  gammapy/modeling/tests/data/make.py
  gammapy/modeling/tests/test_serialize_yaml.py
  gammapy/utils/scripts.py
Labels: cleanup

#2343 Implement `WcsNDMap.sample()` and remove `MapEventSampler`
  gammapy/maps/tests/test_wcsnd.py
  gammapy/maps/wcsnd.py
  gammapy/utils/random/inverse_cdf.py
  gammapy/utils/random/tests/test_inverse_cdf.py
Labels: cleanup, feature

#2360 Add `SpectrumDatasetOnOff.stack()`
  gammapy/spectrum/dataset.py
  gammapy/spectrum/tests/test_dataset.py
Labels: feature

#2361 Remove `SpectrumDatasetOnOffStacker`and replace it with `Datasets.stack_reduce()`
  gammapy/modeling/datasets.py
  gammapy/scripts/analysis.py
  gammapy/spectrum/dataset.py
  gammapy/spectrum/tests/test_dataset.py
  gammapy/spectrum/tests/test_fit.py
  tutorials/cta_data_analysis.ipynb
  tutorials/pulsar_analysis.ipynb
  tutorials/spectrum_analysis.ipynb
Labels: cleanup, feature

#2358 Adapt MapMakerObs to also compute an EDispMap and PSFMap
  gammapy/cube/make.py
  gammapy/cube/psf_map.py
  gammapy/cube/tests/test_make.py
  gammapy/irf/psf_gauss.py
Labels: feature

#2347 Simplify stacking in edisp map and psf map
  gammapy/cube/edisp_map.py
  gammapy/cube/psf_map.py
  gammapy/cube/tests/test_edisp_map.py
  gammapy/cube/tests/test_psf_map.py
Labels: cleanup

#2365 Remove gammapy/maps/measure.py
  gammapy/maps/__init__.py
  gammapy/maps/measure.py
  gammapy/maps/tests/test_measure.py
Labels: cleanup

#2368 Add MapDataset.create method
  gammapy/cube/fit.py
  gammapy/cube/make.py
  gammapy/cube/psf_map.py
  gammapy/cube/tests/test_fit.py
  gammapy/cube/tests/test_make.py
Labels: feature

#2375 Adapt MapMakerObs to return a MapDataset
  gammapy/cube/make.py
  gammapy/cube/tests/test_make.py
Labels: cleanup, feature

#2370 Major update of Gammapy installation instructions
  docs/development/release.rst
  docs/getting-started.rst
  docs/index.rst
  docs/install/conda.rst
  docs/install/dependencies.rst
  docs/install/index.rst
  docs/install/macports.rst
  docs/install/other.rst
  docs/install/pip.rst
  docs/references.txt
Labels: cleanup, docs

#2371 Merge elongated Gaussian and ellipse sky models with symmetric model classes
  gammapy/catalog/fermi.py
  gammapy/cube/tests/test_fit.py
  gammapy/modeling/models/__init__.py
  gammapy/modeling/models/spatial.py
  gammapy/modeling/models/tests/test_cube.py
  gammapy/modeling/models/tests/test_spatial.py
  gammapy/modeling/tests/data/example2.yaml
  gammapy/modeling/tests/data/make.py
Labels: cleanup

#2364 Add absorbed model serialisation
  gammapy/modeling/models/__init__.py
  gammapy/modeling/models/spectral.py
  gammapy/modeling/tests/test_serialize_yaml.py
Labels: feature

#2372 Add sample method in LightCurveTableModel and PhaseCurveTableModel
  gammapy/modeling/models/tests/test_time.py
  gammapy/modeling/models/time.py
Labels: feature

#2316 WIP: Enable DocSearch for gammapy documentation
  docs/_static/gammapy.css
  docs/_templates/layout.html
  docs/conf.py
Labels: docs

#2378 Initial features for 3D analysis use case in high-level interface
  docs/scripts/index.rst
  gammapy/scripts/analysis.py
  gammapy/scripts/config/schema.yaml
  gammapy/scripts/tests/test_analysis.py
Labels: feature

#2379 Cleanup `WcsNDMap` FITS convention handling
  gammapy/maps/base.py
  gammapy/maps/geom.py
  gammapy/maps/hpx.py
  gammapy/maps/hpxmap.py
  gammapy/maps/hpxnd.py
  gammapy/maps/tests/test_base.py
  gammapy/maps/tests/test_hpxmap.py
  gammapy/maps/tests/test_wcsnd.py
  gammapy/maps/wcs.py
  gammapy/maps/wcsmap.py
  tutorials/fermi_lat.ipynb
Labels: cleanup

#2380 Fix Docsearch
  docs/_static/docsearch.js
  docs/_static/gammapy.css
  docs/_templates/layout.html
  docs/conf.py
  docs/development/howto.rst
Labels: bug

#2377 Implement `WcsGeom` coord caching
  gammapy/cube/fit.py
  gammapy/maps/geom.py
  gammapy/maps/tests/test_wcs.py
  gammapy/maps/tests/test_wcsnd.py
  gammapy/maps/wcs.py
Labels: feature

#2367 Fix SkyPointSource evaluation
  gammapy/cube/fit.py
  gammapy/maps/geom.py
  gammapy/modeling/models/cube.py
  gammapy/modeling/models/spatial.py
  gammapy/modeling/models/tests/test_cube.py
  gammapy/modeling/models/tests/test_spatial.py
Labels: bug

#2381 Add MapDataset.stack
  gammapy/cube/fit.py
  gammapy/cube/tests/test_fit.py
  gammapy/maps/base.py
Labels: cleanup

#2382 Cleanup `MapEvaluator`
  gammapy/cube/fit.py
  gammapy/cube/tests/test_fit.py
  gammapy/maps/geom.py
  gammapy/maps/wcs.py
  gammapy/maps/wcsnd.py
  gammapy/modeling/models/spatial.py
  gammapy/modeling/models/tests/test_cube.py
Labels: cleanup

#2383 Add offset cut to IRF exposure map
  gammapy/cube/edisp_map.py
  gammapy/cube/fit.py
  gammapy/cube/make.py
  gammapy/cube/psf_map.py
  gammapy/cube/tests/test_fit.py
Labels: cleanup, feature

#2366 Remove lon wrapping in spatial models
  gammapy/catalog/hess.py
  gammapy/catalog/tests/test_hess.py
  gammapy/modeling/models/spatial.py
Labels: cleanup

#2385 Change spatial model default frame to icrs
  gammapy/cube/tests/test_fit.py
  gammapy/cube/tests/test_simulate.py
  gammapy/maps/tests/test_wcsnd.py
  gammapy/modeling/model.py
  gammapy/modeling/models/spatial.py
  gammapy/modeling/models/tests/test_cube.py
  gammapy/modeling/tests/data/make.py
  tutorials/analysis_3d.ipynb
  tutorials/analysis_3d_joint.ipynb
  tutorials/fermi_lat.ipynb
  tutorials/image_analysis.ipynb
  tutorials/mcmc_sampling.ipynb
  tutorials/simulate_3d.ipynb
Labels: cleanup

#2388 Fix handling of different pixels sizes in MapMaker for geom and geom_true
  gammapy/cube/make.py
  gammapy/cube/tests/test_make.py
Labels: bug

#2389 Fix exposure map upsampling in `MapMakerObs`
  gammapy/cube/make.py
  gammapy/cube/tests/test_make.py
Labels: bug

#2392 High-level interface: refactor config settings templates
  docs/scripts/index.rst
  gammapy/scripts/analysis.py
  gammapy/scripts/config/1D.yaml
  gammapy/scripts/config/3D.yaml
  gammapy/scripts/config/basic.yaml
  gammapy/scripts/config/schema.yaml
  gammapy/scripts/tests/test_analysis.py
Labels: cleanup

#2391 Implement SpectrumDataset.name and SpectrumDatasetOnOff.name
  gammapy/modeling/datasets.py
  gammapy/modeling/tests/test_datasets.py
  gammapy/modeling/tests/test_fit.py
  gammapy/spectrum/dataset.py
  gammapy/spectrum/extract.py
  gammapy/spectrum/flux_point.py
  gammapy/spectrum/tests/test_dataset.py
  gammapy/spectrum/tests/test_extract.py
  tutorials/spectrum_simulation.ipynb
Labels: cleanup

#2393 Minor cleanup of the Analysis class
  .gitignore
  docs/scripts/index.rst
  gammapy/modeling/datasets.py
  gammapy/modeling/fit.py
  gammapy/scripts/analysis.py
  gammapy/scripts/config/1D.yaml
  gammapy/scripts/config/3D.yaml
  gammapy/scripts/config/basic.yaml
  gammapy/scripts/config/model.yaml
  gammapy/scripts/config/schema.yaml
  gammapy/scripts/config/template-1d.yaml
  gammapy/scripts/config/template-3d.yaml
  gammapy/scripts/config/template-basic.yaml
  gammapy/scripts/tests/test_analysis.py
  gammapy/spectrum/tests/test_dataset.py
  gammapy/utils/docs.py
  tutorials/hess.ipynb
Labels: cleanup

#2396 Fix fgst ccube format unit handling
  gammapy/maps/geom.py
  gammapy/maps/tests/test_wcsnd.py
Labels: bug

#2384 Adding stages to travis
  .travis.yml
Labels: infrastructure, tests

#2399 Rename MapGeom base class to Geom
  docs/maps/index.rst
  gammapy/cube/edisp_map.py
  gammapy/cube/fit.py
  gammapy/cube/psf_kernel.py
  gammapy/cube/psf_map.py
  gammapy/data/event_list.py
  gammapy/maps/base.py
  gammapy/maps/geom.py
  gammapy/maps/hpx.py
  gammapy/maps/wcs.py
  tutorials/intro_maps.ipynb
Labels: cleanup

#2400 Clean up temporal model names
  gammapy/modeling/models/__init__.py
  gammapy/modeling/models/temporal.py
  gammapy/modeling/models/tests/test_temporal.py
Labels: cleanup

#2401 Clean up spatial model names
  docs/catalog/index.rst
  examples/example_2_gauss.py
  gammapy/astro/darkmatter/spectra.py
  gammapy/catalog/fermi.py
  gammapy/catalog/gammacat.py
  gammapy/catalog/hess.py
  gammapy/catalog/tests/test_gammacat.py
  gammapy/cube/fit.py
  gammapy/cube/tests/test_fit.py
  gammapy/cube/tests/test_simulate.py
  gammapy/maps/tests/test_wcsnd.py
  gammapy/modeling/model.py
  gammapy/modeling/models/__init__.py
  gammapy/modeling/models/cube.py
  gammapy/modeling/models/spatial.py
  gammapy/modeling/models/tests/test_cube.py
  gammapy/modeling/models/tests/test_spatial.py
  gammapy/modeling/serialize_xml.py
  gammapy/modeling/tests/data/example2.yaml
  gammapy/modeling/tests/data/examples.yaml
  gammapy/modeling/tests/data/make.py
  gammapy/modeling/tests/test_serialize_xml.py
  gammapy/modeling/tests/test_serialize_yaml.py
  gammapy/scripts/config/model.yaml
  gammapy/spectrum/tests/test_flux_point_estimator.py
  tutorials/analysis_3d.ipynb
  tutorials/analysis_3d_joint.ipynb
  tutorials/fermi_lat.ipynb
  tutorials/hess.ipynb
  tutorials/image_analysis.ipynb
  tutorials/light_curve.ipynb
  tutorials/mcmc_sampling.ipynb
  tutorials/simulate_3d.ipynb
Labels: cleanup

#2398 Implement `Analysis` stack-datasets option
  gammapy/scripts/analysis.py
  gammapy/scripts/config/schema.yaml
  gammapy/scripts/config/template-1d.yaml
  gammapy/scripts/config/template-3d.yaml
  gammapy/scripts/config/template-basic.yaml
  gammapy/scripts/tests/test_analysis.py
  tutorials/hess.ipynb
Labels: feature

#2292 First prototype for a SpectrumDatasetMakerObs
  gammapy/cube/fit.py
  gammapy/cube/tests/test_fit.py
Labels: feature

#2407 Minor cleanup of Analysis class #3
  docs/scripts/index.rst
  gammapy/scripts/analysis.py
  gammapy/scripts/config/schema.yaml
  gammapy/scripts/config/template-3d.yaml
  gammapy/scripts/tests/test_analysis.py
Labels: cleanup

#2409 Improve model registries and __all__ lists
  gammapy/catalog/registry.py
  gammapy/modeling/models/__init__.py
  gammapy/modeling/models/cube.py
  gammapy/modeling/models/spatial.py
  gammapy/modeling/models/spectral.py
  gammapy/modeling/models/spectral_cosmic_ray.py
  gammapy/modeling/models/spectral_crab.py
  gammapy/modeling/models/temporal.py
  gammapy/modeling/models/tests/test_spectral.py
Labels: cleanup

#2412 Remove model XML serialization
  gammapy/modeling/models/cube.py
  gammapy/modeling/serialize_xml.py
  gammapy/modeling/tests/test_serialize_xml.py
Labels: cleanup

#2411 Modified spectrum_simulation.ipynb to take background from the IRF
  tutorials/spectrum_simulation.ipynb
Labels: cleanup

#2415 Fix gammapy/modeling/tests/data/make.py
  gammapy/modeling/datasets.py
  gammapy/modeling/tests/data/make.py
Labels: bug, cleanup

#2410 Implement `ConstantTemporalModel`
  gammapy/modeling/models/temporal.py
  gammapy/modeling/models/tests/test_temporal.py
Labels: feature

#2395 update expfactor unit
  gammapy/catalog/fermi.py
  gammapy/modeling/models/spectral.py
  gammapy/modeling/models/tests/test_spectral.py
Labels: bug

#2414 Add Model.create and tests for all models
  gammapy/modeling/model.py
  gammapy/modeling/models/__init__.py
  gammapy/modeling/models/cube.py
  gammapy/modeling/models/temporal.py
  gammapy/modeling/models/tests/test_temporal.py
  gammapy/modeling/tests/test_model.py
  gammapy/modeling/tests/test_serialize_yaml.py
Labels: feature, tests

#2413 Revert introduction of docsearch
  docs/_static/docsearch.js
  docs/_static/gammapy.css
  docs/conf.py
  docs/development/howto.rst
Labels: cleanup

#2416 Minor cleanup of Analysis class #4
  docs/scripts/index.rst
  gammapy/scripts/analysis.py
  gammapy/scripts/config/docs.yaml
  gammapy/scripts/config/schema.yaml
  gammapy/scripts/config/template-1d.yaml
  gammapy/scripts/config/template-3d.yaml
  gammapy/scripts/config/template-basic.yaml
  gammapy/scripts/tests/test_analysis.py
  tutorials/hess.ipynb
Labels: cleanup

#2405 Change value clipping in `LogScale` class
  gammapy/modeling/models/tests/test_spectral.py
  gammapy/utils/interpolation.py
Labels: bug

#2408 Rewrite hess.ipynb tutorial
  .gitignore
  docs/scripts/index.rst
  gammapy/cube/fit.py
  gammapy/data/observations.py
  gammapy/modeling/models/cube.py
  gammapy/scripts/analysis.py
  gammapy/scripts/config/docs.yaml
  gammapy/scripts/config/schema.yaml
  gammapy/scripts/config/template-1d.yaml
  gammapy/scripts/config/template-3d.yaml
  gammapy/scripts/config/template-basic.yaml
  gammapy/scripts/tests/test_analysis.py
  gammapy/spectrum/dataset.py
  gammapy/spectrum/flux_point.py
  tutorials/hess.ipynb
Labels: docs

#2417 Remove FK5 option in spatial models
  gammapy/maps/geom.py
  gammapy/modeling/models/cube.py
  gammapy/modeling/models/spatial.py
  gammapy/modeling/models/tests/test_spatial.py
  gammapy/scripts/config/docs.yaml
  gammapy/scripts/config/schema.yaml
Labels: cleanup

#2418 Fill changelog for v0.14
  CHANGES.rst
Labels: docs

#2421 Improve test coverage in `scripts/analysis.py`
  gammapy/scripts/config/template-3d.yaml
  gammapy/scripts/tests/test_analysis.py
Labels: tests

#2420 Fix spatial model frame in source catalogs
  gammapy/catalog/fermi.py
  gammapy/catalog/gammacat.py
  gammapy/catalog/hess.py
  gammapy/catalog/tests/test_fermi.py
  gammapy/catalog/tests/test_gammacat.py
  gammapy/catalog/tests/test_hess.py
Labels: bug
