Repository gammapy/gammapy, pull requests merged in 2019-07, with the labels that each got.

#2262 Clean up sky region select code
  gammapy/background/phase.py
  gammapy/background/tests/test_phase.py
  gammapy/catalog/__init__.py
  gammapy/catalog/core.py
  gammapy/catalog/tests/test_core.py
  gammapy/catalog/utils.py
  gammapy/data/event_list.py
  gammapy/data/filters.py
  gammapy/data/obs_table.py
  gammapy/data/tests/test_filters.py
  gammapy/data/tests/test_obs_table.py
  gammapy/utils/regions.py
  gammapy/utils/tests/test_regions.py
  tutorials/first_steps.ipynb
  tutorials/pulsar_analysis.ipynb
Labels: cleanup

#2247 Clean up gammapy/powerlaw.py
  gammapy/spectrum/flux_point.py
  gammapy/spectrum/models.py
  gammapy/spectrum/powerlaw.py
  gammapy/spectrum/tests/test_models.py
  gammapy/spectrum/tests/test_powerlaw.py
  gammapy/spectrum/tests/test_utils.py
Labels: cleanup

#2220 Use subprocess.run consistently
  .travis.yml
  gammapy/utils/scripts_test.py
  gammapy/utils/tutorials_process.py
Labels: cleanup

#2265 Add source catalog object position tests
  gammapy/catalog/core.py
  gammapy/catalog/tests/test_core.py
  gammapy/catalog/tests/test_fermi.py
  gammapy/catalog/tests/test_gammacat.py
  gammapy/catalog/tests/test_hawc.py
  gammapy/catalog/tests/test_hess.py
Labels: tests

#2272 Remove SpectrumStats class
  gammapy/data/obs_stats.py
  gammapy/data/tests/test_obs_stats.py
  gammapy/spectrum/dataset.py
  gammapy/spectrum/tests/test_dataset.py
  gammapy/spectrum/tests/test_extract.py
  tutorials/spectrum_simulation.ipynb
Labels: cleanup

#2273 Rename gammapy/stats/significance.py
  docs/time/period.rst
  gammapy/stats/__init__.py
  gammapy/stats/normal.py
  gammapy/stats/poisson.py
  gammapy/time/__init__.py
  gammapy/time/events.py
  gammapy/time/period.py
  gammapy/time/plot_periodogram.py
  gammapy/time/tests/test_exptest.py
  gammapy/time/tests/test_period.py
  gammapy/time/tests/test_plot_periodogram.py
Labels: cleanup

#2238 Introduce the MapEventSampler class
  gammapy/time/models.py
  gammapy/utils/random/inverse_cdf.py
  gammapy/utils/random/tests/test_inverse_cdf.py
Labels: feature

#2276 Fix map pixel solid angle computation
  gammapy/cube/tests/test_background.py
  gammapy/cube/tests/test_make.py
  gammapy/cube/tests/test_models.py
  gammapy/maps/tests/test_wcs.py
  gammapy/maps/wcs.py
  gammapy/utils/random/tests/test_inverse_cdf.py
Labels: bug

#2278 Refactor class CrabSpectrum in a function
  gammapy/spectrum/crab.py
  gammapy/spectrum/tests/test_crab.py
  tutorials/hess.ipynb
  tutorials/light_curve.ipynb
  tutorials/spectrum_analysis.ipynb
Labels: cleanup

#2280 Remove docs/image/models.rst
  docs/image/index.rst
  docs/image/models.rst
Labels: cleanup, docs

#2282 start reformating cosmicrays spectrum
  gammapy/spectrum/cosmic_ray.py
  gammapy/spectrum/crab.py
  gammapy/spectrum/models.py
  gammapy/spectrum/tests/test_cosmic_ray.py
  gammapy/spectrum/tests/test_models.py
Labels: cleanup

#2295 Remove astropy InheritDocstrings
  gammapy/maps/base.py
  gammapy/maps/geom.py
  gammapy/utils/fitting/fit.py
Labels: cleanup

#2277 Add GTI union
  gammapy/data/gti.py
  gammapy/data/tests/test_gti.py
Labels: feature

#2293 Add residuals method for map dataset
  gammapy/cube/fit.py
  gammapy/cube/tests/test_fit.py
  gammapy/maps/base.py
  gammapy/maps/tests/test_wcsnd.py
  gammapy/maps/wcsnd.py
  gammapy/spectrum/core.py
  gammapy/spectrum/dataset.py
  gammapy/spectrum/flux_point.py
  gammapy/utils/fitting/datasets.py
  tutorials/analysis_3d_joint.ipynb
  tutorials/cta_sensitivity.ipynb
  tutorials/image_fitting_with_sherpa.ipynb
  tutorials/mcmc_sampling.ipynb
Labels: feature

#2287 Add __str__ method for Dataset
  gammapy/cube/fit.py
  gammapy/cube/tests/test_fit.py
  gammapy/spectrum/dataset.py
  gammapy/spectrum/flux_point.py
  gammapy/spectrum/tests/test_dataset.py
  gammapy/spectrum/tests/test_flux_point.py
  gammapy/utils/fitting/parameter.py
Labels: feature

#2284 Rename backscale attribute to acceptance
  gammapy/spectrum/dataset.py
  gammapy/spectrum/extract.py
  gammapy/spectrum/simulation.py
  gammapy/spectrum/tests/test_dataset.py
Labels: cleanup

#2289 Add gammapy/utils/fitting/sampling.py
  gammapy/utils/fitting/sampling.py
  tutorials/analysis_3d_joint.ipynb
  tutorials/mcmc_sampling.ipynb
Labels: feature

#2298 Add fake method to Dataset
  gammapy/cube/fit.py
  gammapy/cube/tests/test_fit.py
  gammapy/spectrum/dataset.py
  gammapy/spectrum/tests/test_dataset.py
Labels: feature

#2305 Remove `SpectrumSimulation` class
  gammapy/cube/fit.py
  gammapy/spectrum/__init__.py
  gammapy/spectrum/dataset.py
  gammapy/spectrum/simulation.py
  gammapy/spectrum/tests/test_dataset.py
  gammapy/spectrum/tests/test_flux_point_estimator.py
  gammapy/spectrum/tests/test_simulation.py
  tutorials/spectrum_simulation.ipynb
Labels: cleanup

#2297 Add Fermi 4FGL catalog spectral models
  gammapy/catalog/fermi.py
  gammapy/catalog/tests/test_fermi.py
  gammapy/spectrum/models.py
  gammapy/spectrum/tests/test_models.py
Labels: feature

#2300 Apply iau convention for position angle in sky ellipse
  gammapy/image/models/core.py
  gammapy/image/models/tests/test_core.py
Labels: cleanup

#2299 Add GTI to Dataset
  gammapy/cube/fit.py
  gammapy/spectrum/dataset.py
  gammapy/spectrum/extract.py
  gammapy/spectrum/tests/test_dataset.py
  gammapy/spectrum/tests/test_extract.py
Labels: feature

#2306 Add 4FGL to gammapy data index json file
  dev/datasets/gammapy-data-index.json
Labels: feature, infrastructure

#2281 Add lightcurve with 3D map analysis
  gammapy/time/__init__.py
  gammapy/time/lightcurve.py
  gammapy/time/lightcurve_estimator.py
  gammapy/time/tests/test_lightcurve.py
  tutorials/lightcurve_3d.ipynb
Labels: cleanup, feature

#2309 Add tests for LightCurveEstimator3D
  gammapy/spectrum/dataset.py
  gammapy/spectrum/tests/test_flux_point_estimator.py
  gammapy/time/lightcurve_estimator.py
  gammapy/time/tests/test_lightcurve.py
Labels: feature, tests

#2310 Remove `LightCurveEstimator` class
  docs/tutorials.rst
  gammapy/time/lightcurve.py
  gammapy/time/tests/test_lightcurve.py
  tutorials/light_curve.ipynb
  tutorials/notebooks.yaml
Labels: cleanup

#2294 Fix Pulsar bug
  gammapy/astro/population/tests/test_simulate.py
  gammapy/astro/source/pulsar.py
  gammapy/astro/source/tests/test_pulsar.py
Labels: bug

#2311 Adapt new lightcurve_3d notebook to include also 1D extraction
  gammapy/time/lightcurve_estimator.py
  gammapy/time/tests/test_lightcurve.py
  tutorials/lightcurve_3d.ipynb
Labels: cleanup

#2296 Add model YAML serialisation
  gammapy/catalog/tests/test_snrcat.py
  gammapy/cube/models.py
  gammapy/data/obs_stats.py
  gammapy/image/models/core.py
  gammapy/maps/tests/test_wcs.py
  gammapy/spectrum/models.py
  gammapy/utils/fits.py
  gammapy/utils/fitting/model.py
  gammapy/utils/fitting/parameter.py
  gammapy/utils/scripts.py
  gammapy/utils/serialization/__init__.py
  gammapy/utils/serialization/io.py
  gammapy/utils/serialization/tests/data/example2.yaml
  gammapy/utils/serialization/tests/data/examples.yaml
  gammapy/utils/serialization/tests/make_test_data.py
  gammapy/utils/serialization/tests/test_io.py
  gammapy/utils/setup_package.py
Labels: feature

#2312 Fill changelog for v0.13
  CHANGES.rst
Labels: docs
