Repository gammapy/gammapy, pull requests merged in 2019-02, with the labels that each got.

#2018 Add stacking method for PSFMap
  gammapy/cube/psf_map.py
  gammapy/cube/tests/test_psf_map.py
Labels: feature

#2019 Simplify PSF stacking and containment radii code
  gammapy/cube/tests/test_psf_map.py
  gammapy/irf/irf_reduce.py
  gammapy/irf/psf_3d.py
  gammapy/irf/psf_table.py
  gammapy/irf/tests/test_irf_reduce.py
  gammapy/irf/tests/test_psf_3d.py
  gammapy/irf/tests/test_psf_gauss.py
  gammapy/irf/tests/test_psf_table.py
  gammapy/spectrum/tests/test_extract.py
Labels: cleanup

#2023 Add FluxPointsDatasets class
  gammapy/spectrum/flux_point.py
  gammapy/spectrum/tests/test_flux_point.py
  gammapy/utils/fitting/fit.py
  gammapy/utils/fitting/tests/test_fit.py
  tutorials/sed_fitting_gammacat_fermi.ipynb
Labels: feature

#2015 Make apply_containment_fraction a stand-alone function
  gammapy/irf/irf_reduce.py
  gammapy/irf/tests/test_irf_reduce.py
  gammapy/spectrum/extract.py
Labels: cleanup

#1841 PIG 5 - Gammapy 1.0 Roadmap
  docs/development/pigs/pig-005.rst
Labels: pig

#2026 Adapt `MapFit` to `MapDataset`
  gammapy/cube/fit.py
  gammapy/cube/models.py
  gammapy/cube/tests/test_fit.py
  gammapy/cube/tests/test_models.py
  gammapy/utils/fitting/fit.py
  tutorials/analysis_3d.ipynb
  tutorials/fermi_lat.ipynb
  tutorials/hess.ipynb
  tutorials/image_analysis.ipynb
  tutorials/simulate_3d.ipynb
Labels: cleanup

#2028 Add hess notebook to gammapy download list
  tutorials/notebooks.yaml
Labels: docs

#2032 Correct some docs
  gammapy/image/models/core.py
Labels: docs

#2030 Add Datasets class
  gammapy/cube/fit.py
  gammapy/cube/tests/test_fit.py
  gammapy/spectrum/flux_point.py
  gammapy/spectrum/tests/test_fit.py
  gammapy/spectrum/tests/test_flux_point.py
  gammapy/utils/fitting/__init__.py
  gammapy/utils/fitting/datasets.py
  gammapy/utils/fitting/fit.py
  gammapy/utils/fitting/tests/test_datasets.py
  gammapy/utils/fitting/tests/test_fit.py
  tutorials/analysis_3d.ipynb
  tutorials/cta_sensitivity.ipynb
  tutorials/fermi_lat.ipynb
  tutorials/hess.ipynb
  tutorials/image_analysis.ipynb
  tutorials/sed_fitting_gammacat_fermi.ipynb
  tutorials/simulate_3d.ipynb
Labels: feature

#2031 Introduce EDispMap class
  gammapy/cube/__init__.py
  gammapy/cube/edisp_map.py
  gammapy/cube/tests/test_edisp_map.py
Labels: feature

#2037 Add parameter freezing for sherpa backend
  gammapy/spectrum/tests/test_flux_point.py
  gammapy/utils/fitting/iminuit.py
  gammapy/utils/fitting/parameter.py
  gammapy/utils/fitting/sherpa.py
  gammapy/utils/fitting/tests/test_iminuit.py
  gammapy/utils/fitting/tests/test_parameter.py
  gammapy/utils/fitting/tests/test_sherpa.py
Labels: cleanup, feature

#2034 Redefine symmetric gaussian spatial model on the sphere
  gammapy/cube/tests/test_models.py
  gammapy/image/models/core.py
  gammapy/image/models/tests/test_core.py
Labels: feature

#2035 Symmetric solid angle calculation for WcsGeom
  gammapy/cube/tests/test_background.py
  gammapy/cube/tests/test_make.py
  gammapy/cube/tests/test_models.py
  gammapy/maps/tests/test_wcs.py
  gammapy/maps/wcs.py
Labels: bug

#2036 Change SkyModel addition to return a SkyModels object
  gammapy/cube/models.py
  gammapy/cube/tests/test_models.py
  tutorials/analysis_3d.ipynb
Labels: cleanup

#2033 Correct asymmetric background map generation
  gammapy/cube/background.py
  gammapy/cube/make.py
  gammapy/cube/tests/test_background.py
  gammapy/cube/tests/test_make.py
  gammapy/data/observations.py
  gammapy/data/pointing.py
  gammapy/data/tests/test_pointing.py
Labels: feature

#2045 Add joint likelihood fit test for `MapDataset`
  gammapy/cube/tests/test_fit.py
  gammapy/cube/tests/test_models.py
  gammapy/utils/fitting/parameter.py
Labels: feature, tests

#2039 Simplify and move energy threshold computation
  gammapy/irf/effective_area.py
  gammapy/irf/energy_dispersion.py
  gammapy/irf/tests/test_effective_area.py
  gammapy/spectrum/observation.py
  gammapy/spectrum/tests/test_observation.py
Labels: cleanup, coding-sprint-paris-2019, feature

#2044 Corrected ReflectedRegionFinder to recompute default mask for each observation
  gammapy/background/reflected.py
  gammapy/background/tests/test_reflected.py
  gammapy/data/tests/test_obs_stats.py
Labels: bug

#2051 Cutout on WCS
  gammapy/cube/make.py
  gammapy/maps/tests/test_wcs.py
  gammapy/maps/wcs.py
Labels: feature

#2052 Modify make_background_map to compute FoV coordinates fromSkyCoord
  gammapy/cube/background.py
Labels: bug, feature

#2053 Add evaluation radius
  gammapy/image/models/core.py
  gammapy/image/models/tests/test_core.py
Labels: feature

#2054 Add likelihood profile reoptimize option
  gammapy/utils/fitting/fit.py
  gammapy/utils/fitting/parameter.py
  gammapy/utils/fitting/tests/test_fit.py
Labels: feature

#2049 Add an EventList selection based on Map
  gammapy/cube/counts.py
  gammapy/data/event_list.py
  gammapy/data/tests/test_event_list.py
Labels: feature

#2057 fixing issue in from_dict method
  gammapy/spectrum/models.py
Labels: bug

#2060 Fix slice issue in MapAxis
  gammapy/maps/geom.py
  gammapy/maps/tests/test_geom.py
Labels: bug

#2059 Raise error when creating Map with binsize=0
  gammapy/maps/geom.py
  gammapy/maps/tests/test_geom.py
Labels: bug

#2046 Add elliptical model defined on the sphere
  gammapy/image/models/core.py
  gammapy/image/models/tests/test_core.py
Labels: coding-sprint-paris-2019, feature
