Repository gammapy/gammapy, pull requests merged in 2019-11, with the labels that each got.

#2510 Add EdispMap.sample_coord method
  gammapy/cube/edisp_map.py
  gammapy/cube/tests/test_edisp_map.py
Labels: feature

#2498 Add mask_safe handling in MapDataset.to_image
  gammapy/cube/fit.py
  gammapy/cube/tests/test_fit.py
Labels: cleanup, feature

#2506 Create unique parameters list in Datasets
  gammapy/modeling/datasets.py
  gammapy/modeling/parameter.py
  gammapy/modeling/tests/test_model.py
  gammapy/modeling/tests/test_parameter.py
Labels: cleanup

#2463 PIG 18: Documentation
  docs/development/pigs/index.rst
  docs/development/pigs/pig-018.rst
Labels: docs, pig

#2519 Some cleanup of eventlist code and tests
  gammapy/data/event_list.py
  gammapy/data/tests/test_event_list.py
Labels: cleanup

#2505 Add a tutorial for joint 1d/3d analysis
  dev/datasets/gammapy-data-index.json
  dev/datasets/make_dataset_index.py
  docs/tutorials.rst
  tutorials/joint_1d_3d_analysis.ipynb
  tutorials/notebooks.yaml
Labels: docs

#2521 Remove .to_sherpa() methods
  gammapy/irf/effective_area.py
  gammapy/irf/energy_dispersion.py
Labels: cleanup

#2523 Modify MapDataset io
  gammapy/cube/fit.py
  gammapy/cube/tests/test_fit.py
Labels: bug

#2520 Refactor ring background maker
  gammapy/cube/fit.py
  gammapy/cube/ring.py
  gammapy/cube/tests/test_make.py
  gammapy/cube/tests/test_ring.py
  tutorials/image_analysis.ipynb
Labels: cleanup

#2526 Remove SNRCat
  docs/catalog/index.rst
  gammapy/catalog/__init__.py
  gammapy/catalog/registry.py
  gammapy/catalog/snrcat.py
  gammapy/catalog/tests/test_snrcat.py
Labels: cleanup

#2522 Add sub-covariance matrix management
  gammapy/modeling/iminuit.py
  gammapy/modeling/models/cube.py
  gammapy/modeling/models/spatial.py
  gammapy/modeling/parameter.py
  gammapy/modeling/tests/test_parameter.py
  tutorials/joint_1d_3d_analysis.ipynb
Labels: feature

#2525 Remove MapMakerRing
  gammapy/cube/make.py
  gammapy/cube/ring.py
  gammapy/cube/tests/test_ring.py
  tutorials/image_analysis.ipynb
Labels: cleanup

#2528 Move Analysis to new gammapy.analysis
  docs/analysis/index.rst
  docs/development/howto.rst
  docs/index.rst
  docs/scripts/cli.rst
  docs/scripts/index.rst
  gammapy/analysis/__init__.py
  gammapy/analysis/config/docs.yaml
  gammapy/analysis/config/model.yaml
  gammapy/analysis/config/schema.yaml
  gammapy/analysis/config/template-1d.yaml
  gammapy/analysis/config/template-3d.yaml
  gammapy/analysis/config/template-basic.yaml
  gammapy/analysis/core.py
  gammapy/analysis/tests/__init__.py
  gammapy/analysis/tests/test_analysis.py
  gammapy/scripts/__init__.py
  gammapy/utils/docs.py
  setup.cfg
  tutorials/hess.ipynb
Labels: cleanup

#2529 Improve SkyModels and Datasets
  gammapy/analysis/core.py
  gammapy/analysis/tests/test_analysis.py
  gammapy/catalog/tests/test_gammacat.py
  gammapy/catalog/tests/test_hess.py
  gammapy/cube/fit.py
  gammapy/cube/make.py
  gammapy/cube/tests/test_fit.py
  gammapy/modeling/datasets.py
  gammapy/modeling/models/cube.py
  gammapy/modeling/models/tests/test_cube.py
  gammapy/modeling/serialize.py
  gammapy/modeling/tests/data/make.py
  gammapy/modeling/tests/test_datasets.py
  gammapy/modeling/tests/test_serialize_yaml.py
  gammapy/spectrum/flux_point.py
  gammapy/spectrum/tests/test_flux_point.py
  gammapy/time/lightcurve_estimator.py
  tutorials/joint_1d_3d_analysis.ipynb
  tutorials/mcmc_sampling.ipynb
Labels: cleanup

#2524 Add maxsize limit to lru_cache()
  gammapy/cube/make.py
  gammapy/maps/tests/test_wcs.py
  gammapy/maps/wcs.py
Labels: bug

#2530 Fix Datasets vs Datasets confusion
  gammapy/cube/tests/test_fit.py
  gammapy/modeling/datasets.py
  gammapy/modeling/fit.py
  gammapy/modeling/models/cube.py
  gammapy/modeling/models/tests/test_cube.py
  gammapy/modeling/tests/test_datasets.py
  gammapy/modeling/tests/test_fit.py
  gammapy/spectrum/tests/test_dataset.py
  gammapy/spectrum/tests/test_fit.py
  gammapy/spectrum/tests/test_flux_point.py
  gammapy/time/lightcurve_estimator.py
  tutorials/analysis_3d.ipynb
  tutorials/fermi_lat.ipynb
  tutorials/image_analysis.ipynb
  tutorials/joint_1d_3d_analysis.ipynb
  tutorials/sed_fitting_gammacat_fermi.ipynb
  tutorials/simulate_3d.ipynb
Labels: bug, cleanup

#2531 Improve gammapy.catalog
  dev/datasets/gammapy-data-index.json
  gammapy/catalog/core.py
  gammapy/catalog/fermi.py
  gammapy/catalog/gammacat.py
  gammapy/catalog/hess.py
  gammapy/catalog/tests/data/4fgl_J1409.1-6121e.txt
  gammapy/catalog/tests/test_core.py
  gammapy/catalog/tests/test_gammacat.py
  gammapy/catalog/tests/test_hess.py
  gammapy/modeling/models/cube.py
Labels: cleanup

#2532 Remove PSF3DChecker
  gammapy/irf/__init__.py
  gammapy/irf/psf_check.py
  gammapy/irf/tests/test_psf_check.py
Labels: cleanup

#2533 Improve Parameters.set_error
  gammapy/catalog/fermi.py
  gammapy/catalog/gammacat.py
  gammapy/catalog/hawc.py
  gammapy/catalog/hess.py
  gammapy/modeling/models/tests/test_spectral.py
  gammapy/modeling/parameter.py
  gammapy/modeling/tests/test_parameter.py
  gammapy/utils/tests/test_integrate.py
Labels: cleanup

#2534 Remove gammapy image bin CLI
  gammapy/scripts/image_bin.py
  gammapy/scripts/main.py
  gammapy/scripts/tests/test_image_bin.py
Labels: cleanup

#2127 Add nodetype in docstring
  docs/maps/index.rst
Labels: docs

#2536 Add `.cutout_info` information to WCS header
  gammapy/maps/tests/test_wcs.py
  gammapy/maps/utils.py
  gammapy/maps/wcs.py
  gammapy/maps/wcsnd.py
  tutorials/analysis_3d_joint.ipynb
Labels: feature

#2535 Remove gammapy.detect.CWT
  gammapy/detect/__init__.py
  gammapy/detect/cwt.py
  gammapy/detect/tests/test_cwt.py
  tutorials/cwt.ipynb
  tutorials/notebooks.yaml
Labels: cleanup

#2539 Minor cleanup
  gammapy/catalog/fermi.py
  gammapy/catalog/gammacat.py
  gammapy/maps/tests/test_wcs.py
  gammapy/maps/utils.py
  gammapy/maps/wcs.py
Labels: cleanup

#2538 Move `SafeMaskMaker` and adapt mask_safe handling in `MapDatasetMaker`
  gammapy/analysis/core.py
  gammapy/cube/background.py
  gammapy/cube/edisp_map.py
  gammapy/cube/fit.py
  gammapy/cube/make.py
  gammapy/cube/psf_map.py
  gammapy/cube/tests/test_fit.py
  gammapy/cube/tests/test_make.py
  gammapy/cube/tests/test_ring.py
  gammapy/maps/wcsnd.py
  gammapy/spectrum/make.py
  gammapy/spectrum/tests/test_make.py
  tutorials/analysis_3d.ipynb
  tutorials/analysis_3d_joint.ipynb
  tutorials/cta_data_analysis.ipynb
  tutorials/image_analysis.ipynb
  tutorials/image_fitting_with_sherpa.ipynb
  tutorials/light_curve.ipynb
  tutorials/pulsar_analysis.ipynb
  tutorials/spectrum_analysis.ipynb
Labels: cleanup

#2540 Restructure tutorial notebooks
  README.rst
  docs/analysis/index.rst
  docs/catalog/index.rst
  docs/data/index.rst
  docs/development/howto.rst
  docs/irf/index.rst
  docs/tutorials.rst
  gammapy/data/data_store.py
  gammapy/scripts/main.py
  tutorials/cta.ipynb
  tutorials/cta_data_analysis.ipynb
  tutorials/first_analysis.ipynb
  tutorials/hess.ipynb
  tutorials/maps.ipynb
  tutorials/notebooks.yaml
  tutorials/overview.ipynb
Labels: cleanup, docs

#2543 Restructure tutorial notebooks 2
  docs/analysis/index.rst
  docs/catalog/index.rst
  docs/detect/index.rst
  docs/modeling/index.rst
  docs/tutorials.rst
  tutorials/analysis_1.ipynb
  tutorials/analysis_2.ipynb
  tutorials/catalog.ipynb
  tutorials/detect.ipynb
  tutorials/modeling.ipynb
  tutorials/models.ipynb
  tutorials/notebooks.yaml
Labels: cleanup, docs

#2544 Remove Sherpa tutorial notebooks
  docs/tutorials.rst
  tutorials/image_analysis.ipynb
  tutorials/image_fitting_with_sherpa.ipynb
  tutorials/notebooks.yaml
  tutorials/spectrum_fitting_with_sherpa.ipynb
Labels: cleanup

#2546 Rename likelihood to stat
  gammapy/cube/fit.py
  gammapy/cube/tests/test_fit.py
  gammapy/modeling/datasets.py
  gammapy/modeling/fit.py
  gammapy/modeling/sampling.py
  gammapy/modeling/scipy.py
  gammapy/modeling/tests/test_datasets.py
  gammapy/modeling/tests/test_fit.py
  gammapy/modeling/tests/test_scipy.py
  gammapy/spectrum/dataset.py
  gammapy/spectrum/flux_point.py
  gammapy/spectrum/tests/test_fit.py
  gammapy/spectrum/tests/test_flux_point.py
  gammapy/spectrum/tests/test_flux_point_estimator.py
  gammapy/time/lightcurve_estimator.py
  gammapy/time/tests/test_lightcurve.py
  gammapy/utils/interpolation.py
  tutorials/analysis_1.ipynb
  tutorials/mcmc_sampling.ipynb
  tutorials/spectrum_analysis.ipynb
Labels: cleanup

#2550 Re-structure tutorials docs to include scripts
  docs/index.rst
  docs/tutorials.rst
  docs/tutorials/index.rst
  docs/tutorials/survey_map.rst
  tutorials/hgps.ipynb
Labels: docs

#2551 Cleanup mask safe handling
  gammapy/analysis/core.py
  gammapy/cube/edisp_map.py
  gammapy/cube/exposure.py
  gammapy/cube/fit.py
  gammapy/cube/make.py
  gammapy/cube/psf_map.py
  gammapy/cube/tests/test_edisp_map.py
  gammapy/cube/tests/test_make.py
  gammapy/cube/tests/test_psf_map.py
  gammapy/cube/tests/test_ring.py
  gammapy/maps/tests/test_wcs.py
  gammapy/maps/wcs.py
  gammapy/maps/wcsnd.py
  tutorials/analysis_3d.ipynb
  tutorials/analysis_3d_joint.ipynb
  tutorials/cta_data_analysis.ipynb
  tutorials/image_analysis.ipynb
  tutorials/light_curve.ipynb
Labels: cleanup

#2552 Remove unused functions from `gammapy.irf`
  gammapy/cube/background.py
  gammapy/cube/fit.py
  gammapy/irf/irf_reduce.py
  gammapy/irf/tests/test_effective_area.py
  gammapy/irf/tests/test_energy_dispersion.py
  gammapy/irf/tests/test_irf_reduce.py
  gammapy/spectrum/dataset.py
  gammapy/spectrum/make.py
Labels: cleanup

#2553 Remove MapDataset cstat likelihood option
  gammapy/cube/fit.py
  gammapy/cube/tests/test_fit.py
  gammapy/stats/fit_statistics_cython.pyx
  gammapy/stats/tests/test_fit_statistics.py
Labels: cleanup

#2554 Add docs for cube data reduction
  docs/cube/index.rst
  gammapy/cube/fit.py
Labels: docs

#2558 Remove gammapy.utils.nddata.sqrt_space
  gammapy/cube/tests/test_fit.py
  gammapy/utils/nddata.py
  tutorials/background_model.ipynb
Labels: cleanup

#2557 Add more options to Minuit wrapper
  gammapy/modeling/iminuit.py
  gammapy/modeling/tests/test_iminuit.py
Labels: feature

#2255 PIG 14: Uncertainty estimation
  docs/development/pigs/index.rst
  docs/development/pigs/pig-014.rst
Labels: pig

#2560 Set NaN for no likelihood contribution in FluxPointsEstimator
  gammapy/spectrum/flux_point.py
  gammapy/spectrum/tests/test_flux_point_estimator.py
Labels: cleanup

#2561 Using dataset GTI table in LightCurveEstimator
  gammapy/data/gti.py
  gammapy/time/lightcurve_estimator.py
  gammapy/time/tests/test_lightcurve.py
  tutorials/light_curve.ipynb
Labels: cleanup

#2562 Remove map reprojection functionality
  docs/maps/index.rst
  gammapy/maps/base.py
  gammapy/maps/hpxnd.py
  gammapy/maps/reproject.py
  gammapy/maps/tests/test_base.py
  gammapy/maps/tests/test_wcsnd.py
  gammapy/maps/wcsnd.py
  tutorials/maps.ipynb
Labels: cleanup

#2559 Replace energy grid helper functions with MapAxis
  gammapy/data/event_list.py
  gammapy/irf/effective_area.py
  gammapy/irf/energy_dispersion.py
  gammapy/irf/psf_3d.py
  gammapy/irf/psf_gauss.py
  gammapy/irf/psf_table.py
  gammapy/irf/tests/test_energy_dispersion.py
  gammapy/irf/tests/test_irf_reduce.py
  gammapy/maps/geom.py
  gammapy/modeling/models/spectral.py
  gammapy/modeling/models/tests/test_spectral.py
  gammapy/spectrum/tests/test_core.py
  gammapy/utils/energy.py
  gammapy/utils/tests/test_energy.py
Labels: cleanup

#2564 Remove HpxSparseMap
  docs/maps/hpxmap.rst
  docs/maps/index.rst
  gammapy/maps/__init__.py
  gammapy/maps/_sparse.pyx
  gammapy/maps/base.py
  gammapy/maps/hpxmap.py
  gammapy/maps/hpxsparse.py
  gammapy/maps/sparse.py
  gammapy/maps/tests/test_base.py
  gammapy/maps/tests/test_hpxmap.py
  gammapy/maps/tests/test_hpxsparse.py
  gammapy/maps/tests/test_sparse.py
  setup.py
Labels: cleanup

#2563 Add in memory Observation class
  gammapy/cube/make.py
  gammapy/data/observations.py
  gammapy/data/tests/test_observations.py
Labels: feature

#2565 Add documentation for SpectrumDatasetOnOff to and from ogip methods
  gammapy/spectrum/dataset.py
Labels: cleanup, docs

#2568 Minor cleanup in maps/geom.py and maps/wcs.py
  gammapy/maps/geom.py
  gammapy/maps/wcs.py
Labels: cleanup

#2569 Clean up of gammapy.time
  docs/time/index.rst
  gammapy/time/__init__.py
  gammapy/time/events.py
  gammapy/time/lightcurve.py
  gammapy/time/tests/test_events.py
  gammapy/time/tests/test_lightcurve.py
  gammapy/time/tests/test_variability.py
  gammapy/time/variability.py
Labels: cleanup

#2571 Adding obs_id to log for dataset production
  gammapy/analysis/core.py
Labels: feature

#2573 fix MapDataset plot_residuals
  gammapy/cube/fit.py
Labels: bug

#2572 Adapt simulation notebooks
  gammapy/cube/fit.py
  gammapy/data/observations.py
  gammapy/spectrum/dataset.py
  tutorials/simulate_3d.ipynb
  tutorials/spectrum_simulation.ipynb
Labels: cleanup

#2579 Fix missing parameters when reading from yaml
  gammapy/modeling/model.py
  gammapy/modeling/parameter.py
  gammapy/modeling/tests/test_serialize_yaml.py
Labels: bug

#2577 Add TODO infos to tutorial notebooks
  tutorials/analysis_2.ipynb
  tutorials/analysis_3d.ipynb
  tutorials/analysis_3d_joint.ipynb
  tutorials/fermi_lat.ipynb
  tutorials/hess.ipynb
  tutorials/hgps.ipynb
  tutorials/image_analysis.ipynb
  tutorials/joint_1d_3d_analysis.ipynb
  tutorials/modeling.ipynb
Labels: docs

#2580 Speed up Observations.select_time
  gammapy/data/observations.py
Labels: cleanup

#2581 Fix datasets to yaml
  gammapy/cube/fit.py
  gammapy/cube/tests/test_fit.py
  gammapy/modeling/serialize.py
Labels: bug

#2582 Add SpectrumDatasetOnOff serialization
  gammapy/modeling/serialize.py
  gammapy/spectrum/dataset.py
  gammapy/spectrum/tests/test_dataset.py
Labels: feature

#2567 Add time intervals as an argument to the LIghtCurveEstimator
  gammapy/time/lightcurve_estimator.py
  gammapy/time/tests/test_lightcurve.py
  tutorials/light_curve.ipynb
Labels: feature

#2584 Fix analysis background names
  gammapy/analysis/core.py
Labels: bug

#2586 Docs todos
  docs/getting-started.rst
  docs/howto.rst
  docs/index.rst
  docs/install/check.rst
  docs/install/conda.rst
  docs/install/dependencies.rst
  docs/install/other.rst
  docs/install/pip.rst
  docs/overview.rst
Labels: docs

#2588 Update install docs
  docs/install/index.rst
  docs/install/other.rst
  docs/install/pip.rst
Labels: cleanup, docs

#2583 Select Obervations on several time interval
  gammapy/data/observations.py
  gammapy/data/tests/test_observations.py
Labels: feature

#2585 Improve spectral model error propagation
  .travis.yml
  azure-pipelines.yml
  docs/conf.py
  docs/install/dependencies.rst
  environment-dev.yml
  gammapy/catalog/tests/test_fermi.py
  gammapy/catalog/tests/test_gammacat.py
  gammapy/catalog/tests/test_hawc.py
  gammapy/catalog/tests/test_hess.py
  gammapy/conftest.py
  gammapy/modeling/models/spectral.py
  gammapy/modeling/models/tests/test_spectral.py
  gammapy/modeling/parameter.py
  gammapy/scripts/info.py
  gammapy/utils/integrate.py
  gammapy/utils/tests/test_integrate.py
  tutorials/hgps.ipynb
Labels: bug, cleanup, feature

#2436 LogGaussianSpectralModel mean position
  gammapy/modeling/models/__init__.py
  gammapy/modeling/models/spectral.py
  gammapy/modeling/models/spectral_cosmic_ray.py
  gammapy/modeling/models/tests/test_spectral.py
  gammapy/modeling/tests/test_serialize_yaml.py
  tutorials/models.ipynb
Labels: bug

#2587 Activate EDispMap in MapEvaluator
  gammapy/analysis/core.py
  gammapy/cube/edisp_map.py
  gammapy/cube/fit.py
  gammapy/cube/psf_map.py
  gammapy/cube/tests/test_edisp_map.py
  gammapy/cube/tests/test_fit.py
  gammapy/cube/tests/test_psf_map.py
  gammapy/modeling/tests/data/make.py
  gammapy/spectrum/tests/test_flux_point_estimator.py
  gammapy/time/tests/test_lightcurve.py
Labels: feature

#2595 Change 1D dataset model to SkyModels
  .gitignore
  gammapy/analysis/core.py
  gammapy/astro/population/spatial.py
  gammapy/astro/population/velocity.py
  gammapy/cube/edisp_map.py
  gammapy/cube/fit.py
  gammapy/cube/psf_map.py
  gammapy/cube/tests/test_edisp_map.py
  gammapy/cube/tests/test_fit.py
  gammapy/cube/tests/test_psf_map.py
  gammapy/data/observations.py
  gammapy/data/tests/test_observations.py
  gammapy/irf/psf_3d.py
  gammapy/irf/psf_gauss.py
  gammapy/maps/tests/test_base.py
  gammapy/maps/tests/test_hpxmap.py
  gammapy/modeling/models/cube.py
  gammapy/modeling/models/spectral.py
  gammapy/modeling/models/spectral_cosmic_ray.py
  gammapy/modeling/serialize.py
  gammapy/spectrum/core.py
  gammapy/spectrum/dataset.py
  gammapy/spectrum/flux_point.py
  gammapy/spectrum/sensitivity.py
  gammapy/spectrum/tests/test_core.py
  gammapy/spectrum/tests/test_dataset.py
  gammapy/spectrum/tests/test_fit.py
  gammapy/spectrum/tests/test_flux_point.py
  gammapy/spectrum/tests/test_flux_point_estimator.py
  gammapy/time/lightcurve.py
  gammapy/time/lightcurve_estimator.py
  gammapy/time/tests/test_lightcurve.py
  gammapy/time/tests/test_period.py
  gammapy/time/tests/test_variability.py
  gammapy/time/variability.py
  tutorials/analysis_1.ipynb
  tutorials/cta_data_analysis.ipynb
  tutorials/joint_1d_3d_analysis.ipynb
  tutorials/light_curve.ipynb
  tutorials/pulsar_analysis.ipynb
  tutorials/sed_fitting_gammacat_fermi.ipynb
  tutorials/spectrum_analysis.ipynb
  tutorials/spectrum_simulation.ipynb
Labels: cleanup, feature

#2574 Generalisation of the power law with an exponential cut-off
  gammapy/modeling/models/spectral.py
  gammapy/modeling/models/tests/test_spectral.py
  gammapy/modeling/tests/test_serialize_yaml.py
  tutorials/analysis_3d.ipynb
Labels: feature

#2598 Remove interpolation warning
  gammapy/utils/interpolation.py
  gammapy/utils/tests/test_interpolation.py
Labels: cleanup

#2600 Remove Fermi catalog source categories and flags
  gammapy/catalog/fermi.py
  gammapy/catalog/tests/data/2fhl_j0822.6-4250e.txt
  gammapy/catalog/tests/data/2fhl_j1445.1-0329.txt
  gammapy/catalog/tests/data/3fgl_J0000.1+6545.txt
  gammapy/catalog/tests/data/3fgl_J0001.4+2120.txt
  gammapy/catalog/tests/data/3fgl_J0023.4+0923.txt
  gammapy/catalog/tests/data/3fgl_J0835.3-4510.txt
  gammapy/catalog/tests/data/3fhl_j2301.9+5855e.txt
  gammapy/catalog/tests/data/4fgl_J0000.3-7355.txt
  gammapy/catalog/tests/data/4fgl_J0001.5+2113.txt
  gammapy/catalog/tests/data/4fgl_J0002.8+6217.txt
  gammapy/catalog/tests/data/4fgl_J1409.1-6121e.txt
  gammapy/catalog/tests/test_fermi.py
Labels: cleanup

#2596 Remove error when ReflectedRegionsBackgroundMaker finds no off region
  gammapy/analysis/core.py
  gammapy/spectrum/reflected.py
  gammapy/spectrum/tests/test_reflected.py
Labels: bug

#2604 Implement additional methods on the safe mask maker
  gammapy/cube/make.py
  gammapy/cube/tests/test_make.py
  gammapy/spectrum/tests/test_make.py
Labels: feature

#2607 Change MapDatasetMaker parameters
  docs/cube/index.rst
  gammapy/analysis/core.py
  gammapy/cube/edisp_map.py
  gammapy/cube/fit.py
  gammapy/cube/make.py
  gammapy/cube/psf_map.py
  gammapy/cube/tests/test_make.py
  gammapy/cube/tests/test_ring.py
  gammapy/spectrum/tests/test_flux_point_estimator.py
  tutorials/analysis_3d.ipynb
  tutorials/analysis_3d_joint.ipynb
  tutorials/cta_data_analysis.ipynb
  tutorials/image_analysis.ipynb
  tutorials/light_curve.ipynb
  tutorials/simulate_3d.ipynb
Labels: cleanup

#2605 Add analysis config using pydantic
  .travis.yml
  azure-pipelines.yml
  docs/install/dependencies.rst
  docs/references.txt
  environment-dev.yml
  gammapy/analysis/config.py
  gammapy/analysis/config/config.yaml
  gammapy/analysis/tests/test_config.py
  setup.cfg
Labels: cleanup

#2608 Add gammapy download datasets -- tests flag
  .travis.yml
  Makefile
  azure-pipelines.yml
  gammapy/scripts/download.py
  gammapy/scripts/downloadclasses.py
Labels: cleanup

#2609 Improve CTA with Gammapy tutorial
  tutorials/cta.ipynb
  tutorials/cta_data_analysis.ipynb
  tutorials/images/cta-1dc.png
  tutorials/images/gammapy_datastore_butler.png
  tutorials/notebooks.yaml
Labels: docs

#2603 Test error propagation for AbsorbedSpectralModel
  gammapy/modeling/models/tests/test_spectral.py
Labels: tests

#2610 Improve SourceCatalog and SourceCatalogObject classes
  docs/catalog/index.rst
  gammapy/catalog/core.py
  gammapy/catalog/fermi.py
  gammapy/catalog/gammacat.py
  gammapy/catalog/hawc.py
  gammapy/catalog/hess.py
  gammapy/catalog/tests/data/3fgl_J0000.1+6545.txt
  gammapy/catalog/tests/data/3fgl_J0001.4+2120.txt
  gammapy/catalog/tests/data/3fgl_J0023.4+0923.txt
  gammapy/catalog/tests/data/3fgl_J0835.3-4510.txt
  gammapy/catalog/tests/data/4fgl_J0000.3-7355.txt
  gammapy/catalog/tests/data/4fgl_J0001.5+2113.txt
  gammapy/catalog/tests/data/4fgl_J0002.8+6217.txt
  gammapy/catalog/tests/test_core.py
  gammapy/catalog/tests/test_fermi.py
  gammapy/catalog/tests/test_gammacat.py
  gammapy/catalog/tests/test_hess.py
Labels: cleanup

#2612 Improve gammapy.catalog code
  gammapy/catalog/core.py
  gammapy/catalog/fermi.py
  gammapy/catalog/gammacat.py
  gammapy/catalog/hawc.py
  gammapy/catalog/hess.py
  gammapy/catalog/tests/data/2hwc_j0534+220.txt
  gammapy/catalog/tests/data/2hwc_j0631+169.txt
  gammapy/catalog/tests/data/3fhl_j2301.9+5855e.txt
  gammapy/catalog/tests/data/gammacat_hess_j1813-178.txt
  gammapy/catalog/tests/data/gammacat_hess_j1848-018.txt
  gammapy/catalog/tests/data/gammacat_vela_x.txt
  gammapy/catalog/tests/test_gammacat.py
  gammapy/catalog/tests/test_hess.py
Labels: cleanup

#2614 Remove default spectral model from SkyModel
  gammapy/catalog/fermi.py
  gammapy/catalog/gammacat.py
  gammapy/catalog/hawc.py
  gammapy/catalog/hess.py
  gammapy/modeling/models/cube.py
  gammapy/modeling/models/tests/test_cube.py
  gammapy/spectrum/tests/test_dataset.py
  gammapy/spectrum/tests/test_flux_point.py
  gammapy/spectrum/tests/test_flux_point_estimator.py
  gammapy/time/tests/test_lightcurve.py
  tutorials/fermi_lat.ipynb
Labels: cleanup

#2615 Write gammapy.catalog docs and tutorial
  docs/catalog/index.rst
  tutorials/catalog.ipynb
Labels: docs

#2617 Remove gamma-cat data collection
  docs/catalog/gammacat.rst
  docs/catalog/index.rst
  gammapy/catalog/gammacat.py
  gammapy/catalog/tests/test_gammacat.py
Labels: cleanup

#2619 Unify model setters of all datasets
  gammapy/modeling/serialize.py
  gammapy/spectrum/core.py
  gammapy/spectrum/dataset.py
  gammapy/spectrum/flux_point.py
  gammapy/spectrum/tests/test_dataset.py
  gammapy/spectrum/tests/test_flux_point.py
Labels: cleanup

#2620 Make SkyModel.spatial_model optional
  gammapy/analysis/tests/test_analysis.py
  gammapy/modeling/models/cube.py
  gammapy/modeling/models/tests/test_cube.py
Labels: cleanup

#2618 Fix ObservationTable select time
  gammapy/data/obs_table.py
  gammapy/data/tests/test_obs_table.py
Labels: bug

#2624 Fix MapDataset mask serialization
  gammapy/cube/fit.py
  gammapy/cube/tests/test_fit.py
Labels: bug

#2616 Add MapDatasetEventSampler with .sample_background() method
  gammapy/cube/simulate.py
  gammapy/cube/tests/test_simulate.py
Labels: feature

#2623 Fix SpectralModel.evaluate_error gradient computation
  gammapy/modeling/models/spectral.py
  gammapy/modeling/models/tests/test_spectral.py
Labels: bug

#2594 Notebook to explain how to compute a LC in small time bin
  tutorials/light_curve_flare.ipynb
Labels: docs

#2628 Edit doc-string of `MapDatasetOnOff`
  gammapy/cube/fit.py
Labels: docs

#2621 Rewrite AnalysisConfig and update Analysis
  .travis.yml
  azure-pipelines.yml
  docs/analysis/index.rst
  docs/install/dependencies.rst
  environment-dev.yml
  gammapy/analysis/__init__.py
  gammapy/analysis/config.py
  gammapy/analysis/config/config.yaml
  gammapy/analysis/config/docs.yaml
  gammapy/analysis/config/model.yaml
  gammapy/analysis/config/schema.yaml
  gammapy/analysis/config/template-1d.yaml
  gammapy/analysis/config/template-3d.yaml
  gammapy/analysis/config/template-basic.yaml
  gammapy/analysis/core.py
  gammapy/analysis/tests/test_analysis.py
  gammapy/analysis/tests/test_config.py
  setup.cfg
  tutorials/analysis_1.ipynb
  tutorials/light_curve.ipynb
Labels: feature

#2629 Improve gammapy.data.Observations
  gammapy/analysis/core.py
  gammapy/data/observations.py
  gammapy/data/tests/test_observations.py
  gammapy/modeling/datasets.py
  gammapy/modeling/models/cube.py
  gammapy/modeling/parameter.py
Labels: cleanup

#2627 Activate PSFMap for fitting
  gammapy/cube/fit.py
  gammapy/cube/psf_map.py
  gammapy/cube/simulate.py
  gammapy/cube/tests/test_fit.py
  gammapy/cube/tests/test_simulate.py
  gammapy/spectrum/tests/test_flux_point_estimator.py
  gammapy/time/tests/test_lightcurve.py
Labels: feature

#2631 Add Datasets read and write methods
  gammapy/cube/tests/test_fit.py
  gammapy/modeling/datasets.py
  gammapy/modeling/tests/data/make.py
  gammapy/modeling/tests/test_serialize_yaml.py
  gammapy/spectrum/tests/test_dataset.py
  gammapy/spectrum/tests/test_flux_point.py
  tutorials/joint_1d_3d_analysis.ipynb
Labels: cleanup

#2632 Hide `MapEvaluator` and `SpectrumEvaluator` from docs
  gammapy/cube/fit.py
  gammapy/maps/tests/test_wcsnd.py
  gammapy/modeling/models/tests/test_cube.py
  gammapy/spectrum/core.py
  gammapy/spectrum/dataset.py
  gammapy/spectrum/tests/test_core.py
  gammapy/spectrum/tests/test_flux_point_estimator.py
  tutorials/fermi_lat.ipynb
Labels: cleanup

#2633 Lighter light curve flare notebook
  tutorials/light_curve_flare.ipynb
Labels: cleanup, docs

#2636 Add map_selection parameter in Analysis
  gammapy/analysis/config.py
  gammapy/analysis/config/config.yaml
  gammapy/analysis/config/docs.yaml
  gammapy/analysis/config/template-1d.yaml
  gammapy/analysis/config/template-3d.yaml
  gammapy/analysis/core.py
Labels: feature

#2637 Remove keepdims option from MapDataset.to_images()
  gammapy/cube/exposure.py
  gammapy/cube/fit.py
Labels: bug

#2634 Remove requirements check for tutorial CI tests
  .travis.yml
  gammapy/utils/tutorials_test.py
  tutorials/notebooks.yaml
Labels: cleanup

#2640 Reduced Light Curve notebook
  tutorials/light_curve.ipynb
Labels: cleanup, docs

#2639 Use PSFMap in Analysis class
  gammapy/analysis/config.py
  gammapy/analysis/config/config.yaml
  gammapy/analysis/config/docs.yaml
  gammapy/analysis/config/template-1d.yaml
  gammapy/analysis/core.py
Labels: cleanup

#2643 Restructured analysis 1 notebook
  tutorials/analysis_1.ipynb
Labels: cleanup, docs

#2641 Update 1d/3d Crab tutorial
  tutorials/joint_1d_3d_analysis.ipynb
Labels: docs

#2642 Improve Analysis and AnalysisConfig
  docs/analysis/index.rst
  gammapy/analysis/config.py
  gammapy/analysis/config/config.yaml
  gammapy/analysis/core.py
  gammapy/analysis/tests/test_analysis.py
  gammapy/analysis/tests/test_config.py
  tutorials/light_curve.ipynb
Labels: cleanup

#2625 Add sample_sources to MapDatasetEventSampler
  gammapy/cube/simulate.py
  gammapy/cube/tests/test_simulate.py
Labels: feature

#2635 Change Datasets model to models
  examples/example_2_gauss.py
  gammapy/analysis/core.py
  gammapy/analysis/tests/test_analysis.py
  gammapy/cube/fit.py
  gammapy/cube/simulate.py
  gammapy/cube/tests/test_fit.py
  gammapy/cube/tests/test_simulate.py
  gammapy/modeling/models/cube.py
  gammapy/modeling/serialize.py
  gammapy/modeling/tests/data/make.py
  gammapy/modeling/tests/test_serialize_yaml.py
  gammapy/spectrum/dataset.py
  gammapy/spectrum/flux_point.py
  gammapy/spectrum/tests/test_dataset.py
  gammapy/spectrum/tests/test_fit.py
  gammapy/spectrum/tests/test_flux_point_estimator.py
  gammapy/time/lightcurve_estimator.py
  tutorials/analysis_1.ipynb
  tutorials/analysis_3d.ipynb
  tutorials/cta_data_analysis.ipynb
  tutorials/fermi_lat.ipynb
  tutorials/image_analysis.ipynb
  tutorials/joint_1d_3d_analysis.ipynb
  tutorials/light_curve.ipynb
  tutorials/light_curve_flare.ipynb
  tutorials/mcmc_sampling.ipynb
  tutorials/pulsar_analysis.ipynb
  tutorials/spectrum_analysis.ipynb
  tutorials/spectrum_simulation.ipynb
Labels: cleanup
