Repository gammapy/gammapy, pull requests merged in 2019-08, with the labels that each got.

#2303 Update PIG 5 - Gammapy 1.0 roadmap
  docs/development/pigs/pig-005.rst
Labels: pig

#2317 Drop Python 3.5 CI testing
  .travis.yml
  azure-pipelines.yml
  gammapy/astro/population/tests/test_spatial.py
  gammapy/astro/population/tests/test_velocity.py
  gammapy/irf/tests/test_io.py
  gammapy/spectrum/models.py
  gammapy/spectrum/tests/test_models.py
Labels: infrastructure, tests

#2274 PIG 16 - Gammapy package structure
  docs/development/pigs/index.rst
  docs/development/pigs/pig-016-gammapy-package-organisation-proposal.png
  docs/development/pigs/pig-016-gammapy-package-organisation-status.png
  docs/development/pigs/pig-016.rst
Labels: pig

#2219 PIG 12 - High-level interface
  docs/development/pigs/pig-012.rst
Labels: pig

#2308 Use parfive in gammapy download
  .travis.yml
  azure-pipelines.yml
  environment-dev.yml
  gammapy/scripts/downloadclasses.py
  gammapy/scripts/tests/test_download.py
  setup.py
Labels: feature

#2313 Add elongated gaussian model
  gammapy/image/models/core.py
  gammapy/image/models/tests/test_core.py
Labels: feature

#2327 Hide progress bar in `gammapy download`
  .travis.yml
  azure-pipelines.yml
  gammapy/scripts/download.py
  gammapy/scripts/downloadclasses.py
Labels: feature

#2326 Fix bug in the Gaussian model evaluate method
  gammapy/spectrum/models.py
  gammapy/spectrum/tests/test_models.py
Labels: bug

#2324 Fix FluxPointDataset plot_residual method
  gammapy/spectrum/flux_point.py
  gammapy/spectrum/tests/test_flux_point.py
Labels: bug

#2323 Add high-level Conf and Analysis classes
  .travis.yml
  azure-pipelines.yml
  environment-dev.yml
  gammapy/scripts/__init__.py
  gammapy/scripts/analysis.py
  gammapy/scripts/config/schema.yaml
  gammapy/scripts/tests/test_analysis.py
  setup.cfg
Labels: feature

#2314 Add datasets serialization
  gammapy/cube/fit.py
  gammapy/cube/models.py
  gammapy/cube/tests/test_fit.py
  gammapy/utils/fitting/datasets.py
  gammapy/utils/serialization/io.py
  gammapy/utils/serialization/tests/data/examples.yaml
  gammapy/utils/serialization/tests/make_test_data.py
  gammapy/utils/serialization/tests/test_io.py
Labels: feature

#2136 PIG 9 - Event sampling
  docs/development/pigs/pig-009.rst
Labels: pig

#2331 Move catalog test data to text files
  Makefile
  gammapy/catalog/hess.py
  gammapy/catalog/registry.py
  gammapy/catalog/tests/data/2hwc_j0534+220.txt
  gammapy/catalog/tests/data/2hwc_j0631+169.txt
  gammapy/catalog/tests/data/3fgl_J0000.1+6545.txt
  gammapy/catalog/tests/data/3fgl_J0001.4+2120.txt
  gammapy/catalog/tests/data/3fgl_J0023.4+0923.txt
  gammapy/catalog/tests/data/3fgl_J0835.3-4510.txt
  gammapy/catalog/tests/data/3fhl_j2301.9+5855e.txt
  gammapy/catalog/tests/data/gammacat_hess_j1813-178.txt
  gammapy/catalog/tests/data/gammacat_hess_j1848-018.txt
  gammapy/catalog/tests/data/gammacat_vela_x.txt
  gammapy/catalog/tests/data/hess_j1713-397.txt
  gammapy/catalog/tests/data/hess_j1825-137.txt
  gammapy/catalog/tests/data/hess_j1930+188.txt
  gammapy/catalog/tests/data/make.py
  gammapy/catalog/tests/test_fermi.py
  gammapy/catalog/tests/test_gammacat.py
  gammapy/catalog/tests/test_hawc.py
  gammapy/catalog/tests/test_hess.py
  gammapy/cube/simulate.py
  gammapy/irf/tests/test_psf_gauss.py
  gammapy/utils/fitting/datasets.py
  gammapy/utils/serialization/io.py
  setup.cfg
Labels: cleanup

#2320 Dissolve gammapy.background
  docs/background/index.rst
  docs/development/pigs/pig-010.rst
  docs/index.rst
  docs/spectrum/create_region.py
  docs/spectrum/index.rst
  docs/spectrum/make_rectangular_reflected_background.py
  docs/spectrum/make_reflected_regions.py
  docs/spectrum/reflected.rst
  gammapy/__init__.py
  gammapy/background/__init__.py
  gammapy/background/tests/__init__.py
  gammapy/cube/__init__.py
  gammapy/cube/make.py
  gammapy/cube/ring.py
  gammapy/cube/tests/test_make.py
  gammapy/cube/tests/test_ring.py
  gammapy/data/obs_stats.py
  gammapy/data/tests/test_obs_stats.py
  gammapy/data/tests/test_obs_summary.py
  gammapy/detect/kernel.py
  gammapy/scripts/jupyter.py
  gammapy/scripts/spectrum_pipe.py
  gammapy/spectrum/__init__.py
  gammapy/spectrum/background_estimate.py
  gammapy/spectrum/extract.py
  gammapy/spectrum/phase.py
  gammapy/spectrum/reflected.py
  gammapy/spectrum/tests/test_extract.py
  gammapy/spectrum/tests/test_phase.py
  gammapy/spectrum/tests/test_reflected.py
  tutorials/cta_data_analysis.ipynb
  tutorials/hess.ipynb
  tutorials/light_curve.ipynb
  tutorials/mcmc_sampling.ipynb
  tutorials/pulsar_analysis.ipynb
  tutorials/spectrum_analysis.ipynb
Labels: cleanup
