Repository gammapy/gammapy, pull requests merged in 2019-10, with the labels that each got.

#2426 Fix compatibility with astropy dev and numpy 1.17
  gammapy/cube/tests/test_fit.py
  gammapy/data/event_list.py
  gammapy/maps/tests/test_wcs.py
  gammapy/maps/wcsnd.py
  gammapy/scripts/analysis.py
  gammapy/spectrum/core.py
  gammapy/spectrum/flux_point.py
Labels: cleanup

#2424 High-level interface: improve test coverage
  gammapy/scripts/analysis.py
  gammapy/scripts/tests/test_analysis.py
Labels: tests

#2433 Update versions in travis
  .travis.yml
Labels: infrastructure, tests

#2435 Add modeling notebook with model plot examples
  docs/maps/index.rst
  docs/modeling/index.rst
  docs/tutorials.rst
  gammapy/modeling/models/spatial.py
  gammapy/modeling/models/spectral.py
  tutorials/first_steps.ipynb
  tutorials/maps.ipynb
  tutorials/models.ipynb
  tutorials/notebooks.yaml
Labels: cleanup, docs

#2441 Add GTI export in datasets
  gammapy/cube/fit.py
  gammapy/cube/tests/test_fit.py
  gammapy/data/gti.py
  gammapy/data/tests/test_gti.py
  gammapy/spectrum/dataset.py
  gammapy/spectrum/tests/test_dataset.py
Labels: bug

#2444 Remove `MapMaker` class
  gammapy/cube/fit.py
  gammapy/cube/make.py
  gammapy/cube/tests/test_make.py
  gammapy/modeling/tests/data/make.py
  tutorials/analysis_3d.ipynb
  tutorials/analysis_3d_joint.ipynb
  tutorials/cta_data_analysis.ipynb
  tutorials/image_analysis.ipynb
  tutorials/image_fitting_with_sherpa.ipynb
  tutorials/light_curve.ipynb
Labels: cleanup

#2445 Fix `SpectrumDatasetOnOff.energy_range` for empty mask_safe
  gammapy/irf/energy_dispersion.py
  gammapy/spectrum/dataset.py
  gammapy/spectrum/tests/test_dataset.py
Labels: bug

#2450 Rename and refactor `MapMakerObs`
  gammapy/cube/make.py
  gammapy/cube/tests/test_make.py
  gammapy/modeling/tests/data/make.py
  gammapy/scripts/analysis.py
  tutorials/analysis_3d.ipynb
  tutorials/analysis_3d_joint.ipynb
  tutorials/cta_data_analysis.ipynb
  tutorials/image_analysis.ipynb
  tutorials/image_fitting_with_sherpa.ipynb
  tutorials/light_curve.ipynb
Labels: cleanup

#2454 Add a norm to the EBL model
  gammapy/modeling/models/spectral.py
  gammapy/modeling/models/tests/test_spectral.py
  gammapy/modeling/tests/test_serialize_yaml.py
  gammapy/spectrum/flux_point.py
Labels: feature

#2456 Change to log binning in flux point estimator tests
  gammapy/spectrum/tests/test_flux_point_estimator.py
  gammapy/time/tests/test_lightcurve.py
Labels: cleanup, tests

#2455 Improve datasets serialization to support different dataset classes
  gammapy/cube/fit.py
  gammapy/modeling/datasets.py
  gammapy/modeling/models/__init__.py
  gammapy/modeling/serialize.py
  gammapy/spectrum/dataset.py
  gammapy/spectrum/flux_point.py
Labels: cleanup

#2449 Fix and improve 2HWC catalog source models
  gammapy/catalog/hawc.py
  gammapy/catalog/tests/data/2hwc_j0534+220.txt
  gammapy/catalog/tests/data/2hwc_j0631+169.txt
  gammapy/catalog/tests/test_hawc.py
Labels: feature

#2462 Use `Conda activate root` in travis setup
  .travis.yml
Labels: bug

#2461 Remove error raising, when model component moves out of the image
  gammapy/cube/fit.py
  gammapy/cube/tests/test_fit.py
Labels: cleanup

#2448 Improve 4FGL catalog support
  gammapy/catalog/fermi.py
  gammapy/catalog/registry.py
  gammapy/catalog/tests/data/3fgl_J0000.1+6545.txt
  gammapy/catalog/tests/data/3fgl_J0001.4+2120.txt
  gammapy/catalog/tests/data/3fgl_J0023.4+0923.txt
  gammapy/catalog/tests/data/3fgl_J0835.3-4510.txt
  gammapy/catalog/tests/data/3fhl_j2301.9+5855e.txt
  gammapy/catalog/tests/data/4fgl_J0000.3-7355.txt
  gammapy/catalog/tests/data/4fgl_J0001.5+2113.txt
  gammapy/catalog/tests/data/4fgl_J0002.8+6217.txt
  gammapy/catalog/tests/data/4fgl_J1409.1-6121e.txt
  gammapy/catalog/tests/data/make.py
  gammapy/catalog/tests/test_fermi.py
  gammapy/maps/geom.py
  gammapy/modeling/models/spatial.py
Labels: feature

#2459 Add FluxPointsDataset serialization
  gammapy/modeling/model.py
  gammapy/modeling/models/spatial.py
  gammapy/spectrum/flux_point.py
  gammapy/spectrum/tests/test_flux_point.py
Labels: feature

#2464 Implement `SpectrumDatasetMaker`
  gammapy/maps/geom.py
  gammapy/spectrum/__init__.py
  gammapy/spectrum/make.py
  gammapy/spectrum/reflected.py
  gammapy/spectrum/tests/test_extract.py
  gammapy/spectrum/tests/test_make.py
Labels: cleanup, feature

#2467 Simplify source catalog registry and improve docs
  docs/catalog/index.rst
  gammapy/catalog/fermi.py
  gammapy/catalog/registry.py
  gammapy/catalog/snrcat.py
  gammapy/catalog/tests/data/make.py
  gammapy/catalog/tests/test_registry.py
  gammapy/maps/geom.py
  gammapy/spectrum/make.py
  gammapy/spectrum/tests/test_extract.py
  gammapy/spectrum/tests/test_make.py
  tutorials/detect_ts.ipynb
Labels: cleanup

#2469 Simplify number type checking
  gammapy/catalog/core.py
  gammapy/catalog/tests/test_core.py
  gammapy/modeling/parameter.py
  gammapy/utils/array.py
Labels: cleanup

#2471 Fix skycoord frame handling in MapCoord.create
  gammapy/maps/geom.py
  gammapy/maps/tests/test_geom.py
Labels: bug

#2470 Add MapDataset.from_geoms
  gammapy/cube/fit.py
  gammapy/cube/tests/test_fit.py
Labels: cleanup

#2468 Improve map and spectrum events fill methods
  docs/maps/index.rst
  gammapy/cube/__init__.py
  gammapy/cube/counts.py
  gammapy/cube/make.py
  gammapy/cube/tests/test_counts.py
  gammapy/data/event_list.py
  gammapy/maps/base.py
  gammapy/modeling/models/spectral.py
  gammapy/scripts/image_bin.py
  gammapy/spectrum/core.py
  gammapy/spectrum/extract.py
  gammapy/spectrum/make.py
  tutorials/pulsar_analysis.ipynb
Labels: cleanup

#2472 Remove multiprocessing code
  docs/detect/index.rst
  docs/development/howto.rst
  gammapy/detect/test_statistics.py
  gammapy/detect/tests/test_test_statistics.py
  gammapy/maps/image_utils.py
Labels: cleanup

#2473 Change path in datasets serialization
  gammapy/cube/fit.py
  gammapy/modeling/datasets.py
  gammapy/modeling/serialize.py
  gammapy/modeling/tests/test_serialize_yaml.py
  gammapy/spectrum/flux_point.py
  gammapy/spectrum/tests/test_flux_point.py
Labels: cleanup

#2474 Change catalog source models to methods for API uniformity
  gammapy/catalog/fermi.py
  gammapy/catalog/gammacat.py
  gammapy/catalog/hawc.py
  gammapy/catalog/hess.py
  gammapy/catalog/tests/test_fermi.py
  gammapy/catalog/tests/test_gammacat.py
  gammapy/catalog/tests/test_hess.py
  gammapy/scripts/jupyter.py
  gammapy/spectrum/tests/test_flux_point.py
  tutorials/first_steps.ipynb
  tutorials/models.ipynb
  tutorials/sed_fitting_gammacat_fermi.ipynb
Labels: cleanup

#2476 Remove Fermi-LAT 1FHL catalog
  docs/catalog/index.rst
  examples/example_fermi_catalogs.py
  gammapy/catalog/fermi.py
  gammapy/catalog/registry.py
  gammapy/catalog/tests/test_fermi.py
Labels: cleanup

#1971 PIG 7 - Models
  docs/development/pigs/pig-007.rst
Labels: pig

#2475 Implement `ReflectedRegionsBackgroundMaker`
  gammapy/spectrum/reflected.py
  gammapy/spectrum/tests/test_reflected.py
Labels: cleanup

#2477 Add SafeMaskMaker
  gammapy/spectrum/make.py
  gammapy/spectrum/tests/test_make.py
Labels: cleanup

#2478 Improve 2FHL catalog support
  gammapy/catalog/core.py
  gammapy/catalog/fermi.py
  gammapy/catalog/tests/data/2fhl_j0822.6-4250e.txt
  gammapy/catalog/tests/data/2fhl_j1445.1-0329.txt
  gammapy/catalog/tests/data/make.py
  gammapy/catalog/tests/test_fermi.py
Labels: feature

#2480 Clean syntax to make links to docs in notebooks
  CHANGES.rst
  Makefile
  docs/astro/darkmatter/index.rst
  docs/catalog/index.rst
  docs/cube/index.rst
  docs/data/index.rst
  docs/detect/index.rst
  docs/development/howto.rst
  docs/irf/index.rst
  docs/maps/index.rst
  docs/modeling/index.rst
  docs/scripts/index.rst
  docs/spectrum/index.rst
  docs/spectrum/reflected.rst
  gammapy/catalog/hess.py
  gammapy/data/data_store.py
  gammapy/maps/plotting.py
  gammapy/spectrum/extract.py
  gammapy/spectrum/reflected.py
  gammapy/spectrum/sensitivity.py
  gammapy/utils/docs.py
  gammapy/utils/tutorials_links.py
  gammapy/utils/units.py
  tutorials/analysis_3d.ipynb
  tutorials/analysis_3d_joint.ipynb
  tutorials/astro_dark_matter.ipynb
  tutorials/background_model.ipynb
  tutorials/cta_1dc_introduction.ipynb
  tutorials/cta_data_analysis.ipynb
  tutorials/cta_sensitivity.ipynb
  tutorials/cwt.ipynb
  tutorials/detect_ts.ipynb
  tutorials/fermi_lat.ipynb
  tutorials/first_steps.ipynb
  tutorials/hess.ipynb
  tutorials/hgps.ipynb
  tutorials/image_analysis.ipynb
  tutorials/image_fitting_with_sherpa.ipynb
  tutorials/light_curve.ipynb
  tutorials/maps.ipynb
  tutorials/mcmc_sampling.ipynb
  tutorials/models.ipynb
  tutorials/pulsar_analysis.ipynb
  tutorials/sed_fitting_gammacat_fermi.ipynb
  tutorials/simulate_3d.ipynb
  tutorials/source_population_model.ipynb
  tutorials/spectrum_analysis.ipynb
  tutorials/spectrum_fitting_with_sherpa.ipynb
  tutorials/spectrum_simulation.ipynb
Labels: cleanup, docs

#2479 Change parametrisation from `geom_true` to `energy_axis_true`
  gammapy/cube/fit.py
  gammapy/cube/make.py
  gammapy/cube/tests/test_fit.py
  gammapy/cube/tests/test_make.py
  gammapy/scripts/analysis.py
  gammapy/scripts/config/docs.yaml
  gammapy/scripts/config/schema.yaml
  gammapy/scripts/config/template-3d.yaml
  gammapy/scripts/tests/test_analysis.py
  tutorials/hess.ipynb
  tutorials/light_curve.ipynb
Labels: cleanup

#2489 Refactor spectrum extraction tests
  gammapy/scripts/analysis.py
  gammapy/spectrum/make.py
  gammapy/spectrum/reflected.py
  gammapy/spectrum/tests/test_extract.py
  gammapy/spectrum/tests/test_make.py
Labels: cleanup

#2490 Improve Parameters class
  gammapy/cube/fit.py
  gammapy/modeling/datasets.py
  gammapy/modeling/fit.py
  gammapy/modeling/iminuit.py
  gammapy/modeling/model.py
  gammapy/modeling/models/cube.py
  gammapy/modeling/models/spatial.py
  gammapy/modeling/models/spectral.py
  gammapy/modeling/parameter.py
  gammapy/modeling/serialize.py
  gammapy/modeling/tests/data/example2.yaml
  gammapy/modeling/tests/data/make.py
  gammapy/modeling/tests/test_iminuit.py
  gammapy/modeling/tests/test_parameter.py
  gammapy/modeling/tests/test_serialize_yaml.py
  gammapy/scripts/tests/test_analysis.py
  gammapy/spectrum/dataset.py
  gammapy/spectrum/flux_point.py
  tutorials/image_analysis.ipynb
  tutorials/simulate_3d.ipynb
Labels: cleanup

#2486 update default value in simulate_dataset (0°->1°)
  gammapy/cube/simulate.py
  gammapy/cube/tests/test_simulate.py
  gammapy/spectrum/tests/test_flux_point_estimator.py
  gammapy/time/tests/test_lightcurve.py
Labels: cleanup

#2492 Change `MapDataset.mask_fit` and `MapDataset.mask_safe` to maps
  gammapy/cube/fit.py
  gammapy/cube/make.py
  gammapy/cube/tests/test_fit.py
  gammapy/modeling/datasets.py
  tutorials/image_analysis.ipynb
Labels: cleanup

#2481 Add MapDatasetOnOff
  gammapy/cube/edisp_map.py
  gammapy/cube/fit.py
  gammapy/cube/psf_map.py
  gammapy/cube/tests/test_fit.py
  gammapy/stats/fit_statistics.py
Labels: feature

#1451 PIG 11 - Light curves
  docs/development/pigs/pig-011.rst
Labels: pig

#2493 Add region info to `CountsSpectrum` and adapt tutorials
  gammapy/spectrum/core.py
  gammapy/spectrum/dataset.py
  gammapy/spectrum/make.py
  gammapy/spectrum/reflected.py
  gammapy/spectrum/tests/test_reflected.py
  gammapy/utils/regions.py
  tutorials/cta_data_analysis.ipynb
  tutorials/light_curve.ipynb
  tutorials/spectrum_analysis.ipynb
Labels: cleanup

#2491 Add SpatialModel.position_error and SpatialModel.to_region
  gammapy/catalog/fermi.py
  gammapy/catalog/gammacat.py
  gammapy/catalog/hawc.py
  gammapy/catalog/hess.py
  gammapy/catalog/tests/test_fermi.py
  gammapy/catalog/tests/test_gammacat.py
  gammapy/catalog/tests/test_hawc.py
  gammapy/catalog/tests/test_hess.py
  gammapy/modeling/models/spatial.py
  gammapy/modeling/parameter.py
Labels: feature

#2497 Refactor PhaseBackgroundEstimator to PhaseBackgroundMaker
  gammapy/spectrum/phase.py
  gammapy/spectrum/tests/test_phase.py
  tutorials/pulsar_analysis.ipynb
Labels: cleanup

#2496 Add PSFMap.sample_coord method
  gammapy/cube/psf_map.py
  gammapy/cube/tests/test_psf_map.py
Labels: feature

#2500 Add empty docs pages: "Overview" and "How To"
  docs/getting-started.rst
  docs/howto.rst
  docs/index.rst
  docs/maps/index.rst
  docs/maps/wcsmap.rst
  docs/overview.rst
  docs/tutorials.rst
Labels: cleanup

#2501 Add .to_region() test for each spatial model
  gammapy/modeling/models/spatial.py
  gammapy/modeling/models/tests/test_spatial.py
Labels: bug

#1877 PIG 6 - CTA observation handling
  docs/development/pigs/index.rst
  docs/development/pigs/pig-006-class-diagram.png
  docs/development/pigs/pig-006.rst
Labels: pig

#2502 Remove ObservationStats, ObservationsSummary and BackgroundEstimate
  docs/spectrum/make_rectangular_reflected_background.py
  docs/spectrum/reflected.rst
  gammapy/data/__init__.py
  gammapy/data/obs_stats.py
  gammapy/data/obs_summary.py
  gammapy/data/tests/test_obs_stats.py
  gammapy/data/tests/test_obs_summary.py
  gammapy/modeling/datasets.py
  gammapy/scripts/analysis.py
  gammapy/spectrum/__init__.py
  gammapy/spectrum/background_estimate.py
  gammapy/spectrum/dataset.py
  gammapy/spectrum/reflected.py
  gammapy/spectrum/tests/test_dataset.py
  gammapy/spectrum/tests/test_make.py
  gammapy/spectrum/tests/test_reflected.py
  tutorials/cta_data_analysis.ipynb
  tutorials/light_curve.ipynb
  tutorials/spectrum_analysis.ipynb
Labels: cleanup

#2494 Improve model parameter framework
  docs/spectrum/make_reflected_regions.py
  gammapy/astro/darkmatter/spectra.py
  gammapy/catalog/hawc.py
  gammapy/cube/tests/test_exposure.py
  gammapy/irf/effective_area.py
  gammapy/irf/psf_table.py
  gammapy/maps/tests/test_wcsnd.py
  gammapy/modeling/model.py
  gammapy/modeling/models/cube.py
  gammapy/modeling/models/spatial.py
  gammapy/modeling/models/spectral.py
  gammapy/modeling/models/spectral_cosmic_ray.py
  gammapy/modeling/models/temporal.py
  gammapy/modeling/models/tests/test_cube.py
  gammapy/modeling/models/tests/test_spatial.py
  gammapy/modeling/models/tests/test_spectral.py
  gammapy/modeling/models/tests/test_spectral_cosmic_ray.py
  gammapy/modeling/models/tests/test_temporal.py
  gammapy/modeling/parameter.py
  gammapy/modeling/tests/test_model.py
  gammapy/modeling/tests/test_parameter.py
  gammapy/modeling/tests/test_serialize_yaml.py
  gammapy/spectrum/tests/test_core.py
  gammapy/spectrum/tests/test_dataset.py
  gammapy/spectrum/tests/test_fit.py
  gammapy/spectrum/tests/test_flux_point_estimator.py
  gammapy/time/lightcurve.py
  tutorials/fermi_lat.ipynb
  tutorials/models.ipynb
  tutorials/spectrum_simulation.ipynb
Labels: cleanup, feature
