Repository gammapy/gammapy, pull requests merged in 2019-06, with the labels that each got.

#2189 Move Binder environment to gammapy-webpage repo
  Dockerfile
  README.rst
  binder.py
  docs/development/release.rst
  gammapy/utils/docs.py
  setup.cfg
Labels: docs, infrastructure

#2201 Make links in notebooks point to right docs version
  gammapy/utils/docs.py
  gammapy/utils/tutorials_process.py
  tutorials/first_steps.ipynb
  tutorials/mcmc_sampling.ipynb
  tutorials/spectrum_fitting_with_sherpa.ipynb
Labels: docs

#2205 Remove unused profile_background_estimate function
  gammapy/background/background_estimate.py
Labels: cleanup

#2206 Remove unused map iter_by_pix and iter_by_coord methods
  docs/maps/index.rst
  gammapy/maps/base.py
  gammapy/maps/hpxsparse.py
  gammapy/maps/tests/test_hpxmap.py
  gammapy/maps/tests/test_wcsnd.py
  gammapy/maps/utils.py
Labels: cleanup

#2207 Simplify Jupyter notebook execution
  gammapy/scripts/jupyter.py
  gammapy/utils/tutorials_process.py
Labels: cleanup, docs

#2209 Improve .lo_threshold setter for `PHACountsSpectrum` and improve tests for spectrum.core.py
  gammapy/spectrum/core.py
  gammapy/spectrum/tests/test_core.py
Labels: cleanup

#2212 Remove git_commit flag in the doc building process
  Makefile
  docs/development/howto.rst
  docs/development/release.rst
  gammapy/utils/docs.py
  gammapy/utils/tutorials_process.py
  setup.cfg
Labels: cleanup, docs

#2178 Remove errors thrown by gammapy download
  gammapy/scripts/downloadclasses.py
Labels: bug

#2204 Clean-up in gammapy.utils.random
  docs/astro/population/plot_radial_distributions.py
  docs/astro/population/plot_velocity_distributions.py
  docs/utils/index.rst
  gammapy/astro/population/simulate.py
  gammapy/utils/distributions/general_random_array.py
  gammapy/utils/distributions/tests/test_general_random_array.py
  gammapy/utils/distributions/utils.py
  gammapy/utils/random/__init__.py
  gammapy/utils/random/general_random.py
  gammapy/utils/random/tests/__init__.py
  gammapy/utils/random/tests/test_general_random.py
  gammapy/utils/random/tests/test_random.py
  gammapy/utils/random/utils.py
Labels: cleanup

#2217 Refactor gammapy download
  gammapy/scripts/download.py
  gammapy/scripts/downloadclasses.py
  gammapy/scripts/tests/test_download.py
Labels: cleanup

#2224 Test notebooks in temporal folder
  gammapy/utils/tutorials_test.py
Labels: cleanup

#2222 Replace subprocess.call with subprocess.run
  gammapy/data/data_store.py
  gammapy/scripts/jupyter.py
  gammapy/utils/scripts_test.py
  gammapy/utils/tutorials_process.py
  gammapy/utils/tutorials_test.py
Labels: cleanup

#2214 Improve coverage for spectrum
  gammapy/spectrum/dataset.py
  gammapy/spectrum/tests/test_crab.py
  gammapy/spectrum/tests/test_dataset.py
  gammapy/spectrum/tests/test_extract.py
Labels: tests

#2230 Improve spectrum/models.py coverage
  gammapy/spectrum/tests/test_models.py
Labels: tests

#2231 Further clean-up of spectrum datasets
  gammapy/scripts/spectrum_pipe.py
  gammapy/spectrum/core.py
  gammapy/spectrum/dataset.py
  gammapy/spectrum/extract.py
  gammapy/spectrum/tests/test_dataset.py
  gammapy/time/lightcurve.py
  tutorials/pulsar_analysis.ipynb
Labels: cleanup

#2229 Adding the InverseCDFSampler
  gammapy/utils/random/__init__.py
  gammapy/utils/random/inverse_cdf.py
  gammapy/utils/random/tests/test_inverse_cdf.py
  gammapy/utils/random/utils.py
Labels: feature

#2235 removed unused functions in stats/data.py
  gammapy/stats/data.py
Labels: cleanup

#2237 Remove Energy and EnergyBounds classes
  docs/utils/index.rst
  gammapy/catalog/fermi.py
  gammapy/data/event_list.py
  gammapy/irf/effective_area.py
  gammapy/irf/energy_dispersion.py
  gammapy/irf/irf_reduce.py
  gammapy/irf/psf_3d.py
  gammapy/irf/psf_gauss.py
  gammapy/irf/psf_king.py
  gammapy/irf/psf_table.py
  gammapy/irf/tests/test_energy_dispersion.py
  gammapy/irf/tests/test_irf_reduce.py
  gammapy/scripts/tests/test_spectrum_pipe.py
  gammapy/spectrum/core.py
  gammapy/spectrum/models.py
  gammapy/spectrum/simulation.py
  gammapy/spectrum/tests/test_core.py
  gammapy/spectrum/tests/test_models.py
  gammapy/spectrum/tests/test_simulation.py
  gammapy/time/tests/test_lightcurve.py
  gammapy/utils/energy.py
  gammapy/utils/fits.py
  gammapy/utils/tests/test_energy.py
  tutorials/cta_data_analysis.ipynb
  tutorials/light_curve.ipynb
  tutorials/pulsar_analysis.ipynb
Labels: cleanup

#2239 Remove GeneralRandom class
  gammapy/astro/population/tests/test_simulate.py
  gammapy/utils/random/__init__.py
  gammapy/utils/random/general_random.py
  gammapy/utils/random/tests/test_general_random.py
  gammapy/utils/random/utils.py
Labels: cleanup

#2241 Remove gammapy.catalog.coordinate_iau_format
  gammapy/catalog/tests/test_utils.py
  gammapy/catalog/utils.py
Labels: cleanup

#2240 Remove use of NDDataArray from CountsSpectrum
  gammapy/spectrum/core.py
  gammapy/spectrum/dataset.py
  gammapy/spectrum/flux_point.py
  gammapy/spectrum/sensitivity.py
  gammapy/spectrum/simulation.py
  gammapy/spectrum/tests/test_core.py
  gammapy/spectrum/tests/test_dataset.py
  gammapy/spectrum/tests/test_extract.py
  gammapy/spectrum/tests/test_fit.py
  gammapy/spectrum/tests/test_sensitivity.py
  gammapy/spectrum/tests/test_simulation.py
  gammapy/spectrum/tests/test_utils.py
  gammapy/time/lightcurve.py
  gammapy/utils/nddata.py
  gammapy/utils/tests/test_nddata.py
  tutorials/cta_sensitivity.ipynb
Labels: cleanup

#2129 PIG 10 - Regions
  docs/development/pigs/index.rst
  docs/development/pigs/pig-010.rst
Labels: pig

#2242 Add gammapy.utils.regions helpers
  docs/utils/index.rst
  gammapy/utils/regions.py
  gammapy/utils/tests/test_regions.py
Labels: feature

#2243 Speed up mcmc_sampling tutorial
  tutorials/mcmc_sampling.ipynb
Labels: cleanup, docs

#2245 Remove gaussian_sum_moments
  gammapy/utils/gauss.py
  gammapy/utils/tests/test_gauss.py
Labels: cleanup

#2246 Simplify `PHACountsSpectrum`
  gammapy/spectrum/core.py
  gammapy/spectrum/dataset.py
  gammapy/spectrum/extract.py
  gammapy/spectrum/tests/test_core.py
  gammapy/spectrum/tests/test_dataset.py
  gammapy/spectrum/tests/test_fit.py
  tutorials/cta_data_analysis.ipynb
Labels: cleanup

#2250 Remove PHACountsSpectrum class
  gammapy/spectrum/core.py
  gammapy/spectrum/dataset.py
  gammapy/spectrum/extract.py
  gammapy/spectrum/simulation.py
  gammapy/spectrum/tests/test_core.py
  gammapy/spectrum/tests/test_dataset.py
  gammapy/spectrum/tests/test_fit.py
  gammapy/time/lightcurve.py
Labels: cleanup

#2244 Add Gaussian spectral model
  gammapy/spectrum/models.py
  gammapy/spectrum/tests/test_models.py
Labels: feature

#2254 Add select_region method for event lists
  gammapy/data/event_list.py
  gammapy/data/tests/test_event_list.py
  gammapy/utils/regions.py
  gammapy/utils/tests/test_regions.py
Labels: feature

#2259 Fix Fit.minos contour method for frozen parameters.
  gammapy/utils/fitting/iminuit.py
  gammapy/utils/fitting/tests/test_fit.py
Labels: bug

#2089 Improved Reflected Background class
  docs/background/create_region.py
  docs/background/make_rectangular_reflected_background.py
  docs/background/reflected.rst
  gammapy/background/reflected.py
  gammapy/background/tests/test_reflected.py
  gammapy/data/tests/test_obs_stats.py
  gammapy/spectrum/tests/test_extract.py
  gammapy/time/tests/test_lightcurve.py
  setup.py
Labels: feature

#2263 Fix compatibility of SpectrumEvaluator with Powerlaw2 models
  gammapy/spectrum/tests/test_utils.py
  gammapy/spectrum/utils.py
Labels: bug
