Repository gammapy/gammapy, pull requests merged in 2019-04, with the labels that each got.

#2106 Add `frame` attribute for SkyDiffuseMap
  gammapy/image/models/core.py
  gammapy/image/models/tests/test_core.py
Labels: bug

#2108 Fix `frame` attribute of SkyDiffuseCube and SkyDiffuseMap
  gammapy/cube/models.py
  gammapy/cube/tests/test_models.py
  gammapy/image/models/core.py
  gammapy/image/models/tests/test_core.py
Labels: bug

#2110 Changed from CountsPredictor to SpectrumEvaluator
  gammapy/spectrum/fit.py
  gammapy/spectrum/observation.py
  gammapy/spectrum/sensitivity.py
  gammapy/spectrum/simulation.py
  gammapy/spectrum/tests/test_utils.py
  gammapy/spectrum/utils.py
  gammapy/time/lightcurve.py
Labels: cleanup

#2104 Implement sparse summed fit statistics in cython
  gammapy/cube/fit.py
  gammapy/detect/_test_statistics_cython.pyx
  gammapy/detect/test_statistics.py
  gammapy/stats/__init__.py
  gammapy/stats/fit_statistics_cython.pyx
  gammapy/stats/tests/test_fit_statistics.py
Labels: feature

#2111 Introduce SpectrumDatasetOnOff
  gammapy/spectrum/__init__.py
  gammapy/spectrum/dataset.py
  gammapy/spectrum/tests/test_dataset.py
Labels: feature

#2112 Refactor FluxPointEstimator to use Datasets
  gammapy/cube/fit.py
  gammapy/scripts/spectrum_pipe.py
  gammapy/spectrum/dataset.py
  gammapy/spectrum/energy_group.py
  gammapy/spectrum/flux_point.py
  gammapy/spectrum/observation.py
  gammapy/spectrum/tests/test_energy_group.py
  gammapy/spectrum/tests/test_flux_point_estimator.py
  gammapy/utils/fitting/datasets.py
  tutorials/cta_data_analysis.ipynb
  tutorials/pulsar_analysis.ipynb
  tutorials/spectrum_analysis.ipynb
Labels: cleanup

#2114 Refactor energy grouping
  gammapy/maps/geom.py
  gammapy/maps/tests/test_geom.py
  gammapy/scripts/spectrum_pipe.py
  gammapy/spectrum/__init__.py
  gammapy/spectrum/energy_group.py
  gammapy/spectrum/flux_point.py
  gammapy/spectrum/tests/test_energy_group.py
  gammapy/spectrum/tests/test_flux_point_estimator.py
  tutorials/cta_data_analysis.ipynb
  tutorials/pulsar_analysis.ipynb
  tutorials/spectrum_analysis.ipynb
Labels: cleanup

#2115 Remove SpectrumResult object
  gammapy/scripts/spectrum_pipe.py
  gammapy/spectrum/flux_point.py
  gammapy/spectrum/results.py
  gammapy/spectrum/tests/test_results.py
  tutorials/cta_data_analysis.ipynb
  tutorials/pulsar_analysis.ipynb
  tutorials/spectrum_analysis.ipynb
  tutorials/spectrum_pipe.ipynb
Labels: cleanup

#2117 Fix pytest test collection in test_profile.py
  gammapy/image/tests/test_profile.py
Labels: bug, tests

#2116 Partly refactor gammapy/spectrum/tests/test_fit.py to use SpectrumDataset
  gammapy/spectrum/dataset.py
  gammapy/spectrum/results.py
  gammapy/spectrum/tests/test_fit.py
  gammapy/spectrum/tests/test_results.py
  tutorials/spectrum_analysis.ipynb
Labels: cleanup

#2118 Remove tutorials/astropy_introduction.ipynb ?
  docs/tutorials.rst
  tutorials/astropy_introduction.ipynb
  tutorials/first_steps.ipynb
  tutorials/intro_maps.ipynb
  tutorials/notebooks.yaml
Labels: cleanup, docs

#2119 Clean up Jupyter notebooks with PyCharm static code analysis
  tutorials/analysis_3d.ipynb
  tutorials/analysis_3d_joint.ipynb
  tutorials/background_model.ipynb
  tutorials/cta_data_analysis.ipynb
  tutorials/cwt.ipynb
  tutorials/detect_ts.ipynb
  tutorials/fermi_lat.ipynb
  tutorials/first_steps.ipynb
  tutorials/hess.ipynb
  tutorials/image_analysis.ipynb
  tutorials/image_fitting_with_sherpa.ipynb
  tutorials/light_curve.ipynb
  tutorials/pulsar_analysis.ipynb
  tutorials/simulate_3d.ipynb
  tutorials/spectrum_analysis.ipynb
  tutorials/spectrum_models.ipynb
  tutorials/spectrum_pipe.ipynb
  tutorials/spectrum_simulation_cta.ipynb
Labels: cleanup, docs

#2121 Move plotting helper functions from SpectrumFitResult to SpectrumDatasetOnOff
  gammapy/spectrum/dataset.py
  gammapy/spectrum/results.py
  gammapy/spectrum/tests/test_dataset.py
  gammapy/spectrum/tests/test_fit.py
  gammapy/spectrum/tests/test_results.py
  tutorials/spectrum_analysis.ipynb
Labels: cleanup

#2122 Remove xfail from two tests that now pass
  gammapy/spectrum/tests/test_extract.py
  gammapy/time/tests/test_lightcurve.py
Labels: cleanup

#2123 Remove SpectrumFit class
  docs/spectrum/fitting.rst
  docs/spectrum/index.rst
  gammapy/scripts/spectrum_pipe.py
  gammapy/spectrum/__init__.py
  gammapy/spectrum/dataset.py
  gammapy/spectrum/fit.py
  gammapy/spectrum/flux_point.py
  gammapy/spectrum/observation.py
  gammapy/spectrum/results.py
  gammapy/spectrum/tests/test_fit.py
  gammapy/spectrum/tests/test_results.py
  gammapy/utils/fitting/fit.py
  tutorials/cta_data_analysis.ipynb
  tutorials/fermi_lat.ipynb
  tutorials/hess.ipynb
  tutorials/pulsar_analysis.ipynb
  tutorials/spectrum_pipe.ipynb
  tutorials/spectrum_simulation.ipynb
  tutorials/spectrum_simulation_cta.ipynb
Labels: cleanup
