Repository gammapy/gammapy, pull requests merged in 2020-08, with the labels that each got.

#2963 Add static images used in tutorial notebooks
  .gitignore
  docs/tutorials/images/DC1_3d.png
  docs/tutorials/images/gammapy_maps.png
  docs/tutorials/images/gammapy_mcmc.png
  gammapy/scripts/downloadclasses.py
Labels: docs

#2962 First clean up of estimators
  docs/tutorials/cta_sensitivity.ipynb
  gammapy/estimators/flux.py
  gammapy/estimators/flux_point.py
  gammapy/estimators/lightcurve.py
  gammapy/estimators/parameter_estimator.py
  gammapy/estimators/sensitivity.py
  gammapy/estimators/ts_map.py
Labels: cleanup

#2944 PIG 21 - Model framework improvements
  docs/development/pigs/index.rst
  docs/development/pigs/pig-021.rst
Labels: pig

#2966 Implement MapDataset.slice_by_idx
  gammapy/datasets/map.py
  gammapy/datasets/tests/test_map.py
  gammapy/irf/irf_map.py
  gammapy/maps/core.py
Labels: feature

#2965 Add `Map.to_cube()`
  gammapy/estimators/tests/test_ts_map.py
  gammapy/maps/tests/test_wcsnd.py
  gammapy/maps/wcsnd.py
Labels: feature

#2967 Allow for varying energy range between datasets in FluxPointEstimator
  gammapy/datasets/core.py
  gammapy/estimators/flux.py
  gammapy/estimators/flux_point.py
  gammapy/maps/geom.py
Labels: feature

#2959 Lazy dataset loading prototype
  gammapy/data/observations.py
  gammapy/datasets/core.py
  gammapy/datasets/flux_points.py
  gammapy/datasets/map.py
  gammapy/datasets/spectrum.py
  gammapy/estimators/tests/test_asmooth_map.py
  gammapy/estimators/tests/test_flux.py
  gammapy/irf/__init__.py
  gammapy/irf/edisp_map.py
  gammapy/irf/irf_map.py
  gammapy/irf/psf_map.py
  gammapy/maps/wcsnd.py
  gammapy/modeling/iminuit.py
  gammapy/modeling/models/core.py
  gammapy/modeling/models/cube.py
  gammapy/utils/fits.py
Labels: feature

#2968 Clean up estimators
  docs/tutorials/detect.ipynb
  gammapy/estimators/excess_map.py
  gammapy/estimators/excess_profile.py
  gammapy/estimators/flux.py
  gammapy/estimators/parameter_estimator.py
  gammapy/estimators/tests/test_flux.py
  gammapy/estimators/tests/test_ts_map.py
  gammapy/estimators/ts_map.py
Labels: cleanup

#2969 Estimator parameter cleanup
  gammapy/estimators/asmooth_map.py
  gammapy/estimators/ts_map.py
Labels: cleanup

#2964 Modify MapDataset.to_image()
  docs/tutorials/ring_background.ipynb
  gammapy/datasets/map.py
  gammapy/datasets/tests/test_map.py
  gammapy/estimators/asmooth_map.py
  gammapy/estimators/tests/test_asmooth_map.py
  gammapy/estimators/ts_map.py
  gammapy/irf/edisp_kernel.py
  gammapy/irf/edisp_map.py
  gammapy/irf/tests/test_edisp_map.py
  gammapy/irf/tests/test_energy_dispersion.py
  gammapy/makers/tests/test_map.py
  gammapy/maps/core.py
  gammapy/maps/wcsnd.py
Labels: cleanup

#2970 Clean up estimators - 3
  docs/tutorials/analysis_3d.ipynb
  docs/tutorials/detect.ipynb
  docs/tutorials/exclusion_mask.ipynb
  docs/tutorials/ring_background.ipynb
  gammapy/estimators/asmooth_map.py
  gammapy/estimators/core.py
  gammapy/estimators/excess_map.py
  gammapy/estimators/excess_profile.py
  gammapy/estimators/flux.py
  gammapy/estimators/flux_point.py
  gammapy/estimators/lightcurve.py
  gammapy/estimators/parameter_estimator.py
  gammapy/estimators/profile.py
  gammapy/estimators/tests/test_excess_map.py
  gammapy/estimators/tests/test_excess_profile.py
  gammapy/estimators/tests/test_flux.py
  gammapy/estimators/tests/test_flux_point_estimator.py
  gammapy/estimators/tests/test_lightcurve.py
  gammapy/estimators/tests/test_parameter_estimator.py
  gammapy/estimators/tests/test_ts_map.py
  gammapy/estimators/ts_map.py
Labels: cleanup

#2958 Adapt `ExcessMapEstimator` to optionally apply mask_fit
  gammapy/estimators/excess_map.py
  gammapy/estimators/tests/test_excess_map.py
Labels: feature

#2974 Implement meta table stacking
  gammapy/datasets/core.py
  gammapy/datasets/map.py
  gammapy/datasets/spectrum.py
  gammapy/datasets/tests/test_map.py
  gammapy/datasets/tests/test_spectrum.py
  gammapy/makers/map.py
  gammapy/makers/spectrum.py
  gammapy/modeling/tests/test_fit.py
  gammapy/utils/table.py
Labels: feature

#2975 Implement generic Maker.__str__ and Estimator.__str__
  gammapy/estimators/core.py
  gammapy/estimators/flux.py
  gammapy/estimators/flux_point.py
  gammapy/estimators/parameter_estimator.py
  gammapy/makers/core.py
Labels: feature

#2973 Modified required columns for likelihood SED type
  gammapy/estimators/flux_point.py
  gammapy/estimators/tests/test_flux_point_estimator.py
Labels: cleanup

#2979 Improve CompoundSpectralModel serialisation adding from_dict() method
  gammapy/modeling/models/spectral.py
  gammapy/modeling/models/tests/test_io.py
  gammapy/modeling/models/tests/test_spectral.py
Labels: cleanup, feature

#2980 Remove inheritance pattern for Estimators
  gammapy/estimators/core.py
  gammapy/estimators/flux.py
  gammapy/estimators/flux_point.py
  gammapy/estimators/lightcurve.py
  gammapy/estimators/parameter.py
  gammapy/estimators/parameter_estimator.py
  gammapy/estimators/tests/test_flux.py
  gammapy/estimators/tests/test_flux_point_estimator.py
  gammapy/estimators/tests/test_lightcurve.py
  gammapy/estimators/tests/test_parameter_estimator.py
  gammapy/estimators/ts_map.py
Labels: cleanup

#2978 Add support for energy dependent spatial models
  gammapy/modeling/models/cube.py
  gammapy/modeling/models/spatial.py
  gammapy/modeling/models/tests/data/example2.yaml
  gammapy/modeling/models/tests/data/examples.yaml
  gammapy/modeling/models/tests/data/make.py
  gammapy/modeling/models/tests/test_io.py
  gammapy/modeling/models/tests/test_spatial.py
Labels: cleanup, feature

#2982 Lightcurve code clean up
  gammapy/data/gti.py
  gammapy/datasets/core.py
  gammapy/estimators/lightcurve.py
  gammapy/estimators/tests/test_lightcurve.py
Labels: cleanup

#2983 Implement radial profile estimation
  gammapy/estimators/excess_profile.py
  gammapy/estimators/tests/test_excess_profile.py
  gammapy/irf/edisp_map.py
  gammapy/utils/regions.py
Labels: feature

#2984 Change SpectrumDataset.aeff to RegionNDMap
  docs/tutorials/cta_sensitivity.ipynb
  gammapy/analysis/tests/test_analysis.py
  gammapy/datasets/map.py
  gammapy/datasets/spectrum.py
  gammapy/datasets/tests/test_map.py
  gammapy/datasets/tests/test_spectrum.py
  gammapy/estimators/flux.py
  gammapy/estimators/flux_point.py
  gammapy/estimators/tests/test_flux_point_estimator.py
  gammapy/estimators/tests/test_sensitivity.py
  gammapy/irf/effective_area.py
  gammapy/makers/safe.py
  gammapy/makers/spectrum.py
  gammapy/makers/tests/test_spectrum.py
  gammapy/maps/geom.py
  gammapy/maps/region.py
  gammapy/maps/regionnd.py
Labels: cleanup

#2981 Add basic NormSpectralModels
  gammapy/modeling/models/__init__.py
  gammapy/modeling/models/spectral.py
  gammapy/modeling/models/tests/test_io.py
  gammapy/modeling/models/tests/test_spectral.py
  gammapy/utils/integrate.py
Labels: feature

#2985 Introduce Estimator.selection_optional
  docs/tutorials/analysis_3d.ipynb
  docs/tutorials/detect.ipynb
  docs/tutorials/exclusion_mask.ipynb
  docs/tutorials/ring_background.ipynb
  gammapy/datasets/map.py
  gammapy/estimators/asmooth_map.py
  gammapy/estimators/core.py
  gammapy/estimators/excess_map.py
  gammapy/estimators/excess_profile.py
  gammapy/estimators/flux.py
  gammapy/estimators/flux_point.py
  gammapy/estimators/lightcurve.py
  gammapy/estimators/parameter.py
  gammapy/estimators/tests/test_excess_map.py
  gammapy/estimators/tests/test_flux.py
  gammapy/estimators/tests/test_flux_point_estimator.py
  gammapy/estimators/tests/test_lightcurve.py
  gammapy/estimators/tests/test_parameter_estimator.py
  gammapy/estimators/tests/test_ts_map.py
  gammapy/estimators/ts_map.py
Labels: cleanup

#2986 Refactor TSMapEstimator
  docs/tutorials/detect.ipynb
  gammapy/estimators/tests/test_ts_map.py
  gammapy/estimators/ts_map.py
  gammapy/maps/wcs.py
  gammapy/modeling/models/spatial.py
  gammapy/stats/fit_statistics_cython.pyx
Labels: cleanup

#2987 Use norm parameter in TSMapEstimator
  gammapy/estimators/tests/test_ts_map.py
  gammapy/estimators/ts_map.py
  gammapy/stats/fit_statistics_cython.pyx
Labels: cleanup

#2976 Fix filename handling in read/write methods
  gammapy/datasets/flux_points.py
  gammapy/datasets/map.py
  gammapy/datasets/spectrum.py
  gammapy/irf/background.py
  gammapy/irf/edisp_kernel.py
  gammapy/irf/effective_area.py
  gammapy/irf/energy_dispersion.py
  gammapy/irf/psf_3d.py
  gammapy/irf/psf_gauss.py
  gammapy/irf/psf_king.py
  gammapy/irf/psf_table.py
  gammapy/maps/core.py
  gammapy/utils/fits.py
Labels: feature

#2990 Optional exposure map for the EdispMap and PSF in the MapDataset
  gammapy/datasets/map.py
  gammapy/irf/edisp_map.py
Labels: feature

#2991 Implement energy slicing for FluxPointsEstimator
  docs/tutorials/analysis_mwl.ipynb
  docs/tutorials/pulsar_analysis.ipynb
  gammapy/analysis/core.py
  gammapy/analysis/tests/test_analysis.py
  gammapy/datasets/spectrum.py
  gammapy/estimators/flux.py
  gammapy/estimators/flux_point.py
  gammapy/estimators/tests/test_flux_point_estimator.py
  gammapy/irf/edisp_map.py
  gammapy/irf/psf_kernel.py
  gammapy/maps/geom.py
Labels: cleanup

#2994 Clean up estimators to use exposure in reco energy
  gammapy/estimators/asmooth_map.py
  gammapy/estimators/excess_map.py
  gammapy/estimators/tests/test_excess_map.py
  gammapy/estimators/tests/test_ts_map.py
  gammapy/estimators/ts_map.py
  gammapy/estimators/utils.py
  gammapy/makers/utils.py
Labels: cleanup

#2993 Reuse FluxPointsEstimator in LightCurveEstimator
  docs/tutorials/light_curve_simulation.ipynb
  gammapy/datasets/spectrum.py
  gammapy/estimators/lightcurve.py
  gammapy/estimators/tests/test_lightcurve.py
Labels: cleanup
