Repository gammapy/gammapy, pull requests merged in 2020-06, with the labels that each got.

#2914 Simplify and clean up script documentation
  docs/makers/make_rectangular_reflected_background.py
  docs/scripts/index.rst
  docs/scripts/significance.py
Labels: cleanup, docs

#2916 Doc corrections
  docs/estimators/detect.rst
  tutorials/spectrum_simulation.ipynb
Labels: cleanup, docs

#2912 Cache npred in MapEvaluator
  gammapy/datasets/map.py
  gammapy/maps/wcs.py
  gammapy/modeling/models/tests/test_core.py
Labels: cleanup

#2926 Split overview.rst into dataset/index.rst and modeling/index.rst
  docs/datasets/index.rst
  docs/modeling/index.rst
  docs/overview.rst
Labels: cleanup, docs

#2925 Add an option to avoid saving Covariance to file
  gammapy/datasets/core.py
  gammapy/modeling/models/core.py
Labels: feature

#2928 removed at_least1d for wstat
  gammapy/stats/fit_statistics.py
Labels: cleanup

#2929 Add meta_table to SpectrumDataset
  gammapy/datasets/spectrum.py
  gammapy/makers/spectrum.py
  gammapy/makers/tests/test_spectrum.py
Labels: feature

#2924 Add meta_table to MapDataset
  gammapy/datasets/map.py
  gammapy/makers/map.py
  gammapy/makers/tests/test_map.py
Labels: feature

#2930 Add meta_table to FluxPointsDataset
  gammapy/datasets/flux_points.py
  gammapy/datasets/tests/test_flux_points.py
Labels: feature

#2927 Introduce Maker and Estimator base classes and registries
  docs/tutorials/catalog.ipynb
  docs/tutorials/detect.ipynb
  docs/tutorials/exclusion_mask.ipynb
  docs/tutorials/models.ipynb
  docs/tutorials/sed_fitting.ipynb
  gammapy/catalog/__init__.py
  gammapy/catalog/tests/data/make.py
  gammapy/datasets/__init__.py
  gammapy/datasets/core.py
  gammapy/estimators/__init__.py
  gammapy/estimators/asmooth_map.py
  gammapy/estimators/core.py
  gammapy/estimators/excess_map.py
  gammapy/estimators/flux.py
  gammapy/estimators/flux_point.py
  gammapy/estimators/lightcurve.py
  gammapy/estimators/parameter_estimator.py
  gammapy/estimators/profile.py
  gammapy/estimators/sensitivity.py
  gammapy/estimators/tests/test_core.py
  gammapy/estimators/ts_map.py
  gammapy/makers/__init__.py
  gammapy/makers/background/fov.py
  gammapy/makers/background/phase.py
  gammapy/makers/background/reflected.py
  gammapy/makers/background/ring.py
  gammapy/makers/core.py
  gammapy/makers/map.py
  gammapy/makers/safe.py
  gammapy/makers/spectrum.py
  gammapy/makers/tests/test_core.py
  gammapy/makers/utils.py
  gammapy/maps/__init__.py
  gammapy/maps/core.py
  gammapy/maps/hpxmap.py
  gammapy/maps/region.py
  gammapy/maps/regionnd.py
  gammapy/maps/wcsmap.py
  gammapy/modeling/models/__init__.py
  gammapy/modeling/models/core.py
  gammapy/modeling/models/cube.py
  gammapy/modeling/models/spectral.py
  gammapy/modeling/models/tests/test_io.py
  gammapy/modeling/models/tests/test_spectral.py
Labels: cleanup

#2931 Remove gammapy.time sub-package
  docs/index.rst
  docs/time/index.rst
  docs/time/period.rst
  gammapy/stats/tests/test_variability.py
  gammapy/stats/variability.py
  gammapy/time/__init__.py
  gammapy/time/period.py
  gammapy/time/tests/__init__.py
  gammapy/time/tests/test_period.py
Labels: cleanup

#2934 Clean up gammapy/utils/fits
  gammapy/datasets/spectrum.py
  gammapy/irf/edisp_kernel.py
  gammapy/maps/geom.py
  gammapy/maps/hpx.py
  gammapy/maps/region.py
  gammapy/maps/utils.py
  gammapy/utils/fits.py
  gammapy/utils/tests/test_fits.py
Labels: cleanup
