Repository gammapy/gammapy, pull requests merged in 2020-10, with the labels that each got.

#3034 Fix MapAxis oversampling for irregular binnings
  gammapy/maps/geom.py
  gammapy/maps/tests/test_geom.py
  gammapy/maps/tests/test_wcsnd.py
  gammapy/maps/wcsnd.py
Labels: bug

#3035 Update Numpy to 1.17
  setup.cfg
Labels: infrastructure

#3039 Use MapAxis in gammapy.irf consistently
  docs/irf/index.rst
  gammapy/datasets/map.py
  gammapy/datasets/tests/test_map.py
  gammapy/irf/background.py
  gammapy/irf/effective_area.py
  gammapy/irf/energy_dispersion.py
  gammapy/irf/psf_3d.py
  gammapy/irf/psf_gauss.py
  gammapy/irf/psf_king.py
  gammapy/irf/psf_map.py
  gammapy/irf/psf_table.py
  gammapy/irf/tests/test_background.py
  gammapy/irf/tests/test_edisp_map.py
  gammapy/irf/tests/test_effective_area.py
  gammapy/irf/tests/test_energy_dispersion.py
  gammapy/irf/tests/test_irf_write.py
  gammapy/irf/tests/test_psf_3d.py
  gammapy/irf/tests/test_psf_gauss.py
  gammapy/irf/tests/test_psf_king.py
  gammapy/irf/tests/test_psf_map.py
  gammapy/irf/tests/test_psf_table.py
  gammapy/makers/map.py
  gammapy/makers/safe.py
  gammapy/makers/tests/test_map.py
  gammapy/makers/tests/test_utils.py
  gammapy/makers/utils.py
  gammapy/maps/geom.py
Labels: cleanup

#3044 Clean IRF I/O by using MapAxes
  gammapy/datasets/tests/test_map.py
  gammapy/datasets/tests/test_simulate.py
  gammapy/estimators/tests/test_flux_point_estimator.py
  gammapy/irf/background.py
  gammapy/irf/effective_area.py
  gammapy/irf/energy_dispersion.py
  gammapy/irf/io.py
  gammapy/irf/psf_3d.py
  gammapy/irf/psf_gauss.py
  gammapy/irf/psf_king.py
  gammapy/irf/tests/test_io.py
  gammapy/irf/tests/test_psf_gauss.py
  gammapy/maps/geom.py
Labels: cleanup

#3037 Add generalized gaussian model
  examples/models/spatial/plot_gen_gauss.py
  gammapy/modeling/models/__init__.py
  gammapy/modeling/models/spatial.py
  gammapy/modeling/models/tests/test_spatial.py
Labels: feature

#3041 Add integral_error for models.spectral
  gammapy/modeling/models/spectral.py
  gammapy/modeling/models/tests/test_spectral.py
Labels: feature

#3038 Implement Fit.stat_surface() method
  gammapy/modeling/fit.py
  gammapy/modeling/tests/test_fit.py
Labels: feature

#3045 Add temporal models to model gallery
  examples/models/temporal/README.txt
  examples/models/temporal/plot_LightCurveTemplate_temporal.py
  examples/models/temporal/plot_constant_temporal.py
  examples/models/temporal/plot_expdecay_temporal.py
  examples/models/temporal/plot_gaussian_temporal.py
  gammapy/modeling/models/temporal.py
  gammapy/modeling/models/tests/test_temporal.py
Labels: docs

#3046 Add parameter type properties
  gammapy/modeling/models/core.py
  gammapy/modeling/models/cube.py
  gammapy/modeling/models/spatial.py
  gammapy/modeling/models/spectral.py
  gammapy/modeling/models/temporal.py
  gammapy/modeling/models/tests/test_core.py
  gammapy/modeling/models/tests/test_spatial.py
  gammapy/modeling/parameter.py
  gammapy/modeling/tests/test_fit.py
Labels: feature

#3043 Harmonise npred between OnOff and normal datasets
  docs/stats/fit_statistics.rst
  docs/stats/wstat_derivation.rst
  gammapy/datasets/map.py
  gammapy/datasets/spectrum.py
  gammapy/datasets/tests/test_map.py
  gammapy/datasets/tests/test_spectrum.py
  gammapy/estimators/asmooth_map.py
  gammapy/estimators/excess_map.py
  gammapy/estimators/sensitivity.py
  gammapy/estimators/tests/test_flux_point_estimator.py
Labels: cleanup, feature

#3049 Mask to spectrum
  gammapy/datasets/map.py
  gammapy/datasets/spectrum.py
  gammapy/datasets/tests/test_map.py
  gammapy/maps/tests/test_wcsnd.py
  gammapy/maps/wcsnd.py
Labels: cleanup

#3042 Refactor SpectrumDataset to use exposure
  docs/tutorials/cta_data_analysis.ipynb
  docs/tutorials/cta_sensitivity.ipynb
  docs/tutorials/light_curve_flare.ipynb
  docs/tutorials/light_curve_simulation.ipynb
  docs/tutorials/spectrum_analysis.ipynb
  docs/tutorials/spectrum_simulation.ipynb
  gammapy/analysis/core.py
  gammapy/analysis/tests/test_analysis.py
  gammapy/data/gti.py
  gammapy/datasets/map.py
  gammapy/datasets/spectrum.py
  gammapy/datasets/tests/test_map.py
  gammapy/datasets/tests/test_spectrum.py
  gammapy/estimators/tests/test_flux_point_estimator.py
  gammapy/estimators/tests/test_sensitivity.py
  gammapy/irf/edisp_map.py
  gammapy/irf/irf_map.py
  gammapy/makers/spectrum.py
  gammapy/makers/tests/test_spectrum.py
  gammapy/maps/core.py
  gammapy/maps/region.py
  gammapy/maps/regionnd.py
  gammapy/maps/wcsnd.py
Labels: cleanup

#3055 Cleanup tutorials
  docs/tutorials/background_model.ipynb
  docs/tutorials/light_curve_flare.ipynb
  docs/tutorials/light_curve_simulation.ipynb
  notebooks.yaml
Labels: cleanup, docs

#3054 Unify dataset info dicts
  docs/tutorials/extended_source_spectral_analysis.ipynb
  docs/tutorials/spectrum_analysis.ipynb
  docs/tutorials/spectrum_simulation.ipynb
  gammapy/datasets/map.py
  gammapy/datasets/spectrum.py
  gammapy/datasets/tests/test_map.py
  gammapy/datasets/tests/test_spectrum.py
  gammapy/irf/irf_map.py
  gammapy/irf/psf_map.py
  gammapy/makers/tests/test_spectrum.py
  gammapy/makers/utils.py
  gammapy/maps/core.py
  gammapy/maps/tests/test_wcsnd.py
Labels: cleanup

#3058 Clean up MapDataset mask handling
  docs/tutorials/cta_data_analysis.ipynb
  gammapy/datasets/map.py
  gammapy/datasets/tests/test_map.py
  gammapy/estimators/tests/test_ts_map.py
  gammapy/maps/core.py
  gammapy/maps/wcsnd.py
  gammapy/utils/table.py
Labels: cleanup

#3053 Add bkg systematics condition for the sensitivity computation
  docs/tutorials/cta_sensitivity.ipynb
  gammapy/estimators/sensitivity.py
  gammapy/estimators/tests/test_sensitivity.py
Labels: effort-low, feature

#3065 Document stat_contour in modeling tutorial
  docs/tutorials/analysis_3d.ipynb
  docs/tutorials/cta_data_analysis.ipynb
  docs/tutorials/cta_sensitivity.ipynb
  docs/tutorials/detect.ipynb
  docs/tutorials/fermi_lat.ipynb
  docs/tutorials/hess.ipynb
  docs/tutorials/modeling.ipynb
  docs/tutorials/pulsar_analysis.ipynb
Labels: docs

#3059 Uniform keys in fit methods and estimators
  docs/tutorials/modeling.ipynb
  gammapy/datasets/tests/test_flux_points.py
  gammapy/datasets/tests/test_spectrum.py
  gammapy/estimators/parameter.py
  gammapy/modeling/fit.py
  gammapy/modeling/tests/test_fit.py
Labels: cleanup

#3063 Add PiecewiseNormSpectralModel
  examples/models/spectral/plot_piecewise_norm_spectral.py
  gammapy/modeling/models/__init__.py
  gammapy/modeling/models/spectral.py
  gammapy/modeling/models/tests/test_io.py
  gammapy/modeling/models/tests/test_spectral.py
Labels: feature

#3067 Fix documentation for gammapy.irf
  docs/irf/aeff.rst
  docs/irf/bkg.rst
  docs/irf/edisp.rst
  docs/irf/index.rst
  docs/irf/plot_aeff.py
  docs/irf/plot_aeff_param.py
  docs/irf/plot_aeff_table.py
  docs/irf/plot_bkg_3d.py
  docs/irf/plot_edisp.py
  docs/irf/plot_edisp_kernel.py
  docs/irf/plot_edisp_kernel_param.py
  docs/irf/plot_psf.py
  docs/irf/plot_psf_table.py
  docs/irf/psf.rst
  docs/irf/theory.rst
Labels: cleanup

#3068 fixed broken link in bkg.rst irf documentation
  docs/irf/bkg.rst
Labels: bug

#3052 Adapt LightCurveEstimator to take energy edges
  gammapy/estimators/lightcurve.py
  gammapy/estimators/tests/test_lightcurve.py
Labels: feature

#3060 Remove code duplication between MapDataset and SpectrumDataset
  gammapy/datasets/map.py
  gammapy/datasets/spectrum.py
  gammapy/datasets/tests/test_spectrum.py
  gammapy/estimators/tests/test_flux.py
  gammapy/estimators/tests/test_flux_point_estimator.py
  gammapy/estimators/tests/test_lightcurve.py
  gammapy/estimators/tests/test_parameter_estimator.py
  gammapy/makers/safe.py
  gammapy/makers/tests/test_spectrum.py
  gammapy/maps/regionnd.py
  gammapy/modeling/models/cube.py
Labels: cleanup

#3061 Add energy_flux_error to SpectralModel
  gammapy/modeling/models/spectral.py
  gammapy/modeling/models/tests/test_spectral.py
Labels: feature

#3069 Remove pre-processing from Fermi tutorial
  docs/tutorials/fermi_lat.ipynb
  gammapy/irf/psf_table.py
  gammapy/modeling/models/cube.py
  gammapy/modeling/models/spectral.py
Labels: cleanup

#3071 Fix model evaluation for point source model and speed up generalised gaussian tests
  gammapy/maps/wcs.py
  gammapy/modeling/models/spatial.py
  gammapy/modeling/models/tests/test_spatial.py
Labels: bug

#3070 Remove intervals option from integrate_spectrum()
  gammapy/astro/darkmatter/tests/test_utils.py
  gammapy/datasets/map.py
  gammapy/estimators/tests/test_flux.py
  gammapy/estimators/tests/test_parameter_estimator.py
  gammapy/irf/psf_3d.py
  gammapy/makers/utils.py
  gammapy/maps/geom.py
  gammapy/maps/utils.py
  gammapy/modeling/models/cube.py
  gammapy/modeling/models/spectral.py
  gammapy/modeling/models/tests/test_core.py
  gammapy/modeling/models/tests/test_spectral.py
  gammapy/visualization/utils.py
Labels: cleanup

#3073 Print parameter values to 4 significant digits
  gammapy/modeling/parameter.py
Labels: cleanup

#3072 Allow to apply PSF in reconstructed energy
  gammapy/datasets/map.py
  gammapy/datasets/tests/test_map.py
  gammapy/irf/psf_map.py
  gammapy/maps/core.py
  gammapy/maps/geom.py
  gammapy/maps/tests/test_wcsnd.py
  gammapy/maps/wcsnd.py
Labels: feature

#3074 Implement option to store fit trace to Fit
  docs/tutorials/modeling.ipynb
  gammapy/datasets/tests/test_datasets.py
  gammapy/modeling/fit.py
  gammapy/modeling/iminuit.py
  gammapy/modeling/likelihood.py
  gammapy/modeling/scipy.py
  gammapy/modeling/sherpa.py
  gammapy/modeling/tests/test_fit.py
  gammapy/utils/table.py
Labels: feature

#3076 Introduce `MapDataset.geoms` property
  gammapy/datasets/map.py
  gammapy/datasets/tests/test_map.py
Labels: feature

#3080 Remove significance and replace with sqrt_ts
  docs/getting-started.rst
  docs/scripts/index.rst
  docs/scripts/significance.py
  docs/stats/index.rst
  docs/stats/plot_cash_errors.py
  docs/stats/plot_cash_significance.py
  docs/stats/plot_wstat_errors.py
  docs/stats/plot_wstat_significance.py
  docs/tutorials/analysis_3d.ipynb
  docs/tutorials/exclusion_mask.ipynb
  docs/tutorials/ring_background.ipynb
  gammapy/datasets/map.py
  gammapy/datasets/spectrum.py
  gammapy/estimators/asmooth_map.py
  gammapy/estimators/excess_map.py
  gammapy/estimators/excess_profile.py
  gammapy/estimators/tests/test_excess_map.py
  gammapy/estimators/ts_map.py
  gammapy/makers/utils.py
  gammapy/stats/counts_statistic.py
  gammapy/stats/tests/test_counts_statistic.py
Labels: cleanup

#3081 Unify axis ordering in gammapy.irf
  docs/irf/aeff.rst
  docs/irf/bkg.rst
  docs/irf/edisp.rst
  docs/irf/psf.rst
  gammapy/irf/background.py
  gammapy/irf/energy_dispersion.py
  gammapy/irf/psf_3d.py
  gammapy/irf/psf_gauss.py
  gammapy/irf/psf_table.py
  gammapy/irf/tests/test_effective_area.py
  gammapy/irf/tests/test_psf_3d.py
  gammapy/irf/tests/test_psf_map.py
  gammapy/makers/utils.py
  gammapy/utils/nddata.py
  gammapy/utils/tests/test_nddata.py
Labels: bug, cleanup

#3077 Add minimal estimators docs
  docs/estimators/index.rst
  docs/stats/index.rst
Labels: docs

#3082 Fix some comments in the tutorial hess.ipynb
  docs/tutorials/hess.ipynb
Labels: docs

#3083 Example of Energy Dependent Spatial Model
  docs/howto.rst
  docs/tutorials/models.ipynb
  gammapy/modeling/models/spatial.py
  gammapy/modeling/models/tests/test_cube.py
  gammapy/modeling/models/tests/test_spatial.py
Labels: docs

#3051 Introduce dataset specific FoVBackgroundModel
  docs/stats/index.rst
  docs/tutorials/analysis_2.ipynb
  docs/tutorials/analysis_3d.ipynb
  docs/tutorials/cta_data_analysis.ipynb
  docs/tutorials/cta_sensitivity.ipynb
  docs/tutorials/detect.ipynb
  docs/tutorials/modeling_2D.ipynb
  docs/tutorials/spectrum_simulation.ipynb
  gammapy/analysis/core.py
  gammapy/analysis/tests/test_analysis.py
  gammapy/datasets/core.py
  gammapy/datasets/flux_points.py
  gammapy/datasets/map.py
  gammapy/datasets/simulate.py
  gammapy/datasets/spectrum.py
  gammapy/datasets/tests/test_io.py
  gammapy/datasets/tests/test_map.py
  gammapy/datasets/tests/test_simulate.py
  gammapy/datasets/tests/test_spectrum.py
  gammapy/estimators/asmooth_map.py
  gammapy/estimators/excess_map.py
  gammapy/estimators/sensitivity.py
  gammapy/estimators/tests/test_asmooth_map.py
  gammapy/estimators/tests/test_excess_map.py
  gammapy/estimators/tests/test_flux_point_estimator.py
  gammapy/estimators/tests/test_sensitivity.py
  gammapy/estimators/tests/test_ts_map.py
  gammapy/makers/background/fov.py
  gammapy/makers/background/ring.py
  gammapy/makers/background/tests/test_fov.py
  gammapy/makers/map.py
  gammapy/makers/safe.py
  gammapy/makers/spectrum.py
  gammapy/makers/tests/test_map.py
  gammapy/makers/tests/test_spectrum.py
  gammapy/modeling/models/__init__.py
  gammapy/modeling/models/core.py
  gammapy/modeling/models/cube.py
  gammapy/modeling/models/spectral.py
  gammapy/modeling/models/temporal.py
  gammapy/modeling/models/tests/test_core.py
Labels: cleanup, feature

#3084 Enable different axis orders in Background fits files
  gammapy/irf/background.py
  gammapy/irf/tests/test_background.py
  gammapy/irf/tests/test_irf_write.py
Labels: bug, cleanup

#3087 Remove line about reprojection
  docs/tutorials/overview.ipynb
Labels: cleanup

#3086 Stats background convention
  docs/stats/index.rst
  gammapy/datasets/map.py
  gammapy/datasets/spectrum.py
  gammapy/datasets/tests/test_map.py
  gammapy/datasets/tests/test_spectrum.py
  gammapy/estimators/excess_map.py
  gammapy/estimators/excess_profile.py
  gammapy/estimators/sensitivity.py
  gammapy/estimators/tests/test_flux_point_estimator.py
  gammapy/stats/counts_statistic.py
  gammapy/utils/nddata.py
Labels: cleanup

#3088 Allowing Estimators norm parameter to be negative
  gammapy/estimators/core.py
  gammapy/estimators/flux.py
  gammapy/estimators/parameter.py
  gammapy/estimators/tests/test_lightcurve.py
  gammapy/estimators/ts_map.py
Labels: cleanup
