Repository gammapy/gammapy, pull requests merged in 2020-12, with the labels that each got.

#3146 Move dataset I/O code
  gammapy/datasets/io.py
  gammapy/datasets/spectrum.py
  gammapy/datasets/tests/test_spectrum.py
  gammapy/maps/region.py
  gammapy/maps/regionnd.py
Labels: cleanup

#3149 Updated excess and ts estimators
  gammapy/estimators/excess_map.py
  gammapy/estimators/ts_map.py
Labels: cleanup

#3150 Fix Map NaN plotting
  gammapy/maps/tests/test_wcsnd.py
  gammapy/maps/wcsnd.py
Labels: bug

#3152 Unify dataset I/O interface
  docs/modeling/index.rst
  docs/tutorials/analysis_mwl.ipynb
  docs/tutorials/modeling.ipynb
  docs/tutorials/spectrum_analysis.ipynb
  gammapy/datasets/core.py
  gammapy/datasets/flux_points.py
  gammapy/datasets/io.py
  gammapy/datasets/map.py
  gammapy/datasets/spectrum.py
  gammapy/datasets/tests/test_io.py
  gammapy/datasets/tests/test_map.py
  gammapy/datasets/tests/test_simulate.py
  gammapy/datasets/tests/test_spectrum.py
  gammapy/estimators/lightcurve.py
  gammapy/estimators/tests/test_flux.py
  gammapy/estimators/tests/test_parameter_estimator.py
  gammapy/irf/edisp_kernel.py
  gammapy/modeling/tests/test_fit.py
Labels: cleanup

#3148 Add various models and parameters management options
  gammapy/datasets/flux_points.py
  gammapy/datasets/map.py
  gammapy/estimators/parameter.py
  gammapy/modeling/covariance.py
  gammapy/modeling/fit.py
  gammapy/modeling/likelihood.py
  gammapy/modeling/models/core.py
  gammapy/modeling/models/cube.py
  gammapy/modeling/models/spatial.py
  gammapy/modeling/models/spectral.py
  gammapy/modeling/models/tests/test_core.py
  gammapy/modeling/models/tests/test_management.py
  gammapy/modeling/parameter.py
  gammapy/modeling/scipy.py
Labels: cleanup, feature

#3156 Clean up model freezing code a bit
  gammapy/modeling/models/core.py
  gammapy/modeling/models/cube.py
  gammapy/modeling/models/tests/test_management.py
Labels: cleanup

#3154 Fix code in RST files
  .github/workflows/ci.yml
  .gitignore
  docs/analysis/index.rst
  docs/data/index.rst
  docs/development/howto.rst
  docs/development/setup.rst
  docs/estimators/index.rst
  docs/estimators/lightcurve.rst
  docs/getting-started.rst
  docs/modeling/index.rst
  docs/scripts/index.rst
  docs/stats/fit_statistics.rst
  docs/stats/index.rst
  docs/utils/index.rst
Labels: bug, cleanup

#3145 Change the `_compute_flux_spatial` method on `MapEvaluator`
  gammapy/analysis/core.py
  gammapy/datasets/map.py
  gammapy/datasets/tests/test_map.py
  gammapy/modeling/models/spatial.py
Labels: feature

#3159 Fix FoVBackgroundModel.freeze()
  gammapy/modeling/models/core.py
  gammapy/modeling/models/cube.py
  gammapy/modeling/models/tests/test_management.py
  gammapy/modeling/parameter.py
Labels: bug, cleanup

#3161 Improve irf axis name checks
  gammapy/irf/background.py
  gammapy/irf/edisp_kernel.py
  gammapy/irf/edisp_map.py
  gammapy/irf/effective_area.py
  gammapy/irf/energy_dispersion.py
  gammapy/irf/irf_map.py
  gammapy/irf/psf_3d.py
  gammapy/irf/psf_gauss.py
  gammapy/irf/psf_king.py
  gammapy/irf/psf_map.py
  gammapy/irf/psf_table.py
  gammapy/irf/tests/test_edisp_map.py
  gammapy/maps/geom.py
Labels: bug, cleanup

#3158 Add binary_erosion/dilation to WcsNDMap
  docs/makers/ring.rst
  docs/tutorials/analysis_2.ipynb
  docs/tutorials/cta_data_analysis.ipynb
  docs/tutorials/exclusion_mask.ipynb
  docs/tutorials/ring_background.ipynb
  docs/tutorials/spectrum_analysis.ipynb
  gammapy/analysis/tests/test_analysis.py
  gammapy/data/tests/test_event_list.py
  gammapy/datasets/tests/test_map.py
  gammapy/makers/background/reflected.py
  gammapy/makers/background/tests/test_fov.py
  gammapy/makers/background/tests/test_reflected.py
  gammapy/makers/background/tests/test_ring.py
  gammapy/makers/tests/test_spectrum.py
  gammapy/maps/tests/test_wcs.py
  gammapy/maps/tests/test_wcsnd.py
  gammapy/maps/wcs.py
  gammapy/maps/wcsnd.py
Labels: feature

#3157 Add .reassign_dataset() method to models
  gammapy/estimators/flux.py
  gammapy/modeling/models/core.py
  gammapy/modeling/models/cube.py
  gammapy/modeling/models/tests/test_management.py
Labels: cleanup, feature

#3155 Add a tutorials notebooks gallery layout
  docs/conf.py
  docs/tutorials/analysis_1.ipynb
  docs/tutorials/analysis_2.ipynb
  docs/tutorials/analysis_3d.ipynb
  docs/tutorials/analysis_mwl.ipynb
  docs/tutorials/astro_dark_matter.ipynb
  docs/tutorials/background_model.ipynb
  docs/tutorials/catalog.ipynb
  docs/tutorials/cta.ipynb
  docs/tutorials/cta_data_analysis.ipynb
  docs/tutorials/cta_sensitivity.ipynb
  docs/tutorials/detect.ipynb
  docs/tutorials/event_sampling.ipynb
  docs/tutorials/exclusion_mask.ipynb
  docs/tutorials/extended_source_spectral_analysis.ipynb
  docs/tutorials/fermi_lat.ipynb
  docs/tutorials/hess.ipynb
  docs/tutorials/index.rst
  docs/tutorials/light_curve.ipynb
  docs/tutorials/light_curve_flare.ipynb
  docs/tutorials/light_curve_simulation.ipynb
  docs/tutorials/maps.ipynb
  docs/tutorials/mcmc_sampling.ipynb
  docs/tutorials/modeling.ipynb
  docs/tutorials/modeling_2D.ipynb
  docs/tutorials/models.ipynb
  docs/tutorials/overview.ipynb
  docs/tutorials/pulsar_analysis.ipynb
  docs/tutorials/ring_background.ipynb
  docs/tutorials/sed_fitting.ipynb
  docs/tutorials/simulate_3d.ipynb
  docs/tutorials/spectrum_analysis.ipynb
  docs/tutorials/spectrum_simulation.ipynb
  docs/tutorials/survey_map.rst
Labels: feature

#3163 Clean up mask handling a bit
  gammapy/datasets/map.py
  gammapy/makers/background/fov.py
  gammapy/makers/background/reflected.py
  gammapy/makers/background/ring.py
  gammapy/maps/core.py
  gammapy/maps/geom.py
  gammapy/maps/regionnd.py
  gammapy/maps/wcsmap.py
  gammapy/maps/wcsnd.py
Labels: cleanup

#3164 Remove MapDataset.apply_mask_safe()
  docs/tutorials/pulsar_analysis.ipynb
  gammapy/analysis/core.py
  gammapy/datasets/core.py
  gammapy/datasets/map.py
  gammapy/datasets/tests/test_map.py
  gammapy/datasets/tests/test_spectrum.py
  gammapy/estimators/tests/test_lightcurve.py
  gammapy/irf/tests/test_edisp_map.py
  gammapy/makers/tests/test_safe.py
  gammapy/makers/tests/test_spectrum.py
  gammapy/maps/geom.py
  gammapy/maps/tests/test_wcs.py
  gammapy/maps/wcs.py
Labels: cleanup

#3162 Correct Models.from_dict to check input parameters names
  gammapy/modeling/models/core.py
  gammapy/modeling/models/tests/test_spectral.py
Labels: bug

#3140 Add an option to ExcessMapEstimator to choose to correlate off events
  gammapy/estimators/excess_map.py
  gammapy/estimators/tests/test_excess_map.py
Labels: feature

#3170 Add check for mask_safe existence for OGIP serialization
  gammapy/datasets/io.py
  gammapy/datasets/tests/test_spectrum.py
Labels: bug

#3171 Fix and cleanup RegionNDMap I/O
  gammapy/datasets/io.py
  gammapy/datasets/map.py
  gammapy/maps/geom.py
  gammapy/maps/region.py
  gammapy/maps/regionnd.py
  gammapy/maps/tests/test_regionnd.py
  gammapy/maps/wcs.py
Labels: bug, cleanup

#3165 Improve documentation of RegionGeom and RegionNDMap
  docs/maps/index.rst
  docs/maps/regionmap.rst
  gammapy/maps/region.py
  gammapy/maps/regionnd.py
Labels: docs
