Repository gammapy/gammapy, pull requests merged in 2020-03, with the labels that each got.

#2794 Refactor catalog registry
  gammapy/catalog/__init__.py
  gammapy/catalog/core.py
  gammapy/catalog/fermi.py
  gammapy/catalog/gammacat.py
  gammapy/catalog/hawc.py
  gammapy/catalog/hess.py
  gammapy/catalog/registry.py
  gammapy/catalog/tests/test_gammacat.py
  gammapy/catalog/tests/test_hawc.py
  gammapy/catalog/tests/test_hess.py
  gammapy/datasets/__init__.py
  gammapy/utils/registry.py
  tutorials/catalog.ipynb
  tutorials/exclusion_mask.ipynb
  tutorials/sed_fitting.ipynb
Labels: cleanup

#2793 Add notebooks test to azure pipelines
  azure-pipelines.yml
  gammapy/scripts/check.py
Labels: infrastructure

#2796 Change beta sign in SmoothBrokenPowerLawSpectralModel
  gammapy/modeling/models/spectral.py
  gammapy/modeling/models/tests/test_spectral.py
Labels: cleanup

#2791 Introducing gammapy.estimators and the ParameterEstimator
  docs/estimators/index.rst
  gammapy/estimators/__init__.py
  gammapy/estimators/parameter_estimator.py
  gammapy/estimators/tests/__init__.py
  gammapy/estimators/tests/test_parameter_estimator.py
Labels: feature, infrastructure

#2797 Remove KernelBackgroundEstimator class
  gammapy/detect/__init__.py
  gammapy/detect/kernel.py
  gammapy/detect/tests/test_kernel.py
  gammapy/makers/background/ring.py
Labels: cleanup

#2801 Correct FluxPointsEstimator behaviour with SpectrumDataset
  gammapy/spectrum/flux_point.py
Labels: bug

#2775 Introduce fit statistics classes to estimate signal counts errors and upper limits
  docs/stats/index.rst
  gammapy/stats/__init__.py
  gammapy/stats/counts_statistic.py
  gammapy/stats/tests/test_counts_statistic.py
Labels: feature

#2802 Remove detect sub package
  docs/estimators/detect.rst
  docs/estimators/index.rst
  docs/index.rst
  gammapy/detect/__init__.py
  gammapy/detect/_test_statistics_cython.pyx
  gammapy/detect/tests/__init__.py
  gammapy/estimators/__init__.py
  gammapy/estimators/asmooth_map.py
  gammapy/estimators/lima_map.py
  gammapy/estimators/tests/test_asmooth_map.py
  gammapy/estimators/tests/test_lima_map.py
  gammapy/estimators/tests/test_ts_map.py
  gammapy/estimators/tests/test_utils.py
  gammapy/estimators/ts_map.py
  gammapy/estimators/utils.py
  gammapy/stats/fit_statistics_cython.pyx
  setup.py
  tutorials/cta_data_analysis.ipynb
  tutorials/detect.ipynb
  tutorials/exclusion_mask.ipynb
  tutorials/ring_background.ipynb
Labels: cleanup

#2799 Adding the functionality to sample the background only in MapDatasetEventSampler
  gammapy/cube/simulate.py
  gammapy/cube/tests/test_simulate.py
Labels: feature

#2800 Fix covariance checks
  gammapy/modeling/fit.py
Labels: cleanup

#2803 Remove spectrum sub package
  docs/estimators/detect.rst
  docs/index.rst
  docs/overview.rst
  docs/spectrum/index.rst
  gammapy/analysis/core.py
  gammapy/catalog/fermi.py
  gammapy/catalog/gammacat.py
  gammapy/catalog/hess.py
  gammapy/datasets/flux_points.py
  gammapy/datasets/tests/test_flux_points.py
  gammapy/datasets/tests/test_spectrum.py
  gammapy/estimators/__init__.py
  gammapy/estimators/flux_point.py
  gammapy/estimators/sensitivity.py
  gammapy/estimators/tests/test_flux_point.py
  gammapy/estimators/tests/test_flux_point_estimator.py
  gammapy/estimators/tests/test_sensitivity.py
  gammapy/spectrum/__init__.py
  gammapy/spectrum/tests/__init__.py
  gammapy/spectrum/tests/test_fit.py
  gammapy/spectrum/tests/test_flux_point_core.py
  gammapy/time/lightcurve_estimator.py
  gammapy/time/tests/test_lightcurve.py
  tutorials/analysis_2.ipynb
  tutorials/analysis_mwl.ipynb
  tutorials/cta_data_analysis.ipynb
  tutorials/cta_sensitivity.ipynb
  tutorials/pulsar_analysis.ipynb
  tutorials/sed_fitting.ipynb
  tutorials/spectrum_analysis.ipynb
Labels: cleanup

#2804 Remove cube sub package
  docs/cube/index.rst
  docs/index.rst
  docs/overview.rst
  gammapy/cube/__init__.py
  gammapy/cube/tests/__init__.py
  gammapy/datasets/__init__.py
  gammapy/datasets/simulate.py
  gammapy/datasets/tests/test_simulate.py
  gammapy/estimators/__init__.py
  gammapy/estimators/asmooth_map.py
  gammapy/estimators/profile.py
  gammapy/estimators/tests/test_profile.py
  gammapy/makers/background/ring.py
  gammapy/maps/__init__.py
  gammapy/maps/image_utils.py
  gammapy/maps/tests/test_counts.py
  gammapy/utils/array.py
Labels: cleanup

#2805 Move LightcurveEstimator to gammapy.estimators
  docs/estimators/detect.rst
  docs/estimators/index.rst
  docs/estimators/lightcurve.rst
  docs/time/index.rst
  gammapy/catalog/fermi.py
  gammapy/estimators/__init__.py
  gammapy/estimators/lightcurve.py
  gammapy/estimators/tests/test_lightcurve.py
  gammapy/time/__init__.py
  gammapy/time/lightcurve.py
  gammapy/time/simulate.py
  gammapy/time/tests/test_simulate.py
  gammapy/time/tests/test_variability.py
  gammapy/utils/random/tests/test_random.py
  gammapy/utils/random/utils.py
  tutorials/light_curve.ipynb
  tutorials/light_curve_flare.ipynb
Labels: cleanup

#2807 Add filename argument in BackgroundModel().from_dict()
  gammapy/modeling/models/cube.py
  gammapy/modeling/models/tests/test_cube.py
Labels: bug

#2810 Flux estimator
  gammapy/estimators/__init__.py
  gammapy/estimators/flux.py
  gammapy/estimators/parameter_estimator.py
  gammapy/estimators/tests/test_flux.py
Labels: feature

#2808 Add temporal model evaluation
  gammapy/datasets/map.py
  gammapy/modeling/models/__init__.py
  gammapy/modeling/models/cube.py
  gammapy/modeling/models/temporal.py
  gammapy/modeling/models/tests/test_cube.py
  gammapy/modeling/models/tests/test_io.py
  gammapy/modeling/models/tests/test_temporal.py
Labels: feature

#2815 Remove CountsSpectrum class
  docs/development/dataformats.rst
  docs/overview.rst
  gammapy/analysis/core.py
  gammapy/analysis/tests/test_analysis.py
  gammapy/data/event_list.py
  gammapy/datasets/core.py
  gammapy/datasets/map.py
  gammapy/datasets/spectrum.py
  gammapy/datasets/tests/test_map.py
  gammapy/datasets/tests/test_spectrum.py
  gammapy/estimators/flux_point.py
  gammapy/estimators/sensitivity.py
  gammapy/estimators/tests/test_flux.py
  gammapy/estimators/tests/test_flux_point_estimator.py
  gammapy/estimators/tests/test_lightcurve.py
  gammapy/estimators/tests/test_parameter_estimator.py
  gammapy/estimators/tests/test_sensitivity.py
  gammapy/irf/edisp_kernel.py
  gammapy/irf/tests/test_energy_dispersion.py
  gammapy/makers/background/phase.py
  gammapy/makers/background/reflected.py
  gammapy/makers/background/tests/test_reflected.py
  gammapy/makers/safe.py
  gammapy/makers/spectrum.py
  gammapy/maps/__init__.py
  gammapy/maps/base.py
  gammapy/maps/counts_spectrum.py
  gammapy/maps/region.py
  gammapy/maps/regionnd.py
  gammapy/maps/tests/test_counts_spectrum.py
  gammapy/maps/tests/test_wcsnd.py
  gammapy/maps/wcsnd.py
  gammapy/modeling/iminuit.py
  gammapy/modeling/tests/test_iminuit.py
  gammapy/visualization/utils.py
  tutorials/cta_sensitivity.ipynb
  tutorials/extended_source_spectral_analysis.ipynb
  tutorials/modeling.ipynb
  tutorials/pulsar_analysis.ipynb
  tutorials/spectrum_analysis.ipynb
  tutorials/spectrum_simulation.ipynb
Labels: cleanup

#2816 Remove RegionGeom.energy_mask()
  gammapy/analysis/tests/test_analysis.py
  gammapy/makers/tests/test_safe.py
  gammapy/maps/geom.py
  gammapy/maps/region.py
  gammapy/maps/tests/test_wcs.py
Labels: cleanup

#2811 Correct error in confidence interval range
  gammapy/stats/counts_statistic.py
  gammapy/stats/tests/test_counts_statistic.py
Labels: bug

#2818 Fix background serialization in order to preserve parameters order and links
  gammapy/datasets/flux_points.py
  gammapy/datasets/io.py
  gammapy/datasets/map.py
  gammapy/datasets/spectrum.py
  gammapy/modeling/models/cube.py
  gammapy/modeling/models/io.py
  gammapy/modeling/models/tests/data/examples.yaml
  gammapy/modeling/models/tests/test_io.py
Labels: bug

#2817 Remove spectrum evaluator
  docs/makers/make_rectangular_reflected_background.py
  gammapy/analysis/config/model-1d.yaml
  gammapy/analysis/tests/test_analysis.py
  gammapy/datasets/map.py
  gammapy/datasets/spectrum.py
  gammapy/datasets/tests/test_map.py
  gammapy/datasets/tests/test_spectrum.py
  gammapy/estimators/flux.py
  gammapy/estimators/tests/test_flux.py
  gammapy/estimators/tests/test_flux_point_estimator.py
  gammapy/makers/safe.py
  gammapy/makers/spectrum.py
  gammapy/maps/base.py
  gammapy/maps/region.py
  gammapy/maps/regionnd.py
  gammapy/maps/tests/test_region.py
  gammapy/modeling/models/cube.py
  gammapy/modeling/models/spatial.py
  gammapy/modeling/models/spectral.py
  gammapy/modeling/models/tests/test_cube.py
Labels: cleanup

#2823 Add temporal evaluation for spectral datasets
  gammapy/datasets/spectrum.py
  gammapy/datasets/tests/test_spectrum.py
Labels: feature

#2822 Redistribute serialization code to classes
  gammapy/datasets/core.py
  gammapy/datasets/io.py
  gammapy/modeling/models/core.py
  gammapy/modeling/models/io.py
  gammapy/modeling/models/tests/test_io.py
Labels: cleanup

#2824 Correct GaussianTemporalModel.integral
  gammapy/modeling/models/temporal.py
  gammapy/modeling/models/tests/test_temporal.py
Labels: bug

#2809 Add sampling of temporal models to event sampler
  gammapy/datasets/simulate.py
  gammapy/datasets/tests/test_simulate.py
  gammapy/modeling/models/temporal.py
  gammapy/modeling/models/tests/test_temporal.py
Labels: feature

#2820 Replace LiMaMapEstimator with ExcessMapEstimator
  gammapy/estimators/__init__.py
  gammapy/estimators/excess_map.py
  gammapy/estimators/lima_map.py
  gammapy/estimators/tests/test_excess_map.py
  gammapy/estimators/tests/test_lima_map.py
  gammapy/stats/counts_statistic.py
  tutorials/exclusion_mask.ipynb
  tutorials/ring_background.ipynb
Labels: cleanup, feature

#2821 Adapt FluxPointsEstimator
  gammapy/datasets/core.py
  gammapy/estimators/flux.py
  gammapy/estimators/flux_point.py
  gammapy/estimators/parameter_estimator.py
  gammapy/estimators/tests/test_flux.py
  gammapy/estimators/tests/test_flux_point_estimator.py
  gammapy/estimators/tests/test_parameter_estimator.py
Labels: cleanup

#2825 Adding metadata keywords in MapDatasetEventSampler
  gammapy/datasets/simulate.py
  gammapy/datasets/tests/test_simulate.py
Labels: cleanup, feature

#2812 Add ring background estimation in high-level interface.
  gammapy/analysis/config.py
  gammapy/analysis/config/docs.yaml
  gammapy/analysis/core.py
  gammapy/analysis/tests/test_analysis.py
Labels: feature

#2827 Improve covariance handling / implement Covariance class
  gammapy/catalog/fermi.py
  gammapy/catalog/gammacat.py
  gammapy/catalog/hawc.py
  gammapy/catalog/hess.py
  gammapy/catalog/tests/test_hess.py
  gammapy/datasets/core.py
  gammapy/datasets/flux_points.py
  gammapy/datasets/map.py
  gammapy/datasets/tests/test_flux_points.py
  gammapy/datasets/tests/test_map.py
  gammapy/datasets/tests/test_spectrum.py
  gammapy/estimators/lightcurve.py
  gammapy/estimators/parameter_estimator.py
  gammapy/estimators/tests/test_flux.py
  gammapy/estimators/tests/test_flux_point_estimator.py
  gammapy/estimators/tests/test_lightcurve.py
  gammapy/makers/background/tests/test_fov.py
  gammapy/modeling/__init__.py
  gammapy/modeling/covariance.py
  gammapy/modeling/fit.py
  gammapy/modeling/iminuit.py
  gammapy/modeling/models/core.py
  gammapy/modeling/models/cube.py
  gammapy/modeling/models/spatial.py
  gammapy/modeling/models/spectral.py
  gammapy/modeling/models/tests/test_cube.py
  gammapy/modeling/models/tests/test_spatial.py
  gammapy/modeling/models/tests/test_spectral.py
  gammapy/modeling/parameter.py
  gammapy/modeling/scipy.py
  gammapy/modeling/tests/test_covariance.py
  gammapy/modeling/tests/test_fit.py
  gammapy/modeling/tests/test_iminuit.py
  gammapy/modeling/tests/test_parameter.py
  gammapy/visualization/__init__.py
  gammapy/visualization/heatmap.py
  tutorials/analysis_2.ipynb
  tutorials/analysis_3d.ipynb
  tutorials/analysis_mwl.ipynb
  tutorials/cta_data_analysis.ipynb
  tutorials/modeling.ipynb
  tutorials/pulsar_analysis.ipynb
  tutorials/sed_fitting.ipynb
  tutorials/spectrum_analysis.ipynb
Labels: cleanup, feature

#2829 Add a tutorial for the event sampler
  .gitignore
  docs/tutorials/index.rst
  gammapy/data/event_list.py
  gammapy/datasets/map.py
  gammapy/datasets/simulate.py
  tutorials/event_sampling.ipynb
Labels: cleanup

#2834 Fix Travis CI fails due to not found datasets
  .travis.yml
  Makefile
  dev/datasets/gammapy-data-index.json
  gammapy/scripts/check.py
  gammapy/scripts/downloadclasses.py
  gammapy/scripts/tests/test_download.py
  gammapy/scripts/tests/test_main.py
  gammapy/utils/tutorials_process.py
Labels: cleanup

#2830 Allow stacking of MapDatasetOnOff into MapDataset
  docs/makers/ring.rst
  gammapy/analysis/tests/test_analysis.py
  gammapy/datasets/map.py
  gammapy/datasets/tests/test_map.py
Labels: bug, cleanup

#2837 Improve Background2D visualisation
  gammapy/irf/background.py
  gammapy/irf/tests/test_background.py
Labels: bug

#2828 Add notebook for light curve simulation
  docs/tutorials/index.rst
  tutorials/light_curve_simulation.ipynb
  tutorials/notebooks.yaml
Labels: docs

#2839 Improve stats documentation with plots
  docs/stats/index.rst
  docs/stats/plot_cash_errors.py
  docs/stats/plot_cash_significance.py
  docs/stats/plot_wstat_errors.py
  docs/stats/plot_wstat_significance.py
Labels: docs

#2842 Cleaning gammapy.stats
  gammapy/datasets/spectrum.py
  gammapy/estimators/asmooth_map.py
  gammapy/estimators/sensitivity.py
  gammapy/estimators/tests/test_asmooth_map.py
  gammapy/stats/__init__.py
  gammapy/stats/counts_statistic.py
  gammapy/stats/normal.py
  gammapy/stats/poisson.py
  gammapy/stats/tests/test_counts_statistic.py
  gammapy/stats/tests/test_normal.py
  gammapy/stats/tests/test_poisson.py
  tutorials/detect.ipynb
Labels: cleanup

#2840 Reorganize install.rst page
  docs/getting-started.rst
  docs/install/index.rst
Labels: docs

#2845 Add plotting to Background3D
  gammapy/irf/background.py
  gammapy/irf/tests/test_background.py
Labels: feature

#2848 Adapt FluxEstimator, FluxPointsEstimator and ParameterEstimator
  gammapy/analysis/core.py
  gammapy/estimators/flux.py
  gammapy/estimators/flux_point.py
  gammapy/estimators/parameter_estimator.py
  gammapy/estimators/tests/test_flux.py
  gammapy/estimators/tests/test_flux_point_estimator.py
  gammapy/estimators/tests/test_parameter_estimator.py
  tutorials/analysis_2.ipynb
  tutorials/analysis_mwl.ipynb
  tutorials/cta_data_analysis.ipynb
  tutorials/pulsar_analysis.ipynb
  tutorials/spectrum_analysis.ipynb
Labels: cleanup

#2846 Updating keywords in MapDatasetEventSampler
  gammapy/datasets/simulate.py
  gammapy/datasets/tests/test_simulate.py
Labels: feature

#2843 Adapt ExcessMapEstimator to estimators init scheme
  gammapy/estimators/excess_map.py
  gammapy/estimators/tests/test_excess_map.py
  tutorials/exclusion_mask.ipynb
  tutorials/ring_background.ipynb
Labels: cleanup

#2832 Implement EDispKernelMap
  gammapy/irf/edisp_map.py
  gammapy/irf/irf_map.py
  gammapy/irf/psf_map.py
  gammapy/irf/tests/test_edisp_map.py
  gammapy/irf/tests/test_psf_map.py
  gammapy/maps/geom.py
  gammapy/maps/wcsnd.py
Labels: feature

#2833 Add covariance serialization
  gammapy/modeling/covariance.py
  gammapy/modeling/models/core.py
  gammapy/modeling/models/cube.py
  gammapy/modeling/models/tests/test_io.py
  gammapy/modeling/tests/test_covariance.py
Labels: cleanup, feature

#2850 Adapt LightcurveEstimator to the new FluxEstimator
  gammapy/estimators/lightcurve.py
  gammapy/estimators/parameter_estimator.py
  gammapy/estimators/tests/test_lightcurve.py
  gammapy/estimators/tests/test_parameter_estimator.py
  tutorials/light_curve.ipynb
  tutorials/light_curve_flare.ipynb
  tutorials/light_curve_simulation.ipynb
Labels: cleanup

#2844 Change TSMapEstimator to use PSFMap and source model as input
  gammapy/datasets/map.py
  gammapy/estimators/tests/test_ts_map.py
  gammapy/estimators/ts_map.py
  gammapy/irf/psf_kernel.py
  gammapy/irf/tests/test_psf_kernel.py
  gammapy/modeling/models/spatial.py
  tutorials/cta_data_analysis.ipynb
  tutorials/detect.ipynb
Labels: cleanup
