Repository gammapy/gammapy, pull requests merged in 2020-05, with the labels that each got.

#2885 Add comparators on Map
  gammapy/maps/base.py
  gammapy/maps/tests/test_base.py
  tutorials/exclusion_mask.ipynb
Labels: feature

#2886 Improve coverage of visualization, utils and irf packages
  gammapy/datasets/tests/test_spectrum.py
  gammapy/irf/psf_table.py
  gammapy/irf/tests/test_psf_gauss.py
  gammapy/irf/tests/test_psf_table.py
  gammapy/utils/tests/test_fits.py
  gammapy/visualization/tests/test_utils.py
  gammapy/visualization/utils.py
Labels: tests

#2884 MapDataset.background_model as property
  gammapy/datasets/map.py
  gammapy/datasets/tests/test_io.py
  gammapy/datasets/tests/test_map.py
  gammapy/datasets/tests/test_simulate.py
Labels: cleanup

#2888 Adding unit test for the mcmc sampling
  gammapy/modeling/tests/test_sampling.py
Labels: tests

#2881 Change models handling on dataset copy and stack
  gammapy/datasets/core.py
  gammapy/datasets/map.py
  gammapy/datasets/tests/test_io.py
  gammapy/datasets/tests/test_map.py
  tutorials/simulate_3d.ipynb
Labels: cleanup

#2883 Improve path handling in serialization
  gammapy/datasets/core.py
  gammapy/datasets/flux_points.py
  gammapy/datasets/map.py
  gammapy/datasets/spectrum.py
  gammapy/datasets/tests/test_flux_points.py
  gammapy/datasets/tests/test_io.py
  gammapy/datasets/tests/test_spectrum.py
  gammapy/estimators/tests/test_asmooth_map.py
  gammapy/estimators/tests/test_flux.py
  gammapy/modeling/models/core.py
  gammapy/modeling/models/spectral.py
  gammapy/modeling/models/tests/test_io.py
  gammapy/modeling/models/tests/test_spectral.py
  gammapy/modeling/sampling.py
  gammapy/modeling/tests/test_sampling.py
  tutorials/analysis_mwl.ipynb
  tutorials/event_sampling.ipynb
  tutorials/exclusion_mask.ipynb
Labels: cleanup

#2891 Modify SpectrumDataset.create() to take MapAxis arguments
  gammapy/analysis/core.py
  gammapy/datasets/spectrum.py
  gammapy/datasets/tests/test_spectrum.py
  gammapy/makers/background/tests/test_phase.py
  gammapy/makers/background/tests/test_reflected.py
  gammapy/makers/tests/test_spectrum.py
  tutorials/cta_data_analysis.ipynb
  tutorials/cta_sensitivity.ipynb
  tutorials/light_curve_flare.ipynb
  tutorials/light_curve_simulation.ipynb
  tutorials/pulsar_analysis.ipynb
  tutorials/spectrum_analysis.ipynb
  tutorials/spectrum_simulation.ipynb
Labels: cleanup

#2892 Improve coverage in gammapy.data
  gammapy/data/observations.py
  gammapy/data/tests/test_event_list.py
  gammapy/data/tests/test_hdu_index_table.py
  gammapy/data/tests/test_observations.py
Labels: tests

#2898 Add check for regular geom for geom.__eq__
  gammapy/maps/tests/test_wcs.py
  gammapy/maps/wcs.py
Labels: bug

#2882 Add `event_det_coord()` to `MapDatasetEventSampler`
  gammapy/datasets/simulate.py
  gammapy/datasets/tests/test_simulate.py
Labels: feature

#2896 Add pyproject.toml, fixes 2895
  pyproject.toml
  setup.cfg
  setup.py
Labels: infrastructure

#2890 Improve Models management on Dataset and Datasets
  gammapy/analysis/core.py
  gammapy/datasets/core.py
  gammapy/datasets/flux_points.py
  gammapy/datasets/map.py
  gammapy/datasets/spectrum.py
  gammapy/datasets/tests/test_io.py
  gammapy/datasets/tests/test_map.py
  gammapy/datasets/tests/test_spectrum.py
  gammapy/estimators/tests/test_ts_map.py
  gammapy/estimators/ts_map.py
  gammapy/modeling/models/core.py
  gammapy/modeling/models/tests/test_core.py
  gammapy/modeling/tests/test_fit.py
  tutorials/light_curve.ipynb
Labels: cleanup, feature

#2900 Correct some coding style errors
  gammapy/data/observations.py
  gammapy/datasets/core.py
  gammapy/datasets/flux_points.py
  gammapy/datasets/spectrum.py
  gammapy/modeling/models/core.py
Labels: cleanup

#2903 Add multi-dimension support for RegionGeom
  gammapy/maps/region.py
  gammapy/maps/tests/test_region.py
Labels: feature

#2906 Add read/write example for exclusion masks
  tutorials/exclusion_mask.ipynb
Labels: docs

#2905 Fix evaluators cache
  gammapy/datasets/map.py
  gammapy/datasets/simulate.py
  gammapy/datasets/spectrum.py
  gammapy/datasets/tests/test_map.py
  gammapy/datasets/tests/test_spectrum.py
  gammapy/modeling/models/core.py
  gammapy/modeling/models/tests/test_core.py
Labels: bug, cleanup

#2897 Change to EDispKernelMap in MapDataset
  gammapy/datasets/map.py
  gammapy/datasets/tests/test_map.py
  gammapy/datasets/tests/test_simulate.py
  gammapy/estimators/tests/test_flux_point_estimator.py
  gammapy/estimators/tests/test_lightcurve.py
  gammapy/irf/edisp_map.py
  gammapy/irf/irf_map.py
  gammapy/makers/background/tests/test_fov.py
  gammapy/makers/background/tests/test_ring.py
  gammapy/makers/map.py
  gammapy/makers/safe.py
  gammapy/makers/tests/test_map.py
  gammapy/makers/tests/test_safe.py
  gammapy/makers/tests/test_utils.py
  gammapy/makers/utils.py
Labels: feature

#2907 Add info_dict to MapDataset
  gammapy/datasets/core.py
  gammapy/datasets/map.py
  gammapy/datasets/spectrum.py
  gammapy/datasets/tests/test_map.py
  tutorials/analysis_3d.ipynb
Labels: bug, cleanup

#2909 fix MapDatasetOnOff.mask_safe on read
  gammapy/datasets/map.py
  gammapy/datasets/tests/test_map.py
Labels: bug
