Repository gammapy/gammapy, pull requests merged in 2020-11, with the labels that each got.

#3095 Fix livetime stacking Fix #3093
  gammapy/datasets/map.py
  gammapy/datasets/spectrum.py
  gammapy/datasets/tests/test_spectrum.py
Labels: bug

#3096 Export edisp exposure in .to_spectrum_dataset()
  gammapy/datasets/map.py
  gammapy/datasets/tests/test_map.py
Labels: bug

#3099 Fix #3097
  gammapy/estimators/flux_point.py
  gammapy/estimators/tests/test_flux_point.py
  gammapy/modeling/models/tests/test_cube.py
  gammapy/modeling/models/tests/test_spatial.py
Labels: bug

#3089 Introduce DatasetModels class and global model
  docs/tutorials/analysis_2.ipynb
  docs/tutorials/analysis_3d.ipynb
  docs/tutorials/analysis_mwl.ipynb
  docs/tutorials/event_sampling.ipynb
  docs/tutorials/exclusion_mask.ipynb
  docs/tutorials/mcmc_sampling.ipynb
  docs/tutorials/simulate_3d.ipynb
  gammapy/analysis/core.py
  gammapy/datasets/core.py
  gammapy/datasets/flux_points.py
  gammapy/datasets/map.py
  gammapy/datasets/simulate.py
  gammapy/datasets/spectrum.py
  gammapy/datasets/tests/test_flux_points.py
  gammapy/datasets/tests/test_io.py
  gammapy/datasets/tests/test_map.py
  gammapy/datasets/tests/test_simulate.py
  gammapy/datasets/tests/test_spectrum.py
  gammapy/estimators/tests/test_asmooth_map.py
  gammapy/estimators/tests/test_excess_map.py
  gammapy/estimators/tests/test_flux.py
  gammapy/estimators/tests/test_flux_point_estimator.py
  gammapy/estimators/tests/test_lightcurve.py
  gammapy/estimators/tests/test_parameter_estimator.py
  gammapy/makers/background/tests/test_fov.py
  gammapy/modeling/models/core.py
  gammapy/modeling/models/cube.py
  gammapy/modeling/models/tests/test_core.py
  gammapy/modeling/models/tests/test_io.py
  gammapy/modeling/tests/test_sampling.py
Labels: cleanup, feature

#3092 Update energy naming convention for gammapy.analysis
  gammapy/analysis/core.py
Labels: cleanup

#3100 Simplify EBL absorption spectral model
  examples/models/spectral/plot_absorbed.py
  examples/models/spectral/plot_absorption.py
  gammapy/modeling/models/__init__.py
  gammapy/modeling/models/spectral.py
  gammapy/modeling/models/tests/test_io.py
  gammapy/modeling/models/tests/test_spectral.py
Labels: cleanup

#3103 Fix unit handling in .stack() methods and energy range in FluxEstimator
  gammapy/datasets/map.py
  gammapy/estimators/flux.py
  gammapy/estimators/flux_point.py
  gammapy/estimators/tests/test_flux.py
  gammapy/maps/regionnd.py
  gammapy/maps/tests/test_regionnd.py
  gammapy/maps/tests/test_wcsnd.py
  gammapy/maps/wcsnd.py
Labels: bug

#3104 Correct Map.resample_axis for incomplete axis coverage and improve excess map mask handling
  gammapy/datasets/map.py
  gammapy/datasets/tests/test_map.py
  gammapy/estimators/excess_map.py
  gammapy/estimators/tests/test_excess_map.py
  gammapy/maps/core.py
  gammapy/maps/tests/test_hpxmap.py
  gammapy/maps/tests/test_regionnd.py
  gammapy/maps/tests/test_wcsnd.py
Labels: bug, cleanup

#3106 Remove default FoVBackgroundModel
  docs/tutorials/analysis_2.ipynb
  docs/tutorials/analysis_3d.ipynb
  docs/tutorials/cta_data_analysis.ipynb
  docs/tutorials/extended_source_spectral_analysis.ipynb
  docs/tutorials/light_curve_simulation.ipynb
  docs/tutorials/models.ipynb
  gammapy/analysis/core.py
  gammapy/analysis/tests/test_analysis.py
  gammapy/datasets/core.py
  gammapy/datasets/map.py
  gammapy/datasets/tests/test_map.py
  gammapy/datasets/tests/test_spectrum.py
  gammapy/estimators/excess_map.py
  gammapy/estimators/flux.py
  gammapy/estimators/flux_point.py
  gammapy/estimators/parameter.py
  gammapy/estimators/tests/test_flux.py
  gammapy/makers/background/fov.py
  gammapy/makers/background/tests/test_fov.py
  gammapy/makers/tests/test_spectrum.py
  gammapy/modeling/models/__init__.py
  gammapy/modeling/models/cube.py
  gammapy/modeling/models/tests/test_cube.py
Labels: cleanup

#3108 Change FluxEstimator UL backend to scipy
  docs/tutorials/light_curve.ipynb
  docs/tutorials/light_curve_simulation.ipynb
  docs/tutorials/spectrum_analysis.ipynb
  gammapy/estimators/parameter.py
Labels: bug

#3107 Fill changelog for v0.18.
  CHANGES.rst
Labels: docs

#3112 Improve error messages for wrong shapes
  gammapy/irf/psf_3d.py
  gammapy/irf/psf_table.py
  gammapy/irf/tests/test_effective_area.py
  gammapy/irf/tests/test_psf_3d.py
  gammapy/utils/nddata.py
  gammapy/utils/tests/test_nddata.py
Labels: cleanup

#3111 Adapt ExcessMapEstimator for missing models
  gammapy/estimators/excess_map.py
  gammapy/estimators/tests/test_excess_map.py
Labels: bug

#3110 Correct plot_residual methods
  gammapy/datasets/map.py
  gammapy/datasets/tests/test_map.py
Labels: bug

#3113 Modified TSMapEstimator to keep model term
  gammapy/estimators/tests/test_ts_map.py
  gammapy/estimators/ts_map.py
Labels: bug

#3114 Corrected exclusion mask notebook
  docs/tutorials/exclusion_mask.ipynb
  docs/tutorials/light_curve_flare.ipynb
Labels: bug

#3117 Fill changelog for v0.18.1
  CHANGES.rst
Labels: docs

#3116 Fix model handling in FluxEstimator
  gammapy/analysis/tests/test_analysis.py
  gammapy/datasets/core.py
  gammapy/estimators/flux.py
  gammapy/estimators/tests/test_flux.py
  gammapy/estimators/tests/test_flux_point_estimator.py
  gammapy/modeling/models/cube.py
  gammapy/modeling/parameter.py
Labels: bug

#3124 Small cleanup in tutorial
  docs/tutorials/cta.ipynb
Labels: docs

#3125 Update Astropy version to 4.0
  .travis.yml
  setup.cfg
Labels: infrastructure

#3126 Fix #3123
  gammapy/astro/darkmatter/tests/test_spectra.py
  gammapy/estimators/tests/test_flux_point_estimator.py
  gammapy/modeling/models/spectral.py
  gammapy/modeling/models/tests/test_spectral.py
Labels: bug, cleanup

#3127 Fix containment radius computation
  gammapy/analysis/tests/test_analysis.py
  gammapy/datasets/tests/test_map.py
  gammapy/irf/psf_3d.py
  gammapy/irf/psf_table.py
  gammapy/irf/tests/test_psf_3d.py
  gammapy/irf/tests/test_psf_map.py
  gammapy/makers/tests/test_spectrum.py
Labels: bug, cleanup

#3122 Correct excess_matching_significance behavior
  gammapy/estimators/excess_profile.py
  gammapy/stats/counts_statistic.py
  gammapy/stats/tests/test_counts_statistic.py
Labels: bug

#3129 Fix `spectral._propagate_error`
  gammapy/modeling/models/spectral.py
  gammapy/modeling/models/tests/test_spectral.py
Labels: bug

#3130 Fix too small energy bin handling for FluxEstimator
  gammapy/estimators/flux.py
  gammapy/estimators/tests/test_flux.py
Labels: bug

#3133 Change find_peaks to work with flat maps rather than images
  docs/tutorials/cta_data_analysis.ipynb
  docs/tutorials/detect.ipynb
  gammapy/estimators/tests/test_utils.py
  gammapy/estimators/utils.py
Labels: cleanup

#3135 Fix API links in notebooks
  docs/tutorials/catalog.ipynb
  docs/tutorials/light_curve.ipynb
  docs/tutorials/light_curve_flare.ipynb
Labels: bug

#3136 Evaluate spatial model in RegionGeom
  gammapy/maps/region.py
  gammapy/maps/tests/test_region.py
  gammapy/modeling/models/spatial.py
Labels: feature

#3139 Fix spatial.integrate_geom
  gammapy/modeling/models/spatial.py
  gammapy/modeling/models/tests/test_spatial.py
Labels: feature

#3137 Adding a function to update parameters from dict
  gammapy/modeling/parameter.py
  gammapy/modeling/tests/test_parameter.py
Labels: feature

#3131 Further remove code duplication between SpectrumDataset and MapDataset
  docs/tutorials/cta_data_analysis.ipynb
  docs/tutorials/cta_sensitivity.ipynb
  docs/tutorials/light_curve_flare.ipynb
  docs/tutorials/light_curve_simulation.ipynb
  docs/tutorials/pulsar_analysis.ipynb
  docs/tutorials/spectrum_analysis.ipynb
  docs/tutorials/spectrum_simulation.ipynb
  gammapy/analysis/core.py
  gammapy/datasets/map.py
  gammapy/datasets/spectrum.py
  gammapy/datasets/tests/test_map.py
  gammapy/datasets/tests/test_spectrum.py
  gammapy/estimators/flux.py
  gammapy/estimators/flux_point.py
  gammapy/estimators/tests/test_flux_point_estimator.py
  gammapy/irf/irf_map.py
  gammapy/makers/background/tests/test_phase.py
  gammapy/makers/background/tests/test_reflected.py
  gammapy/makers/tests/test_spectrum.py
  gammapy/maps/hpx.py
  gammapy/maps/region.py
  gammapy/maps/regionnd.py
  gammapy/maps/wcs.py
  gammapy/modeling/models/cube.py
Labels: cleanup

#3141 Allow SkyModel.integrate_geom to integrate over a RegionGeom
  gammapy/modeling/models/cube.py
  gammapy/modeling/models/tests/test_cube.py
Labels: feature

#3138 Migrate Travis CI to Github actions
  .github/workflows/ci.yml
  .travis.yml
  README.rst
  azure-pipelines.yml
  environment-dev.yml
Labels: cleanup, infrastructure

#3142 Remove support for EDispKernel and PSFKernel from MapDataset
  gammapy/datasets/map.py
  gammapy/datasets/tests/test_map.py
Labels: cleanup

#3144 Add the option to impose a minimal width in RegionGeom.to_wcs_geom()
  gammapy/maps/region.py
  gammapy/maps/tests/test_region.py
Labels: feature
