Repository gammapy/gammapy, pull requests merged in 2020-07, with the labels that each got.

#2936 Correct edisp bias caption
  gammapy/irf/edisp_kernel.py
Labels: bug

#2932 Fix plot_spectrum_datasets_off_regions and make customization more flexible
  gammapy/visualization/utils.py
Labels: feature

#2943 Add BrokenPowerLawSpectralModel
  examples/models/spectral/plot_broken_powerlaw.py
  gammapy/modeling/models/__init__.py
  gammapy/modeling/models/spectral.py
  gammapy/modeling/models/tests/test_spectral.py
Labels: feature

#2946 Improve models residuals and fit quality sections in tutorials
  docs/tutorials/analysis_3d.ipynb
  docs/tutorials/analysis_mwl.ipynb
  docs/tutorials/detect.ipynb
  docs/tutorials/extended_source_spectral_analysis.ipynb
  docs/tutorials/fermi_lat.ipynb
  docs/tutorials/light_curve_flare.ipynb
  docs/tutorials/light_curve_simulation.ipynb
  docs/tutorials/modeling.ipynb
  docs/tutorials/spectrum_analysis.ipynb
  docs/tutorials/spectrum_simulation.ipynb
Labels: docs

#2940 Introduce EDispKernelMap for SpectrumDataset
  docs/tutorials/cta_sensitivity.ipynb
  docs/tutorials/light_curve_flare.ipynb
  docs/tutorials/light_curve_simulation.ipynb
  docs/tutorials/spectrum_simulation.ipynb
  gammapy/datasets/spectrum.py
  gammapy/datasets/tests/test_spectrum.py
  gammapy/estimators/sensitivity.py
  gammapy/irf/edisp_map.py
  gammapy/irf/tests/test_edisp_map.py
  gammapy/makers/safe.py
  gammapy/makers/spectrum.py
  gammapy/makers/tests/test_spectrum.py
  gammapy/maps/region.py
  gammapy/maps/tests/test_region.py
Labels: cleanup

#2938 Add shorter tags for models
  gammapy/catalog/fermi.py
  gammapy/catalog/gammacat.py
  gammapy/catalog/hawc.py
  gammapy/catalog/hess.py
  gammapy/catalog/tests/test_fermi.py
  gammapy/estimators/tests/test_flux_point_estimator.py
  gammapy/modeling/models/__init__.py
  gammapy/modeling/models/core.py
  gammapy/modeling/models/spatial.py
  gammapy/modeling/models/spectral.py
  gammapy/modeling/models/temporal.py
  gammapy/modeling/models/tests/test_core.py
  gammapy/modeling/models/tests/test_io.py
  gammapy/modeling/models/tests/test_temporal.py
  gammapy/utils/registry.py
Labels: cleanup, feature

#2950 Remove IRFStacker class
  gammapy/datasets/map.py
  gammapy/datasets/spectrum.py
  gammapy/datasets/tests/test_map.py
  gammapy/datasets/tests/test_spectrum.py
  gammapy/estimators/tests/test_sensitivity.py
  gammapy/irf/__init__.py
  gammapy/irf/edisp_map.py
  gammapy/irf/irf_map.py
  gammapy/irf/irf_reduce.py
  gammapy/irf/irf_stack.py
  gammapy/irf/psf_3d.py
  gammapy/irf/psf_map.py
  gammapy/irf/tests/test_edisp_map.py
  gammapy/irf/tests/test_irf_reduce.py
  gammapy/makers/tests/test_map.py
  gammapy/makers/utils.py
  gammapy/maps/core.py
  gammapy/maps/geom.py
  gammapy/maps/region.py
  gammapy/maps/regionnd.py
  gammapy/maps/wcsnd.py
Labels: cleanup

#2947 Improve spectral residuals plot
  gammapy/datasets/map.py
  gammapy/datasets/spectrum.py
  gammapy/maps/regionnd.py
Labels: cleanup, feature

#2937 Send warning in case parameter value is set outside boundaries
  gammapy/modeling/fit.py
  gammapy/modeling/models/spatial.py
  gammapy/modeling/parameter.py
Labels: cleanup

#2945 PSF-convolved spatial model caching in MapEvaluator
  gammapy/datasets/map.py
  gammapy/datasets/tests/test_map.py
  gammapy/estimators/tests/test_flux.py
  gammapy/maps/wcsnd.py
  gammapy/modeling/models/tests/test_core.py
Labels: cleanup

#2951 Implement Map.resample_axis() method
  gammapy/maps/core.py
  gammapy/maps/geom.py
  gammapy/maps/tests/test_wcsnd.py
Labels: feature

#2955 Modify EdispKernel constructor to work with MapAxis
  gammapy/irf/edisp_kernel.py
  gammapy/irf/edisp_map.py
  gammapy/irf/energy_dispersion.py
Labels: cleanup

#2956 Implement `MapDataset.downsample()` and `MapDataset.pad()` methods
  gammapy/datasets/map.py
  gammapy/estimators/ts_map.py
  gammapy/irf/irf_map.py
  gammapy/maps/geom.py
  gammapy/maps/wcsnd.py
Labels: feature

#2939 Add theta squared plot example
  docs/tutorials/hess.ipynb
  gammapy/makers/tests/test_utils.py
  gammapy/makers/utils.py
  gammapy/visualization/tests/test_utils.py
  gammapy/visualization/utils.py
Labels: docs

#2957 Adapt MapDataset.stack
  gammapy/datasets/map.py
  gammapy/datasets/tests/test_map.py
Labels: bug, cleanup

#2960 Implement IRF registry
  gammapy/data/hdu_index_table.py
  gammapy/data/tests/test_hdu_index_table.py
  gammapy/irf/__init__.py
  gammapy/irf/background.py
  gammapy/irf/effective_area.py
  gammapy/irf/energy_dispersion.py
  gammapy/irf/psf_3d.py
  gammapy/irf/psf_gauss.py
  gammapy/irf/psf_king.py
  gammapy/maps/core.py
  gammapy/utils/fits.py
Labels: cleanup

#2961 Add possiblity to plot Map with non-spatial axes of size 1
  docs/tutorials/cta_data_analysis.ipynb
  docs/tutorials/ring_background.ipynb
  gammapy/maps/geom.py
  gammapy/maps/tests/test_wcsnd.py
  gammapy/maps/wcsnd.py
Labels: feature
