Repository gammapy/gammapy, pull requests merged in 2021-01, with the labels that each got.

#3177 Further clean up Map axes handling and interpolation
  docs/maps/regionmap.rst
  docs/tutorials/fermi_lat.ipynb
  docs/tutorials/maps.ipynb
  gammapy/maps/core.py
  gammapy/maps/geom.py
  gammapy/maps/hpxnd.py
  gammapy/maps/region.py
  gammapy/maps/tests/test_base.py
  gammapy/maps/tests/test_hpxmap.py
  gammapy/maps/tests/test_wcsnd.py
  gammapy/maps/utils.py
  gammapy/maps/wcs.py
  gammapy/maps/wcsmap.py
  gammapy/maps/wcsnd.py
  gammapy/modeling/models/spatial.py
  gammapy/utils/interpolation.py
  gammapy/utils/nddata.py
  gammapy/utils/tests/test_nddata.py
Labels: cleanup

#3176 Changed logging level for background makers to warning.
  gammapy/makers/background/fov.py
  gammapy/makers/background/reflected.py
Labels: cleanup

#3168 Remove evaluator update from models setter
  gammapy/datasets/map.py
  gammapy/datasets/simulate.py
Labels: cleanup

#3178 Clean up PSF classes in gammapy.irf
  gammapy/datasets/map.py
  gammapy/datasets/tests/test_map.py
  gammapy/estimators/tests/test_flux.py
  gammapy/estimators/tests/test_flux_point_estimator.py
  gammapy/estimators/tests/test_parameter_estimator.py
  gammapy/irf/__init__.py
  gammapy/irf/core.py
  gammapy/irf/edisp_map.py
  gammapy/irf/effective_area.py
  gammapy/irf/io.py
  gammapy/irf/psf/__init__.py
  gammapy/irf/psf/gauss.py
  gammapy/irf/psf/kernel.py
  gammapy/irf/psf/king.py
  gammapy/irf/psf/psf_map.py
  gammapy/irf/psf/table.py
  gammapy/irf/psf/tests/__init__.py
  gammapy/irf/psf/tests/data/psf.txt
  gammapy/irf/psf/tests/data/psf_info.txt
  gammapy/irf/psf/tests/test_psf_gauss.py
  gammapy/irf/psf/tests/test_psf_kernel.py
  gammapy/irf/psf/tests/test_psf_king.py
  gammapy/irf/psf/tests/test_psf_map.py
  gammapy/irf/psf/tests/test_psf_table.py
  gammapy/irf/psf_3d.py
  gammapy/irf/tests/test_io.py
  gammapy/irf/tests/test_irf_write.py
  gammapy/irf/tests/test_psf_3d.py
  gammapy/makers/background/fov.py
  gammapy/makers/background/tests/test_fov.py
  gammapy/makers/utils.py
  gammapy/utils/nddata.py
Labels: cleanup

#3179 Further PSF clean up
  gammapy/irf/psf/gauss.py
  gammapy/irf/psf/tests/data/psf.txt
  gammapy/irf/psf/tests/test_psf_gauss.py
Labels: cleanup

#3181 Make more use of MapAxis and MapAxes in gammapy.irf
  gammapy/datasets/tests/test_spectrum.py
  gammapy/irf/background.py
  gammapy/irf/edisp_kernel.py
  gammapy/irf/edisp_map.py
  gammapy/irf/effective_area.py
  gammapy/irf/energy_dispersion.py
  gammapy/irf/psf/table.py
  gammapy/irf/tests/test_edisp_map.py
  gammapy/irf/tests/test_energy_dispersion.py
  gammapy/makers/tests/test_utils.py
  gammapy/maps/geom.py
  gammapy/maps/tests/test_regionnd.py
  gammapy/modeling/models/tests/test_cube.py
Labels: cleanup

#3180 Remove code duplication from models.spectral
  gammapy/modeling/models/spectral.py
Labels: cleanup

#3173 Restructure hawc catalog in 2hwc and 3hwc
  gammapy/catalog/__init__.py
  gammapy/catalog/hawc.py
Labels: cleanup, feature

#3182 Introduce FluxEstimate class
  gammapy/estimators/flux_estimate.py
  gammapy/estimators/tests/test_flux_estimate.py
Labels: feature

#3029 Helper functions for the interactive parameter editing
  gammapy/modeling/models/core.py
  gammapy/modeling/models/tests/test_core.py
  gammapy/modeling/parameter.py
  gammapy/modeling/tests/test_parameter.py
Labels: feature

#3187 Fix CI with python version 3.6.2
  .github/workflows/ci.yml
Labels: bug

#3185 Introduce IRF base class and remove code duplication
  docs/development/howto.rst
  docs/irf/index.rst
  docs/tutorials/background_model.ipynb
  docs/tutorials/cta.ipynb
  docs/utils/index.rst
  gammapy/datasets/tests/test_map.py
  gammapy/irf/__init__.py
  gammapy/irf/background.py
  gammapy/irf/core.py
  gammapy/irf/edisp_kernel.py
  gammapy/irf/edisp_map.py
  gammapy/irf/effective_area.py
  gammapy/irf/energy_dispersion.py
  gammapy/irf/io.py
  gammapy/irf/psf/gauss.py
  gammapy/irf/psf/kernel.py
  gammapy/irf/psf/king.py
  gammapy/irf/psf/psf_map.py
  gammapy/irf/psf/table.py
  gammapy/irf/psf/tests/test_psf_gauss.py
  gammapy/irf/psf/tests/test_psf_king.py
  gammapy/irf/psf/tests/test_psf_map.py
  gammapy/irf/psf/tests/test_psf_table.py
  gammapy/irf/tests/test_background.py
  gammapy/irf/tests/test_edisp_map.py
  gammapy/irf/tests/test_effective_area.py
  gammapy/irf/tests/test_energy_dispersion.py
  gammapy/irf/tests/test_io.py
  gammapy/makers/safe.py
  gammapy/makers/spectrum.py
  gammapy/makers/tests/test_spectrum.py
  gammapy/makers/tests/test_utils.py
  gammapy/makers/utils.py
  gammapy/maps/core.py
  gammapy/maps/geom.py
  gammapy/maps/regionnd.py
  gammapy/utils/__init__.py
  gammapy/utils/nddata.py
  gammapy/utils/tests/test_nddata.py
Labels: cleanup

#3190 Correct WcsNDMap full sky plot
  gammapy/maps/tests/test_wcsnd.py
  gammapy/maps/wcsnd.py
Labels: bug

#3166 Unify npred background handling in dataset methods
  gammapy/datasets/core.py
  gammapy/datasets/map.py
  gammapy/datasets/tests/test_spectrum.py
  gammapy/estimators/asmooth_map.py
  gammapy/estimators/flux.py
  gammapy/estimators/tests/test_flux.py
  gammapy/estimators/tests/test_flux_point_estimator.py
  gammapy/makers/background/fov.py
  gammapy/modeling/models/core.py
  gammapy/modeling/models/cube.py
  gammapy/modeling/models/tests/test_management.py
Labels: cleanup

#3194 Add a how-to for memory issues caused by large datasets.
  docs/howto.rst
Labels: docs

#3191 Remove code duplication between SpectrumDatasetMaker and MapDatasetMaker
  gammapy/analysis/tests/test_analysis.py
  gammapy/datasets/tests/test_map.py
  gammapy/irf/edisp_kernel.py
  gammapy/makers/map.py
  gammapy/makers/safe.py
  gammapy/makers/spectrum.py
  gammapy/makers/tests/test_spectrum.py
  gammapy/makers/utils.py
  gammapy/maps/core.py
  gammapy/maps/utils.py
  gammapy/maps/wcsmap.py
Labels: cleanup

#3188 Fix deprecation warnings
  gammapy/conftest.py
  gammapy/data/data_store.py
  gammapy/data/gti.py
  gammapy/data/tests/test_data_store.py
  gammapy/modeling/models/spatial.py
  gammapy/modeling/models/spectral.py
Labels: cleanup

#3199 Enable tests of code in RST files and in docstrings of Python scripts
  .github/workflows/ci.yml
  docs/astro/index.rst
  docs/astro/population/index.rst
  docs/conf.py
  docs/data/index.rst
  docs/development/howto.rst
  docs/getting-started.rst
  docs/howto.rst
  docs/maps/hpxmap.rst
  docs/maps/index.rst
  docs/maps/regionmap.rst
  docs/scripts/index.rst
  docs/stats/index.rst
  docs/tutorials/background_model.ipynb
  docs/tutorials/ring_background.ipynb
  docs/utils/index.rst
  environment-dev.yml
  gammapy/catalog/gammacat.py
  gammapy/catalog/hess.py
  gammapy/data/data_store.py
  gammapy/data/event_list.py
  gammapy/data/obs_table.py
  gammapy/data/pointing.py
  gammapy/estimators/flux_point.py
  gammapy/irf/background.py
  gammapy/irf/edisp_kernel.py
  gammapy/irf/effective_area.py
  gammapy/irf/energy_dispersion.py
  gammapy/irf/io.py
  gammapy/makers/background/reflected.py
  gammapy/modeling/models/core.py
  gammapy/modeling/models/spectral_crab.py
  gammapy/modeling/models/temporal.py
  gammapy/utils/random/utils.py
  setup.cfg
Labels: cleanup, docs

#3200 Small modifs in documentation structure
  docs/_static/gammapy.js
  docs/index.rst
Labels: docs, feature

#3197 Introduce PSF and ParametricPSF base classes
  docs/tutorials/cta_sensitivity.ipynb
  gammapy/data/observations.py
  gammapy/datasets/map.py
  gammapy/datasets/tests/test_map.py
  gammapy/irf/core.py
  gammapy/irf/io.py
  gammapy/irf/psf/__init__.py
  gammapy/irf/psf/core.py
  gammapy/irf/psf/gauss.py
  gammapy/irf/psf/king.py
  gammapy/irf/psf/parametric.py
  gammapy/irf/psf/psf_map.py
  gammapy/irf/psf/table.py
  gammapy/irf/psf/tests/data/psf_info.txt
  gammapy/irf/psf/tests/test_parametric.py
  gammapy/irf/psf/tests/test_psf_gauss.py
  gammapy/irf/psf/tests/test_psf_king.py
  gammapy/irf/psf/tests/test_psf_map.py
  gammapy/irf/psf/tests/test_psf_table.py
  gammapy/irf/tests/test_io.py
  gammapy/makers/map.py
  gammapy/makers/spectrum.py
  gammapy/maps/tests/test_wcsnd.py
  gammapy/modeling/models/spatial.py
  gammapy/utils/gauss.py
  gammapy/utils/interpolation.py
  gammapy/utils/tests/test_gauss.py
Labels: cleanup

#3201 Remove TablePSF
  docs/tutorials/fermi_lat.ipynb
  gammapy/datasets/tests/test_map.py
  gammapy/estimators/ts_map.py
  gammapy/irf/psf/kernel.py
  gammapy/irf/psf/psf_map.py
  gammapy/irf/psf/table.py
  gammapy/irf/psf/tests/test_parametric.py
  gammapy/irf/psf/tests/test_psf_kernel.py
  gammapy/irf/psf/tests/test_psf_map.py
  gammapy/irf/psf/tests/test_psf_table.py
  gammapy/maps/wcs.py
  gammapy/modeling/models/spatial.py
  gammapy/modeling/models/tests/test_cube.py
Labels: cleanup

#3204 Select nearest well-defined irf for sources outside geom
  gammapy/datasets/map.py
  gammapy/datasets/simulate.py
  gammapy/datasets/tests/test_map.py
  gammapy/estimators/ts_map.py
Labels: bug

#3206 Adapt label in peek()
  gammapy/irf/background.py
Labels: bug

#3203 Use caplog in FoVBackgroundMaker tests
  gammapy/makers/background/fov.py
  gammapy/makers/background/tests/test_fov.py
Labels: cleanup

#3196 Updated documentation for makers and background
  docs/makers/fov.rst
  docs/makers/index.rst
  docs/makers/make_rectangular_reflected_background.py
  docs/makers/reflected.rst
  docs/makers/ring.rst
Labels: docs

#3169 Add .select_region() and .select_mask() methods to Models
  gammapy/datasets/map.py
  gammapy/datasets/simulate.py
  gammapy/estimators/ts_map.py
  gammapy/maps/core.py
  gammapy/maps/tests/test_wcsnd.py
  gammapy/maps/wcs.py
  gammapy/maps/wcsnd.py
  gammapy/modeling/models/core.py
  gammapy/modeling/models/cube.py
  gammapy/modeling/models/spatial.py
  gammapy/modeling/models/tests/test_management.py
Labels: feature

#3202 Add an option to the SpectrumDatasetMaker to average IRFs over a Region
  gammapy/makers/map.py
  gammapy/makers/spectrum.py
  gammapy/makers/tests/test_spectrum.py
  gammapy/makers/utils.py
  gammapy/maps/region.py
  gammapy/maps/tests/test_region.py
  gammapy/maps/wcs.py
Labels: feature

#3153 Refactor gammapy download
  .github/workflows/ci.yml
  .gitignore
  Makefile
  docs/_downloads/notebooks-dev.tar
  docs/development/howto.rst
  docs/development/release.rst
  docs/howto.rst
  docs/install/dependencies.rst
  docs/install/index.rst
  docs/references.txt
  environment-dev.yml
  examples/README.rst
  gammapy/analysis/core.py
  gammapy/scripts/download.py
  gammapy/scripts/downloadclasses.py
  gammapy/scripts/info.py
  gammapy/scripts/jupyter.py
  gammapy/scripts/main.py
  gammapy/scripts/tests/test_download.py
  gammapy/utils/notebooks_process.py
  gammapy/utils/notebooks_test.py
  gammapy/utils/scripts.py
  gammapy/utils/scripts_test.py
  gammapy/utils/tests/test_scripts.py
Labels: cleanup
