Repository gammapy/gammapy, pull requests merged in 2021-07, with the labels that each got.

#3402 Change `energy_range` to `energy_bounds` in `SpectralModel.plot()`
  docs/tutorials/analysis/1D/sed_fitting.ipynb
  docs/tutorials/analysis/1D/spectral_analysis.ipynb
  docs/tutorials/analysis/3D/analysis_3d.ipynb
  docs/tutorials/analysis/3D/analysis_mwl.ipynb
  docs/tutorials/analysis/3D/mcmc_sampling.ipynb
  docs/tutorials/analysis/time/pulsar_analysis.ipynb
  docs/tutorials/api/astro_dark_matter.ipynb
  docs/tutorials/api/catalog.ipynb
  docs/tutorials/api/fitting.ipynb
  docs/tutorials/api/models.ipynb
  docs/tutorials/data/fermi_lat.ipynb
  docs/tutorials/starting/analysis_2.ipynb
  docs/tutorials/starting/overview.ipynb
  examples/models/spectral/plot_absorbed.py
  examples/models/spectral/plot_broken_powerlaw.py
  examples/models/spectral/plot_compound.py
  examples/models/spectral/plot_constant_spectral.py
  examples/models/spectral/plot_exp_cutoff_powerlaw.py
  examples/models/spectral/plot_exp_cutoff_powerlaw_3fgl.py
  examples/models/spectral/plot_gauss_spectral.py
  examples/models/spectral/plot_logparabola.py
  examples/models/spectral/plot_naima.py
  examples/models/spectral/plot_piecewise_norm_spectral.py
  examples/models/spectral/plot_powerlaw.py
  examples/models/spectral/plot_powerlaw2.py
  examples/models/spectral/plot_smooth_broken_powerlaw.py
  examples/models/spectral/plot_super_exp_cutoff_powerlaw_3fgl.py
  examples/models/spectral/plot_super_exp_cutoff_powerlaw_4fgl.py
  examples/models/spectral/plot_template_spectral.py
  gammapy/datasets/flux_points.py
  gammapy/modeling/models/spectral.py
  gammapy/modeling/models/tests/test_spectral.py
Labels: cleanup

#3405 Improve mask_fit handling in analysis_3d notebook
  docs/tutorials/analysis/3D/analysis_3d.ipynb
Labels: cleanup, docs

#3404 Add is_pointlike property on irfs
  gammapy/irf/core.py
  gammapy/irf/tests/test_effective_area.py
  gammapy/irf/tests/test_energy_dispersion.py
  gammapy/makers/map.py
  gammapy/makers/spectrum.py
  gammapy/makers/tests/test_spectrum.py
  gammapy/makers/utils.py
Labels: feature

#3403 Add sparse option to get_coord() methods
  gammapy/datasets/tests/test_map.py
  gammapy/irf/edisp_map.py
  gammapy/irf/effective_area.py
  gammapy/irf/energy_dispersion.py
  gammapy/irf/psf/kernel.py
  gammapy/irf/psf/psf_map.py
  gammapy/irf/tests/test_energy_dispersion.py
  gammapy/makers/utils.py
  gammapy/maps/geom.py
  gammapy/maps/hpx.py
  gammapy/maps/region.py
  gammapy/maps/tests/test_region.py
  gammapy/maps/wcs.py
  gammapy/maps/wcsnd.py
  gammapy/modeling/models/cube.py
  gammapy/modeling/models/spatial.py
Labels: cleanup

#3406 Add scan specification to the Parameter object
  docs/tutorials/api/fitting.ipynb
  gammapy/datasets/tests/test_flux_points.py
  gammapy/datasets/tests/test_spectrum.py
  gammapy/estimators/flux.py
  gammapy/estimators/parameter.py
  gammapy/estimators/tests/test_parameter_estimator.py
  gammapy/modeling/fit.py
  gammapy/modeling/parameter.py
  gammapy/modeling/tests/test_fit.py
  gammapy/modeling/tests/test_parameter.py
Labels: cleanup, feature

#3408 Return optimize_results and covariance_results in Fit.run()
  docs/tutorials/analysis/1D/extended_source_spectral_analysis.ipynb
  docs/tutorials/analysis/1D/spectral_analysis.ipynb
  docs/tutorials/analysis/3D/analysis_3d.ipynb
  docs/tutorials/analysis/3D/event_sampling.ipynb
  docs/tutorials/analysis/3D/simulate_3d.ipynb
  docs/tutorials/analysis/time/light_curve_simulation.ipynb
  docs/tutorials/api/fitting.ipynb
  docs/tutorials/starting/analysis_2.ipynb
  gammapy/analysis/core.py
  gammapy/datasets/flux_points.py
  gammapy/datasets/tests/test_flux_points.py
  gammapy/datasets/tests/test_map.py
  gammapy/datasets/tests/test_spectrum.py
  gammapy/estimators/parameter.py
  gammapy/makers/background/fov.py
  gammapy/modeling/fit.py
  gammapy/modeling/tests/test_fit.py
Labels: bug, cleanup

#3411 Introduce edisp irf subfolder
  gammapy/irf/__init__.py
  gammapy/irf/edisp/__init__.py
  gammapy/irf/edisp/core.py
  gammapy/irf/edisp/kernel.py
  gammapy/irf/edisp/map.py
  gammapy/irf/edisp/tests/__init__.py
  gammapy/irf/edisp/tests/test_core.py
  gammapy/irf/edisp/tests/test_kernel.py
  gammapy/irf/edisp/tests/test_map.py
  gammapy/irf/io.py
  gammapy/irf/psf/__init__.py
  gammapy/irf/psf/core.py
  gammapy/irf/psf/map.py
  gammapy/irf/psf/tests/test_kernel.py
  gammapy/irf/psf/tests/test_map.py
  gammapy/irf/psf/tests/test_table.py
  gammapy/irf/tests/test_effective_area.py
Labels: cleanup

#3412 Change definition of disk edge parameter
  examples/models/spatial/plot_disk.py
  gammapy/irf/psf/tests/test_kernel.py
  gammapy/modeling/models/spatial.py
  gammapy/modeling/models/tests/test_spatial.py
  gammapy/modeling/parameter.py
Labels: cleanup

#3415 Improve mask fit documentation
  docs/tutorials/api/mask_maps.ipynb
  gammapy/datasets/map.py
Labels: docs

#3393 Implement TimeMapAxis class
  gammapy/maps/__init__.py
  gammapy/maps/axes.py
  gammapy/maps/tests/test_axes.py
Labels: feature

#3421 Move MapAxes and MapAxis classes to axes.py
  gammapy/maps/axes.py
  gammapy/maps/core.py
  gammapy/maps/geom.py
  gammapy/maps/hpx.py
  gammapy/maps/region.py
  gammapy/maps/wcs.py
Labels: cleanup

#3416 Mask invalid background values in SafeMaskMaker
  gammapy/makers/safe.py
  gammapy/makers/tests/test_safe.py
Labels: bug, feature

#3425 Clean-up of how-to's
  docs/howto.rst
Labels: cleanup, docs

#3422 Implement HpxNDMap.to_nside()
  gammapy/maps/hpxnd.py
  gammapy/maps/tests/test_hpxnd.py
Labels: feature

#3413 Introduce inheritance for Estimator classes
  gammapy/datasets/map.py
  gammapy/estimators/core.py
  gammapy/estimators/excess_map.py
  gammapy/estimators/flux.py
  gammapy/estimators/flux_point.py
  gammapy/estimators/lightcurve.py
  gammapy/estimators/parameter.py
  gammapy/estimators/tests/test_flux.py
  gammapy/estimators/tests/test_lightcurve.py
Labels: cleanup

#3426 Cleanup reflected regions finder
  docs/makers/make_reflected_regions.py
  docs/maps/regionmap.rst
  docs/stats/index.rst
  docs/tutorials/api/makers.ipynb
  gammapy/analysis/core.py
  gammapy/datasets/tests/test_map.py
  gammapy/irf/psf/map.py
  gammapy/makers/background/reflected.py
  gammapy/makers/background/tests/test_reflected.py
  gammapy/maps/core.py
  gammapy/maps/tests/test_region.py
Labels: cleanup

#3429 Remove MCMC sampling code
  docs/tutorials/analysis/3D/mcmc_sampling.ipynb
  gammapy/modeling/__init__.py
  gammapy/modeling/sampling.py
  gammapy/modeling/tests/test_sampling.py
Labels: cleanup

#3428 Support serialisation of TimeMapAxis
  gammapy/estimators/lightcurve.py
  gammapy/maps/axes.py
  gammapy/maps/region.py
  gammapy/maps/tests/test_axes.py
  gammapy/maps/tests/test_base.py
Labels: feature

#3418 Refactor FluxPoints to rely on maps internally
  docs/estimators/index.rst
  docs/tutorials/analysis/1D/sed_fitting.ipynb
  docs/tutorials/analysis/1D/spectral_analysis.ipynb
  docs/tutorials/analysis/3D/analysis_mwl.ipynb
  docs/tutorials/analysis/3D/cta_data_analysis.ipynb
  docs/tutorials/analysis/time/pulsar_analysis.ipynb
  docs/tutorials/api/catalog.ipynb
  docs/tutorials/starting/overview.ipynb
  gammapy/analysis/core.py
  gammapy/analysis/tests/test_analysis.py
  gammapy/catalog/tests/test_fermi.py
  gammapy/catalog/tests/test_gammacat.py
  gammapy/datasets/flux_points.py
  gammapy/datasets/tests/test_flux_points.py
  gammapy/estimators/core.py
  gammapy/estimators/flux_map.py
  gammapy/estimators/flux_point.py
  gammapy/estimators/lightcurve.py
  gammapy/estimators/tests/test_core.py
  gammapy/estimators/tests/test_flux_map.py
  gammapy/estimators/tests/test_flux_point.py
  gammapy/estimators/tests/test_flux_point_estimator.py
  gammapy/estimators/tests/test_lightcurve.py
  gammapy/estimators/ts_map.py
  gammapy/irf/background.py
  gammapy/irf/core.py
  gammapy/maps/axes.py
  gammapy/maps/maps.py
  gammapy/maps/region.py
  gammapy/maps/regionnd.py
  gammapy/modeling/models/spectral.py
  gammapy/modeling/models/tests/test_spectral.py
  gammapy/utils/table.py
Labels: cleanup

#3432 Remove FluxEstimate class
  gammapy/data/observations.py
  gammapy/estimators/core.py
  gammapy/estimators/flux.py
  gammapy/estimators/flux_map.py
  gammapy/estimators/flux_point.py
  gammapy/estimators/tests/test_core.py
  gammapy/estimators/tests/test_flux_map.py
  gammapy/maps/axes.py
  gammapy/maps/maps.py
  gammapy/maps/tests/test_maps.py
  gammapy/modeling/models/spectral.py
  gammapy/modeling/scipy.py
Labels: cleanup

#3433 Minor Estimator cleanup
  gammapy/datasets/core.py
  gammapy/estimators/flux.py
  gammapy/estimators/flux_point.py
  gammapy/estimators/lightcurve.py
  gammapy/estimators/parameter.py
  gammapy/estimators/tests/test_flux.py
  gammapy/modeling/models/spectral.py
Labels: cleanup

#3434 Time axis plotting
  gammapy/maps/axes.py
  gammapy/maps/core.py
  gammapy/maps/regionnd.py
  gammapy/maps/tests/test_regionnd.py
Labels: feature

#3435 Generalise Map.from_images
  gammapy/estimators/asmooth_map.py
  gammapy/estimators/ts_map.py
  gammapy/maps/core.py
Labels: feature

#3436 Cleanup plot_ts_profiles a bit
  gammapy/estimators/flux_point.py
  gammapy/maps/regionnd.py
Labels: cleanup

#3420 Disable IRF extrapolation
  docs/development/howto.rst
  gammapy/datasets/map.py
  gammapy/datasets/simulate.py
  gammapy/irf/background.py
  gammapy/irf/core.py
  gammapy/irf/edisp/core.py
  gammapy/irf/psf/tests/test_map.py
  gammapy/irf/tests/test_background.py
  gammapy/makers/tests/test_safe.py
  gammapy/makers/tests/test_spectrum.py
  gammapy/makers/tests/test_utils.py
  gammapy/stats/fit_statistics.py
Labels: cleanup

#3439 Allow to choose scaling method per parameter
  gammapy/modeling/fit.py
  gammapy/modeling/models/spectral.py
  gammapy/modeling/parameter.py
  gammapy/modeling/tests/test_fit.py
  gammapy/modeling/tests/test_parameter.py
Labels: cleanup, feature

#3442 Fix region geom width computation
  docs/development/howto.rst
  gammapy/catalog/core.py
  gammapy/catalog/fermi.py
  gammapy/catalog/gammacat.py
  gammapy/catalog/tests/data/2fhl_j0822.6-4250e.txt
  gammapy/catalog/tests/data/2fhl_j1445.1-0329.txt
  gammapy/catalog/tests/data/3fhl_j2301.9+5855e.txt
  gammapy/catalog/tests/data/4fgl_J0002.8+6217.txt
  gammapy/catalog/tests/data/4fgl_J1409.1-6121e.txt
  gammapy/catalog/tests/data/gammacat_hess_j1813-178.txt
  gammapy/catalog/tests/data/gammacat_hess_j1848-018.txt
  gammapy/catalog/tests/data/gammacat_vela_x.txt
  gammapy/catalog/tests/data/hess_j1713-397.txt
  gammapy/catalog/tests/data/hess_j1825-137.txt
  gammapy/catalog/tests/data/hess_j1930+188.txt
  gammapy/catalog/tests/test_fermi.py
  gammapy/catalog/tests/test_gammacat.py
  gammapy/irf/edisp/tests/test_map.py
  gammapy/makers/background/reflected.py
  gammapy/maps/region.py
  gammapy/utils/regions.py
  gammapy/utils/tests/test_regions.py
Labels: bug, cleanup

#3443 Fix doctest errors
  docs/development/howto.rst
  docs/development/pigs/pig-010.rst
  docs/maps/regionmap.rst
  gammapy/catalog/hess.py
  gammapy/makers/background/reflected.py
  gammapy/utils/regions.py
Labels: tests

#3438 Unify plot unit handling
  docs/howto.rst
  docs/tutorials/analysis/1D/sed_fitting.ipynb
  docs/tutorials/analysis/1D/spectral_analysis.ipynb
  docs/tutorials/api/astro_dark_matter.ipynb
  docs/tutorials/api/catalog.ipynb
  docs/tutorials/data/fermi_lat.ipynb
  examples/models/spectral/plot_absorbed.py
  examples/models/spectral/plot_naima.py
  examples/models/spectral/plot_piecewise_norm_spectral.py
  gammapy/data/event_list.py
  gammapy/estimators/flux_map.py
  gammapy/estimators/flux_point.py
  gammapy/irf/background.py
  gammapy/irf/edisp/core.py
  gammapy/irf/edisp/kernel.py
  gammapy/irf/effective_area.py
  gammapy/irf/psf/core.py
  gammapy/irf/psf/map.py
  gammapy/modeling/models/spectral.py
  gammapy/modeling/models/tests/test_spectral.py
Labels: cleanup

#3444 Clean up region nd map plotting and adapt flux points plotting
  gammapy/catalog/gammacat.py
  gammapy/catalog/hess.py
  gammapy/datasets/flux_points.py
  gammapy/datasets/map.py
  gammapy/datasets/spectrum.py
  gammapy/estimators/flux_point.py
  gammapy/maps/regionnd.py
  gammapy/modeling/models/spectral.py
Labels: cleanup

#3445 Use FluxPoints object in LightcurveEstimator
  docs/tutorials/analysis/3D/analysis_mwl.ipynb
  docs/tutorials/analysis/time/light_curve.ipynb
  docs/tutorials/analysis/time/light_curve_simulation.ipynb
  gammapy/analysis/core.py
  gammapy/analysis/tests/test_analysis.py
  gammapy/data/gti.py
  gammapy/datasets/core.py
  gammapy/datasets/flux_points.py
  gammapy/estimators/flux_map.py
  gammapy/estimators/flux_point.py
  gammapy/estimators/lightcurve.py
  gammapy/estimators/tests/test_flux_point_estimator.py
  gammapy/estimators/tests/test_lightcurve.py
  gammapy/maps/regionnd.py
Labels: cleanup, feature

#3446 corrected axis label units for PSF containment radius
  gammapy/irf/psf/core.py
Labels: bug
