Repository gammapy/gammapy, pull requests merged in 2021-06, with the labels that each got.

#3343 Display progress bar in gammapy
  gammapy/analysis/core.py
  gammapy/estimators/asmooth_map.py
  gammapy/estimators/flux_point.py
  gammapy/estimators/lightcurve.py
  gammapy/estimators/ts_map.py
  gammapy/modeling/fit.py
  gammapy/utils/pbar.py
Labels: feature

#3380 Fix the source position and add the exclusion region
  docs/tutorials/starting/analysis_1.ipynb
Labels: bug, effort-low

#3379 Use find_roots to call root finding methods
  docs/tutorials/starting/analysis_2.ipynb
  gammapy/estimators/tests/test_utils.py
  gammapy/estimators/ts_map.py
  gammapy/estimators/utils.py
  gammapy/irf/edisp_kernel.py
  gammapy/makers/safe.py
  gammapy/makers/tests/test_safe.py
  gammapy/makers/tests/test_spectrum.py
  gammapy/modeling/models/spectral.py
  gammapy/modeling/models/tests/test_spectral.py
  gammapy/modeling/scipy.py
  gammapy/stats/counts_statistic.py
  gammapy/utils/gauss.py
  gammapy/utils/roots.py
  gammapy/utils/scripts.py
  gammapy/utils/tests/test_roots.py
Labels: bug, cleanup

#3390 Fix parameter type for PiecewiseNormSpectralModel and NaimaSpectralModel
  gammapy/modeling/models/core.py
  gammapy/modeling/models/tests/test_spectral.py
Labels: bug

#3389 Remove find_roots from TSMapEstimator for performance
  gammapy/estimators/tests/test_ts_map.py
  gammapy/estimators/ts_map.py
Labels: cleanup

#3371 Add plot_mask to HpxNDMap
  gammapy/maps/hpxnd.py
  gammapy/maps/tests/test_hpxnd.py
Labels: feature

#3364 Introduce a Maps container
  gammapy/maps/__init__.py
  gammapy/maps/maps.py
  gammapy/maps/tests/test_maps.py
Labels: feature

#3391 Improve documentation in gammapy.data and gammapy.irf
  docs/data/index.rst
  docs/irf/edisp.rst
  docs/irf/psf.rst
  docs/maps/hpxmap.rst
Labels: docs

#3372 Remove datasets argument from Fit.__init__
  docs/tutorials/analysis/1D/extended_source_spectral_analysis.ipynb
  docs/tutorials/analysis/1D/sed_fitting.ipynb
  docs/tutorials/analysis/1D/spectral_analysis.ipynb
  docs/tutorials/analysis/1D/spectrum_simulation.ipynb
  docs/tutorials/analysis/3D/analysis_3d.ipynb
  docs/tutorials/analysis/3D/analysis_mwl.ipynb
  docs/tutorials/analysis/3D/cta_data_analysis.ipynb
  docs/tutorials/analysis/3D/event_sampling.ipynb
  docs/tutorials/analysis/3D/simulate_3d.ipynb
  docs/tutorials/analysis/time/light_curve.ipynb
  docs/tutorials/analysis/time/light_curve_simulation.ipynb
  docs/tutorials/analysis/time/pulsar_analysis.ipynb
  docs/tutorials/api/fitting.ipynb
  docs/tutorials/api/model_management.ipynb
  docs/tutorials/api/models.ipynb
  docs/tutorials/data/fermi_lat.ipynb
  docs/tutorials/starting/analysis_2.ipynb
  gammapy/analysis/core.py
  gammapy/datasets/tests/test_flux_points.py
  gammapy/datasets/tests/test_map.py
  gammapy/datasets/tests/test_spectrum.py
  gammapy/estimators/flux.py
  gammapy/estimators/flux_point.py
  gammapy/estimators/lightcurve.py
  gammapy/estimators/parameter.py
  gammapy/estimators/tests/test_flux.py
  gammapy/estimators/tests/test_flux_point_estimator.py
  gammapy/estimators/tests/test_lightcurve.py
  gammapy/estimators/tests/test_parameter_estimator.py
  gammapy/makers/background/fov.py
  gammapy/modeling/fit.py
  gammapy/modeling/tests/test_fit.py
Labels: cleanup

#3396 Fix stacking of cutouts
  gammapy/maps/tests/test_wcs.py
  gammapy/maps/tests/test_wcsnd.py
  gammapy/maps/wcs.py
  gammapy/maps/wcsnd.py
Labels: bug

#3392 Implement padding for TSMapEstimator
  gammapy/estimators/asmooth_map.py
  gammapy/estimators/core.py
  gammapy/estimators/excess_map.py
  gammapy/estimators/flux_map.py
  gammapy/estimators/tests/test_ts_map.py
  gammapy/estimators/ts_map.py
  gammapy/maps/core.py
  gammapy/maps/geom.py
  gammapy/maps/wcsnd.py
Labels: cleanup, feature

#3397 Use string for model name in npred_signal()
  gammapy/datasets/map.py
  gammapy/datasets/tests/test_map.py
  gammapy/datasets/tests/test_spectrum.py
Labels: cleanup

#3395 Remove counts data caching from MapDataset
  gammapy/datasets/map.py
Labels: bug

#3401 Use dataset._geom in SafeMaskMaker
  gammapy/makers/safe.py
Labels: cleanup

#3399 Implement WcsGeom.from_aligned
  gammapy/maps/tests/test_wcs.py
  gammapy/maps/wcs.py
Labels: feature

#3400 Add containment option to PSFMap.get_psf_kernel()
  gammapy/datasets/map.py
  gammapy/estimators/tests/test_excess_map.py
  gammapy/estimators/tests/test_flux.py
  gammapy/estimators/tests/test_ts_map.py
  gammapy/irf/psf/psf_map.py
  gammapy/irf/psf/tests/test_psf_map.py
Labels: feature

#3383 Change default correlate_off to True for ExcessMapEstimator
  gammapy/estimators/excess_map.py
  gammapy/estimators/tests/test_excess_map.py
Labels: bug

#3394 Further cleanup Fit class
  docs/tutorials/api/fitting.ipynb
  gammapy/datasets/tests/test_flux_points.py
  gammapy/makers/background/tests/test_fov.py
  gammapy/modeling/fit.py
  gammapy/modeling/iminuit.py
  gammapy/modeling/tests/test_fit.py
  gammapy/modeling/tests/test_iminuit.py
Labels: cleanup

#3366 Change default kernel_size to None in TSMapEstimator
  gammapy/datasets/map.py
  gammapy/estimators/tests/test_ts_map.py
  gammapy/estimators/ts_map.py
  gammapy/maps/wcs.py
  gammapy/maps/wcsnd.py
Labels: bug
