Repository gammapy/gammapy, pull requests merged in 2021-02, with the labels that each got.

#3211 Refactor notebooks processing
  Makefile
  README.rst
  docs/development/howto.rst
  docs/development/index.rst
  docs/development/intro.rst
  docs/development/release.rst
  docs/development/setup.rst
  docs/estimators/index.rst
  gammapy/scripts/jupyter.py
  gammapy/utils/notebooks_links.py
  gammapy/utils/notebooks_process.py
  gammapy/utils/notebooks_test.py
  notebooks.yaml
  setup.cfg
Labels: cleanup

#3214 Add entry for test coverage in developer documentation
  docs/development/setup.rst
Labels: docs

#3207 Remove EnergyDependentTablePSF
  docs/development/dataformats.rst
  docs/irf/plot_fermi_psf.py
  docs/irf/plot_psf_table.py
  docs/irf/psf.rst
  docs/tutorials/cta.ipynb
  docs/tutorials/detect.ipynb
  docs/tutorials/fermi_lat.ipynb
  gammapy/analysis/tests/test_analysis.py
  gammapy/data/observations.py
  gammapy/datasets/map.py
  gammapy/datasets/tests/test_map.py
  gammapy/estimators/tests/test_ts_map.py
  gammapy/irf/core.py
  gammapy/irf/psf/core.py
  gammapy/irf/psf/kernel.py
  gammapy/irf/psf/psf_map.py
  gammapy/irf/psf/table.py
  gammapy/irf/psf/tests/test_parametric.py
  gammapy/irf/psf/tests/test_psf_map.py
  gammapy/irf/psf/tests/test_psf_table.py
  gammapy/makers/tests/test_map.py
  gammapy/makers/tests/test_utils.py
  gammapy/maps/core.py
  gammapy/maps/geom.py
  gammapy/maps/region.py
  gammapy/maps/regionnd.py
  gammapy/maps/tests/test_wcsnd.py
  gammapy/maps/wcs.py
  gammapy/maps/wcsnd.py
Labels: cleanup

#3210 Improve models tutorial
  docs/tutorials/models.ipynb
  gammapy/modeling/models/spatial.py
Labels: docs

#3217 Make `is_norm_spectral_model` as classproperty
  docs/tutorials/models.ipynb
  gammapy/modeling/models/spectral.py
Labels: cleanup

#3215 Further improve model region / mask selection
  gammapy/datasets/map.py
  gammapy/datasets/simulate.py
  gammapy/estimators/ts_map.py
  gammapy/irf/core.py
  gammapy/irf/edisp_map.py
  gammapy/irf/psf/psf_map.py
  gammapy/maps/core.py
  gammapy/maps/region.py
  gammapy/maps/wcsnd.py
  gammapy/modeling/models/core.py
  gammapy/modeling/models/cube.py
  gammapy/modeling/models/tests/test_management.py
  gammapy/utils/regions.py
  gammapy/utils/tests/test_regions.py
Labels: cleanup, feature

#3222 Add alternative parametrization for ShellSpatialModel
  examples/models/spatial/plot_gen_gauss.py
  examples/models/spatial/plot_shell2.py
  gammapy/modeling/models/__init__.py
  gammapy/modeling/models/spatial.py
  gammapy/modeling/models/tests/test_spatial.py
  gammapy/utils/regions.py
Labels: feature

#3223 Add info in developers HowTo docs
  docs/development/dataformats.rst
  docs/development/howto.rst
  docs/development/index.rst
  docs/development/setup.rst
  docs/install/index.rst
  examples/scripts.yaml
  gammapy/analysis/core.py
Labels: docs

#3224 Unify handling of list of regions
  docs/tutorials/analysis_2.ipynb
  docs/tutorials/cta_data_analysis.ipynb
  docs/tutorials/exclusion_mask.ipynb
  docs/tutorials/ring_background.ipynb
  docs/tutorials/spectrum_analysis.ipynb
  gammapy/analysis/tests/test_analysis.py
  gammapy/data/event_list.py
  gammapy/data/tests/test_event_list.py
  gammapy/data/tests/test_filters.py
  gammapy/makers/background/reflected.py
  gammapy/makers/background/tests/test_fov.py
  gammapy/makers/background/tests/test_reflected.py
  gammapy/makers/background/tests/test_ring.py
  gammapy/makers/tests/test_spectrum.py
  gammapy/maps/region.py
  gammapy/maps/tests/test_wcs.py
  gammapy/maps/wcs.py
  gammapy/maps/wcsnd.py
  gammapy/modeling/models/core.py
  gammapy/utils/regions.py
Labels: cleanup

#3227 Add method on geom to evaluate memory usage
  gammapy/maps/geom.py
  gammapy/maps/tests/test_wcsnd.py
Labels: feature

#3228 Remove EffectiveAreaTable class
  docs/irf/aeff.rst
  docs/irf/plot_aeff_param.py
  docs/irf/plot_aeff_table.py
  gammapy/datasets/tests/test_spectrum.py
  gammapy/estimators/tests/test_flux_point_estimator.py
  gammapy/irf/effective_area.py
  gammapy/irf/tests/test_effective_area.py
  gammapy/makers/safe.py
  gammapy/makers/spectrum.py
  gammapy/maps/geom.py
  gammapy/modeling/models/spectral.py
Labels: cleanup

#3232 added caplog in test_spectral 10 02
  gammapy/modeling/models/tests/test_spatial.py
  gammapy/modeling/models/tests/test_spectral.py
Labels: tests

#3205 Adapt Datastore to not include runs with missing IRFs
  gammapy/data/data_store.py
  gammapy/data/tests/test_data_store.py
Labels: feature

#3233 added caplog for test_fit 10 02
  gammapy/modeling/tests/test_fit.py
Labels: tests

#3236 Caplogtest parameter
  gammapy/modeling/tests/test_parameter.py
Labels: tests

#3235 Add regression tests for background with missing HDUCLAS keyword
  gammapy/irf/background.py
  gammapy/irf/core.py
  gammapy/irf/tests/test_background.py
Labels: feature

#3230 Expand extended source analysis tutorial
  docs/tutorials/extended_source_spectral_analysis.ipynb
  gammapy/datasets/map.py
  gammapy/datasets/tests/test_map.py
  gammapy/makers/tests/test_spectrum.py
  gammapy/maps/region.py
  gammapy/maps/regionnd.py
  gammapy/maps/tests/test_region.py
  gammapy/maps/tests/test_regionnd.py
  gammapy/modeling/models/spectral.py
  gammapy/modeling/models/tests/test_cube.py
  gammapy/modeling/models/tests/test_spatial.py
Labels: docs

#3238 Unify integration in EDispMap.get_edisp_kernel() and EnergyDispersion2D.get_edisp_kernel()
  gammapy/irf/core.py
  gammapy/irf/edisp_map.py
  gammapy/irf/energy_dispersion.py
  gammapy/irf/psf/core.py
  gammapy/irf/psf/psf_map.py
  gammapy/irf/psf/tests/test_psf_map.py
  gammapy/irf/tests/test_energy_dispersion.py
  gammapy/makers/utils.py
  gammapy/maps/core.py
  gammapy/maps/geom.py
Labels: cleanup

#3075 Proposal for addition of a FluxMap container
  gammapy/datasets/core.py
  gammapy/estimators/__init__.py
  gammapy/estimators/core.py
  gammapy/estimators/flux_estimate.py
  gammapy/estimators/flux_map.py
  gammapy/estimators/tests/test_core.py
  gammapy/estimators/tests/test_flux_estimate.py
  gammapy/estimators/tests/test_flux_map.py
Labels: feature

#3242 Add disk edge illustration
  docs/makers/index.rst
  examples/models/spatial/plot_disk.py
Labels: docs

#3231 Introduce "gadf" format for RegionNDMap
  docs/maps/regionmap.rst
  gammapy/datasets/io.py
  gammapy/irf/core.py
  gammapy/maps/core.py
  gammapy/maps/geom.py
  gammapy/maps/region.py
  gammapy/maps/regionnd.py
  gammapy/maps/tests/test_regionnd.py
Labels: feature

#3241 Update 4FGL catalogue to DR2
  docs/tutorials/catalog.ipynb
  gammapy/catalog/fermi.py
  gammapy/catalog/hawc.py
  gammapy/catalog/tests/test_fermi.py
  gammapy/catalog/tests/test_hawc.py
  gammapy/estimators/tests/test_flux_point.py
Labels: feature

#3237 Improve spectral analysis tutorial
  docs/tutorials/spectrum_analysis.ipynb
Labels: docs

#3244 Fix evaluation radius for DiskSpatialModel and Generalized GaussianSpatialModel
  examples/models/spatial/plot_gen_gauss.py
  gammapy/modeling/models/spatial.py
  gammapy/modeling/models/tests/test_spatial.py
Labels: bug

#3243 Support I/O for RegionGeom in MapDataset
  gammapy/datasets/map.py
  gammapy/datasets/tests/test_map.py
  gammapy/irf/core.py
  gammapy/irf/edisp_map.py
  gammapy/maps/wcsnd.py
  gammapy/utils/fits.py
Labels: feature

#3245 Add how to to copy part of a datastore
  docs/howto.rst
Labels: docs

#3246 Clean up and fix WcsNDMap binary operations
  gammapy/estimators/ts_map.py
  gammapy/maps/tests/test_wcs.py
  gammapy/maps/tests/test_wcsnd.py
  gammapy/maps/wcs.py
  gammapy/maps/wcsnd.py
  gammapy/modeling/models/cube.py
  gammapy/modeling/models/tests/test_management.py
  gammapy/utils/array.py
Labels: bug, cleanup

#3250 Fix model contribution selection
  gammapy/datasets/map.py
  gammapy/datasets/tests/test_map.py
  gammapy/maps/core.py
  gammapy/maps/wcsnd.py
  gammapy/modeling/models/core.py
  gammapy/modeling/models/cube.py
  gammapy/modeling/models/tests/test_management.py
Labels: bug

#3251 Implement and clean-up IRF normalisation
  gammapy/datasets/tests/test_map.py
  gammapy/irf/core.py
  gammapy/irf/edisp_map.py
  gammapy/irf/energy_dispersion.py
  gammapy/irf/psf/core.py
  gammapy/irf/psf/psf_map.py
  gammapy/irf/psf/tests/test_psf_map.py
  gammapy/makers/tests/test_spectrum.py
  gammapy/makers/utils.py
  gammapy/maps/core.py
Labels: cleanup

#3249 Add caplog for safe mask maker tests
  gammapy/makers/tests/test_safe.py
Labels: cleanup, infrastructure
