Repository gammapy/gammapy, pull requests merged in 2021-10, with the labels that each got.

#3514 Create an Observation object from a single file
  gammapy/data/observations.py
  gammapy/data/tests/test_observations.py
  gammapy/irf/io.py
  gammapy/irf/tests/test_io.py
Labels: feature

#3528 Change tutorials to use Models.to_parameters_table() method.
  docs/tutorials/analysis/1D/extended_source_spectral_analysis.ipynb
  docs/tutorials/analysis/1D/sed_fitting.ipynb
  docs/tutorials/analysis/1D/spectral_analysis.ipynb
  docs/tutorials/analysis/2D/modeling_2D.ipynb
  docs/tutorials/analysis/3D/analysis_3d.ipynb
  docs/tutorials/starting/analysis_2.ipynb
Labels: cleanup, docs

#3519 Allow for neg. ULs in CountsStatistics
  docs/estimators/index.rst
  gammapy/stats/counts_statistic.py
  gammapy/stats/tests/test_counts_statistic.py
Labels: cleanup

#3536 Cleanup table rendering
  docs/datasets/index.rst
Labels: cleanup

#3529 Correct map evaluator to avoid memory overload
  gammapy/datasets/evaluator.py
  gammapy/datasets/tests/test_evaluator.py
  gammapy/modeling/models/spatial.py
  gammapy/modeling/models/tests/test_spatial.py
Labels: bug
