Repository gammapy/gammapy, pull requests merged in 2022-09, with the labels that each got.

#4054 Update temporal model docs
  examples/models/temporal/plot_expdecay_temporal.py
  examples/models/temporal/plot_gaussian_temporal.py
  examples/models/temporal/plot_generalized_gaussian_temporal.py
  examples/models/temporal/plot_linear_temporal.py
  examples/models/temporal/plot_powerlaw_temporal.py
  examples/models/temporal/plot_sine_temporal.py
  examples/models/temporal/plot_template_temporal.py
  gammapy/modeling/models/temporal.py
Labels: docs

#4043 Colour blind friendly visualisations
  docs/user-guide/howto.rst
Labels: feature, docs

#4064 Remove iminuit version constraint
  environment-dev.yml
  gammapy/modeling/tests/test_fit.py
  setup.cfg
Labels: infrastructure

#4058 Serialisation in the primary HDU of the Dataset name
  gammapy/datasets/map.py
  gammapy/datasets/tests/test_io.py
  gammapy/datasets/tests/test_map.py
Labels: feature

#3950 PIG 23 - Gammapy Release Cycle and Version Numbering
  docs/development/pigs/pig-023.rst
Labels: docs, pig

#4066 Solve circular import in gammapy.visualization
  gammapy/visualization/utils.py
Labels: bug

#4075 Validate nside parameter for HpxGeom
  gammapy/maps/hpx/geom.py
  gammapy/maps/hpx/tests/test_geom.py
Labels: feature

#4067 Fix bug on `TemporalModel.sample_time()`
  gammapy/datasets/tests/test_simulate.py
  gammapy/modeling/models/temporal.py
  gammapy/modeling/models/tests/test_temporal.py
Labels: bug

#4083 Implement Observation.copy() and tests
  gammapy/data/observations.py
  gammapy/data/tests/test_observations.py
Labels: feature

#4079 Update of the mailmap for the git push management
  .mailmap
Labels: infrastructure

#4085 Adapt map resampling API
  gammapy/maps/core.py
  gammapy/maps/tests/test_core.py
  gammapy/maps/wcs/ndmap.py
Labels: cleanup

#4073 Make spatial coordinates optional in RegionNDMap.interp_by_coord()
  gammapy/maps/core.py
  gammapy/maps/region/geom.py
  gammapy/maps/region/ndmap.py
  gammapy/maps/region/tests/test_ndmap.py
Labels: feature

#4024 Add HowTo for adding phase column
  docs/user-guide/howto.rst
  gammapy/data/observations.py
  gammapy/data/tests/test_observations.py
Labels: bug, docs

#4092 Correct GTI.__str__
  gammapy/data/gti.py
  gammapy/data/tests/test_gti.py
Labels: bug

#4088 Add sample_coord for RegionNDMap
  gammapy/maps/core.py
  gammapy/maps/hpx/ndmap.py
  gammapy/maps/hpx/tests/test_ndmap.py
  gammapy/maps/region/tests/test_ndmap.py
  gammapy/maps/wcs/ndmap.py
Labels: feature

#4099 Correct a HEASARC link
  gammapy/stats/fit_statistics.py
Labels: docs

#4090 Playing with the configuration parameters of the FluxPointEstimator and the LightCurveEstimator
  examples/tutorials/analysis-time/light_curve.py
  examples/tutorials/starting/analysis_1.py
Labels: docs

#4071 Add tag on DM Annihilation spectral model
  gammapy/astro/darkmatter/spectra.py
  gammapy/astro/darkmatter/tests/test_spectra.py
Labels: bug

#4076 Allow for DRIFT mode observations in the MapDatasetMaker
  gammapy/makers/map.py
  gammapy/makers/tests/test_map.py
Labels: feature

#4101 Correct CountsStatistic documentation plots
  Makefile
  docs/user-guide/stats/plot_cash_errors.py
  docs/user-guide/stats/plot_wstat_errors.py
Labels: bug, docs

#4102 Fix weights in resample
  gammapy/maps/core.py
  gammapy/maps/tests/test_core.py
Labels: bug

#4025 Add support for PSF in reco energy
  gammapy/datasets/evaluator.py
  gammapy/datasets/map.py
  gammapy/datasets/tests/test_evaluator.py
  gammapy/datasets/tests/test_map.py
  gammapy/irf/__init__.py
  gammapy/irf/core.py
  gammapy/irf/io.py
  gammapy/irf/psf/__init__.py
  gammapy/irf/psf/kernel.py
  gammapy/irf/psf/map.py
  gammapy/irf/psf/tests/test_map.py
  gammapy/makers/map.py
  gammapy/makers/utils.py
Labels: cleanup

#4104 Solve missing parenthesis in docs
  examples/models/temporal/plot_gaussian_temporal.py
Labels: docs

#4018 Computation of the WcsMap kernel at the nearest valid exposure
  gammapy/datasets/utils.py
  gammapy/estimators/map/tests/test_ts.py
  gammapy/estimators/map/ts.py
Labels: bug

#4103 Activate binder for tutorials
  Makefile
  docs/binder/requirements.txt
  docs/binder/runtime.txt
  docs/conf.py
  examples/tutorials/analysis-1d/cta_sensitivity.py
  examples/tutorials/analysis-1d/extended_source_spectral_analysis.py
  examples/tutorials/analysis-1d/sed_fitting.py
  examples/tutorials/analysis-1d/spectral_analysis.py
  examples/tutorials/analysis-1d/spectral_analysis_hli.py
  examples/tutorials/analysis-1d/spectral_analysis_rad_max.py
  examples/tutorials/analysis-1d/spectrum_simulation.py
  examples/tutorials/analysis-2d/detect.py
  examples/tutorials/analysis-2d/modeling_2D.py
  examples/tutorials/analysis-2d/ring_background.py
  examples/tutorials/analysis-3d/analysis_3d.py
  examples/tutorials/analysis-3d/analysis_mwl.py
  examples/tutorials/analysis-3d/cta_data_analysis.py
  examples/tutorials/analysis-3d/event_sampling.py
  examples/tutorials/analysis-3d/flux_profiles.py
  examples/tutorials/analysis-time/light_curve.py
  examples/tutorials/analysis-time/light_curve_flare.py
  examples/tutorials/analysis-time/light_curve_simulation.py
  examples/tutorials/analysis-time/pulsar_analysis.py
  examples/tutorials/api/astro_dark_matter.py
  examples/tutorials/api/catalog.py
  examples/tutorials/api/datasets.py
  examples/tutorials/api/fitting.py
  examples/tutorials/api/makers.py
  examples/tutorials/api/maps.py
  examples/tutorials/api/mask_maps.py
  examples/tutorials/api/model_management.py
  examples/tutorials/api/models.py
  examples/tutorials/data/cta.py
  examples/tutorials/data/fermi_lat.py
  examples/tutorials/data/hess.py
  examples/tutorials/starting/analysis_1.py
  examples/tutorials/starting/analysis_2.py
  examples/tutorials/starting/overview.py
  gammapy/utils/check.py
  gammapy/utils/docs.py
Labels: infrastructure, docs

#4095 Filling of the glossary
  docs/user-guide/maps/index.rst
  docs/user-guide/references.rst
  docs/user-guide/stats/index.rst
Labels: docs

#4105 Fix WcsNDMap upsampling along axis
  gammapy/maps/wcs/ndmap.py
  gammapy/maps/wcs/tests/test_ndmap.py
Labels: bug

#4050 Test if there are too many free norm parameters in the FluxEstimator
  gammapy/estimators/flux.py
  gammapy/estimators/tests/test_flux.py
Labels: bug

#4017 Introduce a phase curve model
  examples/models/temporal/plot_template_phase_temporal.py
  gammapy/modeling/models/__init__.py
  gammapy/modeling/models/temporal.py
  gammapy/modeling/models/tests/test_temporal.py
Labels: feature

#4097 Precise that the `SafeMaskMaker` uses the true energy range to select events for the methods "aeff*"
  examples/tutorials/api/makers.py
  gammapy/makers/safe.py
Labels: docs

#4109 Raise error in FluxPointsEstimator for NormSpectralModel
  gammapy/estimators/points/sed.py
Labels: bug

#4093 Update Astropy package template
  .github/workflows/ci.yml
  MANIFEST.in
  Makefile
  docs/Makefile
  docs/conf.py
  docs/development/dependencies.rst
  docs/development/intro.rst
  docs/development/setup.rst
  docs/getting-started/install.rst
  docs/make.bat
  docs/user-guide/astro/population/plot_velocity_distributions.py
  docs/user-guide/irf/plot_aeff_param.py
  environment-dev.yml
  gammapy/_astropy_init.py
  gammapy/astro/source/tests/test_pwn.py
  gammapy/conftest.py
  gammapy/data/event_list.py
  gammapy/data/tests/test_data_store.py
  gammapy/data/tests/test_event_list.py
  gammapy/irf/psf/tests/test_parametric.py
  gammapy/irf/tests/test_core.py
  gammapy/makers/background/tests/test_fov.py
  gammapy/maps/hpx/geom.py
  gammapy/modeling/models/tests/test_io.py
  gammapy/modeling/models/tests/test_spectral.py
  gammapy/scripts/download.py
  gammapy/scripts/tests/test_download.py
  gammapy/utils/docs.py
  pyproject.toml
  setup.cfg
  setup.py
  tox.ini
Labels: infrastructure

#4107 Implement peek methods for map evaluator and psf kernel
  gammapy/datasets/evaluator.py
  gammapy/datasets/tests/test_evaluator.py
  gammapy/irf/psf/kernel.py
  gammapy/irf/psf/map.py
  gammapy/irf/psf/tests/test_kernel.py
Labels: feature

#3862 Add Map.reproject method
  gammapy/maps/core.py
  gammapy/maps/tests/test_axes.py
  gammapy/maps/tests/test_core.py
Labels: feature

#4108 Add tests with HAWC data
  gammapy/datasets/tests/test_map.py
  gammapy/irf/psf/tests/test_map.py
  gammapy/makers/map.py
  gammapy/makers/tests/test_map.py
Labels: cleanup, tests

#4114 Minor docs improvements / restructure
  docs/user-guide/catalog.rst
  docs/user-guide/datasets/index.rst
  docs/user-guide/dl3.rst
  docs/user-guide/estimators.rst
  docs/user-guide/hli.rst
  docs/user-guide/irf/aeff.rst
  docs/user-guide/irf/edisp.rst
  docs/user-guide/irf/index.rst
  docs/user-guide/irf/psf.rst
  docs/user-guide/irf/theory.rst
  docs/user-guide/makers/index.rst
  docs/user-guide/maps/index.rst
  docs/user-guide/modeling.rst
  docs/user-guide/references.rst
  docs/user-guide/scripts/index.rst
  gammapy/utils/docs.py
Labels: docs

#4115 Add code of conduct file
  CODE_OF_CONDUCT.md
Labels: infrastructure

#4116 Adapt Astropy and Numpy versions in tox configuration
  .github/workflows/ci.yml
  .github/workflows/greetings.yml
  MANIFEST.in
  gammapy/analysis/config/example-3d.yaml
  gammapy/analysis/tests/test_analysis.py
  gammapy/makers/tests/test_spectrum.py
  gammapy/maps/core.py
  gammapy/maps/wcs/tests/test_ndmap.py
  gammapy/visualization/tests/test_utils.py
  setup.cfg
  tox.ini
Labels: infrastructure
