Repository gammapy/gammapy, pull requests merged in 2022-03, with the labels that each got.

#3834 Rename IRF.is_offset_dependent to IRF.has_offset_axis
  gammapy/data/observations.py
  gammapy/irf/core.py
  gammapy/makers/utils.py
Labels: cleanup

#3802 Use DatasetsMaker in Analysis class
  gammapy/analysis/config.py
  gammapy/analysis/core.py
  gammapy/makers/background/ring.py
  gammapy/makers/reduce.py
Labels: cleanup

#3820 Improve serialisation in analysis
  gammapy/analysis/config.py
  gammapy/analysis/core.py
  gammapy/analysis/tests/test_analysis.py
Labels: feature, cleanup

#3806 Improve documentation for the DatasetsMaker
  docs/tutorials/api/makers.ipynb
  gammapy/makers/reduce.py
  gammapy/makers/tests/test_reduce.py
Labels: docs

#3712 Added a notebook tutorial showing an energy-dependent spectrum extraction
  docs/tutorials/analysis/1D/spectral_analysis_rad_max.ipynb
  docs/tutorials/index.rst
Labels: docs

#3819 Refactor content in User Guide and Getting Started docs
  docs/_static/atom.png
  docs/_static/box.png
  docs/_static/gammapy.css
  docs/_static/gears.png
  docs/_static/install.png
  docs/_static/upgrade.png
  docs/_static/using.png
  docs/conf.py
  docs/development/dependencies.rst
  docs/development/index.rst
  docs/getting-started/index.rst
  docs/getting-started/install.rst
  docs/getting-started/otherinstall.rst
  docs/getting-started/troubleshooting.rst
  docs/getting-started/upgrade.rst
  docs/index.rst
  docs/tutorials/index.rst
  docs/userguide/index.rst
  docs/userguide/package.rst
Labels: docs

#3832 Add fov_alignment and is_pointlike attributes to IRF
  gammapy/irf/__init__.py
  gammapy/irf/background.py
  gammapy/irf/core.py
  gammapy/irf/io.py
  gammapy/irf/tests/test_core.py
  gammapy/irf/tests/test_rad_max.py
  gammapy/makers/map.py
Labels: cleanup

#3837 Allow nearest neighbor interpolation with scalar data
  gammapy/data/event_list.py
  gammapy/irf/core.py
  gammapy/irf/rad_max.py
  gammapy/irf/tests/test_rad_max.py
  gammapy/makers/utils.py
  gammapy/utils/interpolation.py
Labels: bug

#3850 Allow for flux points plotting without error measurements
  gammapy/estimators/points/core.py
  gammapy/estimators/points/tests/test_core.py
Labels: bug

#3829 Move content in API to User Guide
  docs/_static/gammapy.css
  docs/analysis/index.rst
  docs/api.rst
  docs/astro/darkmatter/index.rst
  docs/astro/index.rst
  docs/astro/population/index.rst
  docs/astro/source/index.rst
  docs/catalog/index.rst
  docs/conf.py
  docs/data/index.rst
  docs/datasets/index.rst
  docs/estimators/index.rst
  docs/irf/index.rst
  docs/makers/index.rst
  docs/maps/index.rst
  docs/modeling/index.rst
  docs/scripts/index.rst
  docs/stats/index.rst
  docs/tutorials/api/datasets.ipynb
  docs/userguide/astro.rst
  docs/userguide/catalog.rst
  docs/userguide/cli.rst
  docs/userguide/dl3.rst
  docs/userguide/dl4.rst
  docs/userguide/hli.rst
  docs/userguide/makers.rst
  docs/userguide/modeling.rst
  docs/userguide/package.rst
  docs/userguide/stats.rst
  docs/userguide/utils.rst
  docs/userguide/visualization.rst
  docs/utils/index.rst
  docs/visualization/index.rst
  gammapy/datasets/flux_points.py
Labels: docs

#3797 Refactor pointing information handling and `Observation.create`
  docs/datasets/plot_stack.py
  docs/tutorials/analysis/1D/cta_sensitivity.ipynb
  docs/tutorials/analysis/1D/spectrum_simulation.ipynb
  docs/tutorials/analysis/3D/event_sampling.ipynb
  docs/tutorials/analysis/3D/simulate_3d.ipynb
  docs/tutorials/analysis/time/light_curve_simulation.ipynb
  gammapy/analysis/tests/test_analysis.py
  gammapy/data/gti.py
  gammapy/data/observations.py
  gammapy/data/pointing.py
  gammapy/data/tests/test_gti.py
  gammapy/data/tests/test_observations.py
  gammapy/data/tests/test_pointing.py
  gammapy/datasets/tests/test_simulate.py
  gammapy/estimators/points/tests/test_sed.py
  gammapy/makers/tests/test_map.py
  gammapy/makers/tests/test_safe.py
  gammapy/utils/fits.py
Labels: cleanup

#3830 Improve FOVALIGN check for background
  gammapy/makers/map.py
  gammapy/makers/tests/test_utils.py
  gammapy/makers/utils.py
Labels: cleanup

#3841 Modified mask_fit handling in FoVBackgroundMaker
  gammapy/makers/background/fov.py
  gammapy/makers/background/tests/test_fov.py
Labels: bug

#3807 Allow MapAxis with single bin and node type center
  gammapy/estimators/map/core.py
  gammapy/estimators/map/ts.py
  gammapy/estimators/points/core.py
  gammapy/estimators/points/tests/test_core.py
  gammapy/maps/axes.py
  gammapy/maps/tests/test_axes.py
Labels: feature

#3854 Implement Observation.write
  environment-dev.yml
  gammapy/data/event_list.py
  gammapy/data/gti.py
  gammapy/data/observations.py
  gammapy/data/tests/test_event_list.py
  gammapy/data/tests/test_observations.py
  setup.cfg
Labels: feature

#3831 Serialise meta information on Dataset
  docs/userguide/dl4.rst
  gammapy/datasets/map.py
  gammapy/datasets/tests/test_map.py
Labels: feature
