Repository gammapy/gammapy, pull requests merged in 2022-10, with the labels that each got.

#4120 Fix incorrect documentation
  examples/tutorials/api/model_management.py
Labels: bug, docs

#4118 Issue #4117
  gammapy/datasets/core.py
  gammapy/datasets/map.py
  gammapy/datasets/tests/test_map.py
  gammapy/estimators/flux.py
  gammapy/estimators/points/sed.py
  gammapy/estimators/points/tests/test_sed.py
  gammapy/estimators/tests/test_flux.py
  gammapy/makers/map.py
  gammapy/makers/reduce.py
  gammapy/maps/region/geom.py
  gammapy/maps/region/tests/test_geom.py
  gammapy/utils/scripts.py
Labels: bug

#4127 Correct safe mask parameters in spectral analysis with the HLI tutorial
  examples/tutorials/analysis-1d/spectral_analysis_hli.py
Labels: cleanup

#4128 Fix covariance serialisation
  examples/tutorials/data/fermi_lat.py
  gammapy/modeling/models/core.py
  gammapy/modeling/models/tests/test_io.py
Labels: bug

#4131 Improve tutorial cell structures
  examples/tutorials/analysis-1d/spectral_analysis_rad_max.py
  examples/tutorials/analysis-3d/analysis_3d.py
  examples/tutorials/data/cta.py
  examples/tutorials/data/fermi_lat.py
  examples/tutorials/starting/overview.py
  gammapy/estimators/points/sed.py
  gammapy/modeling/models/tests/test_temporal.py
Labels: cleanup

#4126 Fix TemplateSpectralModel serialisation
  gammapy/modeling/models/spectral.py
  gammapy/modeling/models/tests/test_spectral.py
Labels: bug

#4134 Fix docstring in MapDatasetOnOff.fake
  gammapy/datasets/map.py
Labels: cleanup, backport-v1.0.x

#4130 Add changelog for v1.0
  docs/release-notes/index.rst
  docs/release-notes/v1.0.rst
Labels: backport-v1.0.x

#4135 Merge pull request #4134 from gammapy/AtreyeeS-patch-1
  gammapy/datasets/map.py
Labels: cleanup, backport-v1.0.x

#4136 Backport PR #4130 : v1.0 release notes
  docs/release-notes/index.rst
  docs/release-notes/v1.0.rst
Labels: backport-v1.0.x

#4138 Correct bug with ReflectedRegionFinder and PointSkyRegion
  gammapy/makers/background/reflected.py
  gammapy/makers/background/tests/test_reflected.py
Labels: bug, backport-v1.0.x

#4139 Backport PR #4138: Correct bug with ReflectedRegionFinder and PointSkyRegion
  gammapy/makers/background/reflected.py
  gammapy/makers/background/tests/test_reflected.py
Labels: bug, backport-v1.0.x

#4137 Implement minimal release pipeline
  .github/workflows/release.yml
  LONG_DESCRIPTION.rst
  dev/codemeta.py
  dev/prepare-release.py
  docs/development/release.rst
Labels: infrastructure, backport-v1.0.x

#4133 Fix handling of point sky region for model contribution check
  gammapy/datasets/map.py
  gammapy/makers/tests/test_reduce.py
  gammapy/maps/region/geom.py
  gammapy/maps/region/tests/test_ndmap.py
  gammapy/modeling/models/cube.py
  gammapy/modeling/models/tests/test_cube.py
Labels: bug, backport-v1.0.x

#4140 Backport PR #4137: Implement minimal release pipeline
  .github/workflows/release.yml
  LONG_DESCRIPTION.rst
  dev/codemeta.py
  dev/prepare-release.py
  docs/development/release.rst
Labels: infrastructure, backport-v1.0.x

#4141 Backport PR #4133: Fix handling of point sky region for model contribution check
  gammapy/datasets/map.py
  gammapy/makers/tests/test_reduce.py
  gammapy/maps/region/geom.py
  gammapy/maps/region/tests/test_ndmap.py
  gammapy/modeling/models/cube.py
  gammapy/modeling/models/tests/test_cube.py
Labels: bug, backport-v1.0.x

#4142 Updates for the candidate release
  CITATION.cff
  codemeta.json
  docs/development/release.rst
Labels: docs, backport-v1.0.x

#4147 Corrected release notes for v1.0
  docs/release-notes/v1.0.rst
Labels: cleanup, backport-v1.0.x

#4148 Backport PR #4147: Corrected release notes for v1.0
  docs/release-notes/v1.0.rst
Labels: cleanup, backport-v1.0.x

#3970 PIG 24: Authorship Policy
  docs/development/pigs/pig-024.rst
Labels: pig, backport-v1.0.x

#4153 Backport PR 3970: PIG 24
  docs/development/pigs/pig-024.rst
Labels: pig, backport-v1.0.x

#4157 Backport PR #4151: M1 installation notes
  docs/getting-started/install.rst
  docs/getting-started/quickstart.rst
Labels: docs, backport-v1.0.x

#4152 Return correct covariance matrix on CovarianceResult
  examples/tutorials/api/fitting.py
  gammapy/modeling/fit.py
Labels: bug, backport-v1.0.x

#4159 Backport PR #4152: Return correct covariance on CovarianceResult
  examples/tutorials/api/fitting.py
  gammapy/modeling/fit.py
Labels: bug, backport-v1.0.x

#4161 Backport PR #4150: Fix missing units in resampled maps
  gammapy/maps/core.py
  gammapy/maps/tests/test_core.py
Labels: bug, backport-v1.0.x
