Repository gammapy/gammapy, pull requests merged in 2022-05, with the labels that each got.

#3900 Support plotting of point regions
  docs/tutorials/analysis/1D/spectral_analysis_rad_max.ipynb
  gammapy/data/data_store.py
  gammapy/data/observations.py
  gammapy/maps/region/geom.py
Labels: feature

#3904 Fix bug on MC_ID when sampling IRF background events
  gammapy/datasets/simulate.py
  gammapy/datasets/tests/test_simulate.py
Labels: bug

#3908 Support matplotlib >v3.5
  docs/tutorials/analysis/1D/sed_fitting.ipynb
  docs/userguide/howto.rst
  environment-dev.yml
  gammapy/estimators/points/core.py
  gammapy/estimators/points/tests/test_core.py
  gammapy/maps/axes.py
  gammapy/modeling/models/spectral.py
Labels: infrastructure

#3907 Allow tolerance in fft binary operations
  gammapy/maps/wcs/tests/test_ndmap.py
Labels: tests

#3910 Fix issue #3801
  gammapy/datasets/core.py
  gammapy/datasets/tests/test_datasets.py
Labels: bug

#3914 Fix latex typos in equations of models
  examples/models/spatial/plot_disk.py
  examples/models/spatial/plot_gen_gauss.py
  examples/models/spatial/plot_shell2.py
  examples/models/spectral/plot_broken_powerlaw.py
  examples/models/temporal/plot_generalized_gaussian_temporal.py
Labels: docs

#3911 Fix issue #3902
  gammapy/makers/background/tests/test_fov.py
  gammapy/makers/core.py
Labels: bug

#3915 Fix evaluate_containment calculation in class PSFKing(ParametricPSF)
  gammapy/irf/psf/parametric.py
Labels: bug

#3909 Require Python 3.8
  .github/workflows/ci.yml
  docs/development/dev_howto.rst
  environment-dev.yml
  gammapy/irf/psf/tests/test_parametric.py
  gammapy/utils/regions.py
  gammapy/utils/tests/test_regions.py
  setup.cfg
Labels: infrastructure

#3916 Simplify user guide
  docs/index.rst
  docs/userguide/analysis.rst
  docs/userguide/dl4.rst
  docs/userguide/estimators.rst
  docs/userguide/index.rst
  docs/userguide/maps.rst
  docs/userguide/modeling.rst
  docs/userguide/package.rst
  docs/userguide/references.rst
Labels: docs

#3906 Require astropy>=5.0
  .github/workflows/ci.yml
  gammapy/modeling/scipy.py
  setup.cfg
Labels: infrastructure

#3919 Make upsample / downsample API consistent
  gammapy/maps/core.py
  gammapy/maps/hpx/ndmap.py
  gammapy/maps/region/ndmap.py
Labels: cleanup

#3892 Allow for regular reflected region analysis with fixed rad_max IRFs
  gammapy/irf/rad_max.py
  gammapy/irf/tests/test_rad_max.py
  gammapy/makers/background/reflected.py
  gammapy/makers/background/tests/test_reflected.py
Labels: feature

#3876 Add temporal model on flux point dataset
  docs/tutorials/analysis/time/light_curve_simulation.ipynb
  docs/userguide/howto.rst
  gammapy/datasets/core.py
  gammapy/datasets/flux_points.py
  gammapy/datasets/tests/test_flux_points.py
  gammapy/estimators/map/core.py
  gammapy/estimators/map/tests/test_core.py
  gammapy/maps/axes.py
  gammapy/maps/core.py
  gammapy/maps/tests/test_core.py
  gammapy/modeling/models/temporal.py
Labels: feature

#3924 Clean up user guide a bit
  docs/index.rst
  docs/userguide/dl3.rst
  docs/userguide/irf.rst
  docs/userguide/makers.rst
  docs/userguide/maps.rst
  docs/userguide/package.rst
  docs/userguide/stats.rst
Labels: docs

#3918 Improve fit results
  docs/tutorials/api/fitting.ipynb
  gammapy/modeling/fit.py
  gammapy/modeling/models/cube.py
  gammapy/modeling/models/spatial.py
  gammapy/modeling/models/tests/test_cube.py
  gammapy/modeling/models/tests/test_spatial.py
  gammapy/modeling/tests/test_fit.py
Labels: bug

#3887 Implement __eq__ for DL3 IRFs
  gammapy/irf/core.py
  gammapy/irf/edisp/tests/test_core.py
  gammapy/irf/psf/parametric.py
  gammapy/irf/psf/tests/test_parametric.py
  gammapy/irf/tests/test_background.py
  gammapy/irf/tests/test_effective_area.py
Labels: feature

#3926 Update of the CITATION.cff
  CITATION.cff
Labels: infrastructure

#3929 Change tooltip and minor edits in lightcurve simulation notebook
  docs/tutorials/analysis/time/light_curve_simulation.ipynb
Labels: cleanup, docs

#3930 Small improvements in documentation
  docs/getting-started/index.rst
  docs/userguide/catalog.rst
  docs/userguide/estimators.rst
  docs/userguide/howto.rst
  docs/userguide/modeling.rst
  docs/userguide/package.rst
  docs/userguide/references.rst
  docs/userguide/stats.rst
Labels: docs

#3932 Add serialisation info for datasets
  docs/userguide/dl4.rst
Labels: docs

#3934 Fix issue #3931
  gammapy/data/observers.py
  gammapy/estimators/flux.py
  gammapy/estimators/points/tests/test_sed.py
  gammapy/irf/core.py
Labels: bug

#3933 Support regions 0.6
  .github/workflows/ci.yml
  docs/tutorials/api/models.ipynb
  environment-dev.yml
  gammapy/makers/tests/test_reduce.py
  gammapy/maps/region/geom.py
  gammapy/modeling/models/core.py
  gammapy/modeling/models/spatial.py
  gammapy/modeling/models/tests/test_spatial.py
  gammapy/utils/regions.py
  setup.cfg
Labels: infrastructure

#3935 Implement is_allclose methods consistently
  gammapy/irf/core.py
  gammapy/irf/psf/parametric.py
  gammapy/maps/axes.py
  gammapy/maps/core.py
  gammapy/maps/hpx/geom.py
  gammapy/maps/region/geom.py
  gammapy/maps/wcs/geom.py
Labels: feature

#3936 Introduce iminuit as required dependency
  environment-dev.yml
  gammapy/analysis/tests/test_analysis.py
  gammapy/datasets/tests/test_flux_points.py
  gammapy/datasets/tests/test_io.py
  gammapy/datasets/tests/test_map.py
  gammapy/datasets/tests/test_spectrum.py
  gammapy/estimators/points/tests/test_lightcurve.py
  gammapy/estimators/points/tests/test_profile.py
  gammapy/estimators/points/tests/test_sed.py
  gammapy/estimators/tests/test_flux.py
  gammapy/estimators/tests/test_parameter_estimator.py
  gammapy/makers/background/tests/test_fov.py
  gammapy/modeling/fit.py
  gammapy/modeling/iminuit.py
  gammapy/modeling/tests/test_fit.py
  setup.cfg
Labels: infrastructure

#3937 Cleanup fixed rad max checks
  gammapy/irf/rad_max.py
  gammapy/irf/tests/test_rad_max.py
  gammapy/makers/background/reflected.py
  gammapy/makers/background/tests/test_reflected.py
Labels: cleanup

#3938 Revert sed node type change in FluxMaps
  gammapy/estimators/map/core.py
  gammapy/estimators/map/tests/test_core.py
  gammapy/maps/axes.py
Labels: bug, cleanup

#3940 return models.positions in same frame
  gammapy/modeling/models/core.py
  gammapy/modeling/models/tests/test_core.py
Labels: bug

#3943 Change sphinx thumbnail
  docs/tutorials/analysis/time/light_curve_simulation.ipynb
Labels: cleanup, docs

#3945 Implement handling of covariance copy
  gammapy/estimators/points/tests/test_lightcurve.py
  gammapy/modeling/covariance.py
  gammapy/modeling/fit.py
  gammapy/modeling/models/core.py
  gammapy/modeling/models/cube.py
  gammapy/modeling/models/spatial.py
  gammapy/modeling/tests/test_fit.py
Labels: bug, cleanup

#3855 Prepare Changelog
  CHANGES.rst
  docs/changelog/index.rst
  docs/changelog/v0.20.rst
Labels: infrastructure, docs

#3956 Safe mask range on the 1D spectrum tutorial
  docs/tutorials/analysis/1D/spectral_analysis.ipynb
Labels: docs

#3965 Correct doc string in MapDatasetOnOff.to_spectrum_dataset
  gammapy/datasets/map.py
Labels: bug

#3961 Avoid evaluator update if model not contributes
  gammapy/datasets/evaluator.py
Labels: bug, performance

#3964 Fix Background2D.plot_at_energy
  gammapy/irf/background.py
  gammapy/irf/tests/test_background.py
Labels: bug
