Repository gammapy/gammapy, pull requests merged in 2022-06, with the labels that each got.

#3976 Disable radiative_model cache in NaimaSpectralModel init
  gammapy/modeling/models/spectral.py
  gammapy/modeling/models/tests/test_spectral.py
Labels: bug

#3966 Adapt Observation.peek according to available hdus
  gammapy/data/event_list.py
  gammapy/data/observations.py
  gammapy/data/tests/test_observations.py
  gammapy/irf/background.py
  gammapy/irf/edisp/core.py
  gammapy/irf/psf/core.py
  gammapy/irf/rad_max.py
Labels: cleanup

#3974 Fix issue #3973
  gammapy/datasets/tests/test_spectrum.py
  gammapy/maps/region/geom.py
  gammapy/visualization/tests/test_utils.py
  gammapy/visualization/utils.py
Labels: bug

#3957 Fix DM spectral model
  gammapy/astro/darkmatter/spectra.py
  gammapy/astro/darkmatter/tests/test_spectra.py
Labels: bug

#3968 Set reasonable error message case of no free parameters for optimisation
  gammapy/estimators/points/tests/test_sed.py
  gammapy/modeling/fit.py
  gammapy/modeling/tests/test_fit.py
Labels: bug

#3986 Fix bug in RegionNDMap.fill_events with PointSkyRegion
  gammapy/makers/tests/test_reduce.py
  gammapy/maps/region/geom.py
  gammapy/maps/region/tests/test_ndmap.py
Labels: bug

#3988 Fix issue #3983
  gammapy/estimators/map/excess.py
  gammapy/estimators/map/tests/test_excess.py
Labels: bug

#3987 Fix the SafeMaskMaker
  gammapy/makers/safe.py
  gammapy/makers/tests/test_safe.py
Labels: bug

#3975 Fix error bars on plot_excess method of SpectrumDataset and SpectrumDatasetOnOff and plot_residuals_spectral
  gammapy/datasets/map.py
  gammapy/datasets/spectrum.py
Labels: bug

#3991 Further docs fixes 0.20.1
  docs/tutorials/analysis/1D/extended_source_spectral_analysis.ipynb
  docs/tutorials/analysis/1D/spectral_analysis.ipynb
  docs/tutorials/analysis/2D/detect.ipynb
  docs/tutorials/analysis/time/light_curve.ipynb
  docs/tutorials/api/catalog.ipynb
  docs/tutorials/api/datasets.ipynb
  docs/tutorials/api/maps.ipynb
  docs/tutorials/api/models.ipynb
  docs/tutorials/starting/analysis_2.ipynb
  docs/user-guide/astro/darkmatter/index.rst
  docs/user-guide/astro/population/index.rst
  docs/user-guide/astro/source/index.rst
  docs/user-guide/makers/fov.rst
  docs/user-guide/makers/ring.rst
  docs/user-guide/maps/regionmap.rst
  examples/models/README.txt
  examples/models/spectral/plot_absorbed.py
  gammapy/irf/__init__.py
Labels: cleanup, docs

#3977 Fix parameters min/max display in serialization
  gammapy/modeling/models/core.py
  gammapy/modeling/models/tests/test_io.py
Labels: bug

#4002 Modify conf.py to support bugfix versions
  docs/conf.py
Labels: bug

#4000 MNT: Raise error rather than silently proceed
  gammapy/scripts/download.py
Labels: bug, infrastructure

#4005 Modify Makefile to add release number to notebook tar file
  Makefile
  docs/development/release.rst
Labels: feature
