Repository gammapy/gammapy, pull requests merged in 2022-01, with the labels that each got.

#3678 Minor modifs for project contact and description
  LONG_DESCRIPTION.rst
  setup.cfg
Labels: infrastructure, cleanup

#3688 Apply min counts consistently to scale and fit in FoVBackgroundMaker
  gammapy/makers/background/fov.py
  gammapy/makers/background/tests/test_fov.py
Labels: cleanup

#3699 Use mamba in CI jobs
  .github/workflows/ci.yml
Labels: infrastructure

#3684 Started to implement the energy-dependent 1D spectrum extraction
  gammapy/datasets/spectrum.py
  gammapy/makers/background/reflected.py
  gammapy/makers/map.py
  gammapy/makers/tests/test_reduce.py
  gammapy/makers/utils.py
Labels: feature

#3704 Fix zero clipping in npred calculation
  gammapy/datasets/evaluator.py
  gammapy/datasets/map.py
  gammapy/datasets/tests/test_evaluator.py
Labels: bug

#3713 Fix matplotlib 3.5+ incompatibility with WcsNDMap.plot()
  gammapy/maps/wcs/ndmap.py
Labels: bug

#3719 Fix return of covariance result
  gammapy/modeling/fit.py
  gammapy/modeling/tests/test_fit.py
Labels: bug

#3714 Correct FluxEstimator bug with compound model
  gammapy/estimators/flux.py
  gammapy/estimators/tests/test_flux.py
Labels: bug

#3722 Switch documentation to PyData Sphinx Theme
  CHANGES.rst
  docs/_static/copybutton.js
  docs/_static/galleryicon.png
  docs/_static/gammapy.css
  docs/_static/gammapy.js
  docs/_static/gammapy_logo.png
  docs/_static/glossaryicon.png
  docs/_static/index_api.svg
  docs/_static/index_contribute.svg
  docs/_static/index_getting_started.svg
  docs/_static/index_user_guide.svg
  docs/api.rst
  docs/conf.py
  docs/data/index.rst
  docs/development/dev_howto.rst
  docs/development/doc_howto.rst
  docs/development/index.rst
  docs/development/intro.rst
  docs/getting-started/index.rst
  docs/getting-started/quickstart.rst
  docs/getting-started/upgrade.rst
  docs/howto.rst
  docs/index.rst
  docs/maps/regionmap.rst
  docs/overview/index.rst
  docs/tutorials/analysis/1D/extended_source_spectral_analysis.ipynb
  docs/tutorials/analysis/1D/spectrum_simulation.ipynb
  docs/tutorials/analysis/2D/modeling_2D.ipynb
  docs/tutorials/analysis/2D/ring_background.ipynb
  docs/tutorials/analysis/3D/simulate_3d.ipynb
  docs/tutorials/analysis/time/light_curve.ipynb
  docs/tutorials/analysis/time/light_curve_flare.ipynb
  docs/tutorials/analysis/time/light_curve_simulation.ipynb
  docs/tutorials/api/datasets.ipynb
  docs/tutorials/api/models.ipynb
  docs/tutorials/starting/analysis_1.ipynb
  docs/tutorials/starting/analysis_2.ipynb
  docs/tutorials/starting/overview.ipynb
  docs/userguide/analysis.rst
  docs/userguide/dependencies.rst
  docs/userguide/howto.rst
  docs/userguide/index.rst
  docs/userguide/package.rst
  docs/userguide/references.rst
  docs/visualization/index.rst
  environment-dev.yml
  gammapy/utils/notebooks_links.py
Labels: docs

#3728 Add missing required GADF headers in IRF classes
  gammapy/irf/core.py
  gammapy/irf/io.py
  gammapy/irf/tests/test_gadf.py
Labels: bug

#3687 Fix Fit.covariance shape in case of linked parameters
  gammapy/datasets/tests/test_map.py
  gammapy/modeling/fit.py
  gammapy/modeling/tests/test_fit.py
Labels: bug

#3730 Mamba doc update
  docs/development/intro.rst
  docs/getting-started/index.rst
Labels: docs

#3754 Fix ci hangs due to coverage 6.3 by pinning to 6.2
  .github/workflows/ci.yml
  environment-dev.yml
Labels: infrastructure

#3757 Use Pool context directly, fixes #3755
  gammapy/estimators/map/ts.py
  gammapy/makers/reduce.py
Labels: cleanup

#3761 Execute notebooks in parallel
  gammapy/scripts/jupyter.py
  gammapy/utils/notebooks_test.py
Labels: infrastructure

#3762 Run tests in parallel
  .github/workflows/ci.yml
  environment-dev.yml
  gammapy/modeling/models/tests/test_cube.py
Labels: infrastructure, tests

#3753 Fix broken links and add subpackages in documentation
  CHANGES.rst
  docs/datasets/index.rst
  docs/development/dev_howto.rst
  docs/development/doc_howto.rst
  docs/development/intro.rst
  docs/development/pigs/pig-018.rst
  docs/estimators/index.rst
  docs/getting-started/install.rst
  docs/irf/bkg.rst
  docs/irf/index.rst
  docs/makers/fov.rst
  docs/makers/index.rst
  docs/makers/reflected.rst
  docs/makers/ring.rst
  docs/maps/index.rst
  docs/references.txt
  docs/stats/index.rst
  docs/tutorials/data/cta.ipynb
  docs/tutorials/starting/analysis_1.ipynb
  docs/tutorials/starting/overview.ipynb
  docs/userguide/howto.rst
  docs/userguide/package.rst
  docs/userguide/references.rst
  docs/utils/index.rst
  gammapy/astro/source/pulsar.py
  gammapy/data/data_store.py
  gammapy/estimators/points/sensitivity.py
  gammapy/irf/__init__.py
  gammapy/makers/background/reflected.py
  gammapy/modeling/fit.py
Labels: cleanup, docs

#3737 Change API of ReflectedRegionsFinder, fixes #3734
  docs/makers/make_reflected_regions.py
  gammapy/makers/background/reflected.py
  gammapy/makers/background/tests/test_reflected.py
  gammapy/makers/tests/test_spectrum.py
  gammapy/makers/utils.py
Labels: cleanup

#3770 Make `make docs-show` work not only on macOS
  Makefile
  docs/serve.py
Labels: docs

#3772 Update mailmap and CITATION.cff
  .mailmap
  CITATION.cff
Labels: infrastructure

#3774 Bug fix in ParametricPSF
  gammapy/irf/psf/parametric.py
  gammapy/irf/psf/tests/test_parametric.py
Labels: bug

#3773 Remove uneeded pins to old versions of h5py and nbformat
  environment-dev.yml
Labels: infrastructure

#3759 Fix print of catalogs
  gammapy/catalog/core.py
  gammapy/catalog/tests/test_core.py
  gammapy/catalog/tests/test_hess.py
Labels: bug
