Repository gammapy/gammapy, pull requests merged in 2022-11, with the labels that each got.

#4158 Better handlling of empty region lists in RegionGeom and DatasetModels
  gammapy/maps/region/geom.py
  gammapy/maps/region/tests/test_geom.py
  gammapy/modeling/models/core.py
  gammapy/modeling/models/tests/test_core.py
Labels: bug, backport-v1.0.x

#4167 Backport PR #4158: Better handlling of empty region lists in RegionGeom and DatasetModels
  gammapy/maps/region/geom.py
  gammapy/maps/region/tests/test_geom.py
  gammapy/modeling/models/core.py
  gammapy/modeling/models/tests/test_core.py
Labels: bug, backport-v1.0.x

#4165 Use unique parameter names in fit profiles
  examples/tutorials/api/fitting.py
  gammapy/modeling/fit.py
  gammapy/modeling/tests/test_fit.py
Labels: bug, backport-v1.0.x

#4168 Backport PR #4165: Use unique parameter names in fit profiles
  examples/tutorials/api/fitting.py
  gammapy/modeling/fit.py
  gammapy/modeling/tests/test_fit.py
Labels: bug, backport-v1.0.x

#4160 Better handling of regions with inhomogeneous frames in RegionGeom
  gammapy/utils/regions.py
  gammapy/utils/tests/test_regions.py
Labels: bug, backport-v1.0.x

#4170 Backport PR #4160: Better handling of regions with inhomogeneous frames in RegionGeom
  gammapy/utils/regions.py
  gammapy/utils/tests/test_regions.py
Labels: bug, backport-v1.0.x

#4172 Fix grid plot with label axis
  gammapy/maps/core.py
  gammapy/maps/wcs/tests/test_ndmap.py
Labels: bug, backport-v1.0.x

#4175 Backport PR #4172: Fix grid plot with label axis
  gammapy/maps/core.py
  gammapy/maps/wcs/tests/test_ndmap.py
Labels: bug, backport-v1.0.x

#4174 Cleanup tutorials
  examples/tutorials/analysis-1d/cta_sensitivity.py
  examples/tutorials/analysis-1d/extended_source_spectral_analysis.py
  examples/tutorials/analysis-1d/sed_fitting.py
  examples/tutorials/analysis-1d/spectral_analysis.py
  examples/tutorials/analysis-1d/spectral_analysis_hli.py
  examples/tutorials/analysis-1d/spectral_analysis_rad_max.py
  examples/tutorials/analysis-1d/spectrum_simulation.py
  examples/tutorials/analysis-2d/detect.py
  examples/tutorials/analysis-2d/modeling_2D.py
  examples/tutorials/analysis-2d/ring_background.py
  examples/tutorials/analysis-3d/analysis_3d.py
  examples/tutorials/analysis-3d/cta_data_analysis.py
  examples/tutorials/analysis-3d/event_sampling.py
  examples/tutorials/analysis-3d/flux_profiles.py
  examples/tutorials/analysis-3d/simulate_3d.py
  examples/tutorials/analysis-time/light_curve.py
  examples/tutorials/analysis-time/light_curve_flare.py
  examples/tutorials/analysis-time/light_curve_simulation.py
  examples/tutorials/analysis-time/pulsar_analysis.py
  examples/tutorials/api/astro_dark_matter.py
  examples/tutorials/api/catalog.py
  examples/tutorials/api/datasets.py
  examples/tutorials/api/fitting.py
  examples/tutorials/api/makers.py
  examples/tutorials/api/maps.py
  examples/tutorials/api/mask_maps.py
  examples/tutorials/api/model_management.py
  examples/tutorials/api/models.py
Labels: cleanup, docs, backport-v1.0.x

#4176 Backport PR #4174: cleanup tutorials
  examples/tutorials/analysis-1d/cta_sensitivity.py
  examples/tutorials/analysis-1d/extended_source_spectral_analysis.py
  examples/tutorials/analysis-1d/sed_fitting.py
  examples/tutorials/analysis-1d/spectral_analysis.py
  examples/tutorials/analysis-1d/spectral_analysis_hli.py
  examples/tutorials/analysis-1d/spectral_analysis_rad_max.py
  examples/tutorials/analysis-1d/spectrum_simulation.py
  examples/tutorials/analysis-2d/detect.py
  examples/tutorials/analysis-2d/modeling_2D.py
  examples/tutorials/analysis-2d/ring_background.py
  examples/tutorials/analysis-3d/analysis_3d.py
  examples/tutorials/analysis-3d/cta_data_analysis.py
  examples/tutorials/analysis-3d/event_sampling.py
  examples/tutorials/analysis-3d/flux_profiles.py
  examples/tutorials/analysis-3d/simulate_3d.py
  examples/tutorials/analysis-time/light_curve.py
  examples/tutorials/analysis-time/light_curve_flare.py
  examples/tutorials/analysis-time/light_curve_simulation.py
  examples/tutorials/analysis-time/pulsar_analysis.py
  examples/tutorials/api/astro_dark_matter.py
  examples/tutorials/api/catalog.py
  examples/tutorials/api/datasets.py
  examples/tutorials/api/fitting.py
  examples/tutorials/api/makers.py
  examples/tutorials/api/maps.py
  examples/tutorials/api/mask_maps.py
  examples/tutorials/api/model_management.py
  examples/tutorials/api/models.py
Labels: cleanup, docs, backport-v1.0.x

#4164 Consistent Interpolation scale for bkg 2d and 3d
  gammapy/irf/background.py
  gammapy/irf/tests/test_background.py
  gammapy/makers/map.py
  gammapy/makers/tests/test_map.py
  gammapy/makers/tests/test_utils.py
Labels: bug, cleanup, backport-v1.0.x

#4177 Backport PR #4164: Consistent Interpolation scale for bkg 2d and 3d
  gammapy/irf/background.py
  gammapy/irf/tests/test_background.py
  gammapy/makers/map.py
  gammapy/makers/tests/test_map.py
  gammapy/makers/tests/test_utils.py
Labels: bug, cleanup, backport-v1.0.x

#4178 Updated release notes
  docs/release-notes/v1.0.rst
Labels: docs, backport-v1.0.x

#4179 Backport PR #4173 : Remove exception for non-standard OBS_MODE in FixedPointingInfo
  gammapy/data/pointing.py
  gammapy/data/tests/test_pointing.py
Labels: bug, backport-v1.0.x

#4180 Backport PR #4178: Updated release notes
  docs/release-notes/v1.0.rst
Labels: docs, backport-v1.0.x

#4163 Fix Models.to_dict()
  gammapy/modeling/models/core.py
  gammapy/modeling/models/temporal.py
  gammapy/modeling/models/tests/test_io.py
Labels: bug, backport-v1.0.x

#4181 Backport PR #4163: Fix Models.to_dict()
  gammapy/modeling/models/core.py
  gammapy/modeling/models/temporal.py
  gammapy/modeling/models/tests/test_io.py
Labels: bug, backport-v1.0.x

#4182 Adapt tutorial figure handling
  docs/conf.py
  examples/models/spectral/plot_absorbed.py
  examples/tutorials/analysis-1d/cta_sensitivity.py
  examples/tutorials/analysis-1d/extended_source_spectral_analysis.py
  examples/tutorials/analysis-1d/spectral_analysis.py
  examples/tutorials/analysis-1d/spectral_analysis_hli.py
  examples/tutorials/analysis-1d/spectral_analysis_rad_max.py
  examples/tutorials/analysis-1d/spectrum_simulation.py
  examples/tutorials/analysis-2d/detect.py
  examples/tutorials/analysis-2d/modeling_2D.py
  examples/tutorials/analysis-2d/ring_background.py
  examples/tutorials/analysis-3d/analysis_3d.py
  examples/tutorials/analysis-3d/analysis_mwl.py
  examples/tutorials/analysis-3d/cta_data_analysis.py
  examples/tutorials/analysis-3d/event_sampling.py
  examples/tutorials/analysis-3d/flux_profiles.py
  examples/tutorials/analysis-3d/simulate_3d.py
  examples/tutorials/analysis-time/light_curve.py
  examples/tutorials/analysis-time/light_curve_flare.py
  examples/tutorials/analysis-time/light_curve_simulation.py
  examples/tutorials/analysis-time/pulsar_analysis.py
  examples/tutorials/api/astro_dark_matter.py
  examples/tutorials/api/catalog.py
  examples/tutorials/api/datasets.py
  examples/tutorials/api/fitting.py
  examples/tutorials/api/makers.py
  examples/tutorials/api/maps.py
  examples/tutorials/api/mask_maps.py
  examples/tutorials/api/model_management.py
  examples/tutorials/api/models.py
  examples/tutorials/data/cta.py
  examples/tutorials/data/fermi_lat.py
  examples/tutorials/data/hess.py
Labels: docs, backport-v1.0.x

#4183 Backport PR #4182: Adapt tutorial figure handling
  docs/conf.py
  examples/models/spectral/plot_absorbed.py
  examples/tutorials/analysis-1d/cta_sensitivity.py
  examples/tutorials/analysis-1d/extended_source_spectral_analysis.py
  examples/tutorials/analysis-1d/spectral_analysis.py
  examples/tutorials/analysis-1d/spectral_analysis_hli.py
  examples/tutorials/analysis-1d/spectral_analysis_rad_max.py
  examples/tutorials/analysis-1d/spectrum_simulation.py
  examples/tutorials/analysis-2d/detect.py
  examples/tutorials/analysis-2d/modeling_2D.py
  examples/tutorials/analysis-2d/ring_background.py
  examples/tutorials/analysis-3d/analysis_3d.py
  examples/tutorials/analysis-3d/analysis_mwl.py
  examples/tutorials/analysis-3d/cta_data_analysis.py
  examples/tutorials/analysis-3d/event_sampling.py
  examples/tutorials/analysis-3d/flux_profiles.py
  examples/tutorials/analysis-3d/simulate_3d.py
  examples/tutorials/analysis-time/light_curve.py
  examples/tutorials/analysis-time/light_curve_flare.py
  examples/tutorials/analysis-time/light_curve_simulation.py
  examples/tutorials/analysis-time/pulsar_analysis.py
  examples/tutorials/api/astro_dark_matter.py
  examples/tutorials/api/catalog.py
  examples/tutorials/api/datasets.py
  examples/tutorials/api/fitting.py
  examples/tutorials/api/makers.py
  examples/tutorials/api/maps.py
  examples/tutorials/api/mask_maps.py
  examples/tutorials/api/model_management.py
  examples/tutorials/api/models.py
  examples/tutorials/data/cta.py
  examples/tutorials/data/fermi_lat.py
  examples/tutorials/data/hess.py
Labels: docs, backport-v1.0.x

#4184 Change if clause in catalog to remove astropy deprecation warning
  gammapy/catalog/core.py
Labels: cleanup, backport-v1.0.x

#4185 Backport PR #4184 : Change if clause in catalog to remove astropy deprecation warning
  gammapy/catalog/core.py
Labels: cleanup, backport-v1.0.x

#4186 Correct links in how to
  docs/user-guide/howto.rst
Labels: docs, backport-v1.0.x

#4187 Backport PR #4186: Correct links in how to
  docs/user-guide/howto.rst
Labels: docs, backport-v1.0.x

#4189 Correct documentation
  docs/development/pigs/index.rst
  docs/development/pigs/pig-024.rst
  docs/release-notes/index.rst
  docs/user-guide/howto.rst
  docs/user-guide/references.rst
  examples/tutorials/analysis-1d/spectral_analysis.py
  examples/tutorials/analysis-2d/detect.py
  examples/tutorials/analysis-time/light_curve_flare.py
  examples/tutorials/analysis-time/light_curve_simulation.py
  examples/tutorials/api/fitting.py
  examples/tutorials/api/model_management.py
  examples/tutorials/api/models.py
  examples/tutorials/data/fermi_lat.py
  examples/tutorials/starting/analysis_2.py
  examples/tutorials/starting/overview.py
Labels: cleanup, docs, backport-v1.0.x

#4190 Backport PR #4189: correct documentation
  docs/development/pigs/index.rst
  docs/development/pigs/pig-024.rst
  docs/release-notes/index.rst
  docs/user-guide/howto.rst
  docs/user-guide/references.rst
  examples/tutorials/analysis-1d/spectral_analysis.py
  examples/tutorials/analysis-2d/detect.py
  examples/tutorials/analysis-time/light_curve_flare.py
  examples/tutorials/analysis-time/light_curve_simulation.py
  examples/tutorials/api/fitting.py
  examples/tutorials/api/model_management.py
  examples/tutorials/api/models.py
  examples/tutorials/data/fermi_lat.py
  examples/tutorials/starting/analysis_2.py
  examples/tutorials/starting/overview.py
Labels: cleanup, docs, backport-v1.0.x

#4193 Minor cleanup event sampling tutorial
  examples/tutorials/analysis-3d/event_sampling.py
Labels: backport-v1.0.x

#4194 Backport PR #4193 : clean-up event sampling
  examples/tutorials/analysis-3d/event_sampling.py
Labels: docs, backport-v1.0.x

#4192 Correct documentation part 2
  docs/development/pigs/pig-024.rst
  docs/getting-started/index.rst
  docs/user-guide/howto.rst
  docs/user-guide/maps/index.rst
  docs/user-guide/scripts/index.rst
  examples/tutorials/analysis-1d/extended_source_spectral_analysis.py
  examples/tutorials/analysis-1d/spectrum_simulation.py
  examples/tutorials/analysis-time/light_curve_flare.py
  examples/tutorials/api/makers.py
  examples/tutorials/api/maps.py
  examples/tutorials/api/mask_maps.py
  examples/tutorials/data/cta.py
  examples/tutorials/starting/analysis_1.py
  examples/tutorials/starting/analysis_2.py
  examples/tutorials/starting/overview.py
Labels: cleanup, docs, backport-v1.0.x

#4197 Backports PR #4035: Update the documentation for the use of the DCO
  CONTRIBUTING.md
  README.rst
  docs/development/intro.rst
Labels: docs, backport-v1.0.x

#4196 Correct documentation part 3
  docs/getting-started/install.rst
  examples/tutorials/analysis-1d/spectral_analysis.py
  examples/tutorials/analysis-1d/spectral_analysis_rad_max.py
  examples/tutorials/analysis-2d/detect.py
  examples/tutorials/analysis-2d/ring_background.py
  examples/tutorials/analysis-3d/analysis_mwl.py
  examples/tutorials/analysis-3d/flux_profiles.py
  examples/tutorials/starting/analysis_2.py
Labels: cleanup, docs, backport-v1.0.x

#4077 Review of CITATION.cff for the LTS release
  CITATION.cff
  codemeta.json
  environment-dev.yml
Labels: docs, backport-v1.0.x

#4201 Backport #4077: Review of CITATION.cff for the LTS release
  CITATION.cff
  codemeta.json
  environment-dev.yml
Labels: docs, backport-v1.0.x

#4200 Cleanup datasets tutorial
  examples/tutorials/api/datasets.py
Labels: cleanup, docs, backport-v1.0.x

#4203 Backport #4200 : Cleanup datasets tutorial
  examples/tutorials/api/datasets.py
Labels: docs, backport-v1.0.x

#4202 New PR with the codemeta.json
  codemeta.json
Labels: docs, backport-v1.0.x

#4204 Backport PR #4202 : codemeta.json
  codemeta.json
Labels: backport-v1.0.x
