Repository gammapy/gammapy, pull requests merged in 2022-07, with the labels that each got.

#4004 Add code block substitution and conditional quick start in doc getting-started
  docs/conf.py
  docs/getting-started/index.rst
  docs/getting-started/quickstart.rst
  gammapy/utils/docs.py
Labels: docs

#4014 Avoid unnecessary copy in Map.stack
  gammapy/maps/hpx/ndmap.py
  gammapy/maps/region/ndmap.py
  gammapy/maps/wcs/ndmap.py
Labels: cleanup

#4013 Fix zeros errors in models created from 3HWC catalog
  codemeta.json
  gammapy/catalog/hawc.py
  gammapy/catalog/tests/test_hawc.py
Labels: bug

#4026 Fix TemplateSpatialModel overwrite
  gammapy/modeling/models/spatial.py
Labels: bug

#4015 Allow to stack mask_fit in Dataset.stack
  gammapy/datasets/map.py
  gammapy/datasets/tests/test_map.py
Labels: cleanup

#4022 Introduce consistent .rename_axes and .rename API for maps
  gammapy/maps/axes.py
  gammapy/maps/core.py
  gammapy/maps/geom.py
  gammapy/maps/tests/test_axes.py
  gammapy/maps/tests/test_core.py
Labels: feature, cleanup

#3925 Temporal model integration
  gammapy/modeling/models/temporal.py
  gammapy/modeling/models/tests/test_temporal.py
Labels: feature

#4041 Fix small typos in the documentation
  gammapy/irf/background.py
  gammapy/makers/background/reflected.py
  gammapy/maps/axes.py
Labels: bug, docs

#4037 Implement IRF.slice_by_idx()
  gammapy/irf/core.py
  gammapy/irf/tests/test_core.py
Labels: feature

#3998 MAINT: minor setup.cfg cleanup
  .github/workflows/ci.yml
  setup.cfg
Labels: infrastructure

#4040 Usage of Compound spectral models for a SkyModel
  examples/models/spectral/plot_compound.py
  gammapy/modeling/models/cube.py
  gammapy/modeling/models/tests/test_cube.py
Labels: bug, feature, effort-low
