Repository gammapy/gammapy, pull requests merged in 2022-04, with the labels that each got.

#3864 Restructure getting started page
  docs/getting-started/index.rst
  docs/getting-started/install.rst
  docs/getting-started/otherinstall.rst
  docs/getting-started/upgrade.rst
  docs/index.rst
  docs/userguide/howto.rst
Labels: cleanup, docs

#3875 Corrections in docstrings and model definitions
  examples/models/spatial/plot_gen_gauss.py
  examples/models/spectral/plot_broken_powerlaw.py
  gammapy/estimators/map/core.py
Labels: docs

#3846 Allows DataStoreMaker to be used with IRFs not following CALDB structure
  docs/tutorials/analysis/3D/event_sampling.ipynb
  gammapy/data/data_store.py
  gammapy/data/tests/test_data_store.py
  gammapy/utils/scripts.py
Labels: bug, feature

#3856 Make obs_table optional on DataStore
  gammapy/data/data_store.py
  gammapy/data/observations.py
  gammapy/data/tests/test_data_store.py
Labels: cleanup

#3872 Fix gaussians with missing size in SourceCatalogHGPS.to_models
  gammapy/catalog/hess.py
  gammapy/catalog/tests/test_hess.py
Labels: bug

#3735 Cleanup HDUs required in Datastore.get_observations()
  docs/tutorials/analysis/1D/spectral_analysis_rad_max.ipynb
  gammapy/analysis/config.py
  gammapy/analysis/core.py
  gammapy/analysis/tests/test_analysis.py
  gammapy/data/data_store.py
  gammapy/data/observations.py
  gammapy/data/tests/test_data_store.py
  gammapy/data/tests/test_observations.py
  gammapy/makers/tests/test_spectrum.py
Labels: feature, cleanup

#3769 Change flux map attribute axis type
  gammapy/estimators/map/core.py
  gammapy/estimators/map/tests/test_core.py
  gammapy/maps/axes.py
Labels: cleanup

#3874 Allow MapDatasetOff in Datasets serialization and avoid read_lazy
  gammapy/datasets/__init__.py
  gammapy/datasets/map.py
  gammapy/datasets/tests/test_map.py
Labels: bug, feature

#3861 Fix interp_to_geom to use correctly fill_value
  gammapy/maps/core.py
  gammapy/maps/hpx/ndmap.py
  gammapy/maps/tests/test_core.py
  gammapy/maps/wcs/ndmap.py
  gammapy/modeling/models/tests/test_cube.py
  gammapy/modeling/models/tests/test_spatial.py
Labels: bug

#3884 Raise TypeError if FoVBackgroundMaker is called with a Region based dataset
  gammapy/makers/background/fov.py
  gammapy/makers/background/tests/test_fov.py
Labels: bug

#3873 Modify SafeMaskMaker to ignore data only below the background peak
  gammapy/makers/safe.py
  gammapy/makers/tests/test_safe.py
  gammapy/makers/tests/test_spectrum.py
Labels: bug

#3860 Introduce Parameter.is_norm property
  docs/tutorials/api/models.ipynb
  examples/models/spectral/plot_compound.py
  gammapy/datasets/flux_points.py
  gammapy/estimators/tests/test_flux.py
  gammapy/modeling/models/core.py
  gammapy/modeling/models/cube.py
  gammapy/modeling/models/spectral.py
  gammapy/modeling/models/spectral_crab.py
  gammapy/modeling/models/tests/test_core.py
  gammapy/modeling/models/tests/test_io.py
  gammapy/modeling/models/tests/test_management.py
  gammapy/modeling/models/tests/test_spectral.py
  gammapy/modeling/parameter.py
  gammapy/modeling/tests/test_parameter.py
Labels: feature, cleanup

#3833 Automate generation of codemeta.json and .zenodo.json files
  .github/workflows/cffconvert.yml
  CITATION.cff
  codemeta.json
  dev/codemeta.py
Labels: infrastructure

#3891 Add notes about order of observations to docstrings
  gammapy/data/data_store.py
Labels: docs

#3869 Re-computation of upper limits on flux points
  gammapy/estimators/points/core.py
  gammapy/estimators/points/tests/test_lightcurve.py
  gammapy/estimators/points/tests/test_sed.py
Labels: feature

#3870 Enable serialisation of spectrum datasets
  gammapy/datasets/__init__.py
  gammapy/datasets/map.py
  gammapy/datasets/spectrum.py
  gammapy/datasets/tests/test_io.py
  gammapy/datasets/tests/test_spectrum.py
Labels: feature

#3886 Improve docs get started
  docs/_static/1d-analysis-image.png
  docs/_static/2d-analysis-image.png
  docs/_static/3d-analysis-image.png
  docs/_static/gammapy.css
  docs/changelog/index.rst
  docs/development/intro.rst
  docs/getting-started/environments.rst
  docs/getting-started/index.rst
  docs/getting-started/install.rst
  docs/index.rst
  docs/userguide/howto.rst
  gammapy/data/data_store.py
  gammapy/irf/__init__.py
Labels: docs

#3798 Counts stat sum
  gammapy/datasets/map.py
  gammapy/datasets/tests/test_map.py
  gammapy/stats/counts_statistic.py
  gammapy/stats/tests/test_counts_statistic.py
Labels: feature

#3895 Add MapAxes .__eq__, .__neq__, and .copy()
  codemeta.json
  gammapy/maps/axes.py
  gammapy/maps/tests/test_axes.py
Labels: feature

#3896 Separate handling of safe mask default thresholds
  gammapy/makers/safe.py
  gammapy/makers/tests/test_safe.py
Labels: bug

#3897 Add plot_rad_max_vs_energy() and test
  gammapy/irf/rad_max.py
  gammapy/irf/tests/test_rad_max.py
Labels: feature

#3894 Add peek method to IRFMaps and unify peek methods
  docs/tutorials/analysis/3D/analysis_3d.ipynb
  gammapy/datasets/evaluator.py
  gammapy/datasets/map.py
  gammapy/datasets/spectrum.py
  gammapy/estimators/profile.py
  gammapy/irf/background.py
  gammapy/irf/edisp/kernel.py
  gammapy/irf/edisp/map.py
  gammapy/irf/edisp/tests/test_map.py
  gammapy/irf/effective_area.py
  gammapy/irf/psf/core.py
  gammapy/irf/psf/map.py
  gammapy/irf/psf/tests/test_map.py
  gammapy/makers/safe.py
  gammapy/makers/tests/test_map.py
  gammapy/makers/tests/test_utils.py
Labels: feature, cleanup

#3898 Add Map.resample method
  gammapy/maps/core.py
  gammapy/maps/hpx/ndmap.py
  gammapy/maps/region/ndmap.py
  gammapy/maps/tests/test_core.py
  gammapy/maps/wcs/ndmap.py
Labels: feature

#3899 Refactor Map.iter_by_image
  docs/tutorials/api/maps.ipynb
  gammapy/maps/core.py
  gammapy/maps/hpx/ndmap.py
  gammapy/maps/region/ndmap.py
  gammapy/maps/tests/test_core.py
  gammapy/maps/wcs/ndmap.py
Labels: feature, cleanup

#3901 Update authors and CITATION.cff
  .mailmap
  CITATION.cff
  codemeta.json
  dev/authors.py
Labels: infrastructure
