Repository gammapy/gammapy, pull requests merged in 2022-12, with the labels that each got.

#4213 Add deprecation warning system
  docs/development/dev_howto.rst
  gammapy/utils/deprecation.py
  gammapy/utils/tests/test_deprecation.py
Labels: feature

#4224 Fix check_tutorials_setup
  gammapy/utils/check.py
Labels: bug, backport-v1.0.x

#4214 Fix IO for EBLAbsorptionNormSpectralModel
  gammapy/modeling/models/spectral.py
  gammapy/modeling/models/tests/test_io.py
Labels: bug, backport-v1.0.x

#4227 Backport PR #4224 on branch v1.0.x (Fix check_tutorials_setup)
  gammapy/utils/check.py
Labels: bug, backport-v1.0.x

#4228 Backport PR #4214 on branch v1.0.x (Fix IO for EBLAbsorptionNormSpectralModel )
  gammapy/modeling/models/spectral.py
  gammapy/modeling/models/tests/test_io.py
Labels: bug, backport-v1.0.x

#4225 Replace deprecated numpy type aliases
  gammapy/estimators/map/tests/test_core.py
  gammapy/irf/edisp/kernel.py
  gammapy/maps/region/tests/test_ndmap.py
  gammapy/maps/tests/test_maps.py
  gammapy/modeling/tests/test_parameter.py
Labels: cleanup, backport-v1.0.x

#4226 Fix inhomogeneous array shape deprecation
  gammapy/modeling/models/spectral.py
  gammapy/visualization/panel.py
Labels: cleanup, backport-v1.0.x

#4232 Backport PR #4225 on branch v1.0.x (Replace deprecated numpy type aliases)
  gammapy/estimators/map/tests/test_core.py
  gammapy/irf/edisp/kernel.py
  gammapy/maps/region/tests/test_ndmap.py
  gammapy/maps/tests/test_maps.py
  gammapy/modeling/tests/test_parameter.py
Labels: cleanup, backport-v1.0.x

#4233 Backport PR #4226 on branch v1.0.x (Fix inhomogeneous array shape deprecation)
  gammapy/modeling/models/spectral.py
  gammapy/visualization/panel.py
Labels: cleanup, backport-v1.0.x

#4221 Fix wrong name in required hdus
  gammapy/data/data_store.py
Labels: bug, backport-v1.0.x

#4234 Backport PR #4221 on branch v1.0.x (Fix wrong name in required hdus)
  gammapy/data/data_store.py
Labels: bug, backport-v1.0.x

#4219 Allow reading of IRF files with single-value axes
  gammapy/maps/axes.py
  gammapy/maps/tests/test_axes.py
Labels: bug, backport-v1.0.x

#4235 Backport PR #4219 on branch v1.0.x (Allow reading of IRF files with single-value axes)
  gammapy/maps/axes.py
  gammapy/maps/tests/test_axes.py
Labels: bug, backport-v1.0.x

#4245 Added an evaluate method for CompoundSpectralModel
  gammapy/modeling/models/spectral.py
  gammapy/modeling/models/tests/test_spectral.py
Labels: feature, cleanup

#4231 Fix bug in safe mask computation for SpectrumDatasetOnOff
  gammapy/makers/safe.py
  gammapy/makers/tests/test_safe.py
Labels: bug, backport-v1.0.x

#4243 Change _check_intervals from PhaseBackgroundMaker
  gammapy/makers/background/phase.py
  gammapy/makers/background/tests/test_phase.py
Labels: feature

#4215 Adds built-in Franceschini (2018) and Saldana-Lopez (2021) EBL models
  examples/models/spectral/plot_absorbed.py
  gammapy/modeling/models/spectral.py
Labels: feature

#4262 Modify ci.yml to allow devdeps run to fail
  .github/workflows/ci.yml
Labels: infrastructure

#4250 Backport PR #4231 on branch v1.0.x (Fix bug in safe mask computation for SpectrumDatasetOnOff)
  gammapy/makers/safe.py
  gammapy/makers/tests/test_safe.py
Labels: bug, backport-v1.0.x
