Repository gammapy/gammapy, pull requests merged in 2023-02, with the labels that each got.

#4302 Adapt condition on release workflow
  .github/workflows/release.yml
Labels: bug, infrastructure, backport-v1.0.x

#4307 Add black version to CI
  .github/workflows/ci.yml
Labels: infrastructure, backport-v1.0.x

#4309 Backport PR #4307 on branch v1.0.x (Add black version to CI)
  .github/workflows/ci.yml
Labels: infrastructure, backport-v1.0.x

#4300 Fix latex rendering in tutorial
  examples/tutorials/analysis-1d/spectral_analysis_rad_max.py
Labels: backport-v1.0.x

#4311 Backport PR #4300 on branch v1.0.x (Fix latex rendering in tutorial)
  examples/tutorials/analysis-1d/spectral_analysis_rad_max.py
Labels: backport-v1.0.x

#4314 Fix latex equation in doc for 4FGL-DR3 SECPL model
  examples/models/spectral/plot_super_exp_cutoff_powerlaw_4fgl.py
Labels: bug, docs, backport-v1.0.x

#4315 Backport PR #4314 on branch v1.0.x (Fix latex equation in doc for 4FGL-DR3 SECPL model)
  examples/models/spectral/plot_super_exp_cutoff_powerlaw_4fgl.py
Labels: bug, docs, backport-v1.0.x

#4317 fixing red r in generalized gaussian spatial model docs
  examples/models/spatial/plot_gen_gauss.py
Labels: docs, backport-v1.0.x

#4322 Backport PR #4317 on branch v1.0.x (fixing red r in generalized gaussian spatial model docs)
  examples/models/spatial/plot_gen_gauss.py
Labels: docs, backport-v1.0.x

#4323 Backport PR #4321 on branch v1.0.x (fixing 4fgl and broken power law equations in docs)
  examples/models/spectral/plot_broken_powerlaw.py
  examples/models/spectral/plot_super_exp_cutoff_powerlaw_4fgl.py
Labels: docs

#4305 Add `SpectralModel.spectral_index_error`
  gammapy/modeling/models/spectral.py
  gammapy/modeling/models/tests/test_spectral.py
Labels: feature

#4242 Add Observations clustering by IRFs quality
  gammapy/data/observations.py
  gammapy/data/tests/test_observations.py
  gammapy/data/utils.py
  gammapy/estimators/utils.py
  gammapy/utils/cluster.py
Labels: feature

#4319 updating documentation how to
  docs/development/doc_howto.rst
Labels: docs, backport-v1.0.x

#4328 Backport PR #4319 on branch v1.0.x (updating documentation how to)
  docs/development/doc_howto.rst
Labels: docs, backport-v1.0.x

#4333 Backport PR #4330 on branch v1.0.x (Remove Observation.from_caldb() in notebook)
  examples/tutorials/analysis-3d/simulate_3d.py
Labels: docs, backport-v1.0.x

#4335 Fixing docstring for stat_sum in several dataset class
  gammapy/datasets/core.py
  gammapy/datasets/map.py
Labels: docs, backport-v1.0.x

#4337 Backport PR #4335 on branch v1.0.x (Fixing docstring for stat_sum in several dataset class)
  gammapy/datasets/core.py
  gammapy/datasets/map.py
Labels: docs, backport-v1.0.x

#4332 CI fix for astropylts-numpy120 test env
  .github/workflows/ci.yml
  tox.ini
Labels: infrastructure, backport-v1.0.x

#4325 Fix typo in SpatialModel.plot_interactive()
  gammapy/modeling/models/spatial.py
  gammapy/modeling/models/tests/test_spatial.py
Labels: bug, backport-v1.0.x

#4338 Backport PR #4332 on branch v1.0.x (CI fix for astropylts-numpy120 test env)
  .github/workflows/ci.yml
  tox.ini
Labels: infrastructure, backport-v1.0.x

#4334 Replace deprecated property Observation.pointing_radec
  examples/tutorials/analysis-3d/cta_data_analysis.py
  examples/tutorials/api/makers.py
  examples/tutorials/data/hess.py
  examples/tutorials/starting/analysis_2.py
  gammapy/data/utils.py
Labels: cleanup

#4304 Fix zero length shape after WcsGeom.cutout()
  gammapy/maps/wcs/geom.py
  gammapy/maps/wcs/tests/test_geom.py
Labels: bug, backport-v1.0.x

#4324 Fix Parameter init if scale is not one
  gammapy/modeling/models/tests/data/examples.yaml
  gammapy/modeling/parameter.py
  gammapy/modeling/tests/test_iminuit.py
  gammapy/modeling/tests/test_parameter.py
  gammapy/modeling/tests/test_scipy.py
  gammapy/modeling/tests/test_sherpa.py
Labels: bug, backport-v1.0.x

#4277 Fix datasets io with RecoPSFMap
  gammapy/datasets/map.py
  gammapy/irf/core.py
  gammapy/irf/psf/tests/test_map.py
Labels: bug, backport-v1.0.x

#4341 Backport PR #4304 on branch v1.0.x (Fix zero length shape after WcsGeom.cutout())
  gammapy/maps/wcs/geom.py
  gammapy/maps/wcs/tests/test_geom.py
Labels: bug, backport-v1.0.x

#4342 Backport PR #4324 on branch v1.0.x (Fix Parameter init if scale is not one)
  gammapy/modeling/models/tests/data/examples.yaml
  gammapy/modeling/parameter.py
  gammapy/modeling/tests/test_iminuit.py
  gammapy/modeling/tests/test_parameter.py
  gammapy/modeling/tests/test_scipy.py
  gammapy/modeling/tests/test_sherpa.py
Labels: bug, backport-v1.0.x

#4343 Backport PR #4277 on branch v1.0.x (Fix datasets io with RecoPSFMap)
  gammapy/datasets/map.py
  gammapy/irf/core.py
  gammapy/irf/psf/tests/test_map.py
Labels: bug, backport-v1.0.x

#4210 Add plot_rgb() function in gammapy.visualization
  gammapy/visualization/__init__.py
  gammapy/visualization/tests/test_utils.py
  gammapy/visualization/utils.py
Labels: feature
