Repository gammapy/gammapy, pull requests merged in 2023-09, with the labels that each got.

#4733 Backport PR #4721 on branch v1.0.x (Exposing NormSpectralModels)
  examples/models/spectral/plot_exp_cutoff_powerlaw_norm_spectral.py
  examples/models/spectral/plot_logparabola_norm_spectral.py
  examples/models/spectral/plot_powerlaw_norm_spectral.py
Labels: docs, backport-v1.0.x, backport-v1.1.x

#4731 Backport PR #4719 on branch v1.1.x (Fix devdeps test setup)
  tox.ini
Labels: infrastructure, backport-v1.0.x, backport-v1.1.x

#4734 Backport PR #4721 on branch v1.1.x (Exposing NormSpectralModels)
  examples/models/spectral/plot_exp_cutoff_powerlaw_norm_spectral.py
  examples/models/spectral/plot_logparabola_norm_spectral.py
  examples/models/spectral/plot_powerlaw_norm_spectral.py
Labels: docs, backport-v1.0.x, backport-v1.1.x

#4735 Backport PR #4728 on branch v1.0.x (Fixed offset calculation in Background2D.to_3d)
  gammapy/irf/background.py
Labels: bug, backport-v1.0.x, backport-v1.1.x

#4736 Backport PR #4728 on branch v1.1.x (Fixed offset calculation in Background2D.to_3d)
  gammapy/irf/background.py
Labels: bug, backport-v1.0.x, backport-v1.1.x

#4745 Adapt dev docs to include backporting information
  docs/development/dev_howto.rst
Labels: docs

#4608 Add a slice_by_coord function for FluxMaps
  gammapy/estimators/map/core.py
  gammapy/estimators/map/tests/test_core.py
Labels: feature

#4729 Change default index for NormSpectralModel
  gammapy/modeling/models/spectral.py
  gammapy/modeling/models/tests/test_io.py
Labels: cleanup

#4755 Separate units in pcolormesh
  gammapy/irf/background.py
Labels: backport-v1.0.x, backport-v1.1.x

#4759 Display the default model parameters in docstrings
  gammapy/modeling/models/spectral.py
Labels: cleanup, docs

#4757 Backport PR #4755 on branch v1.1.x (Separate units in pcolormesh)
  gammapy/irf/background.py
Labels: backport-v1.0.x, backport-v1.1.x

#4761 Regenerate name to avoid starting with underscore
  gammapy/data/event_list.py
  gammapy/datasets/evaluator.py
  gammapy/modeling/models/spatial.py
  gammapy/modeling/models/tests/test_cube.py
  gammapy/utils/scripts.py
Labels: bug, backport-v1.0.x, backport-v1.1.x

#4764 Backport PR #4761 on branch v1.0.x (Regenerate name to avoid starting with underscore)
  gammapy/data/event_list.py
  gammapy/datasets/evaluator.py
  gammapy/modeling/models/spatial.py
  gammapy/modeling/models/tests/test_cube.py
  gammapy/utils/scripts.py
Labels: bug, backport-v1.0.x, backport-v1.1.x

#4766 Fix matplotlib issue with Polygon in HpxNDMap
  .github/workflows/ci.yml
  gammapy/maps/hpx/ndmap.py
Labels: cleanup

#4770 Raise error if the predicted event number is too large in event sampling
  gammapy/datasets/simulate.py
  gammapy/datasets/tests/test_simulate.py
Labels: bug

#4772 Fix plot spectrum function
  gammapy/irf/background.py
  gammapy/irf/core.py
  gammapy/irf/tests/test_core.py
Labels: bug, backport-v1.0.x, backport-v1.1.x

#4774 Backport PR #4772 on branch v1.1.x (Fix plot spectrum function)
  gammapy/irf/background.py
  gammapy/irf/core.py
  gammapy/irf/tests/test_core.py
Labels: bug

#4769 Display default model parameters (temporal and spatial) in docstrings
  gammapy/modeling/models/spatial.py
  gammapy/modeling/models/temporal.py
Labels: docs

#4584 Add optional sensitivity computation in ExcessMapEstimator
  gammapy/estimators/map/core.py
  gammapy/estimators/map/excess.py
  gammapy/estimators/map/tests/test_excess.py
Labels: feature
