Repository gammapy/gammapy, pull requests merged in 2023-12, with the labels that each got.

#4217 FluxPointsDataset support model with spatial template and NormSpectralModel
  gammapy/datasets/flux_points.py
  gammapy/estimators/flux.py
  gammapy/estimators/points/sed.py
  gammapy/estimators/points/tests/test_sed.py
  gammapy/estimators/tests/test_flux.py
  gammapy/modeling/models/core.py
  gammapy/modeling/models/spatial.py
  gammapy/modeling/models/tests/test_core.py
Labels: bug, feature

#4943 Expose cluster features in API
  docs/api-reference/utils.rst
  gammapy/data/__init__.py
  gammapy/data/utils.py
  gammapy/utils/cluster.py
Labels: cleanup, docs, backport-v1.1.x

#4944 Expose more features
  docs/api-reference/utils.rst
  gammapy/modeling/__init__.py
  gammapy/utils/parallel.py
Labels: cleanup, docs

#4916 Add `energy_true` to `MapDataset.create()` in tutorial
  examples/tutorials/analysis-3d/cta_data_analysis.py
Labels: cleanup, docs

#4931 Remove deprecations in gammapy.modeling
  gammapy/modeling/fit.py
  gammapy/modeling/models/spatial.py
Labels: cleanup

#4930 Remove deprecations in `gammapy.maps`
  gammapy/maps/axes.py
  gammapy/maps/core.py
  gammapy/maps/region/tests/test_ndmap.py
Labels: cleanup

#4817 Computation of total observation time map
  docs/user-guide/howto.rst
  examples/tutorials/api/makers.py
  examples/tutorials/data/hess.py
  gammapy/makers/tests/test_utils.py
  gammapy/makers/utils.py
Labels: docs, coding sprint

#4928 Remove deprecation from datasets/map.py
  examples/tutorials/api/datasets.py
  gammapy/datasets/evaluator.py
  gammapy/datasets/map.py
Labels: cleanup

#4936 PiecewiseNormSpectralModel serialising interp
  gammapy/modeling/models/spectral.py
  gammapy/modeling/models/tests/test_spectral.py
Labels: bug, backport-v1.0.x, backport-v1.1.x

#4828 Adapt SkyModel to evaluate on TimeMapAxis
  gammapy/modeling/models/cube.py
  gammapy/modeling/models/tests/test_cube.py
Labels: feature, coding sprint

#4940 Fix MapEvaluator for the apply_edisp=False case
  gammapy/datasets/evaluator.py
  gammapy/modeling/models/tests/test_cube.py
Labels: bug, backport-v1.0.x, backport-v1.1.x

#4953 Backport PR #4936 on branch v1.0.x (PiecewiseNormSpectralModel serialising interp)
  gammapy/modeling/models/spectral.py
  gammapy/modeling/models/tests/test_spectral.py
Labels: bug, backport-v1.0.x, backport-v1.1.x

#4954 Backport PR #4936 on branch v1.1.x (PiecewiseNormSpectralModel serialising interp)
  gammapy/modeling/models/spectral.py
  gammapy/modeling/models/tests/test_spectral.py
Labels: bug, backport-v1.0.x, backport-v1.1.x

#4955 Backport PR #4940 on branch v1.1.x (Fix MapEvaluator for the apply_edisp=False case)
  gammapy/datasets/evaluator.py
  gammapy/modeling/models/tests/test_cube.py
Labels: bug, backport-v1.0.x, backport-v1.1.x

#4956 Prepare release notes for v1.0.2
  dev/github_summary.py
  docs/release-notes/index.rst
  docs/release-notes/v1.0.2.rst
Labels: docs, backport-v1.0.x, backport-v1.1.x

#4836 Fix a division per zero in `TemplateSpatialModel` normalisation
  gammapy/modeling/models/spatial.py
  gammapy/modeling/models/tests/test_spatial.py
Labels: bug, cleanup, coding sprint

#4958 Backport PR #4956 on branch v1.1.x (Prepare release notes for v1.0.2)
  dev/github_summary.py
  docs/release-notes/index.rst
  docs/release-notes/v1.0.2.rst
Labels: docs, backport-v1.0.x, backport-v1.1.x

#4902 Add norm attribute to estimators and deprecate previous norm related attributes
  examples/tutorials/analysis-3d/flux_profiles.py
  gammapy/estimators/flux.py
  gammapy/estimators/points/lightcurve.py
  gammapy/estimators/points/sed.py
  gammapy/estimators/points/tests/test_lightcurve.py
  gammapy/estimators/points/tests/test_sed.py
  gammapy/estimators/tests/test_flux.py
  gammapy/modeling/models/cube.py
  gammapy/modeling/parameter.py
Labels: cleanup

#3047 Prototype for datasets parallel evaluation with ray
  gammapy/datasets/actors.py
  gammapy/datasets/map.py
  gammapy/datasets/tests/test_map.py
  gammapy/estimators/flux.py
  gammapy/estimators/parameter.py
  gammapy/estimators/points/lightcurve.py
  gammapy/estimators/points/sed.py
  gammapy/estimators/points/tests/test_lightcurve.py
  gammapy/estimators/points/tests/test_sed.py
  gammapy/modeling/fit.py
  gammapy/modeling/scipy.py
Labels: feature, performance

#4903 Remove useless norm parameters from spectral model
  gammapy/modeling/models/spectral.py
  gammapy/modeling/models/tests/test_spectral.py
Labels: cleanup

#4965 Expose more features useful for UL computation
  gammapy/estimators/__init__.py
  gammapy/modeling/__init__.py
Labels: docs

#4964 Adapt accordion id in HowTo
  docs/user-guide/howto.rst
Labels: docs

#4904 Deprecate is_norm on parameter
  gammapy/astro/darkmatter/spectra.py
  gammapy/astro/darkmatter/tests/test_spectra.py
  gammapy/modeling/models/spectral.py
  gammapy/modeling/models/spectral_crab.py
  gammapy/modeling/models/tests/test_io.py
  gammapy/modeling/models/tests/test_spectral.py
  gammapy/modeling/parameter.py
Labels: cleanup, api-change

#4974 Remove unnecessary `# TODO`
  gammapy/makers/tests/test_spectrum.py
  gammapy/maps/region/geom.py
  gammapy/modeling/covariance.py
  gammapy/modeling/fit.py
  gammapy/scripts/tests/test_download.py
  gammapy/utils/fits.py
Labels: cleanup

#4942 Parallel support for FluxProfileEstimation
  gammapy/estimators/points/profile.py
  gammapy/estimators/points/tests/test_profile.py
Labels: performance

#4839 No extrapolation for `PrimaryFlux`
  gammapy/astro/darkmatter/spectra.py
  gammapy/astro/darkmatter/tests/test_spectra.py
  gammapy/astro/darkmatter/tests/test_utils.py
Labels: cleanup

#4980 Consistency with format Part 2
  gammapy/makers/background/fov.py
  gammapy/makers/background/ring.py
  gammapy/makers/map.py
  gammapy/makers/reduce.py
  gammapy/makers/spectrum.py
  gammapy/maps/axes.py
  gammapy/maps/coord.py
  gammapy/maps/core.py
  gammapy/maps/hpx/core.py
  gammapy/maps/hpx/geom.py
  gammapy/maps/hpx/ndmap.py
  gammapy/maps/region/geom.py
  gammapy/maps/region/ndmap.py
Labels: docs

#4981 Consistency with format Part 3
  gammapy/modeling/models/core.py
  gammapy/modeling/models/cube.py
  gammapy/modeling/models/spatial.py
  gammapy/modeling/models/spectral.py
  gammapy/modeling/models/temporal.py
  gammapy/modeling/parameter.py
  gammapy/utils/fits.py
  gammapy/utils/interpolation.py
  gammapy/utils/metadata.py
  gammapy/utils/parallel.py
  gammapy/utils/regions.py
Labels: docs

#4992 Adding a function to guess the format of a FluxPoints object for serialization
  gammapy/estimators/points/core.py
  gammapy/estimators/points/tests/test_lightcurve.py
  gammapy/estimators/points/tests/test_profile.py
  gammapy/estimators/points/tests/test_sed.py
Labels: feature

#4970 Adapt FluxPointsDataset to fit light curves
  examples/tutorials/analysis-time/light_curve_simulation.py
  gammapy/datasets/flux_points.py
  gammapy/datasets/tests/test_flux_points.py
Labels: feature, docs

#4973 Add position as a parameter for TemplateSpatialModel
  gammapy/datasets/tests/test_io.py
  gammapy/estimators/map/tests/test_ts.py
  gammapy/modeling/models/spatial.py
  gammapy/modeling/models/tests/test_cube.py
  gammapy/modeling/models/tests/test_spatial.py
Labels: feature

#4927 Remove deprecations in `gammapy.data`
  gammapy/data/observations.py
  gammapy/data/pointing.py
  gammapy/data/tests/test_observations.py
  gammapy/data/tests/test_pointing.py
Labels: cleanup

#4978 Support negative offset for Background2d.to_3d
  gammapy/irf/background.py
  gammapy/irf/tests/test_background.py
Labels: bug, backport-v1.0.x, backport-v1.1.x

#4847 Variability tutorial
  examples/tutorials/analysis-time/Variability_estimation.py
Labels: docs, coding sprint

#4994 Spatial parameters in FovBackgroundModel
  gammapy/modeling/models/cube.py
  gammapy/modeling/models/tests/test_cube.py
Labels: feature

#4917 Add new class to directly simulate observations
  gammapy/datasets/__init__.py
  gammapy/datasets/simulate.py
  gammapy/datasets/tests/test_simulate.py
Labels: feature, cleanup

#4969 MNT: fix an implicit incompatibility with Python 3.12 (pkg_resources isn't shipped with stdlib)
  gammapy/__init__.py
Labels: infrastructure

#4977 Reduce memory usage of solid_angle
  gammapy/maps/wcs/geom.py
  gammapy/maps/wcs/tests/test_geom.py
Labels: performance
