Repository gammapy/gammapy, pull requests merged in 2023-11, with the labels that each got.

#4810 Adding a tutorial for observational clustering
  docs/user-guide/howto.rst
  examples/tutorials/api/observation_clustering.py
  examples/tutorials/data/README.rst
  examples/tutorials/starting/README.rst
Labels: docs, coding sprint

#4874 Cleanup docstrings for `gammapy.astro`
  gammapy/astro/darkmatter/profiles.py
  gammapy/astro/darkmatter/spectra.py
  gammapy/astro/darkmatter/utils.py
  gammapy/astro/population/simulate.py
  gammapy/astro/population/spatial.py
  gammapy/astro/population/velocity.py
  gammapy/astro/source/pulsar.py
  gammapy/astro/source/pwn.py
  gammapy/astro/source/snr.py
Labels: cleanup, docs, backport-v1.0.x, backport-v1.1.x

#4878 Cleanup docstrings for `gammapy.catalog`
  gammapy/catalog/core.py
  gammapy/catalog/fermi.py
  gammapy/catalog/gammacat.py
  gammapy/catalog/hawc.py
  gammapy/catalog/hess.py
  gammapy/catalog/lhaaso.py
Labels: cleanup, docs, backport-v1.0.x, backport-v1.1.x

#4381 PIG 16 - Model Priors API
  docs/development/pigs/index.rst
  docs/development/pigs/pig-026.rst
Labels: pig

#4869 Adapt overwrite in docstring to be consistent
  gammapy/analysis/core.py
  gammapy/data/data_store.py
  gammapy/data/event_list.py
  gammapy/data/observations.py
  gammapy/datasets/core.py
  gammapy/datasets/flux_points.py
  gammapy/datasets/map.py
  gammapy/datasets/spectrum.py
  gammapy/datasets/tests/test_datasets.py
  gammapy/estimators/map/core.py
  gammapy/estimators/points/core.py
  gammapy/irf/core.py
  gammapy/maps/core.py
  gammapy/maps/maps.py
  gammapy/maps/region/ndmap.py
  gammapy/modeling/models/core.py
  gammapy/modeling/models/cube.py
  gammapy/modeling/models/spatial.py
  gammapy/modeling/models/spectral.py
  gammapy/modeling/models/temporal.py
Labels: cleanup, docs

#4855 Update of the metadata file with the paper reference
  CITATION
  CITATION.cff
  README.rst
  codemeta.json
Labels: docs

#4851 Parallel support for WcsNDMap map convolution
  gammapy/maps/core.py
  gammapy/maps/wcs/ndmap.py
Labels: performance

#4834 Adding prior stat sum to datasets
  gammapy/datasets/core.py
  gammapy/datasets/map.py
  gammapy/datasets/tests/test_map.py
Labels: feature, coding sprint

#4664 Add a faster reprojection method : reproject_by_image
  gammapy/maps/core.py
  gammapy/maps/tests/test_core.py
Labels: feature, performance

#4886 Introduce hierarchical metadata structures
  examples/tutorials/api/observation_clustering.py
  gammapy/data/metadata.py
  gammapy/data/observations.py
  gammapy/data/tests/test_data_store.py
  gammapy/data/tests/test_metadata.py
  gammapy/data/tests/test_observations.py
  gammapy/makers/tests/test_utils.py
  gammapy/utils/fits.py
  gammapy/utils/metadata.py
  gammapy/utils/tests/test_metadata.py
Labels: feature, cleanup

#4808 adding `Observations` in memory generator
  gammapy/data/observations.py
  gammapy/data/tests/test_observations.py
Labels: performance, trigger-benchmarks, coding sprint

#4888 Cleanup docstrings for `gammapy.scripts`, `gammapy.stats` and `gammapy.visualization`
  gammapy/scripts/check.py
  gammapy/scripts/download.py
  gammapy/scripts/info.py
  gammapy/stats/counts_statistic.py
  gammapy/stats/fit_statistics.py
  gammapy/stats/utils.py
  gammapy/stats/variability.py
  gammapy/visualization/cmap.py
  gammapy/visualization/datasets.py
  gammapy/visualization/heatmap.py
  gammapy/visualization/panel.py
Labels: cleanup, docs

#4891 Cleanup docstrings for `gammapy.analysis`
  gammapy/analysis/config.py
  gammapy/analysis/core.py
Labels: cleanup, docs

#4861 Fix TimeMapAxis.pix_to_coord()
  gammapy/maps/axes.py
  gammapy/maps/tests/test_axes.py
  gammapy/maps/wcs/tests/test_geom.py
Labels: bug

#4892 Cleanup docstrings for `gammapy.makers`
  gammapy/makers/background/fov.py
  gammapy/makers/background/phase.py
  gammapy/makers/background/reflected.py
  gammapy/makers/background/ring.py
  gammapy/makers/map.py
  gammapy/makers/reduce.py
  gammapy/makers/safe.py
  gammapy/makers/spectrum.py
  gammapy/makers/utils.py
Labels: cleanup, docs

#4894 Cleanup docstrings for `gammapy.utils`
  gammapy/utils/array.py
  gammapy/utils/check.py
  gammapy/utils/cluster.py
  gammapy/utils/coordinates/__init__.py
  gammapy/utils/coordinates/fov.py
  gammapy/utils/coordinates/other.py
  gammapy/utils/deprecation.py
  gammapy/utils/docs.py
  gammapy/utils/fits.py
  gammapy/utils/gauss.py
  gammapy/utils/integrate.py
  gammapy/utils/interpolation.py
  gammapy/utils/metadata.py
  gammapy/utils/parallel.py
  gammapy/utils/pbar.py
  gammapy/utils/random/utils.py
  gammapy/utils/regions.py
  gammapy/utils/roots.py
  gammapy/utils/scripts.py
  gammapy/utils/table.py
  gammapy/utils/testing.py
  gammapy/utils/time.py
  gammapy/utils/units.py
Labels: cleanup, docs

#4835 Management of metadata for `Models`
  gammapy/modeling/models/core.py
  gammapy/modeling/models/tests/test_io.py
  gammapy/utils/metadata.py
Labels: feature, coding sprint

#4872 Cleanup docstring in `gammapy.data`
  gammapy/data/data_store.py
  gammapy/data/event_list.py
  gammapy/data/filters.py
  gammapy/data/gti.py
  gammapy/data/hdu_index_table.py
  gammapy/data/metadata.py
  gammapy/data/obs_table.py
  gammapy/data/observations.py
  gammapy/data/pointing.py
  gammapy/data/utils.py
Labels: cleanup, docs

#4895 Add `DatasetsMaker` to HowTo
  docs/user-guide/howto.rst
Labels: docs

#4879 Fix energy dependent temporal model simulation
  gammapy/datasets/simulate.py
  gammapy/datasets/tests/test_simulate.py
Labels: bug, backport-v1.0.x, backport-v1.1.x

#4901 Cleanup docstrings for `gammapy.maps.hpx`
  gammapy/maps/hpx/core.py
  gammapy/maps/hpx/geom.py
  gammapy/maps/hpx/io.py
  gammapy/maps/hpx/ndmap.py
  gammapy/maps/hpx/utils.py
Labels: cleanup, docs

#4915 Backport PR #4879 on branch v1.1.x (Fix energy dependent temporal model simulation)
  gammapy/datasets/simulate.py
  gammapy/datasets/tests/test_simulate.py
Labels: bug, backport-v1.0.x, backport-v1.1.x

#4889 Cleanup docstring in `gammapy.maps.axes.py`
  gammapy/maps/axes.py
Labels: cleanup, docs

#4893 Cleanup docstrings for `gammapy.irf`
  gammapy/irf/__init__.py
  gammapy/irf/background.py
  gammapy/irf/core.py
  gammapy/irf/edisp/core.py
  gammapy/irf/edisp/kernel.py
  gammapy/irf/edisp/map.py
  gammapy/irf/effective_area.py
  gammapy/irf/io.py
  gammapy/irf/psf/core.py
  gammapy/irf/psf/kernel.py
  gammapy/irf/psf/map.py
  gammapy/irf/psf/parametric.py
  gammapy/irf/psf/table.py
  gammapy/irf/rad_max.py
Labels: cleanup, docs

#4910 Cleanup docstring in `gammapy.maps`: `coord.py`, `geom.py`, `io.py` and `maps.py`
  gammapy/maps/coord.py
  gammapy/maps/geom.py
  gammapy/maps/io.py
  gammapy/maps/maps.py
Labels: cleanup, docs

#4908 Cleanup docstrings for `gammapy.maps.wcs`
  gammapy/maps/wcs/core.py
  gammapy/maps/wcs/geom.py
  gammapy/maps/wcs/ndmap.py
Labels: cleanup, docs

#4906 Cleanup docstrings for `gammapy.maps.region`
  gammapy/maps/region/geom.py
  gammapy/maps/region/ndmap.py
Labels: cleanup, docs

#4890 Cleanup docstrings for `gammapy.modeling`
  gammapy/modeling/covariance.py
  gammapy/modeling/fit.py
  gammapy/modeling/iminuit.py
  gammapy/modeling/likelihood.py
  gammapy/modeling/models/core.py
  gammapy/modeling/models/cube.py
  gammapy/modeling/models/prior.py
  gammapy/modeling/models/spatial.py
  gammapy/modeling/models/spectral.py
  gammapy/modeling/models/spectral_cosmic_ray.py
  gammapy/modeling/models/spectral_crab.py
  gammapy/modeling/models/temporal.py
  gammapy/modeling/models/utils.py
  gammapy/modeling/parameter.py
  gammapy/modeling/scipy.py
  gammapy/modeling/selection.py
  gammapy/modeling/sherpa.py
Labels: cleanup, docs

#4921 Backport PR #4918 on branch v1.1.x (If statement bug in pointing)
  gammapy/data/pointing.py
  gammapy/data/tests/test_pointing.py
Labels: bug, backport-v1.1.x

#4880 Cleanup docstrings for `gammapy.datasets`
  gammapy/datasets/core.py
  gammapy/datasets/evaluator.py
  gammapy/datasets/flux_points.py
  gammapy/datasets/io.py
  gammapy/datasets/map.py
  gammapy/datasets/simulate.py
  gammapy/datasets/spectrum.py
  gammapy/datasets/utils.py
Labels: cleanup, docs

#4658 Add utility function to find containment region of maps
  gammapy/maps/__init__.py
  gammapy/maps/measure.py
  gammapy/maps/tests/test_measure.py
Labels: feature

#4924 Remove deprecations in `gammapy.utils`
  gammapy/utils/table.py
  gammapy/utils/tests/test_table.py
Labels: cleanup

#4926 Remove deprecations in `gammapy.irf`
  gammapy/irf/__init__.py
  gammapy/irf/io.py
  gammapy/irf/tests/test_io.py
Labels: cleanup, priority-high

#4913 Fix NoOverlapError in SpatialModel.integrate_geom
  gammapy/modeling/models/spatial.py
Labels: bug, backport-v1.0.x, backport-v1.1.x

#4932 Backport PR #4913 on branch v1.0.x (Fix NoOverlapError in SpatialModel.integrate_geom)
  gammapy/modeling/models/spatial.py
Labels: bug, backport-v1.0.x, backport-v1.1.x

#4933 Backport PR #4913 on branch v1.1.x (Fix NoOverlapError in SpatialModel.integrate_geom)
  gammapy/modeling/models/spatial.py
Labels: bug, backport-v1.0.x, backport-v1.1.x

#4845 Add context manager for multiprocessing configuration
  gammapy/utils/parallel.py
  gammapy/utils/tests/test_parallel.py
Labels: feature, performance

#4934 Fix broken links in docs
  examples/models/spectral/plot_absorbed.py
  examples/tutorials/api/makers.py
  gammapy/modeling/models/__init__.py
  gammapy/modeling/models/spectral.py
Labels: docs

#4939 Backport PR #4937 on branch v1.1.x (Fix import of angular_separation for astropy 6)
  docs/development/pigs/pig-021.rst
  examples/tutorials/api/models.py
Labels: cleanup, backport-v1.0.x, backport-v1.1.x
