Repository gammapy/gammapy, pull requests merged in 2023-04, with the labels that each got.

#4440 Fix example code of ring background maker
  docs/user-guide/makers/ring.rst
Labels: bug, docs, backport-v1.0.x

#4449 Backport PR #4440 on branch v1.0.x (Fix example code of ring background maker)
  docs/user-guide/makers/ring.rst
Labels: bug, docs, backport-v1.0.x

#4427 Add example for on-off simulation
  examples/tutorials/analysis-1d/spectral_analysis_rad_max.py
  examples/tutorials/analysis-1d/spectrum_simulation.py
Labels: feature, docs

#4448 Catch invalid conversion warning in pix_tuple_to_idx
  gammapy/maps/geom.py
Labels: cleanup, backport-v1.0.x

#4452 Backport PR #4448 on branch v1.0.x (Catch invalid conversion warning in pix_tuple_to_idx)
  gammapy/maps/geom.py
Labels: cleanup, backport-v1.0.x

#4412 LightCurveTemplateModel serialisation
  gammapy/maps/axes.py
  gammapy/modeling/models/temporal.py
  gammapy/modeling/models/tests/test_temporal.py
Labels: bug, backport-v1.0.x

#4454 Backport PR #4412 on branch v1.0.x (LightCurveTemplateModel serialisation)
  gammapy/maps/axes.py
  gammapy/modeling/models/temporal.py
  gammapy/modeling/models/tests/test_temporal.py
Labels: bug, backport-v1.0.x

#4414 Expose more methods in ExcessMapEstimator
  gammapy/estimators/map/excess.py
Labels: feature, cleanup

#4369 Pulsar analysis tutorial
  examples/tutorials/analysis-time/pulsar_analysis.py
Labels: docs

#4453 Add scale in temporal model
  gammapy/modeling/models/core.py
  gammapy/modeling/models/temporal.py
  gammapy/modeling/models/tests/test_temporal.py
Labels: bug, backport-v1.0.x

#4456 Backport PR #4453 on branch v1.0.x (Add scale in temporal model)
  gammapy/modeling/models/core.py
  gammapy/modeling/models/temporal.py
  gammapy/modeling/models/tests/test_temporal.py
Labels: bug, backport-v1.0.x

#4352 Adding rad max cut in PhaseBackgroundMaker
  gammapy/makers/background/phase.py
  gammapy/makers/background/tests/test_phase.py
  gammapy/makers/tests/test_utils.py
Labels: feature

#4455 Test SpatialModel.from_position()
  gammapy/modeling/models/spatial.py
  gammapy/modeling/models/tests/test_spatial.py
Labels: cleanup, tests, backport-v1.0.x

#4462 Backport PR #4455 on branch v1.0.x (Test SpatialModel.from_position())
  gammapy/modeling/models/spatial.py
  gammapy/modeling/models/tests/test_spatial.py
Labels: cleanup, tests

#4465 Backport PR #4464 on branch v1.0.x (Move noqa comment in math equations)
  gammapy/irf/effective_area.py
  gammapy/modeling/models/spectral.py
Labels: bug, docs, backport-v1.0.x

#4459 Evaluation of energy dep temporal model
  examples/models/temporal/plot_template_temporal.py
  gammapy/datasets/tests/test_simulate.py
  gammapy/modeling/models/temporal.py
  gammapy/modeling/models/tests/test_temporal.py
  gammapy/modeling/models/tests/test_utils.py
  gammapy/modeling/models/utils.py
Labels: feature

#4446 Improve map axis test (x-axis format)
  gammapy/maps/tests/test_axes.py
Labels: tests, backport-v1.0.x

#4469 Backport PR #4446 on branch v1.0.x (Improve map axis test (x-axis format))
  gammapy/maps/tests/test_axes.py
Labels: tests, backport-v1.0.x

#4398 Add profilers to dev environment
  .github/workflows/dispatch_benchmark.yml
  environment-dev.yml
Labels: infrastructure, trigger-benchmarks

#4478 Impose sphinx-gallery<0.13 in environment-dev
  environment-dev.yml
  tox.ini
Labels: bug, infrastructure, backport-v1.0.x

#4479 Backport PR #4478 on branch v1.0.x (Impose sphinx-gallery<0.13 in environment-dev)
  environment-dev.yml
  tox.ini
Labels: bug, infrastructure, backport-v1.0.x

#4402 Support for parallel evaluation in FluxPointsEstimator
  gammapy/analysis/core.py
  gammapy/estimators/points/sed.py
  gammapy/estimators/points/tests/test_sed.py
Labels: performance

#4404 Support for parallel evaluation in LightCurveEstimator
  gammapy/analysis/core.py
  gammapy/estimators/points/lightcurve.py
  gammapy/estimators/points/tests/test_lightcurve.py
Labels: performance

#4474 List the EBL models
  examples/models/spectral/plot_absorbed.py
Labels: docs

#4444 Integral sensitivity in FluxPointsEstimator
  examples/tutorials/analysis-1d/cta_sensitivity.py
  gammapy/estimators/points/sensitivity.py
  gammapy/estimators/points/tests/test_sensitivity.py
Labels: feature

#4466 Add tutorial for the use of HAWC data
  examples/tutorials/data/hawc.py
  examples/tutorials/data/hess.py
  gammapy/datasets/map.py
  gammapy/datasets/tests/test_map.py
  gammapy/irf/psf/map.py
Labels: docs

#4463 Update dev environment to python 3.9
  .github/workflows/ci.yml
  environment-dev.yml
  pyproject.toml
  setup.cfg
  tox.ini
Labels: infrastructure

#4395 Add the possibility to plot in MJD the light curves
  gammapy/estimators/points/core.py
  gammapy/estimators/points/tests/test_lightcurve.py
  gammapy/maps/axes.py
  gammapy/maps/tests/test_axes.py
Labels: feature
