Repository gammapy/gammapy, pull requests merged in 2023-10, with the labels that each got.

#4773 Backport PR #4772 on branch v1.0.x (Fix plot spectrum function)
  gammapy/irf/background.py
  gammapy/irf/core.py
  gammapy/irf/tests/test_core.py
Labels: bug

#4778 Backport PR #4777 on branch v1.0.x (Bump actions/checkout from 3 to 4)
  .github/workflows/cffconvert.yml
  .github/workflows/ci.yml
  .github/workflows/release.yml
Labels: dependencies

#4779 Backport PR #4777 on branch v1.1.x (Bump actions/checkout from 3 to 4)
  .github/workflows/cffconvert.yml
  .github/workflows/ci.yml
  .github/workflows/release.yml
Labels: dependencies

#4665 `plot_distribution` in tutorials
  examples/tutorials/analysis-2d/ring_background.py
  examples/tutorials/analysis-3d/analysis_3d.py
Labels: docs

#4703 Update 4FGL catalog default to DR4
  gammapy/catalog/fermi.py
  gammapy/catalog/tests/test_fermi.py
Labels: feature

#4741 Add Zhao profile
  gammapy/astro/darkmatter/__init__.py
  gammapy/astro/darkmatter/profiles.py
  gammapy/astro/darkmatter/tests/test_profiles.py
Labels: feature

#4714 Replace CashCountsStatistic error calculation by analytical expression
  gammapy/estimators/map/tests/test_excess.py
  gammapy/stats/counts_statistic.py
  gammapy/stats/tests/test_counts_statistic.py
Labels: performance

#4753 Removes size 1 array to scalar conversion deprecation warnings from numpy
  gammapy/irf/psf/map.py
  gammapy/maps/core.py
  gammapy/maps/hpx/geom.py
  gammapy/maps/hpx/ndmap.py
  gammapy/maps/hpx/utils.py
  gammapy/maps/region/geom.py
  gammapy/maps/wcs/geom.py
  gammapy/maps/wcs/ndmap.py
  gammapy/modeling/models/core.py
  gammapy/modeling/models/temporal.py
Labels: cleanup, backport-v1.0.x, backport-v1.1.x

#4795 Modify v1.0.x CI to use gammapy-dataset 1.0
  .github/workflows/ci.yml
  environment-dev.yml
Labels: infrastructure

#4794 Modify ci.yml to use gammapy-datasets of v1.1 release.
  .github/workflows/ci.yml
Labels: infrastructure

#4793 Backport PR #4753 on branch v1.1.x (Removes size 1 array to scalar conversion deprecation warnings from numpy)
  gammapy/irf/psf/map.py
  gammapy/maps/core.py
  gammapy/maps/hpx/geom.py
  gammapy/maps/hpx/ndmap.py
  gammapy/maps/hpx/utils.py
  gammapy/maps/region/geom.py
  gammapy/maps/wcs/geom.py
  gammapy/maps/wcs/ndmap.py
  gammapy/modeling/models/core.py
  gammapy/modeling/models/temporal.py
Labels: cleanup, backport-v1.0.x, backport-v1.1.x

#4796 Backport #4753: Removes size 1 array to scalar conversion deprecation warnings from numpy
  gammapy/irf/psf/map.py
  gammapy/maps/core.py
  gammapy/maps/hpx/geom.py
  gammapy/maps/hpx/ndmap.py
  gammapy/maps/hpx/utils.py
  gammapy/maps/region/geom.py
  gammapy/maps/wcs/geom.py
  gammapy/maps/wcs/ndmap.py
  gammapy/modeling/models/core.py
Labels: cleanup

#4785 Use interpolation for dark matter mass
  examples/tutorials/api/astro_dark_matter.py
  gammapy/astro/darkmatter/spectra.py
  gammapy/astro/darkmatter/tests/test_spectra.py
  gammapy/modeling/models/spectral.py
Labels: feature

#4740 Add DarkMatterDecaySpectralModel
  examples/tutorials/api/astro_dark_matter.py
  gammapy/astro/darkmatter/__init__.py
  gammapy/astro/darkmatter/profiles.py
  gammapy/astro/darkmatter/spectra.py
  gammapy/astro/darkmatter/tests/test_spectra.py
  gammapy/astro/darkmatter/tests/test_utils.py
  gammapy/astro/darkmatter/utils.py
Labels: feature

#4677 Fix wcs.array_shape definition in WcsGeom.create
  gammapy/maps/region/geom.py
  gammapy/maps/wcs/geom.py
  gammapy/maps/wcs/tests/test_geom.py
  gammapy/modeling/models/tests/test_core.py
Labels: bug, backport-v1.0.x, backport-v1.1.x

#4797 Backport PR #4677 on branch v1.0.x (Fix wcs.array_shape definition in WcsGeom.create)
  gammapy/maps/region/geom.py
  gammapy/maps/wcs/geom.py
  gammapy/maps/wcs/tests/test_geom.py
  gammapy/modeling/models/tests/test_core.py
Labels: bug, backport-v1.0.x, backport-v1.1.x

#4798 Backport PR #4677 on branch v1.1.x (Fix wcs.array_shape definition in WcsGeom.create)
  gammapy/maps/region/geom.py
  gammapy/maps/wcs/geom.py
  gammapy/maps/wcs/tests/test_geom.py
  gammapy/modeling/models/tests/test_core.py
Labels: bug, backport-v1.0.x, backport-v1.1.x

#4803 Remove deprecation warning in DM decay model
  gammapy/astro/darkmatter/spectra.py
Labels: infrastructure, coding sprint

#3947 Provide initial implementations of _repr_html_
  docs/development/dev_howto.rst
  gammapy/analysis/config.py
  gammapy/analysis/core.py
  gammapy/astro/darkmatter/profiles.py
  gammapy/astro/darkmatter/utils.py
  gammapy/astro/source/pulsar.py
  gammapy/astro/source/pwn.py
  gammapy/astro/source/snr.py
  gammapy/catalog/core.py
  gammapy/data/data_store.py
  gammapy/data/event_list.py
  gammapy/data/filters.py
  gammapy/data/gti.py
  gammapy/data/observations.py
  gammapy/data/pointing.py
  gammapy/datasets/core.py
  gammapy/datasets/evaluator.py
  gammapy/datasets/simulate.py
  gammapy/datasets/tests/test_map.py
  gammapy/datasets/tests/test_spectrum.py
  gammapy/estimators/core.py
  gammapy/estimators/map/excess.py
  gammapy/irf/core.py
  gammapy/irf/psf/kernel.py
  gammapy/makers/background/reflected.py
  gammapy/makers/core.py
  gammapy/maps/axes.py
  gammapy/maps/coord.py
  gammapy/maps/core.py
  gammapy/maps/geom.py
  gammapy/maps/hpx/geom.py
  gammapy/maps/hpx/io.py
  gammapy/maps/hpx/ndmap.py
  gammapy/maps/hpx/tests/test_geom.py
  gammapy/maps/hpx/utils.py
  gammapy/maps/maps.py
  gammapy/maps/region/geom.py
  gammapy/maps/region/tests/test_geom.py
  gammapy/maps/tests/test_core.py
  gammapy/maps/wcs/geom.py
  gammapy/maps/wcs/tests/test_geom.py
  gammapy/modeling/fit.py
  gammapy/modeling/likelihood.py
  gammapy/modeling/models/core.py
  gammapy/modeling/parameter.py
  gammapy/stats/counts_statistic.py
  gammapy/utils/fits.py
  gammapy/utils/gauss.py
  gammapy/utils/interpolation.py
  gammapy/utils/random/inverse_cdf.py
  gammapy/utils/registry.py
Labels: feature

#4726 Introduce a function to compute the point-to-point fractional variance
  gammapy/estimators/tests/test_utils.py
  gammapy/estimators/utils.py
  gammapy/stats/__init__.py
  gammapy/stats/tests/test_variability.py
  gammapy/stats/variability.py
Labels: feature

#4805 Description of the arguments of the class `Observation'
  gammapy/data/observations.py
Labels: cleanup, docs, coding sprint

#4804 Simple fix for reinitialising observation type
  gammapy/makers/background/reflected.py
Labels: cleanup, performance, coding sprint

#4807 Fix the case of none `counts_off` for the function `to_map_dataset`
  gammapy/datasets/map.py
  gammapy/datasets/tests/test_map.py
  gammapy/makers/background/reflected.py
Labels: bug, coding sprint

#4668 Multidimensional geom support in SkyModel.integrate_geom and evaluate_geom
  gammapy/maps/coord.py
  gammapy/modeling/models/cube.py
  gammapy/modeling/models/tests/test_cube.py
Labels: feature

#4800 Documentation of `SpectrumDatasetMaker`, `NotImplementedError` methods and cleanup
  gammapy/datasets/map.py
  gammapy/datasets/spectrum.py
  gammapy/makers/background/phase.py
  gammapy/makers/map.py
  gammapy/makers/spectrum.py
  gammapy/maps/axes.py
Labels: cleanup, docs, coding sprint

#4799 Fix plotting for Energy Dependent TemplateSpatialModel
  gammapy/modeling/models/spatial.py
  gammapy/modeling/models/tests/test_spatial.py
Labels: bug, backport-v1.1.x, coding sprint

#4771 Fix broken links within the documentation
  docs/development/doc_howto.rst
  docs/development/index.rst
  docs/development/intro.rst
  docs/development/pigs/pig-012.rst
  docs/development/pigs/pig-018.rst
  docs/development/pigs/pig-024.rst
  docs/getting-started/usage.rst
  docs/references.txt
  docs/user-guide/dl3.rst
  docs/user-guide/howto.rst
  examples/models/spatial/README.rst
  examples/tutorials/analysis-1d/spectral_analysis_rad_max.py
  examples/tutorials/analysis-1d/spectrum_simulation.py
  examples/tutorials/api/models.py
Labels: cleanup, docs

#4824 Correct CI issue
  gammapy/modeling/models/tests/test_spatial.py
Labels: bug, infrastructure, coding sprint

#4823 Backport PR #4799 on branch v1.1.x (Fix plotting for Energy Dependent TemplateSpatialModel)
  gammapy/modeling/models/spatial.py
  gammapy/modeling/models/tests/test_spatial.py
Labels: bug, backport-v1.1.x, coding sprint

#4825 fixing broken link
  gammapy/modeling/models/cube.py
Labels: docs, coding sprint

#4809 Fix WSTAT docs
  docs/user-guide/stats/index.rst
  docs/user-guide/stats/wstat_derivation.rst
Labels: cleanup, backport-v1.0.x, backport-v1.1.x, coding sprint

#4738 Introduce Observation metadata container
  gammapy/data/__init__.py
  gammapy/data/metadata.py
  gammapy/data/observations.py
  gammapy/data/tests/test_metadata.py
  gammapy/data/tests/test_observations.py
  gammapy/utils/metadata.py
Labels: feature, coding sprint

#4814 Introduce a function to compute the doubling/halving time for a lightcurve
  gammapy/estimators/tests/test_utils.py
  gammapy/estimators/utils.py
  gammapy/stats/__init__.py
  gammapy/stats/tests/test_variability.py
  gammapy/stats/variability.py
Labels: feature, coding sprint

#4822 Add a function to delete a time interval from GTI
  gammapy/data/gti.py
  gammapy/data/tests/test_gti.py
Labels: feature, coding sprint

#4831 fix vmin vmax to (0, 1) when plotting mask
  gammapy/maps/wcs/ndmap.py
  gammapy/maps/wcs/tests/test_ndmap.py
Labels: cleanup, coding sprint

#4620 Adding prior class
  gammapy/modeling/__init__.py
  gammapy/modeling/models/__init__.py
  gammapy/modeling/models/core.py
  gammapy/modeling/models/prior.py
  gammapy/modeling/models/tests/test_prior.py
  gammapy/modeling/parameter.py
  gammapy/modeling/tests/test_parameter.py
Labels: feature

#4844 Fixing observation copy example
  gammapy/data/observations.py
Labels: cleanup, docs, coding sprint

#4813 Fix the stacking of `DatasetsMaker`
  gammapy/makers/reduce.py
  gammapy/makers/tests/test_reduce.py
  gammapy/utils/parallel.py
Labels: bug, coding sprint

#4857 Correct issue #4856
  gammapy/data/observations.py
  gammapy/data/tests/test_observations.py
Labels: bug

#4837 Add checksum argument to gammapy products write functions
  gammapy/data/event_list.py
  gammapy/data/observations.py
  gammapy/data/tests/test_event_list.py
  gammapy/data/tests/test_observations.py
  gammapy/datasets/core.py
  gammapy/datasets/flux_points.py
  gammapy/datasets/io.py
  gammapy/datasets/map.py
  gammapy/datasets/spectrum.py
  gammapy/datasets/tests/test_map.py
  gammapy/datasets/tests/test_spectrum.py
  gammapy/irf/core.py
  gammapy/maps/core.py
  gammapy/maps/maps.py
  gammapy/maps/region/ndmap.py
  gammapy/maps/wcs/tests/test_ndmap.py
Labels: feature, coding sprint

#4821 Adapt tutorials to include PowerLawNormSpectralModel in the FoVBackgroundMaker
  docs/user-guide/makers/fov.rst
  examples/tutorials/api/makers.py
Labels: cleanup, docs, coding sprint

#4864 Fix small typo in the docstring of the Cash likelihood
  gammapy/stats/fit_statistics.py
Labels: docs, backport-v1.0.x, backport-v1.1.x

#4865 Backport PR #4864 on branch v1.0.x (Fix small typo in the docstring of the Cash likelihood)
  gammapy/stats/fit_statistics.py
Labels: docs, backport-v1.0.x, backport-v1.1.x

#4866 Backport PR #4864 on branch v1.1.x (Fix small typo in the docstring of the Cash likelihood)
  gammapy/stats/fit_statistics.py
Labels: docs, backport-v1.0.x, backport-v1.1.x

#4862 Fixing warning raised when generating the documentation
  examples/models/spectral/plot_absorbed.py
  examples/models/spectral/plot_exp_cutoff_powerlaw_norm_spectral.py
  examples/models/spectral/plot_logparabola_norm_spectral.py
  examples/models/spectral/plot_powerlaw_norm_spectral.py
  examples/tutorials/analysis-1d/extended_source_spectral_analysis.py
  examples/tutorials/analysis-1d/sed_fitting.py
  examples/tutorials/analysis-2d/detect.py
  examples/tutorials/analysis-3d/event_sampling.py
  examples/tutorials/analysis-time/pulsar_analysis.py
  examples/tutorials/api/astro_dark_matter.py
  gammapy/catalog/core.py
  gammapy/catalog/fermi.py
  gammapy/catalog/hess.py
  gammapy/catalog/lhaaso.py
  gammapy/estimators/map/excess.py
  gammapy/modeling/models/spatial.py
Labels: cleanup, docs

#4854 Notebook to sphinx-gallery script
  dev/ipynb_to_gallery.py
  docs/development/dev_howto.rst
  environment-dev.yml
Labels: feature, docs

#4863 Import ray only when asked
  gammapy/utils/parallel.py
Labels: bug, backport-v1.1.x

#4873 Backport PR #4863 on branch v1.1.x (Import ray only when asked)
  gammapy/utils/parallel.py
Labels: bug, backport-v1.1.x

#4881 Remove fit from events sampling tutorial
  examples/tutorials/analysis-3d/event_sampling.py
Labels: docs, backport-v1.0.x, backport-v1.1.x

#4876 Add missing @property on PointSpatialModel.is_energy_dependent
  gammapy/modeling/models/spatial.py
  gammapy/modeling/models/tests/test_spatial.py
Labels: bug, backport-v1.0.x, backport-v1.1.x

#4882 Backport PR #4876 on branch v1.0.x (Add missing @property on PointSpatialModel.is_energy_dependent)
  gammapy/modeling/models/spatial.py
  gammapy/modeling/models/tests/test_spatial.py
Labels: bug, backport-v1.0.x, backport-v1.1.x

#4883 Backport PR #4876 on branch v1.1.x (Add missing @property on PointSpatialModel.is_energy_dependent)
  gammapy/modeling/models/spatial.py
  gammapy/modeling/models/tests/test_spatial.py
Labels: bug, backport-v1.0.x, backport-v1.1.x
