Repository gammapy/gammapy, pull requests merged in 2023-05, with the labels that each got.

#4493 Update docstring in reflected regions
  gammapy/makers/background/reflected.py
Labels: docs, backport-v1.0.x

#4494 Backport PR #4493 on branch v1.0.x (Update docstring in reflected regions)
  gammapy/makers/background/reflected.py
Labels: docs, backport-v1.0.x

#4458 adding weights option to fill_events
  gammapy/maps/core.py
  gammapy/maps/region/tests/test_ndmap.py
  gammapy/maps/tests/test_counts.py
Labels: feature

#4428 Add .to_string() to axis y/xlabel
  docs/user-guide/astro/population/plot_spiral_arm_models.py
  docs/user-guide/astro/population/plot_spiral_arms.py
  docs/user-guide/astro/population/plot_velocity_distributions.py
  examples/tutorials/analysis-1d/cta_sensitivity.py
  gammapy/data/event_list.py
  gammapy/datasets/flux_points.py
  gammapy/estimators/points/core.py
  gammapy/estimators/profile.py
  gammapy/irf/background.py
  gammapy/irf/edisp/kernel.py
  gammapy/irf/effective_area.py
  gammapy/irf/psf/core.py
  gammapy/irf/psf/map.py
  gammapy/irf/rad_max.py
  gammapy/maps/axes.py
  gammapy/maps/region/ndmap.py
  gammapy/modeling/models/spectral.py
  gammapy/visualization/utils.py
Labels: cleanup

#4442 Add stack option to npred_signal()
  gammapy/datasets/map.py
  gammapy/datasets/tests/test_map.py
  gammapy/datasets/tests/test_spectrum.py
  gammapy/estimators/flux.py
Labels: feature

#4216 Add TestStatisticNested class
  gammapy/modeling/selection.py
  gammapy/modeling/tests/test_selection.py
  gammapy/stats/__init__.py
Labels: feature

#4208 Add PiecewiseNormSpatialModel
  examples/models/spatial/plot_piecewise_norm_spatial.py
  gammapy/modeling/models/__init__.py
  gammapy/modeling/models/spatial.py
  gammapy/modeling/models/tests/test_cube.py
  gammapy/modeling/models/tests/test_spatial.py
Labels: feature

#4280 Allow to load observations with only IRFs defined
  gammapy/data/data_store.py
  gammapy/data/tests/test_data_store.py
Labels: feature

#4326 Introduce internal data model for GTI
  gammapy/data/gti.py
  gammapy/data/tests/test_event_list.py
  gammapy/data/tests/test_gti.py
  gammapy/datasets/io.py
  gammapy/datasets/map.py
  gammapy/datasets/simulate.py
  gammapy/datasets/tests/test_flux_points.py
  gammapy/datasets/tests/test_simulate.py
  gammapy/datasets/tests/test_spectrum.py
  gammapy/estimators/map/core.py
  gammapy/estimators/map/tests/test_core.py
  gammapy/estimators/points/tests/test_lightcurve.py
  gammapy/makers/tests/test_spectrum.py
  gammapy/makers/tests/test_utils.py
  gammapy/utils/time.py
Labels: feature, api-change

#4502 Typo in my name in the release notes file v1.0.1
  docs/release-notes/v1.0.1.rst
Labels: bug, docs, backport-v1.0.x

#4503 Backport PR #4502 on branch v1.0.x (Typo in my name in the release notes file v1.0.1)
  docs/release-notes/v1.0.1.rst
Labels: bug, docs, backport-v1.0.x

#4504 Deprecate Fit.minuit member
  examples/tutorials/api/fitting.py
  gammapy/estimators/points/tests/test_lightcurve.py
  gammapy/estimators/points/tests/test_sed.py
  gammapy/modeling/fit.py
  gammapy/modeling/iminuit.py
  gammapy/modeling/tests/test_fit.py
Labels: cleanup

#4483 Suppress some matplotlib outputs in tutorials
  examples/tutorials/analysis-1d/cta_sensitivity.py
  examples/tutorials/analysis-1d/extended_source_spectral_analysis.py
  examples/tutorials/analysis-1d/sed_fitting.py
  examples/tutorials/analysis-1d/spectral_analysis.py
  examples/tutorials/analysis-1d/spectral_analysis_hli.py
  examples/tutorials/analysis-1d/spectral_analysis_rad_max.py
  examples/tutorials/analysis-1d/spectrum_simulation.py
  examples/tutorials/analysis-2d/detect.py
  examples/tutorials/analysis-2d/modeling_2D.py
  examples/tutorials/analysis-2d/ring_background.py
  examples/tutorials/analysis-3d/analysis_3d.py
  examples/tutorials/analysis-3d/analysis_mwl.py
  examples/tutorials/analysis-3d/cta_data_analysis.py
  examples/tutorials/analysis-3d/event_sampling.py
  examples/tutorials/analysis-3d/flux_profiles.py
  examples/tutorials/analysis-3d/simulate_3d.py
  examples/tutorials/analysis-time/light_curve.py
  examples/tutorials/analysis-time/light_curve_simulation.py
  examples/tutorials/analysis-time/pulsar_analysis.py
  examples/tutorials/api/astro_dark_matter.py
  examples/tutorials/api/catalog.py
  examples/tutorials/api/datasets.py
  examples/tutorials/api/fitting.py
  examples/tutorials/api/makers.py
  examples/tutorials/api/maps.py
  examples/tutorials/api/mask_maps.py
  examples/tutorials/api/model_management.py
  examples/tutorials/api/models.py
  examples/tutorials/data/cta.py
  examples/tutorials/data/fermi_lat.py
  examples/tutorials/data/hawc.py
  examples/tutorials/data/hess.py
  examples/tutorials/starting/analysis_1.py
  examples/tutorials/starting/analysis_2.py
  examples/tutorials/starting/overview.py
Labels: docs

#4500 Fix SpectrumDatasetOnOff.stat_sum to support when counts_off is None
  gammapy/datasets/map.py
  gammapy/datasets/tests/test_spectrum.py
Labels: bug, backport-v1.0.x

#4507 Update dev docs for sphinx gallery
  docs/development/doc_howto.rst
Labels: bug, cleanup, docs, backport-v1.0.x

#4512 Backport PR #4507 on branch v1.0.x (Update dev docs for sphinx gallery)
  docs/development/doc_howto.rst
Labels: bug, cleanup, docs, backport-v1.0.x

#3885 Add TemplateNpredModel auto-write on models.write()
  gammapy/modeling/models/core.py
  gammapy/modeling/models/cube.py
  gammapy/modeling/models/spatial.py
  gammapy/modeling/models/tests/data/examples.yaml
  gammapy/modeling/models/tests/test_cube.py
  gammapy/modeling/models/tests/test_io.py
Labels: bug, feature

#4510 Introduce WcsNDMap.cutout_and_mask_region
  gammapy/maps/region/geom.py
  gammapy/maps/wcs/geom.py
  gammapy/maps/wcs/ndmap.py
Labels: feature

#4508 Implement WcsNDMap.to_region_nd_map_histogram
  gammapy/maps/wcs/ndmap.py
  gammapy/maps/wcs/tests/test_ndmap.py
Labels: feature

#4406 Add configuration and helper function to run multiprocessing or ray
  environment-dev.yml
  gammapy/analysis/core.py
  gammapy/conftest.py
  gammapy/estimators/map/tests/test_ts.py
  gammapy/estimators/map/ts.py
  gammapy/estimators/points/lightcurve.py
  gammapy/estimators/points/sed.py
  gammapy/estimators/points/tests/test_lightcurve.py
  gammapy/estimators/points/tests/test_sed.py
  gammapy/makers/reduce.py
  gammapy/makers/tests/test_reduce.py
  gammapy/scripts/info.py
  gammapy/utils/parallel.py
  gammapy/utils/pbar.py
  gammapy/utils/tests/test_parallel.py
  setup.cfg
Labels: feature, cleanup, performance

#4418 Update the `_evaluate_timevar_source` function in `MapDatasetEventSampler`
  gammapy/datasets/simulate.py
  gammapy/datasets/tests/test_simulate.py
  gammapy/estimators/flux.py
  gammapy/maps/axes.py
  gammapy/modeling/models/cube.py
  gammapy/modeling/models/temporal.py
  gammapy/modeling/models/tests/test_io.py
  gammapy/modeling/models/tests/test_temporal.py
  gammapy/modeling/models/tests/test_utils.py
  gammapy/modeling/parameter.py
Labels: feature, cleanup

#4519 Add unit tests for TimeMapAxis.from_gti_bounds()
  gammapy/maps/axes.py
  gammapy/maps/tests/test_axes.py
Labels: tests

#4520 Support Astropy 5.3
  gammapy/catalog/tests/test_fermi.py
  gammapy/catalog/tests/test_gammacat.py
  gammapy/catalog/tests/test_hess.py
  gammapy/maps/tests/test_core.py
  gammapy/utils/testing.py
Labels: tests

#4524 Corrected kwargs docstring of plot_grid()
  gammapy/maps/core.py
Labels: cleanup, backport-v1.0.x, backport-v1.1.x

#4526 Backport PR #4524 on branch v1.0.x (Corrected kwargs docstring of plot_grid())
  gammapy/maps/core.py
Labels: cleanup, backport-v1.0.x, backport-v1.1.x

#4513 Npred plot function in tutorials
  examples/tutorials/analysis-3d/analysis_3d.py
  examples/tutorials/analysis-3d/cta_data_analysis.py
  examples/tutorials/starting/analysis_2.py
Labels: docs, backport-v1.1.x

#4496 Backport PR #4486 on branch v1.0.x (Scale handling in temporal models)
  gammapy/datasets/simulate.py
  gammapy/modeling/models/temporal.py
  gammapy/modeling/models/tests/test_temporal.py
Labels: bug

#4529 Correct docstring in LightCurveEstimator
  gammapy/estimators/points/lightcurve.py
Labels: bug, docs, backport-v1.0.x, backport-v1.1.x

#4532 Backport PR #4529 on branch v1.1.x (Correct docstring in LightCurveEstimator)
  gammapy/estimators/points/lightcurve.py
Labels: bug, docs, backport-v1.0.x, backport-v1.1.x

#4530 Backport PR #4520 : Support Astropy 5.3
  gammapy/catalog/tests/test_fermi.py
  gammapy/catalog/tests/test_gammacat.py
  gammapy/catalog/tests/test_hess.py
  gammapy/datasets/map.py
  gammapy/maps/tests/test_core.py
  gammapy/utils/testing.py
Labels: cleanup

#4531 Simplify binsz_irf handling in create_map_dataset_geoms
  gammapy/datasets/map.py
Labels: cleanup, backport-v1.1.x

#4533 Backport PR #4531 on branch v1.1.x (Simplify binsz_irf handling in create_map_dataset_geoms)
  gammapy/datasets/map.py
Labels: cleanup, backport-v1.1.x

#4125 Add script to perform summary of merged PRs and closed issues
  dev/github_summary.py
  environment-dev.yml
Labels: infrastructure, backport-v1.1.x

#4523 Clean up tests
  gammapy/astro/darkmatter/tests/test_spectra.py
  gammapy/catalog/tests/test_fermi.py
  gammapy/catalog/tests/test_gammacat.py
  gammapy/catalog/tests/test_hess.py
  gammapy/estimators/map/tests/test_core.py
  gammapy/irf/edisp/tests/test_map.py
  gammapy/irf/io.py
  gammapy/makers/tests/test_reduce.py
  gammapy/modeling/models/spatial.py
  gammapy/utils/table.py
Labels: cleanup, tests, backport-v1.1.x

#4534 Backport PR #4125 on branch v1.1.x (Add script to perform summary of merged PRs and closed issues )
  dev/github_summary.py
  environment-dev.yml
Labels: infrastructure, backport-v1.1.x

#4535 Backport PR #4523 on branch v1.1.x (Clean up tests)
  gammapy/astro/darkmatter/tests/test_spectra.py
  gammapy/catalog/tests/test_fermi.py
  gammapy/catalog/tests/test_gammacat.py
  gammapy/catalog/tests/test_hess.py
  gammapy/estimators/map/tests/test_core.py
  gammapy/irf/edisp/tests/test_map.py
  gammapy/irf/io.py
  gammapy/makers/tests/test_reduce.py
  gammapy/modeling/models/spatial.py
  gammapy/utils/table.py
Labels: cleanup, tests, backport-v1.1.x

#4538 Backport PR #4537 on branch v1.0.x (Limit astropy version for docs build)
  setup.cfg
Labels: infrastructure, backport-v1.0.x, backport-v1.1.x

#4539 Backport PR #4537 on branch v1.1.x (Limit astropy version for docs build)
  setup.cfg
Labels: infrastructure, backport-v1.0.x, backport-v1.1.x

#4536 Clean up parallel code
  gammapy/estimators/map/tests/test_ts.py
  gammapy/estimators/map/ts.py
  gammapy/estimators/points/lightcurve.py
  gammapy/estimators/points/sed.py
  gammapy/estimators/points/tests/test_sed.py
  gammapy/makers/reduce.py
  gammapy/utils/parallel.py
  gammapy/utils/tests/test_parallel.py
Labels: cleanup, backport-v1.1.x
