Repository gammapy/gammapy, pull requests merged in 2023-03, with the labels that each got.

#4336 Change label units within parentheses to brackets
  docs/user-guide/astro/population/plot_spiral_arm_models.py
  examples/tutorials/analysis-1d/cta_sensitivity.py
  examples/tutorials/analysis-3d/flux_profiles.py
  examples/tutorials/api/fitting.py
  gammapy/data/event_list.py
  gammapy/estimators/points/core.py
  gammapy/estimators/profile.py
  gammapy/irf/background.py
  gammapy/irf/psf/core.py
  gammapy/irf/psf/map.py
  gammapy/visualization/utils.py
Labels: docs, backport-v1.0.x

#4356 Backport PR #4336 on branch v1.0.x (Change label units within parentheses to brackets)
  docs/user-guide/astro/population/plot_spiral_arm_models.py
  examples/tutorials/analysis-1d/cta_sensitivity.py
  examples/tutorials/analysis-3d/flux_profiles.py
  examples/tutorials/api/fitting.py
  gammapy/data/event_list.py
  gammapy/estimators/points/core.py
  gammapy/estimators/profile.py
  gammapy/irf/background.py
  gammapy/irf/psf/core.py
  gammapy/irf/psf/map.py
  gammapy/visualization/utils.py
Labels: docs, backport-v1.0.x

#4353 Modify constraint on scipy
  setup.cfg
Labels: infrastructure, backport-v1.0.x

#4303 Add __str__ on CountStatisticsObjects
  gammapy/stats/counts_statistic.py
  gammapy/stats/tests/test_counts_statistic.py
Labels: feature

#4357 Backport PR #4353 on branch v1.0.x (Modify constraint on scipy)
  setup.cfg
Labels: infrastructure, backport-v1.0.x

#4358 Backport PR #4301 on branch v1.0.x (Add TIMESYS to lightcurve table meta)
  gammapy/estimators/points/core.py
  gammapy/estimators/points/tests/test_lightcurve.py
  gammapy/maps/axes.py
  gammapy/maps/tests/test_axes.py
Labels: bug, backport-v1.0.x

#4354 Improve performance of 1d analyses
  gammapy/datasets/map.py
  gammapy/datasets/utils.py
  gammapy/maps/axes.py
  gammapy/maps/core.py
  gammapy/maps/geom.py
  gammapy/maps/region/geom.py
Labels: performance, backport-v1.0.x

#4361 Backport PR #4354 on branch v1.0.x (Improve performance of 1d analyses)
  gammapy/datasets/map.py
  gammapy/maps/axes.py
  gammapy/maps/core.py
  gammapy/maps/geom.py
  gammapy/maps/region/geom.py
Labels: performance

#4344 Fix norm_only_changed in MapEvaluator
  gammapy/datasets/evaluator.py
  gammapy/datasets/tests/test_evaluator.py
Labels: bug, performance, backport-v1.0.x

#4362 Backport PR #4344 on branch v1.0.x (Fix norm_only_changed in MapEvaluator)
  gammapy/datasets/evaluator.py
  gammapy/datasets/tests/test_evaluator.py
Labels: bug, performance, backport-v1.0.x

#4359 Fix interpolation values_scale in TemplateSpatialModel
  gammapy/maps/wcs/ndmap.py
  gammapy/modeling/models/spatial.py
  gammapy/modeling/models/tests/test_cube.py
  gammapy/modeling/models/tests/test_spatial.py
Labels: bug, backport-v1.0.x

#4363 Backport PR #4359 on branch v1.0.x (Fix interpolation values_scale in TemplateSpatialModel)
  gammapy/maps/wcs/ndmap.py
  gammapy/modeling/models/spatial.py
  gammapy/modeling/models/tests/test_cube.py
  gammapy/modeling/models/tests/test_spatial.py
Labels: bug, backport-v1.0.x

#4346 Add helper functions for delta TS to significance conversion
  gammapy/stats/tests/test_utils.py
  gammapy/stats/utils.py
Labels: feature

#4209 Add support for spatial model correction on background models
  gammapy/modeling/models/cube.py
  gammapy/modeling/models/tests/test_cube.py
Labels: feature

#4364 Update numpy minimal version to 1.21
  setup.cfg
Labels: infrastructure, backport-v1.0.x

#4365 Backport PR #4364 on branch v1.0.x (Update numpy minimal version to 1.21)
  setup.cfg
Labels: infrastructure, backport-v1.0.x

#4366 correcting small typo in 1D spectral analysis energy dependant cut
  examples/tutorials/analysis-1d/spectral_analysis_rad_max.py
Labels: docs, backport-v1.0.x

#4367 Backport PR #4366 on branch v1.0.x (correcting small typo in 1D spectral analysis energy dependant cut)
  examples/tutorials/analysis-1d/spectral_analysis_rad_max.py
Labels: docs, backport-v1.0.x

#4371 Correcting EDispMap docstring example
  docs/release-notes/v1.0.rst
  docs/release-notes/v1.1.rst
  examples/tutorials/analysis-1d/spectrum_simulation.py
  examples/tutorials/analysis-time/light_curve_flare.py
  examples/tutorials/api/makers.py
  examples/tutorials/api/mask_maps.py
  gammapy/irf/edisp/map.py
Labels: bug, docs, backport-v1.0.x

#4372 Merge pull request #4371 from registerrier/prerelease_corrections
  docs/release-notes/v1.0.rst
  examples/tutorials/analysis-1d/spectrum_simulation.py
  examples/tutorials/analysis-time/light_curve_flare.py
  examples/tutorials/api/makers.py
  examples/tutorials/api/mask_maps.py
  gammapy/irf/edisp/map.py
Labels: bug, docs

#4373 Correct IO for FOVALIGN in gammapy.irf
  gammapy/irf/background.py
  gammapy/irf/core.py
  gammapy/irf/io.py
  gammapy/irf/tests/test_background.py
  gammapy/irf/tests/test_effective_area.py
Labels: bug, backport-v1.0.x

#4375 Backport PR #4373 on branch v1.0.x (Correct IO for FOVALIGN in gammapy.irf)
  gammapy/irf/background.py
  gammapy/irf/core.py
  gammapy/irf/io.py
  gammapy/irf/tests/test_background.py
  gammapy/irf/tests/test_effective_area.py
Labels: bug, backport-v1.0.x

#4374 Release notes for v1.0.1
  docs/release-notes/index.rst
  docs/release-notes/v1.0.1.rst
Labels: docs, backport-v1.0.x

#4377 Backport PR #4374 on branch v1.0.x (Release notes for v1.0.1)
  docs/release-notes/index.rst
  docs/release-notes/v1.0.1.rst
Labels: docs, backport-v1.0.x

#4370 Implement the _sample_coord_time_energy function in MapDatasetEventSampler
  gammapy/datasets/simulate.py
  gammapy/datasets/tests/test_simulate.py
Labels: feature

#4385 Backport PR #4384 on branch v1.0.x (Correct default in FluxPointsEstimator)
  gammapy/estimators/points/sed.py
Labels: bug, docs, backport-v1.0.x

#4382 Fix error message in interp_to_geom()
  .pre-commit-config.yaml
  gammapy/maps/core.py
Labels: bug, backport-v1.0.x

#4306 Add a parameter with is_norm=True for PiecewiseNormSpectralModel
  gammapy/modeling/models/spectral.py
  gammapy/modeling/models/tests/test_io.py
  gammapy/modeling/models/tests/test_spectral.py
Labels: bug

#4400 Impose maximal ipywidget version
  setup.cfg
Labels: bug, infrastructure, backport-v1.0.x

#4397 Fix plot_spectrum_datasets_off_regions with too many regions
  gammapy/maps/axes.py
  gammapy/maps/region/ndmap.py
  gammapy/visualization/utils.py
Labels: bug, backport-v1.0.x

#4405 Adding more documentation on datasets docstring
  gammapy/datasets/core.py
  gammapy/datasets/flux_points.py
  gammapy/datasets/map.py
  gammapy/datasets/spectrum.py
Labels: cleanup, docs, backport-v1.0.x

#4410 Backport PR #4397 on branch v1.0.x (Fix plot_spectrum_datasets_off_regions with too many regions)
  gammapy/maps/axes.py
  gammapy/maps/region/ndmap.py
  gammapy/visualization/utils.py
Labels: bug, backport-v1.0.x

#4411 Backport PR #4405 on branch v1.0.x (Adding more documentation on datasets docstring)
  gammapy/datasets/core.py
  gammapy/datasets/flux_points.py
  gammapy/datasets/map.py
  gammapy/datasets/spectrum.py
Labels: cleanup, docs, backport-v1.0.x

#4380 Adapt default offset for plotting point like IRFs
  gammapy/irf/edisp/core.py
  gammapy/irf/effective_area.py
Labels: cleanup, backport-v1.0.x

#4393 Iminuit output
  gammapy/modeling/iminuit.py
Labels: bug, backport-v1.0.x

#4391 Small notice for beginner in the tutorials page
  examples/tutorials/README.rst
Labels: docs, backport-v1.0.x

#4424 Modify dev doc
  docs/development/dev_howto.rst
  docs/development/release.rst
Labels: docs

#4423 Backport PR #4391 on branch v1.0.x (Small notice for beginner in the tutorials page)
  examples/tutorials/README.rst
Labels: docs, backport-v1.0.x

#4413 Backport PR #4380 on branch v1.0.x (Adapt default offset for plotting point like IRFs)
  gammapy/irf/edisp/core.py
  gammapy/irf/effective_area.py
Labels: cleanup, backport-v1.0.x

#4435 Fix wrong ticks in `rad_max` plot
  gammapy/irf/rad_max.py
Labels: bug, backport-v1.0.x

#4436 Backport PR #4435 on branch v1.0.x (Fix wrong ticks in `rad_max` plot)
  gammapy/irf/rad_max.py
Labels: bug, backport-v1.0.x

#4434 Add --file option to conda env update
  docs/development/intro.rst
Labels: bug, backport-v1.0.x

#4430 Add squash method to LabelMapAxis
  gammapy/maps/axes.py
  gammapy/maps/tests/test_axes.py
Labels: feature

#4429 Fix CI fail in test_spectrum
  gammapy/makers/tests/test_spectrum.py
  gammapy/modeling/models/tests/test_spectral.py
Labels: tests, backport-v1.0.x

#4439 Backport PR #4429 on branch v1.0.x (Fix CI fail in test_spectrum)
  gammapy/makers/tests/test_spectrum.py
  gammapy/modeling/models/tests/test_spectral.py
Labels: tests, backport-v1.0.x
