Repository gammapy/gammapy, pull requests merged in 2023-01, with the labels that each got.

#4191 Modified Dark Matter Jfactor Computation and Dark Matter Tutorial
  examples/tutorials/api/astro_dark_matter.py
  gammapy/astro/darkmatter/profiles.py
  gammapy/astro/darkmatter/tests/test_utils.py
  gammapy/astro/darkmatter/utils.py
  gammapy/modeling/models/tests/test_io.py
Labels: bug

#4212 Remove unneeded table util function
  gammapy/catalog/core.py
  gammapy/datasets/core.py
  gammapy/estimators/points/sed.py
  gammapy/modeling/fit.py
  gammapy/modeling/parameter.py
  gammapy/utils/table.py
  gammapy/utils/tests/test_table.py
Labels: cleanup, api-change

#4252 Map dataset on off in phase maker
  gammapy/makers/background/phase.py
  gammapy/makers/background/tests/test_phase.py
Labels: feature

#4270 Correct doc string in MapAxis.from_edges
  gammapy/maps/axes.py
Labels: cleanup, docs, backport-v1.0.x

#4269 Use linebreaks in passenv list in tox.ini
  .github/workflows/ci.yml
  tox.ini
Labels: cleanup

#4271 Backport PR #4270 on branch v1.0.x (Correct doc string in MapAxis.from_edges)
  gammapy/maps/axes.py
Labels: cleanup, docs, backport-v1.0.x

#4273 Small update of the readme
  README.rst
Labels: docs

#4274 Minor fix in git command
  docs/development/intro.rst
Labels: docs

#4264 Deprecate load_cta_irfs, replace usage with load_irf_dict_from_file
  docs/user-guide/irf/index.rst
  examples/tutorials/analysis-1d/cta_sensitivity.py
  examples/tutorials/analysis-1d/spectrum_simulation.py
  examples/tutorials/analysis-3d/event_sampling.py
  examples/tutorials/analysis-3d/simulate_3d.py
  examples/tutorials/analysis-time/light_curve_simulation.py
  examples/tutorials/data/cta.py
  gammapy/data/tests/test_observations.py
  gammapy/datasets/tests/test_simulate.py
  gammapy/estimators/points/tests/test_sed.py
  gammapy/irf/io.py
  gammapy/irf/psf/map.py
  gammapy/irf/tests/test_io.py
Labels: cleanup

#4284 Allow tox=4 for v1.0.x CI
  .github/workflows/ci.yml
  setup.cfg
  tox.ini
Labels: infrastructure

#4268 Add an HowTo for the fit non-convergence
  docs/user-guide/howto.rst
Labels: docs, backport-v1.0.x

#4285 Backport PR #4268 on branch v1.0.x (Add an HowTo for the fit non-convergence)
  docs/user-guide/howto.rst
Labels: docs, backport-v1.0.x

#4275 Remove safe mask in background stacking
  gammapy/datasets/map.py
  gammapy/datasets/tests/test_map.py
Labels: bug, effort-low, backport-v1.0.x

#4288 Add MapDatasetOnOff type test and associated error for TSMapEstimator
  gammapy/estimators/map/tests/test_ts.py
  gammapy/estimators/map/ts.py
Labels: cleanup

#4290 Backport PR #4275 on branch v1.0.x (Remove safe mask in background stacking)
  gammapy/datasets/map.py
  gammapy/datasets/tests/test_map.py
Labels: bug, effort-low, backport-v1.0.x

#4278 Fix bkgs spectral model io
  gammapy/modeling/models/cube.py
  gammapy/modeling/models/tests/test_io.py
Labels: bug, backport-v1.0.x

#4291 Backport PR #4278 on branch v1.0.x (Fix bkgs spectral model io)
  gammapy/modeling/models/cube.py
  gammapy/modeling/models/tests/test_io.py
Labels: bug, backport-v1.0.x

#4289 gammapy.maps cleanup: move Map.apply_edisp to gammapy.datasets
  gammapy/datasets/evaluator.py
  gammapy/datasets/tests/test_utils.py
  gammapy/datasets/utils.py
  gammapy/maps/core.py
  gammapy/maps/region/tests/test_ndmap.py
Labels: cleanup, api-change

#4276 Allow to set psf max radius in evaluator
  gammapy/datasets/evaluator.py
Labels: bug, backport-v1.0.x

#4293 Backport PR #4276 on branch v1.0.x (Allow to set psf max radius in evaluator)
  gammapy/datasets/evaluator.py
Labels: bug, backport-v1.0.x

#4297 Modified ExcessMapEstimator docstring
  gammapy/estimators/map/excess.py
Labels: cleanup, docs, backport-v1.0.x

#4298 Backport PR #4297 on branch v1.0.x (Modified ExcessMapEstimator docstring)
  gammapy/estimators/map/excess.py
Labels: cleanup, docs, backport-v1.0.x
