Repository gammapy/gammapy, pull requests merged in 2024-02, with the labels that each got.

#5055 Add function to scale colorbar height
  examples/tutorials/analysis-2d/detect.py
  examples/tutorials/analysis-2d/ring_background.py
  examples/tutorials/analysis-time/pulsar_analysis.py
  examples/tutorials/api/irfs.py
  gammapy/datasets/map.py
  gammapy/irf/background.py
  gammapy/irf/edisp/core.py
  gammapy/irf/edisp/kernel.py
  gammapy/irf/effective_area.py
  gammapy/irf/psf/core.py
  gammapy/maps/wcs/ndmap.py
  gammapy/visualization/__init__.py
  gammapy/visualization/tests/test_utils.py
  gammapy/visualization/utils.py
Labels: feature

#4832 Introduce `EventListMetaData` Part 1/2
  gammapy/data/__init__.py
  gammapy/data/event_list.py
  gammapy/data/metadata.py
  gammapy/data/tests/test_event_list.py
  gammapy/data/tests/test_metadata.py
Labels: feature, coding sprint

#5070 Backport PR #5068 on branch v1.0.x (Bump codecov/codecov-action from 3 to 4)
  .github/workflows/ci.yml
Labels: backport-v1.0.x, backport-v1.1.x, dependencies

#5060 TODO: wcs bug in `WcsGeom.from_header`
  gammapy/maps/wcs/geom.py
  gammapy/maps/wcs/tests/test_geom.py
Labels: cleanup

#5071 Backport PR #5068 on branch v1.1.x (Bump codecov/codecov-action from 3 to 4)
  .github/workflows/ci.yml
Labels: backport-v1.0.x, backport-v1.1.x, dependencies

#5072 Backport PR #5069 on branch v1.1.x (Bump peter-evans/repository-dispatch from 2 to 3)
  .github/workflows/dispatch.yml
  .github/workflows/dispatch_benchmark.yml
  .github/workflows/release.yml
Labels: backport-v1.0.x, backport-v1.1.x, dependencies

#5035 Fixing the different behavior of FluxMaps.slice_by_coord for MapAxis and TimeMapAxis
  gammapy/estimators/map/core.py
  gammapy/estimators/map/tests/test_core.py
  gammapy/maps/axes.py
  gammapy/maps/tests/test_axes.py
Labels: cleanup

#5067 Fix tutorial `plt.show()` not showing figures
  examples/tutorials/api/datasets.py
  examples/tutorials/api/mask_maps.py
  examples/tutorials/api/observation_clustering.py
  examples/tutorials/data/cta.py
Labels: docs

#5062 Propagate temporal model format
  gammapy/modeling/models/temporal.py
  gammapy/modeling/models/tests/test_temporal.py
Labels: bug

#5007 Add functionality to rebin flux points
  examples/tutorials/analysis-time/light_curve_flare.py
  gammapy/estimators/points/core.py
  gammapy/estimators/points/tests/test_core.py
  gammapy/estimators/tests/test_utils.py
  gammapy/estimators/utils.py
Labels: feature

#5074 Adapt notebook to show rebinning
  examples/tutorials/analysis-time/Variability_estimation.py
Labels: docs

#4853 Add MapDatasetMetaData container
  gammapy/datasets/__init__.py
  gammapy/datasets/map.py
  gammapy/datasets/metadata.py
  gammapy/datasets/tests/test_map.py
  gammapy/datasets/tests/test_metadata.py
  gammapy/makers/map.py
  gammapy/makers/tests/test_map.py
  gammapy/utils/fits.py
  gammapy/utils/tests/test_metadata.py
Labels: feature

#4993 Add support for checksum in yaml files
  gammapy/datasets/core.py
  gammapy/datasets/tests/test_io.py
  gammapy/datasets/tests/test_map.py
  gammapy/modeling/models/core.py
  gammapy/modeling/models/tests/test_io.py
  gammapy/utils/check.py
  gammapy/utils/scripts.py
  gammapy/utils/tests/test_check.py
  gammapy/utils/tests/test_scripts.py
Labels: feature

#4867 Addition of the class `FluxMetaData`
  gammapy/data/metadata.py
  gammapy/data/tests/test_metadata.py
  gammapy/estimators/__init__.py
  gammapy/estimators/metadata.py
  gammapy/estimators/tests/test_metadata.py
  gammapy/utils/metadata.py
  gammapy/utils/tests/test_metadata.py
Labels: feature

#5083 Add TimeInfoMetaData
  gammapy/data/metadata.py
  gammapy/data/observations.py
  gammapy/data/tests/test_metadata.py
  gammapy/datasets/tests/test_simulate.py
  gammapy/utils/metadata.py
  gammapy/utils/tests/test_metadata.py
Labels: feature

#5082 Fix loading `FoVBackgroundModel` from dict
  gammapy/modeling/models/cube.py
  gammapy/modeling/models/tests/test_spatial.py
Labels: bug, backport-v1.1.x

#5088 Fix TemplateSpatialModel lon_0 and lat_0 default
  gammapy/modeling/models/spatial.py
  gammapy/modeling/models/tests/test_spatial.py
Labels: bug

#5089 Fix another NoOverlapError in spatial model integrate_geom
  gammapy/maps/wcs/tests/test_ndmap.py
  gammapy/modeling/models/spatial.py
Labels: bug, backport-v1.0.x, backport-v1.1.x

#5081 Add checksum verification on FITS file read
  gammapy/data/event_list.py
  gammapy/data/gti.py
  gammapy/data/observations.py
  gammapy/data/tests/test_observations.py
  gammapy/datasets/io.py
  gammapy/datasets/map.py
  gammapy/datasets/spectrum.py
  gammapy/datasets/tests/test_map.py
  gammapy/datasets/tests/test_spectrum.py
  gammapy/estimators/map/core.py
  gammapy/estimators/map/tests/test_core.py
  gammapy/estimators/points/core.py
  gammapy/irf/core.py
  gammapy/irf/edisp/kernel.py
  gammapy/irf/edisp/tests/test_kernel.py
  gammapy/maps/core.py
  gammapy/maps/maps.py
  gammapy/maps/region/ndmap.py
Labels: feature

#5054 Release notes for v1.2
  docs/release-notes/index.rst
  docs/release-notes/v1.2.rst
  docs/release-notes/v1.3.rst
Labels: docs

#5092 Backport PR #5089 on branch v1.0.x (Fix another NoOverlapError in spatial model integrate_geom)
  gammapy/maps/wcs/tests/test_ndmap.py
  gammapy/modeling/models/spatial.py
Labels: bug, backport-v1.0.x, backport-v1.1.x

#5093 Backport PR #5089 on branch v1.1.x (Fix another NoOverlapError in spatial model integrate_geom)
  gammapy/maps/wcs/tests/test_ndmap.py
  gammapy/modeling/models/spatial.py
Labels: bug, backport-v1.0.x, backport-v1.1.x

#5098 Improve the irf tutorial
  examples/tutorials/api/irfs.py
Labels: cleanup, docs, backport-v1.2.x

#5099 Backport PR #5098 on branch v1.2.x (Improve the irf tutorial)
  examples/tutorials/api/irfs.py
Labels: cleanup, docs, backport-v1.2.x

#5096 Fix for sources evaluation outside dataset geom
  gammapy/datasets/evaluator.py
  gammapy/modeling/models/spatial.py
  gammapy/modeling/models/tests/test_spatial.py
Labels: bug, backport-v1.0.x, backport-v1.1.x, backport-v1.2.x

#5100 Backport PR #5096 on branch v1.2.x (Fix for sources evaluation outside dataset geom)
  gammapy/datasets/evaluator.py
  gammapy/modeling/models/spatial.py
  gammapy/modeling/models/tests/test_spatial.py
Labels: bug, backport-v1.0.x, backport-v1.1.x, backport-v1.2.x

#5090 Update citation.cff for v1.2
  CITATION.cff
  codemeta.json
Labels: backport-v1.2.x

#5103 Backport PR #5090 on branch v1.2.x (Update citation.cff for v1.2)
  CITATION.cff
  codemeta.json
Labels: backport-v1.2.x

#5104 Impose numpy <2.0
  setup.cfg
Labels: backport-v1.0.x, backport-v1.1.x, backport-v1.2.x

#5107 Backport PR #5104 on branch v1.2.x (Impose numpy <2.0)
  codemeta.json
  setup.cfg
Labels: infrastructure, backport-v1.0.x, backport-v1.1.x, backport-v1.2.x

#5106 Backport PR #5104 on branch v1.1.x (Impose numpy <2.0)
  setup.cfg
Labels: infrastructure, backport-v1.0.x, backport-v1.1.x, backport-v1.2.x

#5108 Backport PR #5104 on branch v1.0.x (Impose numpy <2.0)
  setup.cfg
Labels: infrastructure

#5105 Expose read_hermes_cube
  docs/api-reference/modeling.rst
  gammapy/modeling/models/__init__.py
  gammapy/modeling/models/utils.py
Labels: docs, backport-v1.2.x

#5110 Prepare release 1.2rc1: citation.cff
  CITATION.cff
  codemeta.json
Labels: backport-v1.2.x

#5111 Backport PR #5110 on branch v1.2.x (Prepare release 1.2rc1: citation.cff)
  CITATION.cff
  codemeta.json
Labels: backport-v1.2.x

#5114 Add an n_event_bunch to sampler classes to alleviate memory issues when sampling bright sources
  gammapy/datasets/simulate.py
  gammapy/datasets/tests/test_simulate.py
  gammapy/irf/edisp/map.py
  gammapy/irf/psf/map.py
Labels: feature, backport-v1.0.x, backport-v1.1.x, backport-v1.2.x

#5116 Backport PR #5114 on branch v1.2.x (Add an n_event_bunch to sampler classes to alleviate memory issues when sampling bright sources)
  gammapy/datasets/simulate.py
  gammapy/datasets/tests/test_simulate.py
  gammapy/irf/edisp/map.py
  gammapy/irf/psf/map.py
Labels: feature, backport-v1.0.x, backport-v1.1.x, backport-v1.2.x

#5119 Adapt `Examples` in docstrings and documentation how to
  docs/development/doc_howto.rst
  gammapy/catalog/gammacat.py
  gammapy/catalog/hess.py
  gammapy/data/gti.py
  gammapy/data/observations.py
  gammapy/datasets/flux_points.py
  gammapy/datasets/map.py
  gammapy/datasets/spectrum.py
  gammapy/estimators/map/excess.py
  gammapy/estimators/map/ts.py
  gammapy/estimators/points/core.py
  gammapy/estimators/points/profile.py
  gammapy/irf/edisp/kernel.py
  gammapy/irf/effective_area.py
  gammapy/irf/psf/map.py
  gammapy/makers/map.py
  gammapy/modeling/models/core.py
  gammapy/modeling/models/spectral_crab.py
  gammapy/modeling/models/temporal.py
  gammapy/modeling/parameter.py
  gammapy/utils/units.py
  gammapy/visualization/utils.py
Labels: cleanup, docs, backport-v1.2.x

#5121 Backport PR #5119 on branch v1.2.x (Adapt `Examples` in docstrings and documentation how to)
  docs/development/doc_howto.rst
  gammapy/catalog/gammacat.py
  gammapy/catalog/hess.py
  gammapy/data/gti.py
  gammapy/data/observations.py
  gammapy/datasets/flux_points.py
  gammapy/datasets/map.py
  gammapy/datasets/spectrum.py
  gammapy/estimators/map/excess.py
  gammapy/estimators/map/ts.py
  gammapy/estimators/points/core.py
  gammapy/estimators/points/profile.py
  gammapy/irf/edisp/kernel.py
  gammapy/irf/effective_area.py
  gammapy/irf/psf/map.py
  gammapy/makers/map.py
  gammapy/modeling/models/core.py
  gammapy/modeling/models/spectral_crab.py
  gammapy/modeling/models/temporal.py
  gammapy/modeling/parameter.py
  gammapy/utils/units.py
  gammapy/visualization/utils.py
Labels: cleanup, docs, backport-v1.2.x

#5122 Fix example and docstrings in irfs
  gammapy/irf/core.py
  gammapy/irf/edisp/kernel.py
  gammapy/irf/edisp/map.py
Labels: cleanup, docs, backport-v1.2.x

#5128 Backport PR #5122 on branch v1.2.x (Fix example and docstrings in irfs)
  gammapy/irf/core.py
  gammapy/irf/edisp/kernel.py
  gammapy/irf/edisp/map.py
Labels: cleanup, docs, backport-v1.2.x

#5117 Fix `meta_table` times for `FixedPointingInfo`
  gammapy/data/pointing.py
Labels: bug, backport-v1.2.x

#5130 Backport PR #5117 on branch v1.2.x (Fix `meta_table` times for `FixedPointingInfo`)
  gammapy/data/pointing.py
Labels: bug, backport-v1.2.x

#5131 Update release notes for v1.2 release
  docs/release-notes/v1.2.rst
  setup.cfg
Labels: backport-v1.2.x

#5133 Final update to citation.cff for v1.2
  CITATION.cff
  codemeta.json
Labels: backport-v1.2.x

#5134 Backport PR #5133 on branch v1.2.x (Final update to citation.cff for v1.2)
  CITATION.cff
  codemeta.json
Labels: backport-v1.2.x
