Repository gammapy/gammapy, pull requests merged in 2024-12, with the labels that each got.

#5629 Update badge link to codecov
  README.rst
Labels: infrastructure

#5577 Add .editorconfig file
  .editorconfig
Labels: infrastructure

#5617 Update release notes from recent release
  docs/development/release.rst
Labels: cleanup, docs

#5640 Helper function for apply_threshold_sensitivity
  gammapy/estimators/map/excess.py
  gammapy/estimators/points/sensitivity.py
  gammapy/estimators/utils.py
Labels: cleanup

#5644 Add ts in combine_significance_maps output
  gammapy/estimators/map/tests/test_excess.py
  gammapy/estimators/utils.py
Labels: cleanup

#5635 Add missing property for MapDataset._background_parameters_changed
  gammapy/datasets/map.py
Labels: bug

#3852 Analysis class cleanup to support future extension of the hli
  gammapy/scripts/main.py
  gammapy/scripts/tests/test_workflow.py
  gammapy/scripts/workflow.py
  gammapy/workflow/__init__.py
  gammapy/workflow/config.py
  gammapy/workflow/config/docs.yaml
  gammapy/workflow/config/example-1d.yaml
  gammapy/workflow/config/example-3d.yaml
  gammapy/workflow/config/model-1d.yaml
  gammapy/workflow/config/model.yaml
  gammapy/workflow/core.py
  gammapy/workflow/steps.py
  gammapy/workflow/tests/__init__.py
  gammapy/workflow/tests/test_config.py
  gammapy/workflow/tests/test_workflow.py
  setup.cfg
Labels: feature, cleanup

#5647 Set apply_irf["edisp"]=False in create_fermi_isotropic_diffuse_model
  gammapy/modeling/models/cube.py
Labels: bug
