Repository gammapy/gammapy, pull requests merged in 2024-03, with the labels that each got.

#5123 Add example to `get_irfs_features`
  gammapy/data/utils.py
Labels: docs

#5146 Fix `geom.energy_mask` docstring
  gammapy/maps/geom.py
Labels: bug, docs

#5138 Add examples to functions in `estimators.utils`
  gammapy/estimators/utils.py
Labels: docs

#5124 Add examples to functions in `utils`
  gammapy/utils/cluster.py
Labels: docs

#5140 Add examples to functions in `estimators`
  gammapy/estimators/energydependentmorphology.py
  gammapy/estimators/parameter.py
  gammapy/estimators/points/sed.py
Labels: docs

#4983 Adjust getting-started page
  docs/getting-started/environments.rst
  docs/getting-started/index.rst
  docs/getting-started/install.rst
  docs/getting-started/quickstart.rst
  docs/getting-started/troubleshooting.rst
  docs/getting-started/usage.rst
  environment-dev.yml
Labels: docs

#5159 Fix FluxPoints.recompute_ul for multidimensional flux points
  gammapy/estimators/points/core.py
  gammapy/estimators/points/tests/test_lightcurve.py
Labels: bug, backport-v1.0.x, backport-v1.1.x, backport-v1.2.x

#5160 Fix select_nested_models if there is no free parameters for the null hypothesis
  gammapy/modeling/selection.py
  gammapy/modeling/tests/test_selection.py
Labels: bug, backport-v1.1.x, backport-v1.2.x

#5168 Backport PR #5129 on branch v1.2.x (Copy on and off phase intervals in `PhaseBackgroundMaker`)
  gammapy/makers/background/phase.py
  gammapy/makers/background/tests/test_phase.py
Labels: backport-v1.2.x

#5166 Backport PR #5160 on branch v1.2.x (Fix select_nested_models if there is no free parameters for the null hypothesis)
  gammapy/modeling/selection.py
  gammapy/modeling/tests/test_selection.py
Labels: bug, backport-v1.1.x, backport-v1.2.x

#5164 Backport PR #5159 on branch v1.2.x (Fix FluxPoints.recompute_ul for multidimensional flux points)
  gammapy/estimators/points/core.py
  gammapy/estimators/points/tests/test_lightcurve.py
Labels: bug, backport-v1.0.x, backport-v1.1.x, backport-v1.2.x

#5167 Fix SourceCatalogObject4FGL.to_models() for DR4
  gammapy/catalog/fermi.py
  gammapy/catalog/tests/test_fermi.py
  gammapy/modeling/models/spatial.py
Labels: bug, backport-v1.2.x

#5172 Backport PR #5167 on branch v1.2.x (Fix SourceCatalogObject4FGL.to_models() for DR4)
  gammapy/catalog/fermi.py
  gammapy/catalog/tests/test_fermi.py
  gammapy/modeling/models/spatial.py
Labels: bug, backport-v1.2.x

#5162 Backport PR #5159 on branch v1.0.x (Fix FluxPoints.recompute_ul for multidimensional flux points)
  gammapy/estimators/points/core.py
  gammapy/estimators/points/tests/test_lightcurve.py
Labels: bug, backport-v1.0.x, backport-v1.1.x, backport-v1.2.x
