Repository gammapy/gammapy, pull requests merged in 2024-01, with the labels that each got.

#5008 Backport PR #5000 on branch v1.0.x (Bump actions/setup-python from 4 to 5)
  .github/workflows/ci.yml
  .github/workflows/release.yml
Labels: backport-v1.0.x, backport-v1.1.x, dependencies

#5009 Backport PR #5000 on branch v1.1.x (Bump actions/setup-python from 4 to 5)
  .github/workflows/ci.yml
  .github/workflows/release.yml
Labels: backport-v1.0.x, backport-v1.1.x, dependencies

#5011 Backport PR #4997 on branch v1.1.x (Fix RootResults default for scipy dev version)
  gammapy/utils/roots.py
Labels: cleanup

#5010 Backport PR #4997 on branch v1.0.x (Fix RootResults default for scipy dev version)
  gammapy/utils/roots.py
Labels: cleanup

#5013 Fix FluxMap.slice_by_coord
  gammapy/estimators/map/core.py
  gammapy/estimators/map/tests/test_core.py
Labels: bug, backport-v1.0.x, backport-v1.1.x

#5018 Small fix in printing OnOFF datasets
  gammapy/datasets/map.py
  gammapy/datasets/tests/test_map.py
Labels: bug

#4998 add ci for python 3.11 noray
  .github/workflows/ci.yml
Labels: infrastructure

#5006 Fix interpolate_profile
  gammapy/estimators/points/tests/test_lightcurve.py
  gammapy/estimators/points/tests/test_sed.py
  gammapy/utils/interpolation.py
Labels: bug, backport-v1.0.x, backport-v1.1.x

#5021 Backport #5006 : Fix interpolate_profile
  gammapy/estimators/points/tests/test_lightcurve.py
  gammapy/estimators/points/tests/test_sed.py
  gammapy/utils/interpolation.py
Labels: bug

#4750 Support pydantic v2.0
  codemeta.json
  environment-dev.yml
  gammapy/analysis/config.py
  gammapy/analysis/core.py
  gammapy/analysis/tests/test_analysis.py
  gammapy/analysis/tests/test_config.py
  gammapy/data/__init__.py
  gammapy/data/metadata.py
  gammapy/data/observations.py
  gammapy/data/tests/test_metadata.py
  gammapy/data/tests/test_observations.py
  gammapy/data/tests/test_pointing.py
  gammapy/datasets/tests/test_map.py
  gammapy/datasets/tests/test_simulate.py
  gammapy/estimators/points/sed.py
  gammapy/maps/core.py
  gammapy/maps/io.py
  gammapy/maps/wcs/core.py
  gammapy/modeling/models/core.py
  gammapy/utils/metadata.py
  gammapy/utils/observers.py
  gammapy/utils/tests/test_metadata.py
  gammapy/utils/types.py
  setup.cfg
Labels: infrastructure

#5024 Remove potential (0, 0) phase interval by check_intervals method
  gammapy/makers/background/phase.py
  gammapy/makers/background/tests/test_phase.py
Labels: cleanup, backport-v1.0.x, backport-v1.1.x

#5023 Adapt tolerance and remove others
  gammapy/datasets/evaluator.py
  gammapy/datasets/map.py
Labels: cleanup, backport-v1.0.x, backport-v1.1.x

#5028 Fix overwrite on TemplateNpredModel
  gammapy/modeling/models/cube.py
  gammapy/modeling/models/tests/test_cube.py
Labels: bug, backport-v1.0.x, backport-v1.1.x

#5027 Fix copy of TemplateSpatialModel when position is not the center of the map
  gammapy/modeling/models/spatial.py
  gammapy/modeling/models/tests/test_spatial.py
Labels: bug

#5029 Fix deprecated min_cut/max_cut for astropy >6.1
  gammapy/maps/wcs/ndmap.py
Labels: bug, backport-v1.0.x, backport-v1.1.x

#5030 Backport PR #5028 on branch v1.1.x (Fix overwrite on TemplateNpredModel)
  gammapy/modeling/models/cube.py
  gammapy/modeling/models/tests/test_cube.py
Labels: bug, backport-v1.0.x, backport-v1.1.x

#5031 Backport PR #5029 on branch v1.0.x (Fix deprecated min_cut/max_cut for astropy >6.1)
  gammapy/maps/wcs/ndmap.py
Labels: bug, backport-v1.0.x, backport-v1.1.x

#5032 Backport PR #5029 on branch v1.1.x (Fix deprecated min_cut/max_cut for astropy >6.1)
  gammapy/maps/wcs/ndmap.py
Labels: bug, backport-v1.0.x, backport-v1.1.x

#5026 Introduction of GTIMetaData
  gammapy/data/gti.py
  gammapy/data/metadata.py
Labels: feature

#3711 Add ObservationsEventsSampler class
  gammapy/data/__init__.py
  gammapy/data/simulate.py
  gammapy/datasets/__init__.py
  gammapy/datasets/map.py
  gammapy/datasets/simulate.py
  gammapy/datasets/tests/test_simulate.py
Labels: feature

#3883 Fix FluxPointsEstimators to support TemplateNPredModel
  gammapy/estimators/map/asmooth.py
  gammapy/estimators/map/ts.py
  gammapy/estimators/points/sed.py
  gammapy/estimators/points/tests/test_sed.py
  gammapy/modeling/models/core.py
  gammapy/modeling/models/cube.py
  gammapy/modeling/models/tests/test_cube.py
Labels: bug

#4975 Reduce memory usage of get_psf_kernel
  gammapy/datasets/tests/test_map.py
  gammapy/estimators/map/tests/test_ts.py
  gammapy/irf/psf/map.py
Labels: performance

#5040 Add degrees of freedom on FluxMaps
  docs/user-guide/estimators.rst
  gammapy/estimators/map/core.py
  gammapy/estimators/points/tests/test_core.py
Labels: feature

#5037 Fix small errors in analysis-time tutorials
  examples/tutorials/analysis-time/Variability_estimation.py
  examples/tutorials/analysis-time/light_curve.py
  examples/tutorials/analysis-time/light_curve_flare.py
  examples/tutorials/analysis-time/light_curve_simulation.py
  examples/tutorials/analysis-time/pulsar_analysis.py
Labels: docs

#4561 Export Datastore to Obscore table
  gammapy/data/ivoa.py
  gammapy/data/tests/test_ivoa.py
Labels: feature

#5015 Examples of radially asymmetric IRFs
  examples/tutorials/api/irfs.py
  gammapy/irf/__init__.py
  gammapy/irf/background.py
  gammapy/makers/tests/test_asymm_irf.py
  gammapy/makers/utils.py
Labels: feature, docs

#4783 Add EnergyDependentMorphologyEstimator
  examples/tutorials/analysis-3d/energy_dependent_estimation.py
  gammapy/estimators/__init__.py
  gammapy/estimators/energydependentmorphology.py
  gammapy/estimators/tests/test_energydependentmorphology.py
Labels: feature

#4615 Improve sensitivity example
  examples/tutorials/analysis-1d/cta_sensitivity.py
Labels: docs

#5045 Modify config definition in modeling_2D
  examples/tutorials/analysis-2d/modeling_2D.py
Labels: docs

#5044 Add stat_null computation on ParameterEstimator
  gammapy/estimators/parameter.py
  gammapy/estimators/points/tests/test_sed.py
  gammapy/estimators/tests/test_parameter_estimator.py
Labels: bug, backport-v1.0.x, backport-v1.1.x

#5036 Include `TimeMapAxis` and `LabelMapAxis` in the documentation
  examples/tutorials/api/maps.py
Labels: docs

#5049 Backport PR #5046 on branch v1.0.x (Background handling in `MapDataset.info_dict()`)
  gammapy/datasets/map.py
Labels: bug, backport-v1.0.x, backport-v1.1.x

#5050 Backport PR #5046 on branch v1.1.x (Background handling in `MapDataset.info_dict()`)
  gammapy/datasets/map.py
Labels: bug, backport-v1.0.x, backport-v1.1.x

#5048 Small cosmetic adaptions to api turorials
  examples/tutorials/api/mask_maps.py
  examples/tutorials/api/model_management.py
  examples/tutorials/api/models.py
  examples/tutorials/api/observation_clustering.py
  examples/tutorials/scripts/survey_map.py
  gammapy/irf/core.py
Labels: cleanup, docs

#5065 Correct CI: Set observatory_location on Observation.read
  gammapy/data/observations.py
  gammapy/data/tests/test_observations.py
Labels: bug
