Repository gammapy/gammapy, pull requests merged in 2024-09, with the labels that each got.

#5433 Sort sampled events by time in `MapDatasetEventSampler`
  gammapy/datasets/simulate.py
  gammapy/datasets/tests/test_simulate.py
Labels: feature, cleanup

#5437 Remove mask in residual plotting
  examples/tutorials/analysis-1d/extended_source_spectral_analysis.py
  examples/tutorials/analysis-1d/spectral_analysis.py
  gammapy/datasets/map.py
  gammapy/datasets/spectrum.py
Labels: feature

#5439 Fix ignored overwrite in datasets.write
  gammapy/datasets/core.py
  gammapy/datasets/tests/test_io.py
Labels: bug

#5435 Add tests for utils/time.py functions
  gammapy/utils/tests/test_time.py
Labels: tests

#5441 Add a warning in TemplateSpatialModel for presence of nan values
  gammapy/modeling/models/spatial.py
  gammapy/modeling/models/tests/test_spatial.py
Labels: bug

#5440 Fix TSmapEstimator stat_scan with sum_over_energy_group=False
  gammapy/estimators/map/tests/test_ts.py
  gammapy/estimators/map/ts.py
Labels: bug
