Repository gammapy/gammapy, pull requests merged in 2024-06, with the labels that each got.

#5284 Update deprecated mamba setup action in CI
  .github/workflows/ci.yml
Labels: infrastructure, backport-v1.0.x, backport-v1.2.x

#5288 Backport PR #5284 on branch v1.2.x (Update deprecated mamba setup action in CI)
  .github/workflows/ci.yml
Labels: infrastructure, backport-v1.0.x, backport-v1.2.x

#5287 Backport PR #5284 on branch v1.0.x (Update deprecated mamba setup action in CI)
  .github/workflows/ci.yml
Labels: infrastructure, backport-v1.0.x, backport-v1.2.x

#5186 Adjust `to_edisp_kernel` input to `MapAxis`
  gammapy/datasets/tests/test_map.py
  gammapy/irf/edisp/core.py
  gammapy/irf/edisp/kernel.py
  gammapy/irf/edisp/tests/test_core.py
Labels: cleanup

#5292 Remove unused lgtm config file
  lgtm.yml
Labels: infrastructure, backport-v1.0.x, backport-v1.2.x

#5293 Backport PR #5292 on branch v1.0.x (Remove unused lgtm config file)
  lgtm.yml
Labels: infrastructure, backport-v1.0.x, backport-v1.2.x

#5294 Backport PR #5292 on branch v1.2.x (Remove unused lgtm config file)
  lgtm.yml
Labels: infrastructure, backport-v1.0.x, backport-v1.2.x

#5300 Fix wrap in PiecewiseNormSpatialModel
  gammapy/modeling/models/spatial.py
  gammapy/modeling/models/tests/test_spatial.py
Labels: bug, backport-v1.0.x, backport-v1.2.x

#5301 Backport PR #5300 on branch v1.2.x (Fix wrap in PiecewiseNormSpatialModel)
  gammapy/modeling/models/spatial.py
  gammapy/modeling/models/tests/test_spatial.py
Labels: bug, backport-v1.0.x, backport-v1.2.x

#5310 Backport PR #5309 on branch v1.2.x (cleanup after #5300)
  gammapy/modeling/models/tests/test_spatial.py
Labels: cleanup, backport-v1.2.x

#5320 Fix parameters unique names
  gammapy/modeling/models/core.py
  gammapy/modeling/models/cube.py
  gammapy/modeling/models/spectral.py
  gammapy/modeling/models/tests/test_io.py
  gammapy/modeling/tests/test_fit.py
Labels: bug, backport-v1.0.x, backport-v1.2.x

#5324 Fix tests fail due to precision
  gammapy/catalog/tests/test_hess.py
Labels: infrastructure, backport-v1.0.x, backport-v1.2.x

#5328 Backport PR #5324 on branch v1.0.x (Fix tests fail due to precision)
  gammapy/catalog/tests/test_hess.py
Labels: infrastructure, backport-v1.0.x, backport-v1.2.x

#5323 Fix covariance for CompoundSpectralModel
  gammapy/modeling/models/spectral.py
  gammapy/modeling/models/tests/test_spectral.py
Labels: bug, backport-v1.0.x, backport-v1.2.x

#5329 Backport PR #5324 on branch v1.2.x (Fix tests fail due to precision)
  gammapy/catalog/tests/test_hess.py
Labels: infrastructure, backport-v1.0.x, backport-v1.2.x

#5322 Backport PR #5320 on branch v1.2.x (Fix parameters unique names)
  gammapy/modeling/models/core.py
  gammapy/modeling/models/cube.py
  gammapy/modeling/models/spectral.py
  gammapy/modeling/models/tests/test_io.py
  gammapy/modeling/tests/test_fit.py
Labels: bug, backport-v1.0.x, backport-v1.2.x

#5330 Backport PR #5323 on branch v1.2.x (Fix covariance for CompoundSpectralModel )
  gammapy/modeling/models/spectral.py
  gammapy/modeling/models/tests/test_spectral.py
Labels: bug, backport-v1.0.x, backport-v1.2.x

#5321 Fix cutout_template_models to work if models is None
  gammapy/datasets/tests/test_utils.py
  gammapy/modeling/models/utils.py
Labels: bug, backport-v1.0.x, backport-v1.2.x

#5332 Backport PR #5321 on branch v1.2.x (Fix cutout_template_models to work if models is None)
  gammapy/datasets/tests/test_utils.py
  gammapy/modeling/models/utils.py
Labels: bug, backport-v1.0.x, backport-v1.2.x

#5298 Coherent units in `TemporalModel.sample_time`
  gammapy/modeling/models/temporal.py
Labels: cleanup, backport-v1.0.x, backport-v1.2.x

#5335 Backport PR #5298 on branch v1.2.x (Coherent units in `TemporalModel.sample_time`)
  gammapy/modeling/models/temporal.py
Labels: cleanup, backport-v1.0.x, backport-v1.2.x

#5317 Fix datasets.models.covariance after fit to match FitResults.models.covariance
  gammapy/datasets/actors.py
  gammapy/datasets/core.py
  gammapy/datasets/tests/test_datasets.py
  gammapy/datasets/tests/test_map.py
  gammapy/modeling/fit.py
  gammapy/modeling/models/core.py
Labels: bug, backport-v1.0.x, backport-v1.2.x

#5337 Backport PR #5317 on branch v1.2.x (Fix datasets.models.covariance after fit to match FitResults.models.covariance)
  gammapy/datasets/actors.py
  gammapy/datasets/core.py
  gammapy/datasets/tests/test_datasets.py
  gammapy/datasets/tests/test_map.py
  gammapy/modeling/fit.py
  gammapy/modeling/models/core.py
Labels: bug, backport-v1.0.x, backport-v1.2.x

#5316 Add CovarianceMixin for multicomponent models classes
  gammapy/modeling/covariance.py
  gammapy/modeling/models/core.py
  gammapy/modeling/models/cube.py
  gammapy/modeling/models/spectral.py
Labels: cleanup

#5279 Add copy method on FluxMaps
  gammapy/estimators/map/core.py
  gammapy/estimators/map/tests/test_core.py
Labels: feature

#5299 Small adaption to appending DM spectra models
  gammapy/astro/darkmatter/__init__.py
  gammapy/astro/darkmatter/spectra.py
Labels: coding sprint

#5327 Temporary fix for CI with numpy 2.0
  environment-dev.yml
  setup.cfg
Labels: infrastructure, backport-v1.2.x

#5350 Adapt `RadMax2D.plot_rad_max_vs_energy`
  gammapy/irf/rad_max.py
Labels: bug, backport-v1.0.x, backport-v1.2.x

#5352 Backport PR #5350 on branch v1.2.x (Adapt `RadMax2D.plot_rad_max_vs_energy`)
  gammapy/irf/rad_max.py
Labels: bug, backport-v1.0.x, backport-v1.2.x
