Repository gammapy/gammapy, pull requests merged in 2025-07, with the labels that each got.

#5965 fix typo in makers tutorial
  examples/tutorials/api/makers.py
Labels: cleanup, docs

#5959 Adapt SafeMaskMaker docstring
  gammapy/makers/safe.py
Labels: cleanup, docs

#5957 Fix #5951
  examples/tutorials/analysis-1d/spectral_analysis.py
Labels: cleanup

#5967 Part 2 - Tutorial cleanup
  examples/tutorials/analysis-3d/analysis_3d.py
  examples/tutorials/analysis-3d/analysis_mwl.py
  examples/tutorials/analysis-3d/cta_data_analysis.py
  examples/tutorials/analysis-3d/energy_dependent_estimation.py
  examples/tutorials/analysis-3d/event_sampling.py
  examples/tutorials/analysis-3d/event_sampling_nrg_depend_models.py
  examples/tutorials/analysis-3d/flux_profiles.py
  examples/tutorials/analysis-3d/simulate_3d.py
  examples/tutorials/analysis-time/light_curve.py
  examples/tutorials/analysis-time/light_curve_flare.py
  examples/tutorials/analysis-time/light_curve_simulation.py
  examples/tutorials/analysis-time/pulsar_analysis.py
  examples/tutorials/analysis-time/time_resolved_spectroscopy.py
Labels: cleanup, docs

#5964 Fix for Issue #5943
  gammapy/data/data_store.py
  gammapy/data/tests/test_data_store.py
Labels: bug

#5743 Helper method for observation selection at Datastore level
  gammapy/data/data_store.py
  gammapy/makers/tests/test_map.py
Labels: feature, SWGO Req.

#5958 Fix TSmapEstimator pad_width
  gammapy/estimators/map/tests/test_ts.py
  gammapy/estimators/map/ts.py
Labels: bug

#5974 Fix links label for CompoundSpectralModel
  gammapy/modeling/models/core.py
  gammapy/modeling/models/tests/test_io.py
Labels: bug

#5968 Part 3 - Tutorial cleanup
  examples/tutorials/api/astro_dark_matter.py
  examples/tutorials/api/catalog.py
  examples/tutorials/api/datasets.py
  examples/tutorials/api/estimators.py
  examples/tutorials/api/fitting.py
  examples/tutorials/api/irfs.py
  examples/tutorials/api/makers.py
  examples/tutorials/api/maps.py
  examples/tutorials/api/mask_maps.py
  examples/tutorials/api/model_management.py
  examples/tutorials/api/models.py
  examples/tutorials/api/nested_sampling_Crab.py
  examples/tutorials/api/observation_clustering.py
  examples/tutorials/api/priors.py
  examples/tutorials/api/theta_square_plot.py
  gammapy/data/observations.py
Labels: cleanup, docs

#5918 Adding VERITAS tutorial
  docs/sphinxext.py
  examples/tutorials/data/veritas.py
Labels: docs

#5993 Fix tutorial page LHS dropdown
  docs/conf.py
  examples/tutorials/data/README.rst
  examples/tutorials/model-gallery/README.rst
Labels: docs

#5927 Add mask plot for spectral
  gammapy/datasets/map.py
Labels: feature

#5934 Estimator documentation: update the n_sigma description
  gammapy/estimators/flux.py
  gammapy/estimators/map/excess.py
  gammapy/estimators/map/ts.py
  gammapy/estimators/parameter.py
  gammapy/estimators/points/core.py
  gammapy/estimators/points/lightcurve.py
  gammapy/estimators/points/sed.py
  gammapy/estimators/utils.py
Labels: docs

#5997 Run doctests
  gammapy/datasets/map.py
  gammapy/datasets/utils.py
  gammapy/estimators/map/excess.py
  gammapy/estimators/map/ts.py
Labels: cleanup, docs

#5855 Utility to filter a table parsing string of logical operations
  gammapy/utils/scripts.py
  gammapy/utils/tests/test_scripts.py
Labels: feature

#5999 Handling non-backward compatible format of the covariance matrix
  gammapy/modeling/models/core.py
  gammapy/modeling/models/tests/test_core.py
Labels: bug

#5979 Fix memory leak related to lru_cache
  docs/api-reference/utils.rst
  gammapy/maps/geom.py
  gammapy/maps/region/geom.py
  gammapy/maps/wcs/geom.py
  gammapy/maps/wcs/tests/test_geom.py
  gammapy/utils/cache.py
Labels: bug, performance, trigger-benchmarks

#5941 Tutorial setup command line option
  examples/tutorials/README.rst
  gammapy/scripts/main.py
  gammapy/scripts/tests/test_tutorial_info.py
  gammapy/scripts/tutorial_info.py
Labels: feature, docs

#5975 Allow configuration of a size_factor in Models.to_regions
  gammapy/modeling/models/core.py
  gammapy/modeling/models/spatial.py
  gammapy/modeling/models/tests/test_core.py
Labels: feature

#5961 Adding description to irf peek functions
  docs/user-guide/references.rst
  gammapy/irf/background.py
  gammapy/irf/edisp/core.py
  gammapy/irf/edisp/kernel.py
  gammapy/irf/edisp/map.py
  gammapy/irf/effective_area.py
  gammapy/irf/psf/kernel.py
  gammapy/irf/psf/map.py
Labels: docs

#6007 Fix doc uniformprior
  gammapy/modeling/models/prior.py
Labels: docs

#5998 Remove tutorial setup
  examples/tutorials/analysis-1d/cta_sensitivity.py
  examples/tutorials/analysis-1d/extended_source_spectral_analysis.py
  examples/tutorials/analysis-1d/spectral_analysis.py
  examples/tutorials/analysis-1d/spectral_analysis_hli.py
  examples/tutorials/analysis-1d/spectral_analysis_rad_max.py
  examples/tutorials/analysis-1d/spectrum_simulation.py
  examples/tutorials/analysis-2d/detect.py
  examples/tutorials/analysis-2d/modeling_2D.py
  examples/tutorials/analysis-2d/ring_background.py
  examples/tutorials/analysis-3d/analysis_3d.py
  examples/tutorials/analysis-3d/analysis_mwl.py
  examples/tutorials/analysis-3d/cta_data_analysis.py
  examples/tutorials/analysis-3d/energy_dependent_estimation.py
  examples/tutorials/analysis-3d/event_sampling.py
  examples/tutorials/analysis-3d/event_sampling_nrg_depend_models.py
  examples/tutorials/analysis-3d/flux_profiles.py
  examples/tutorials/analysis-time/light_curve.py
  examples/tutorials/analysis-time/light_curve_flare.py
  examples/tutorials/analysis-time/light_curve_simulation.py
  examples/tutorials/analysis-time/pulsar_analysis.py
  examples/tutorials/data/cta.py
  examples/tutorials/data/fermi_lat.py
  examples/tutorials/data/hawc.py
  examples/tutorials/data/hess.py
  examples/tutorials/data/veritas.py
Labels: cleanup

#6014 Fix discrepancy in exposure maps unit attached to edsip and psf from FermipyDatasetsReader
  gammapy/datasets/tests/test_io.py
  gammapy/datasets/utils.py
Labels: bug

#5995 Update Fermi-LAT tutorial
  examples/tutorials/data/fermi_lat.py
Labels: docs

#6018 Remove extern
  docs/development/dev_howto.rst
  gammapy/extern/__init__.py
  gammapy/extern/xmltodict.py
Labels: cleanup

#6016 Fix for reco PSF in create_map_dataset_from_dl4
  gammapy/datasets/tests/test_utils.py
  gammapy/datasets/utils.py
Labels: bug

#5949 Adapt tutorial order
  docs/conf.py
  docs/sphinxext.py
  examples/tutorials/analysis-1d/sed_fitting.py
  examples/tutorials/analysis-1d/spectral_analysis.py
  examples/tutorials/analysis-1d/spectral_analysis_rad_max.py
  examples/tutorials/analysis-3d/analysis_3d.py
  examples/tutorials/analysis-3d/event_sampling.py
  examples/tutorials/analysis-time/README.rst
  examples/tutorials/api/README.rst
  examples/tutorials/astrophysics/README.rst
  examples/tutorials/astrophysics/astro_dark_matter.py
  examples/tutorials/astrophysics/ebl.py
  examples/tutorials/astrophysics/energy_dependent_estimation.py
  examples/tutorials/astrophysics/pulsar_analysis.py
  examples/tutorials/details/README.rst
  examples/tutorials/details/catalog.py
  examples/tutorials/details/datasets.py
  examples/tutorials/details/estimators.py
  examples/tutorials/details/fitting.py
  examples/tutorials/details/irfs.py
  examples/tutorials/details/makers.py
  examples/tutorials/details/maps.py
  examples/tutorials/details/mask_maps.py
  examples/tutorials/details/model_management.py
  examples/tutorials/details/models.py
  examples/tutorials/details/nested_sampling_Crab.py
  examples/tutorials/details/observation_clustering.py
  examples/tutorials/details/priors.py
  examples/tutorials/details/theta_square_plot.py
  examples/tutorials/starting/overview.py
  gammapy/irf/core.py
  gammapy/modeling/parameter.py
  gammapy/modeling/sampler.py
Labels: docs

#6022 Add random_variable property on prior
  gammapy/modeling/models/prior.py
Labels: feature, cleanup

#6034 Remove TODO from documentation build
  docs/user-guide/astro/population/index.rst
  docs/user-guide/astro/source/index.rst
  docs/user-guide/utils.rst
  gammapy/catalog/gammacat.py
  gammapy/datasets/core.py
  gammapy/irf/psf/kernel.py
  gammapy/modeling/models/spectral.py
  gammapy/utils/regions.py
Labels: docs

#6033 fix[ci]: ensure linkcheck tox dependencies are installed
  .github/workflows/linkcheck.yml
Labels: infrastructure

#5933 Add tutorial for computing parameter upper limits
  docs/sphinxext.py
  examples/tutorials/details/parameter_ul.py
Labels: docs
