Repository gammapy/gammapy, pull requests merged in 2025-08, with the labels that each got.

#6039 Adapt CTAO tutorial with xmltodict
  examples/tutorials/data/cta.py
Labels: cleanup

#6044 Mention NEP29 guideline for python and numpy support in dev docs
  docs/development/dev_howto.rst
Labels: docs, skip-tests

#6043 Fix docstrings
  docs/api-reference/modeling.rst
  gammapy/datasets/map.py
  gammapy/estimators/energydependentmorphology.py
  gammapy/modeling/models/__init__.py
  gammapy/modeling/models/cube.py
  gammapy/modeling/models/spectral.py
  gammapy/modeling/models/spectral_crab.py
Labels: cleanup, docs, skip-tests

#6038 Vectorized error evaluation of flux uncertainties based on samples
  gammapy/modeling/models/spectral.py
  gammapy/modeling/models/tests/test_spectral.py
Labels: priority-high, performance

#6053 Add mask for PointSkyRegion in geom.region_mask
  gammapy/maps/region/geom.py
  gammapy/maps/wcs/geom.py
  gammapy/maps/wcs/tests/test_geom.py
Labels: bug

#6049 Add info message on geom mismatch
  gammapy/maps/axes.py
  gammapy/maps/region/geom.py
  gammapy/maps/region/tests/test_geom.py
  gammapy/maps/tests/test_axes.py
  gammapy/maps/wcs/geom.py
  gammapy/maps/wcs/tests/test_geom.py
Labels: cleanup

#6058 Adapt the docstring for PSF containment
  gammapy/irf/psf/core.py
  gammapy/irf/psf/parametric.py
Labels: docs

#6064 Docstring formatting
  gammapy/estimators/core.py
  gammapy/estimators/energydependentmorphology.py
  gammapy/estimators/map/core.py
  gammapy/estimators/parameter.py
  gammapy/estimators/points/profile.py
  gammapy/estimators/utils.py
  gammapy/irf/core.py
  gammapy/irf/edisp/kernel.py
  gammapy/irf/edisp/map.py
  gammapy/irf/psf/map.py
  gammapy/makers/background/fov.py
  gammapy/makers/safe.py
  gammapy/makers/utils.py
  gammapy/maps/axes.py
  gammapy/maps/core.py
  gammapy/maps/geom.py
  gammapy/maps/io.py
  gammapy/maps/measure.py
  gammapy/maps/region/ndmap.py
Labels: cleanup, docs

#6067 Docstring formatting part 3
  gammapy/scripts/analysis.py
  gammapy/scripts/download.py
  gammapy/scripts/workflow.py
  gammapy/stats/fit_statistics.py
  gammapy/stats/fit_statistics_jit.py
  gammapy/utils/compilation.py
  gammapy/utils/coordinates/fov.py
  gammapy/utils/docs.py
  gammapy/utils/fits.py
  gammapy/utils/metadata.py
  gammapy/utils/parallel.py
  gammapy/utils/scripts.py
  gammapy/utils/types.py
  gammapy/utils/units.py
  gammapy/visualization/datasets.py
  gammapy/visualization/utils.py
  gammapy/workflow/steps.py
Labels: cleanup, docs

#6073 Backport PR #6071 on branch v2.0.x (Allow passing of `kwargs` to `EventListReader.read`)
  codemeta.json
  gammapy/data/event_list.py
  gammapy/data/tests/test_event_list.py
Labels: cleanup, backport-v2.0.x

#6075 Add list of tutorials to end of H.E.S.S. tutorial
  examples/tutorials/data/hess.py
Labels: docs, backport-v2.0.x

#6076 Backport PR #6075 on branch v2.0.x (Add list of tutorials to end of H.E.S.S. tutorial)
  examples/tutorials/data/hess.py
Labels: docs, backport-v2.0.x

#6079 Backport PR #6055 on branch v2.0.x (Change location and details of rad max tutorial)
  docs/getting-started/index.rst
  docs/sphinxext.py
  docs/user-guide/makers/index.rst
  docs/user-guide/makers/reflected.rst
  examples/tutorials/analysis-1d/spectrum_simulation.py
  examples/tutorials/data/magic.py
Labels: docs, backport-v2.0.x

#6078 Update Nested Sampling tuto with error band from samples
  examples/tutorials/details/nested_sampling_Crab.py
Labels: docs, backport-v2.0.x

#6074 Fix warnings on deprecated license in classifiers and universal bdist wheel options
  setup.cfg
Labels: infrastructure, priority-high, backport-v2.0.x

#6072 Adapt ObservationsEventsSampler.run docstring to observations
  gammapy/data/simulate.py
  gammapy/data/tests/test_simulate.py
  gammapy/datasets/tests/test_simulate.py
Labels: docs, backport-v2.0.x

#6084 Backport PR #6072 on branch v2.0.x (Adapt ObservationsEventsSampler.run docstring to observations)
  gammapy/data/simulate.py
  gammapy/data/tests/test_simulate.py
  gammapy/datasets/tests/test_simulate.py
Labels: docs, backport-v2.0.x

#6061 Workflow to check the building of wheels nightly
  .github/workflows/nightly_builds.yml
Labels: infrastructure, backport-v2.0.x

#6086 Backport PR #6069 on branch v2.0.x (Remove TODO)
  gammapy/estimators/map/core.py
  gammapy/irf/background.py
  gammapy/irf/psf/tests/test_map.py
Labels: cleanup, backport-v2.0.x

#6100 Update installation for windows instruction
  docs/getting-started/environments.rst
Labels: skip-tests, backport-v2.0.x

#6101 Add instrument names in tutorials data section
  examples/tutorials/data/README.rst
Labels: skip-tests, backport-v2.0.x

#6106 Remove deprecated pydantic copy in tutorial
  examples/tutorials/analysis-3d/analysis_3d.py
Labels: docs, skip-tests, backport-v2.0.x

#6095 jupytext requires plt.show
  examples/tutorials/analysis-3d/analysis_3d.py
  examples/tutorials/analysis-time/light_curve_simulation.py
  examples/tutorials/analysis-time/variability_estimation.py
  examples/tutorials/data/hess.py
  examples/tutorials/data/veritas.py
  examples/tutorials/details/datasets.py
  examples/tutorials/details/irfs.py
  examples/tutorials/details/makers.py
Labels: backport-v2.0.x

#6109 Backport PR #6095 on branch v2.0.x (jupytext requires plt.show)
  examples/tutorials/analysis-3d/analysis_3d.py
  examples/tutorials/analysis-time/light_curve_simulation.py
  examples/tutorials/analysis-time/variability_estimation.py
  examples/tutorials/data/hess.py
  examples/tutorials/data/veritas.py
  examples/tutorials/details/datasets.py
  examples/tutorials/details/irfs.py
  examples/tutorials/details/makers.py
Labels: backport-v2.0.x

#6105 Update quickstart.rst for windows installation
  docs/getting-started/quickstart.rst
Labels: backport-v2.0.x

#6094 Fix release notes for v2.0
  docs/release-notes/v2.0.rst
Labels: skip-tests, backport-v2.0.x
