Repository gammapy/gammapy, pull requests merged in 2025-09, with the labels that each got.

#6126 Backport PR #6123 on branch v2.0.x (Bump actions/first-interaction from 2 to 3)
  .github/workflows/greetings.yml
Labels: dependencies

#6027 Correct setup in tutorialjupytexttests.yml
  .github/workflows/tutorialjupytexttests.yml
Labels: infrastructure, docs, skip-tests, skip-docs

#6145 Remove numpy upper limit version constraint in requirements
  setup.cfg
Labels: infrastructure, dependencies

#6141 Add sensitivity for other quantities of the flux maps
  examples/tutorials/analysis-3d/non_detected_source.py
  gammapy/estimators/map/core.py
  gammapy/estimators/map/tests/test_excess.py
  gammapy/estimators/map/tests/test_ts.py
Labels: feature, backport-v2.0.x

#6115 Kwargs updates
  gammapy/estimators/profile.py
  gammapy/maps/hpx/ndmap.py
  gammapy/maps/region/geom.py
  gammapy/maps/wcs/ndmap.py
  gammapy/modeling/models/core.py
  gammapy/modeling/models/spectral.py
Labels: cleanup

#6149 Backport PR #6141 on branch v2.0.x (Add sensitivity for other quantities of the flux maps)
  examples/tutorials/analysis-3d/non_detected_source.py
  gammapy/estimators/map/core.py
  gammapy/estimators/map/tests/test_excess.py
  gammapy/estimators/map/tests/test_ts.py
Labels: feature, backport-v2.0.x

#6146 Remove dev docs dispatch workflow
  .github/workflows/dispatch.yml
Labels: infrastructure, skip-tests, skip-docs, backport-v2.0.x

#6151 Backport PR #6146 on branch v2.0.x (Remove dev docs dispatch workflow)
  .github/workflows/dispatch.yml
Labels: infrastructure, skip-tests, skip-docs, backport-v2.0.x

#6153 Backport PR #6134 on branch v2.0.x (Add energy dependent tool paper)
  examples/tutorials/astrophysics/energy_dependent_estimation.py
  gammapy/estimators/energydependentmorphology.py
Labels: docs

#6136 Add source to FPE in upper limits tutorial
  examples/tutorials/analysis-3d/non_detected_source.py
Labels: cleanup, docs, backport-v2.0.x

#6159 Fix typo in edisp plotting
  gammapy/irf/edisp/kernel.py
Labels: bug, cleanup, backport-v2.0.x

#6160 Backport PR #6159 on branch v2.0.x (Fix typo in edisp plotting)
  gammapy/irf/edisp/kernel.py
Labels: bug, cleanup, backport-v2.0.x

#6163 Backport PR #6155 on branch v2.0.x (Fix blank plot in astro dark matter tutorial)
  examples/tutorials/astrophysics/astro_dark_matter.py
Labels: cleanup, docs, backport-v2.0.x

#6162 Fix small formatting issues in user guide
  docs/user-guide/datasets/index.rst
  docs/user-guide/datasets/plot_stack.py
  docs/user-guide/estimators.rst
  docs/user-guide/irf/index.rst
  docs/user-guide/scripts/index.rst
  docs/user-guide/stats/fit_statistics.rst
  docs/user-guide/stats/index.rst
Labels: cleanup, docs, backport-v2.0.x

#6158 Add further test for sensitivity
  gammapy/estimators/map/tests/test_excess.py
Labels: tests, backport-v2.0.x

#6142 Add further information about fitting to the Low Level Analysis tutorial
  examples/tutorials/starting/analysis_2.py
Labels: docs, backport-v2.0.x

#6172 Backport PR #6164 on branch v2.0.x (Fix division in error calculations for compute_flux_doubling)
  gammapy/estimators/tests/test_utils.py
  gammapy/stats/tests/test_variability.py
  gammapy/stats/variability.py
Labels: bug, backport-v2.0.x
