Repository gammapy/gammapy, pull requests merged in 2025-04, with the labels that each got.

#5708 Use openastronomy workflow to build wheels
  .github/workflows/release.yml
  codemeta.json
Labels: infrastructure, backport-v1.0.x, backport-v1.3.x

#5696 Introducing FitStatistic
  gammapy/datasets/__init__.py
  gammapy/datasets/core.py
  gammapy/datasets/flux_points.py
  gammapy/datasets/map.py
  gammapy/datasets/spectrum.py
  gammapy/datasets/tests/test_map.py
  gammapy/makers/background/fov.py
  gammapy/stats/__init__.py
  gammapy/stats/fit_statistics.py
  gammapy/stats/tests/test_fit_statistics.py
Labels: feature, cleanup

#5754 Fix `e_peak` implementation of `SuperExpCutoffPowerLaw4FGLDR3SpectralModel`
  gammapy/modeling/models/spectral.py
  gammapy/modeling/models/tests/test_spectral.py
Labels: bug, coding sprint

#5764 Fix bug in `dataset.to_region_map_dataset`
  gammapy/datasets/map.py
  gammapy/datasets/tests/test_map.py
Labels: bug

#5768 Correct pydantic deprecation warning
  gammapy/utils/metadata.py
Labels: cleanup

#5760 Added spatial model to FoVBackgroundMaker init
  gammapy/makers/background/fov.py
  gammapy/makers/background/tests/test_fov.py
Labels: feature

#5757 Expose `sigma_to_ts` and `ts_to_sigma`
  docs/api-reference/stats.rst
  gammapy/stats/__init__.py
  gammapy/stats/utils.py
Labels: feature, coding sprint

#5719 Limit misusage of `to_region_map_dataset`
  examples/tutorials/analysis-3d/flux_profiles.py
  gammapy/datasets/map.py
  gammapy/datasets/tests/test_map.py
Labels: bug

#5763 Push the web search engine to display first the stable version
  docs/conf.py
Labels: docs

#5788 Fix broken icons and add help buttons to documentation
  docs/_static/atom.png
  docs/_static/box.svg
  docs/_static/custom.css
  docs/_static/galleryicon.svg
  docs/_static/gears.png
  docs/_static/glossaryicon.svg
  docs/_static/index_api.svg
  docs/_static/index_contribute.svg
  docs/_static/index_getting_started.svg
  docs/_static/index_user_guide.svg
  docs/_static/install.png
  docs/_static/upgrade.png
  docs/_static/using.png
  docs/index.rst
  docs/user-guide/index.rst
Labels: cleanup, docs, coding sprint

#5784 Fix in the HowTo page the tutorial link for `make an on-axis equivalent livetime map`
  docs/user-guide/howto.rst
Labels: docs

#5785 Fit the title and add GADF reference into the data flow page
  docs/user-guide/package.rst
Labels: docs

#5787 Add link to workflow section in the installation section
  docs/getting-started/quickstart.rst
Labels: docs

#5791 Fix links in HowTos
  docs/development/dev_howto.rst
  docs/development/doc_howto.rst
Labels: cleanup, docs

#5795 Clean up conf and dev
  docs/_templates/autosummary/base.rst
  docs/_templates/autosummary/class.rst
  docs/_templates/autosummary/module.rst
  docs/conf.py
  docs/references.txt
  environment-dev.yml
  setup.cfg
Labels: cleanup, docs, coding sprint

#5790 Apply suggested changes to FoVBackgroundMaker docstring
  gammapy/makers/background/fov.py
Labels: docs, coding sprint

#5804 New test to evaluate spectral models (and spot issues like PR-5799)
  gammapy/modeling/models/tests/test_spectral.py
Labels: coding sprint

#5805 Add further message for checking docstring
  docs/development/doc_howto.rst
Labels: docs

#5793 Improvement of the main tutorial page
  docs/development/pigs/pig-027.rst
  examples/tutorials/README.rst
  examples/tutorials/api/makers.py
  examples/tutorials/data/README.rst
Labels: docs

#5767 Add missing _check_name_unique in Models.__setitem__
  gammapy/modeling/models/core.py
  gammapy/modeling/models/tests/test_cube.py
Labels: bug

#5782 Redefine parameter scan_min/max
  gammapy/estimators/flux.py
  gammapy/estimators/points/tests/test_profile.py
  gammapy/estimators/utils.py
  gammapy/modeling/parameter.py
Labels: bug

#5807 datasets write() docstring typo
  gammapy/datasets/core.py
Labels: docs

#5813 Missing negative sign in PLEC4 `evaluate`
  gammapy/catalog/tests/test_fermi.py
  gammapy/modeling/models/spectral.py
Labels: bug

#5773 Add scheduled ci test for rst and examples
  .github/workflows/doctests.yml
Labels: infrastructure, tests, docs

#5810 Allow arrows for sidebar
  docs/conf.py
  docs/user-guide/package.rst
Labels: docs, coding sprint

#5798 Warning fixes in some tests
  gammapy/datasets/tests/test_flux_points.py
Labels: cleanup, tests, coding sprint

#5756 3PC pulse profile
  gammapy/catalog/fermi.py
  gammapy/catalog/tests/test_fermi.py
Labels: feature, coding sprint

#5818 Fix links in docs after link check
  docs/development/dev_howto.rst
  docs/development/pigs/pig-009.rst
  docs/development/pigs/pig-014.rst
  docs/development/pigs/pig-024.rst
  docs/user-guide/howto.rst
  examples/tutorials/analysis-time/variability_estimation.py
  gammapy/data/hdu_index_table.py
  gammapy/estimators/utils.py
  gammapy/stats/variability.py
  gammapy/utils/fits.py
Labels: infrastructure, cleanup

#5792 Update olddeps and CI
  .github/workflows/ci.yml
  tox.ini
Labels: infrastructure

#5802 Add a small tutorial on the theta-square plot
  docs/sphinxext.py
  examples/tutorials/api/theta_square_plot.py
Labels: docs

#5779 Add ObservationMetadata lazy loading
  gammapy/data/data_store.py
  gammapy/data/observations.py
  gammapy/data/tests/test_event_list.py
  gammapy/utils/fits.py
Labels: cleanup

#5832 Fix #5829
  docs/api-reference/stats.rst
Labels: cleanup, docs

#5823 Cleaning of the HESS tutorial
  examples/tutorials/data/hess.py
Labels: cleanup, docs

#5843 Fix energy printing in `PSFMap.peek()`
  gammapy/irf/psf/map.py
Labels: cleanup

#5844 Correct small bug in PSFMap
  gammapy/irf/psf/map.py
Labels: bug

#5842 Replace np.dot by np.matmul
  gammapy/datasets/utils.py
Labels: cleanup, performance

#5841 Update the documentation of the TS and Excess map estimators
  gammapy/estimators/map/excess.py
  gammapy/estimators/map/ts.py
Labels: docs

#5819 Remove unneeded click argument for Python 3
  docs/development/dev_howto.rst
  environment-dev.yml
  gammapy/scripts/main.py
Labels: cleanup

#5513 Use `ctao_south` and `ctao_north` in observatory locations defined in Gammapy
  examples/tutorials/analysis-1d/cta_sensitivity.py
  examples/tutorials/analysis-1d/spectrum_simulation.py
  examples/tutorials/analysis-3d/event_sampling.py
  examples/tutorials/analysis-3d/event_sampling_nrg_depend_models.py
  examples/tutorials/analysis-3d/simulate_3d.py
  examples/tutorials/analysis-time/light_curve_simulation.py
  gammapy/data/tests/test_metadata.py
  gammapy/data/tests/test_pointing.py
  gammapy/datasets/simulate.py
  gammapy/utils/observers.py
Labels: cleanup, api-change
