Repository gammapy/gammapy, pull requests merged in 2025-06, with the labels that each got.

#5895 CI fix : no yield in tests
  gammapy/modeling/models/tests/test_io.py
Labels: infrastructure

#5712 Add parameter limits on phi for Spatial models
  gammapy/modeling/models/spatial.py
  gammapy/modeling/models/tests/test_spatial.py
  gammapy/modeling/parameter.py
  gammapy/utils/tests/test_units.py
  gammapy/utils/units.py
Labels: cleanup

#5885 Update the installation guide in order to reduce the emphasis on Anaconda
  docs/getting-started/environments.rst
  docs/getting-started/index.rst
  docs/getting-started/install.rst
  docs/getting-started/usage.rst
Labels: docs

#5907 Modify GAMMAPY_DATA definition in CI matrix
  .github/workflows/ci.yml
Labels: infrastructure

#5875 Export creation metadata on DL3 and DL4 products
  gammapy/data/__init__.py
  gammapy/data/event_list.py
  gammapy/data/gti.py
  gammapy/data/metadata.py
  gammapy/data/tests/test_event_list.py
  gammapy/data/tests/test_gti.py
  gammapy/data/tests/test_metadata.py
  gammapy/datasets/io.py
  gammapy/datasets/map.py
  gammapy/datasets/spectrum.py
  gammapy/datasets/tests/test_map.py
  gammapy/datasets/tests/test_spectrum.py
  gammapy/irf/edisp/kernel.py
  gammapy/maps/region/ndmap.py
  gammapy/utils/metadata.py
Labels: feature, metadata

#4388 PIG 28 - Roadmap for v2.0
  docs/development/pigs/index.rst
  docs/development/pigs/pig-028.rst
Labels: pig

#5915 Fix parameters links after models copy
  gammapy/modeling/models/core.py
  gammapy/modeling/models/tests/test_io.py
Labels: bug

#5889 Adapt intructions for static figures
  docs/development/doc_howto.rst
Labels: docs

#5929 Add note on PR doc build access
  docs/development/doc_howto.rst
Labels: docs

#5905 Fix documentation of of the installation
  docs/getting-started/index.rst
Labels: bug, docs

#5914 Modify sampler to handle linked params in models
  codemeta.json
  gammapy/modeling/models/core.py
  gammapy/modeling/sampler.py
  gammapy/modeling/tests/test_sampler.py
Labels: bug

#5916 Fix link label display in parameters.to_table
  gammapy/modeling/models/core.py
  gammapy/modeling/models/tests/test_io.py
  gammapy/modeling/parameter.py
Labels: bug

#5940 Update sherpa message and add gammapy info to docs
  docs/getting-started/quickstart.rst
Labels: docs

#5921 Add `Notes` section to `HpxMap`, `HpxNDMap` and `HpxGeom`
  docs/user-guide/maps/hpxmap.rst
  gammapy/maps/hpx/core.py
  gammapy/maps/hpx/geom.py
  gammapy/maps/hpx/ndmap.py
Labels: cleanup, docs

#5922 Clean up of `irf/background.py`
  gammapy/irf/background.py
  gammapy/irf/core.py
  gammapy/utils/interpolation.py
Labels: cleanup, docs

#5925 Adapt docstring for `ReflectedRegionsFinder`
  gammapy/makers/background/reflected.py
Labels: cleanup, docs

#5387 Introduce context manager to set energy range to mask fit
  gammapy/datasets/tests/test_utils.py
  gammapy/datasets/utils.py
Labels: feature

#5774 Add IO class for eventlist
  gammapy/data/event_list.py
  gammapy/data/io.py
  gammapy/data/tests/test_io.py
Labels: feature

#5953 Fix sampler tests
  gammapy/modeling/tests/test_sampler.py
Labels: cleanup, tests
