Repository gammapy/gammapy, pull requests merged in 2025-05, with the labels that each got.

#5848 Ignore PIGs in doctest workflow
  .github/workflows/doctests.yml
Labels: infrastructure, tests

#5837 Adapt parameter conf_min/conf_max (more stable default for ul and sensitivity)
  gammapy/estimators/flux.py
  gammapy/estimators/parameter.py
  gammapy/estimators/points/tests/test_sensitivity.py
  gammapy/modeling/parameter.py
Labels: cleanup

#5797 Sampling tutorial
  docs/_static/cornerplot-multiple-runs-Crab.png
  docs/sphinxext.py
  examples/tutorials/api/nested_sampling_Crab.py
  gammapy/modeling/__init__.py
Labels: docs

#5803 Small update of the introduction of the fitting tutorial
  examples/tutorials/api/fitting.py
Labels: docs

#5451 Improve handling of background IRFs with AltAz alignment
  gammapy/makers/map.py
  gammapy/makers/tests/test_utils.py
  gammapy/makers/utils.py
Labels: feature

#5786 More robust error propagation approach using sampling
  gammapy/catalog/tests/test_fermi.py
  gammapy/catalog/tests/test_gammacat.py
  gammapy/catalog/tests/test_hawc.py
  gammapy/catalog/tests/test_lhaaso.py
  gammapy/modeling/models/spectral.py
  gammapy/modeling/models/tests/test_spectral.py
Labels: bug, feature

#5864 Remove v1.3 deprecations
  examples/tutorials/analysis-3d/flux_profiles.py
  examples/tutorials/data/fermi_lat.py
  gammapy/estimators/map/asmooth.py
  gammapy/estimators/map/tests/test_asmooth.py
  gammapy/estimators/points/profile.py
  gammapy/estimators/points/sensitivity.py
  gammapy/estimators/points/tests/test_profile.py
  gammapy/estimators/points/tests/test_sensitivity.py
  gammapy/irf/edisp/core.py
  gammapy/irf/effective_area.py
  gammapy/irf/psf/kernel.py
  gammapy/irf/psf/map.py
  gammapy/irf/psf/tests/test_kernel.py
  gammapy/irf/psf/tests/test_map.py
  gammapy/irf/tests/test_effective_area.py
  gammapy/modeling/models/cube.py
  gammapy/modeling/models/spectral.py
  gammapy/modeling/models/tests/test_io.py
  gammapy/utils/scripts.py
Labels: cleanup

#4218 Add interp_scale to parameter scaling
  gammapy/modeling/covariance.py
  gammapy/modeling/models/core.py
  gammapy/modeling/parameter.py
  gammapy/modeling/tests/test_covariance.py
  gammapy/modeling/tests/test_fit.py
  gammapy/modeling/tests/test_parameter.py
  gammapy/utils/interpolation.py
Labels: feature

#5715 Modified Polygon region for use as ON region
  gammapy/utils/regions.py
  gammapy/utils/tests/test_regions.py
Labels: feature

#5869 Fix broken link to another tutorial
  examples/tutorials/analysis-time/light_curve_flare.py
Labels: cleanup, docs

#5831 Add license for the documentation
  README.rst
  docs/_templates/custom-footer.html
Labels: docs

#5744 Fix of a HpXGeom simulation error
  gammapy/datasets/tests/test_map.py
  gammapy/maps/hpx/core.py
  gammapy/maps/hpx/ndmap.py
Labels: bug

#5873 Fix link of doc licences in README.rst
  README.rst
Labels: cleanup, skip tests, skip docs, skip CI

#5845 Clean-up the workflow and API pages
  docs/api-reference/index.rst
  docs/user-guide/package.rst
Labels: docs

#5851 Better exposition of the IRFs
  docs/references.txt
  docs/user-guide/irf/index.rst
  docs/user-guide/makers/reflected.rst
  docs/user-guide/makers/ring.rst
  docs/user-guide/references.rst
  docs/user-guide/stats/fit_statistics.rst
  docs/user-guide/stats/index.rst
  examples/tutorials/api/irfs.py
  gammapy/estimators/points/lightcurve.py
  gammapy/irf/core.py
Labels: docs

#5852 Better exposition of hidden pages
  docs/user-guide/irf/index.rst
  docs/user-guide/maps/index.rst
  docs/user-guide/stats/fit_statistics.rst
  docs/user-guide/stats/index.rst
  examples/tutorials/api/irfs.py
  gammapy/stats/__init__.py
  gammapy/stats/fit_statistics.py
Labels: docs

#5877 [CI] Impose astropy<7.1 to fix CI
  setup.cfg
Labels: infrastructure, tests

#5871 `FluxPointsEstimator`: precise the default value of `reoptimize`
  gammapy/estimators/flux.py
  gammapy/estimators/parameter.py
  gammapy/estimators/points/sed.py
Labels: docs

#5876 Add small description for capturing a deprecation in tests
  docs/development/dev_howto.rst
Labels: docs

#2458 PIG 17 - Provenance capture
  docs/development/pigs/pig-017.rst
Labels: pig

#5880 Serialization of GTI extension is not correct in the event sampling tutorial
  examples/tutorials/analysis-3d/event_sampling.py
Labels: cleanup, docs
